### ISSUE TITLE
Inspected component does not reset after page reload

### ISSUE THREAD

**Issue by jgebhardt** [facebook/react-devtools#1]
1. Go to the test page, select & inspect some component inside the tree.
2. Reload the page
   The previously selected component is still visible in the props inspector. This can be especially confusing when comparing components before & after the reload. 

Bonus wishlist feature: It would be awesome if the extension could select the equivalent node in the hierarchy after reload whenever possible (ie. the overall component structure hasn't changed too much)

**Comment by aspiers** [comment]
It seems that the behaviour described in this issue is now implemented.  However I've just submitted #596 contending that this is the exact opposite of the ideal behaviour.  Let the debates commence! ;-)  (I suggest we debate in #596, not in this issue which was closed a long time ago.)
