### ISSUE TITLE
Firefox Devtools highlights elements with a huge dark grey box, obscuring the page

### ISSUE THREAD

**Issue by camjackson** [facebook/react-devtools#1012]
1. Open react devtools in Firefox
2. Hover over a react component in the tree
3. The element's box model is highlighted on the page in blue/orange/green, as expected
4. The element also gets a big, opaque, dark grey box over it, like so:

<img width="407" alt="Screen Shot" src="https://user-images.githubusercontent.com/1930451/38453553-fe13a8d8-3a89-11e8-8e44-4b037e602524.png">

This big grey box is not present in Chrome. Is it there deliberately in Firefox or is this a bug?

Firefox 59.0
React Developer Tools 3.2.1
macOS High Sierra 10.13.3

**Comment by bvaughn** [comment]
Definitely not intentional!

**Comment by bvaughn** [comment]
For what it's worth, this is not what I see on Firefox 59.0.2 / OSX 10.13.4

![screen shot 2018-05-09 at 3 54 10 pm](https://user-images.githubusercontent.com/29597/39843715-3c180374-53a1-11e8-9fab-961077d75f62.png)

**Comment by camjackson** [comment]
I've removed and re-installed the extension and it seems to be fixed! 🤷‍♂️
