### ISSUE TITLE
React Dev Tools not working despite __REACT_DEVTOOLS_GLOBAL_HOOK__ exists 

### ISSUE THREAD

**Issue by canyavall** [facebook/react-devtools#1028]
I've created a new project and for any reason, dev tools is not working.
For other projects it is working but not for this one.
I've been checking if __REACT_DEVTOOLS_GLOBAL_HOOK__ is in window, and yes, I could find it...  can someone tell me what else I've or I can check in order to make it work?

**Comment by gaearon** [comment]
Please see this:

https://github.com/facebook/react-devtools#the-react-tab-doesnt-show-up
