### ISSUE TITLE
nativeObjectCreate

### ISSUE THREAD

**Issue by LuisGonzaga** [facebook/react-devtools#1039]
Hello,
I am starting React & doing an "hello world", to my surprise I got the error described below, after searching the web (no similar results) I tested in FF and IE with no problems.
Then I disabled react-devtools 3.2.3 and everything was fine.

-> The script is very simple, just for the record: 
<script type="text/javascript">
      var helloWorld = React.createElement('h1', null, 'Hello world!')
      ReactDOM.render(helloWorld, document.getElementById('content'))    
</script>

-> error in Chrome  66.0.3359.181 (64 bits)
-> works fine in Firefox 60.0.1 (64-bit)

-> The error:
backend.js:708 Uncaught TypeError: Cannot read property 'nativeObjectCreate' of undefined
    at Object.<anonymous> (backend.js:708)
    at __webpack_require__ (backend.js:20)
    at Object.<anonymous> (backend.js:690)
    at __webpack_require__ (backend.js:20)
    at Object.<anonymous> (backend.js:59)
    at __webpack_require__ (backend.js:20)
    at backend.js:40
    at backend.js:43
(anonymous) @ backend.js:708
__webpack_require__ @ backend.js:20
(anonymous) @ backend.js:690
__webpack_require__ @ backend.js:20
(anonymous) @ backend.js:59
__webpack_require__ @ backend.js:20
(anonymous) @ backend.js:40
(anonymous) @ backend.js:43

**Comment by madlabman** [comment]
I have similar error using React dev tools in Chrome but it's work fine in Firefox, check it out.

**Comment by ashsearle** [comment]
I've seen the same, and think this is the minimum required to reproduce:

* Create an HTML file containing:
```html
<script src="https://unpkg.com/react@^16/umd/react.development.js"></script>
```

* Use "Open File..." in Chrome to open it using `file:///` protocol.
* Inspect page
* Switch to React tab

Observe 1 JavaScript error.  Switch to Console tab to view stack trace.

Serving the same file over http does not give any errors, just the "Waiting for roots to load..."  messages in React devtools.

**Comment by LuisGonzaga** [comment]
Well I believe that this is a conflict with other Extensions.
In my particular case I've disabled Ember Inspector, Ghost Text, "Screenshot, Annotate, & Screen Video Recorder..." plus "Sencha & Ext.js" ... and it started to work.

**Comment by ashsearle** [comment]
@LuisGonzaga I still see the same error even if I disable all other extensions.

Is it working when loading something as a local `file:///` URL, or are you accessing stuff via `http://` now?

**Comment by LuisGonzaga** [comment]
At this stage everything in the project is local. Restarting the browser or the PC may help to validate your changes.
