### ISSUE TITLE
[New Devtools] Uncaught TypeError: Cannot read property 'getNativeFromReactElement' of undefined

### ISSUE THREAD

**Issue by Daniel15** [facebook/react-devtools#105]
I was clicking around for a bit and saw these errors - Not 100% sure of repro steps. Chrome 44.0.2403.125.
```
Uncaught TypeError: Cannot read property 'getNativeFromReactElement' of undefined 
getNodeForID @ VM1438:268
highlight @ VM1438:239
(anonymous function) @ VM1438:142
(anonymous function) @ Bridge.js?1afd:284
(anonymous function) @ Bridge.js?1afd:284
_handleMessage @ Bridge.js?1afd:277
listener @ VM1437:33
postMessage (async)
handleMessageFromDevtools @ VM1459:19
target.(anonymous function) @ extensions::SafeBuiltins:19
EventImpl.dispatchToListener @ extensions::event_bindings:387
target.(anonymous function) @ extensions::SafeBuiltins:19
$Array.forEach.publicClass.(anonymous function) @ extensions::utils:94
EventImpl.dispatch_ @ extensions::event_bindings:371
EventImpl.dispatch @ extensions::event_bindings:393
target.(anonymous function) @ extensions::SafeBuiltins:19
$Array.forEach.publicClass.(anonymous function) @ extensions::utils:94
dispatchOnMessage @ extensions::messaging:316
```

**Comment by jaredly** [comment]
React version?

**Comment by Daniel15** [comment]
Whichever version we're using internally at Facebook, I think it's master
from Friday last week.

**Comment by Daniel15** [comment]
I haven't seen this again, will reopen if I see it again.

**Comment by wadouk** [comment]
+1 
react 0.13.3  
chrome 41.0.2272.118 (64-bit) on linux

**Comment by reactUsr** [comment]
+1
react 0.14.2
chrome 46.0.2490.80
react devtools 0.14.4

**Comment by kassens** [comment]
Does anyone have steps to reproduce or at least something where it happens frequently?

**Comment by reactUsr** [comment]
@kassens happened to me only once, will post again if I get more info

**Comment by LoicUV** [comment]
Happens to me when I click in the right panel. Can't reproduce the steps though. Maybe it happens when the tree has changed but is not refreshed in devtools but I'm not sure.

react 0.13.3
Version 47.0.2526.73 (64-bit) OSX 10.11.1

**Comment by BobWhitelock** [comment]
I'm having a similar error message occur consistently in my project when I load a particular page. When I load that page, within the React Devtools tab I get the following message:

`Waiting for roots to load...to reload the inspector [click here]`

When I click the button the following error is logged repeatedly in the console, about once a second:

`233backend.js:433 Uncaught TypeError: Cannot read property 'getNativeFromReactElement' of undefinedgetNodeForID @ backend.js:433_onUpdate @ backend.js:2226EventEmitter.emit @ backend.js:1895onUpdated @ backend.js:593(anonymous function) @ backend.js:8089(anonymous function) @ VM6221:44emit @ VM6221:43receiveComponent @ backend.js:8301obj.(anonymous function) @ backend.js:8371obj.(anonymous function) @ backend.js:8370ReactChildReconciler.updateChildren @ ReactChildReconciler.js:84ReactMultiChild.Mixin._reconcilerUpdateChildren @ ReactMultiChild.js:216ReactMultiChild.Mixin._updateChildren @ ReactMultiChild.js:351ReactMultiChild.Mixin.updateChildren @ ReactMultiChild.js:326ReactDOMComponent.Mixin._updateDOMChildren @ ReactDOMComponent.js:871ReactDOMComponent.Mixin.updateComponent @ ReactDOMComponent.js:700ReactDOMComponent.Mixin.receiveComponent @ ReactDOMComponent.js:645ReactReconciler.receiveComponent @ ReactReconciler.js:87obj.(anonymous function) @ backend.js:8370obj.(anonymous function) @ backend.js:8370ReactChildReconciler.updateChildren @ ReactChildReconciler.js:84ReactMultiChild.Mixin._reconcilerUpdateChildren @ ReactMultiChild.js:216ReactMultiChild.Mixin._updateChildren @ ReactMultiChild.js:351ReactMultiChild.Mixin.updateChildren @ ReactMultiChild.js:326ReactDOMComponent.Mixin._updateDOMChildren @ ReactDOMComponent.js:871ReactDOMComponent.Mixin.updateComponent @ ReactDOMComponent.js:700ReactDOMComponent.Mixin.receiveComponent @ ReactDOMComponent.js:645ReactReconciler.receiveComponent @ ReactReconciler.js:87obj.(anonymous function) @ backend.js:8370obj.(anonymous function) @ backend.js:8370ReactCompositeComponentMixin._updateRenderedComponent @ ReactCompositeComponent.js:562ReactCompositeComponentMixin._performComponentUpdate @ ReactCompositeComponent.js:544ReactCompositeComponentMixin.updateComponent @ ReactCompositeComponent.js:473ReactCompositeComponent_updateComponent @ ReactPerf.js:66ReactCompositeComponentMixin.receiveComponent @ ReactCompositeComponent.js:405ReactReconciler.receiveComponent @ ReactReconciler.js:87obj.(anonymous function) @ backend.js:8370obj.(anonymous function) @ backend.js:8370ReactChildReconciler.updateChildren @ ReactChildReconciler.js:84ReactMultiChild.Mixin._reconcilerUpdateChildren @ ReactMultiChild.js:216ReactMultiChild.Mixin._updateChildren @ ReactMultiChild.js:351ReactMultiChild.Mixin.updateChildren @ ReactMultiChild.js:326ReactDOMComponent.Mixin._updateDOMChildren @ ReactDOMComponent.js:871ReactDOMComponent.Mixin.updateComponent @ ReactDOMComponent.js:700ReactDOMComponent.Mixin.receiveComponent @ ReactDOMComponent.js:645ReactReconciler.receiveComponent @ ReactReconciler.js:87obj.(anonymous function) @ backend.js:8370obj.(anonymous function) @ backend.js:8370ReactChildReconciler.updateChildren @ ReactChildReconciler.js:84ReactMultiChild.Mixin._reconcilerUpdateChildren @ ReactMultiChild.js:216ReactMultiChild.Mixin._updateChildren @ ReactMultiChild.js:351ReactMultiChild.Mixin.updateChildren @ ReactMultiChild.js:326ReactDOMComponent.Mixin._updateDOMChildren @ ReactDOMComponent.js:871ReactDOMComponent.Mixin.updateComponent @ ReactDOMComponent.js:700ReactDOMComponent.Mixin.receiveComponent @ ReactDOMComponent.js:645ReactReconciler.receiveComponent @ ReactReconciler.js:87obj.(anonymous function) @ backend.js:8370obj.(anonymous function) @ backend.js:8370ReactChildReconciler.updateChildren @ ReactChildReconciler.js:84ReactMultiChild.Mixin._reconcilerUpdateChildren @ ReactMultiChild.js:216ReactMultiChild.Mixin._updateChildren @ ReactMultiChild.js:351ReactMultiChild.Mixin.updateChildren @ ReactMultiChild.js:326ReactDOMComponent.Mixin._updateDOMChildren @ ReactDOMComponent.js:871ReactDOMComponent.Mixin.updateComponent @ ReactDOMComponent.js:700ReactDOMComponent.Mixin.receiveComponent @ ReactDOMComponent.js:645ReactReconciler.receiveComponent @ ReactReconciler.js:87obj.(anonymous function) @ backend.js:8370obj.(anonymous function) @ backend.js:8370ReactCompositeComponentMixin._updateRenderedComponent @ ReactCompositeComponent.js:562ReactCompositeComponentMixin._performComponentUpdate @ ReactCompositeComponent.js:544ReactCompositeComponentMixin.updateComponent @ ReactCompositeComponent.js:473ReactCompositeComponent_updateComponent @ ReactPerf.js:66ReactCompositeComponentMixin.receiveComponent @ ReactCompositeComponent.js:405ReactReconciler.receiveComponent @ ReactReconciler.js:87obj.(anonymous function) @ backend.js:8370obj.(anonymous function) @ backend.js:8370ReactCompositeComponentMixin._updateRenderedComponent @ ReactCompositeComponent.js:562ReactCompositeComponentMixin._performComponentUpdate @ ReactCompositeComponent.js:544ReactCompositeComponentMixin.updateComponent @ ReactCompositeComponent.js:473ReactCompositeComponent_updateComponent @ ReactPerf.js:66ReactCompositeComponentMixin.receiveComponent @ ReactCompositeComponent.js:405ReactReconciler.receiveComponent @ ReactReconciler.js:87obj.(anonymous function) @ backend.js:8370obj.(anonymous function) @ backend.js:8370ReactCompositeComponentMixin._updateRenderedComponent @ ReactCompositeComponent.js:562ReactCompositeComponentMixin._performComponentUpdate @ ReactCompositeComponent.js:544ReactCompositeComponentMixin.updateComponent @ ReactCompositeComponent.js:473ReactCompositeComponent_updateComponent @ ReactPerf.js:66ReactCompositeComponentMixin.performUpdateIfNecessary @ ReactCompositeComponent.js:421ReactReconciler.performUpdateIfNecessary @ ReactReconciler.js:102obj.(anonymous function) @ backend.js:8370obj.(anonymous function) @ backend.js:8370runBatchedUpdates @ ReactUpdates.js:129Mixin.perform @ Transaction.js:136Mixin.perform @ Transaction.js:136assign.perform @ ReactUpdates.js:86flushBatchedUpdates @ ReactUpdates.js:147ReactUpdates_flushBatchedUpdates @ ReactPerf.js:66Mixin.closeAll @ Transaction.js:202Mixin.perform @ Transaction.js:149ReactDefaultBatchingStrategy.batchedUpdates @ ReactDefaultBatchingStrategy.js:62enqueueUpdate @ ReactUpdates.js:176enqueueUpdate @ ReactUpdateQueue.js:24ReactUpdateQueue.enqueueSetState @ ReactUpdateQueue.js:190ReactComponent.setState @ ReactComponent.js:65handleChange @ connect.js:239dispatch @ createStore.js:180updateScrollTop @ LogMonitor.js:136`

Possibly also related, on the initial page load I get the following error (which I do not get on other pages where I don't get the above issue):

`Uncaught TypeError: Cannot read property 'props' of undefinedgetData @ backend.js:8441walkNode @ backend.js:8348(anonymous function) @ backend.js:8351walkNode @ backend.js:8350(anonymous function) @ backend.js:8351walkNode @ backend.js:8350(anonymous function) @ backend.js:8351walkNode @ backend.js:8350(anonymous function) @ backend.js:8351walkNode @ backend.js:8350(anonymous function) @ backend.js:8351walkNode @ backend.js:8350(anonymous function) @ backend.js:8351walkNode @ backend.js:8350(anonymous function) @ backend.js:8351walkNode @ backend.js:8350(anonymous function) @ backend.js:8351walkNode @ backend.js:8350(anonymous function) @ backend.js:8351walkNode @ backend.js:8350(anonymous function) @ backend.js:8351walkNode @ backend.js:8350(anonymous function) @ backend.js:8351walkNode @ backend.js:8350(anonymous function) @ backend.js:8351walkNode @ backend.js:8350(anonymous function) @ backend.js:8351walkNode @ backend.js:8350(anonymous function) @ backend.js:8351walkNode @ backend.js:8350(anonymous function) @ backend.js:8351walkNode @ backend.js:8350(anonymous function) @ backend.js:8351walkNode @ backend.js:8350(anonymous function) @ backend.js:8351walkNode @ backend.js:8350(anonymous function) @ backend.js:8351walkNode @ backend.js:8350(anonymous function) @ backend.js:8351walkNode @ backend.js:8350(anonymous function) @ backend.js:8351walkNode @ backend.js:8350(anonymous function) @ backend.js:8351walkNode @ backend.js:8350(anonymous function) @ backend.js:8351walkNode @ backend.js:8350(anonymous function) @ backend.js:8351walkNode @ backend.js:8350(anonymous function) @ backend.js:8351walkNode @ backend.js:8350(anonymous function) @ backend.js:8351walkNode @ backend.js:8350(anonymous function) @ backend.js:8351walkNode @ backend.js:8350(anonymous function) @ backend.js:8351walkNode @ backend.js:8350(anonymous function) @ backend.js:8351walkNode @ backend.js:8350(anonymous function) @ backend.js:8351walkNode @ backend.js:8350(anonymous function) @ backend.js:8351walkNode @ backend.js:8350(anonymous function) @ backend.js:8351walkNode @ backend.js:8350(anonymous function) @ backend.js:8351walkNode @ backend.js:8350(anonymous function) @ backend.js:8351walkNode @ backend.js:8350(anonymous function) @ backend.js:8351walkNode @ backend.js:8350(anonymous function) @ backend.js:8351walkNode @ backend.js:8350(anonymous function) @ backend.js:8351walkNode @ backend.js:8350(anonymous function) @ backend.js:8351walkNode @ backend.js:8350(anonymous function) @ backend.js:8351walkNode @ backend.js:8350(anonymous function) @ backend.js:8351walkNode @ backend.js:8350(anonymous function) @ backend.js:8351walkNode @ backend.js:8350(anonymous function) @ backend.js:8351walkNode @ backend.js:8350(anonymous function) @ backend.js:8351walkNode @ backend.js:8350(anonymous function) @ backend.js:8351walkNode @ backend.js:8350(anonymous function) @ backend.js:8351walkNode @ backend.js:8350(anonymous function) @ backend.js:8351walkNode @ backend.js:8350(anonymous function) @ backend.js:8351walkNode @ backend.js:8350(anonymous function) @ backend.js:8351walkNode @ backend.js:8350(anonymous function) @ backend.js:8351walkNode @ backend.js:8350walkRoots @ backend.js:8342extras.walkTree @ backend.js:8315(anonymous function) @ backend.js:8075(anonymous function) @ VM7909:44emit @ VM7909:43setupBackend @ backend.js:8152module.exports @ backend.js:8096(anonymous function) @ backend.js:113g @ backend.js:1964EventEmitter.emit @ backend.js:1877(anonymous function) @ backend.js:297(anonymous function) @ backend.js:1024(anonymous function) @ backend.js:1023_handleMessage @ backend.js:1016listener @ backend.js:91`

I don't get the error or initial message if I initially load another page and then navigate to that one (I'm using `react-router`), so I'm guessing there's something in the initial load of that page which the devtools don't like. I don't know what that is however, will let you know if I find out.

Using:
react 0.14.7
chromium 49.0.2623.87 on Debian stretch/sid (64-bit)
react-devtools 0.14.9
