### ISSUE TITLE
react developer tool extension is not working

### ISSUE THREAD

**Issue by govindvuppu** [facebook/react-devtools#1051]
extension is still not working after setting the Allow access to file URLs on

**Comment by BlakeMSteel** [comment]
This is very general, please provide more detail, or you're unlikely to get your issue fixed.

**Comment by ashsearle** [comment]
@govindvuppu Do you see the error mentioned in #1039 ?

**Comment by govindvuppu** [comment]
Hi Blake and Ash thank you for getting back,
Yes it is a general fix which I found after restarting the react Dev tools extension by removing and adding the extension followed by restarting the browser.

Thank you
