### ISSUE TITLE
React-devtools shows outdated React version (16.4)

### ISSUE THREAD

**Issue by immunity20** [facebook/react-devtools#1053]
I dont use props.type ( old or new)

I have installed props.type

there isn't anywhere in project React.createclass

**Comment by ngyikp** [comment]
Is there an example URL/repo to your project?

**Comment by immunity20** [comment]
Found the solution/problem:

I dont use anywhere in the problem the PropTypes ( i have import the library)
since I didn't use React.PropTypes either

"class's Name".PropTypes = {
 ....
}

And now the dev tools shows React project is up to date.
