### ISSUE TITLE
npm run build:extension:chrome 报错

### ISSUE THREAD

**Issue by renzulei** [facebook/react-devtools#1065]
$ npm run build:extension:chrome

> @ build:extension:chrome E:\PACKAGES\react-tools\react-devtools
> node ./shells/chrome/build

E:\PACKAGES\react-tools\react-devtools\shells\chrome\build.js:13
const main = async () => {
                   ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)

npm ERR! Windows_NT 10.0.17134
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:extension:chrome"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @ build:extension:chrome: `node ./shells/chrome/build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build:extension:chrome script 'node ./shells/chrome/build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./shells/chrome/build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\PACKAGES\react-tools\react-devtools\npm-debug.log

**Comment by renzulei** [comment]
my problem. I did  not "npm install"

**Comment by ngyikp** [comment]
> npm ERR! node v6.11.2

Update Node.js to version 8+

**Comment by bvaughn** [comment]
Seems like you're using an older version of Node and the solution is to update, as @ngyikp says. 😄 Going to close this!
