### ISSUE TITLE
cannot run stand alone dev tool 

### ISSUE THREAD

**Issue by Farbod29** [facebook/react-devtools#1071]
I install the **react-devtools** package globally:

but I cannot run it with command `react-devtools` I tried with ` npm run react-devtools` also.
afer installation I have not folder with name of DevTool on my Mac system. maybe need to integrate in my package.jason !!"

**Comment by ngyikp** [comment]
Installing react-devtools globally is working fine on my macOS 10.13.6, we'll need to know the exact terminal commands that you entered to figure out what's going on

```
$ npm install -g react-devtools
/usr/local/bin/react-devtools -> /usr/local/lib/node_modules/react-devtools/bin.js

> electron@1.8.7 postinstall /usr/local/lib/node_modules/react-devtools/node_modules/electron
> node install.js

+ react-devtools@3.2.3
added 234 packages in 17.232s

$ which react-devtools
/usr/local/bin/react-devtools
```

Also try reading https://github.com/facebook/react-devtools/blob/master/packages/react-devtools/README.md

**Comment by bvaughn** [comment]
`npm run react-devtools` won't work unless you run it within a directory that contains a `package.json` that has a script entry named "react-devtools".

You should be able to run just `react-devtools` though, if you've globally installed it:
```sh
npm i -g react-devtools
react-devtools
```

If you're not able to, please provide more info about the exact commands and errors you're seeing. Also please include your OS and Node versions.

Going to close this for now 😄
