### ISSUE TITLE
Uncaught TypeError: React.createClass is not a function

### ISSUE THREAD

**Issue by navruzeraliev** [facebook/react-devtools#1075]

**Comment by bvaughn** [comment]
Not enough error to really help with this issue, but it doesn't seem related to React DevTools. I assume you're seeing this in the console after updating React. `createReactClass` was moved to a separate package some time ago, [create-react-class](https://www.npmjs.com/package/create-react-class). This should be [mentioned in the docs](https://reactjs.org/docs/react-without-es6.html)

You'll just need to install that package:
```sh
npm i create-react-class --save
```

And use it separately:
```js
var createReactClass = require('create-react-class');
var Greeting = createReactClass({
  render: function() {
    return <h1>Hello, {this.props.name}</h1>;
  }
});
```
