### ISSUE TITLE
Make Elements panel feel less cluttered

### ISSUE THREAD

**Issue by bvaughn** [facebook/react-devtools#1079]
Based on some user recent feedback I gathered [via Twitter](https://twitter.com/brian_d_vaughn/status/1025776259056336897), one piece of common feedback is that the Elements panel feels too noisy/cluttered/crowded.

Ritesh [points out a few possible causes for this](https://twitter.com/ritz078/status/1026164993614524416) including "line height" and too many props. I personally agree with the props concern. I like the simplicity of the Vue DevTools panel, which only shows props for the currently selected node:
![image](https://user-images.githubusercontent.com/29597/43724397-b9bdf8fe-994e-11e8-95a5-41d8f7fcb73d.png)

I think we should try doing the same for React DevTools. This would probably also have the side effect of making the DevTools render a little faster as well.

**Comment by bvaughn** [comment]
Took a quick pass at this in a branch this afternoon. I cut the Breadcrumbs panel entirely. (I don't think it's very useful, and it gets in the way.) I also cut the two checkboxes from the settings bar. (I imagine we could move them into the settings popup with the theme.)

Anyway, here's what it looked like:
<img width="906" alt="screen shot 2018-08-06 at 8 32 12 pm" src="https://user-images.githubusercontent.com/29597/43752872-d753f940-99b7-11e8-9b52-a5f5f61dff12.png">

**Comment by bvaughn** [comment]
I've published an early pre-release version of this for people to try out since a screenshot can only do so much: https://devtools-ui-bnfrhtvuzm.now.sh/

**Comment by bvaughn** [comment]
I think it's time to rewrite the `Node.js` component too. It's super confusing and uses a lot of unnecessary HTML elements.

I've got a good start on it locally– and as an added side bonus, elements can now _wrap_ like they do in the browser's Elements panels:
![devtools-node-wrap](https://user-images.githubusercontent.com/29597/43993664-0cf6b5ce-9d46-11e8-8f59-a5200ef99082.gif)

**Comment by bvaughn** [comment]
I'm hacking around on this issue [here](https://github.com/bvaughn/react-devtools/tree/issues/1079) by the way.

**Comment by bvaughn** [comment]
Also re-added the "highlight updates" and "highlight search" options inside of the preferences panel.

![devtools-minimal-settings](https://user-images.githubusercontent.com/29597/43997404-3345238e-9d8f-11e8-97d4-baa445b087e5.gif)

I don't think people use them often, and they take up a lot of space in the settings bar.

**Comment by bvaughn** [comment]
I got some [good feedback on Twitter](https://twitter.com/wongmjane/status/1028465198443708416) that the previous wrapping behavior did not work well with deep trees, so I've improved this with the latest push. Now the available width for nodes will grow as trees are deep to avoid unnecessary wrapping.

![devtools-better-wrap-2](https://user-images.githubusercontent.com/29597/44003754-f9a47962-9e0c-11e8-8839-bd8c9910c3fd.gif)

**Comment by jscheel** [comment]
@bvaughn moving "highlight changes" behind a separate click that opens a separate panel makes the process of rooting out performance issues much more tedious. I find myself having to make a change, refresh the page, move my mouse halfway down the screen, click the dropdown, then re-click the checkbox. Maybe a simple icon in the top bar would work better?

**Comment by bvaughn** [comment]
I'm sorry to hear that this has made your workflow more tedious. 😦

I believe that moving options like "highlight changes" out of the main panel was an a net gain, since space is so limited there. But your suggestion to make it persistent is inline with the spirit of #1077. Just need to find time to implement this.
