### ISSUE TITLE
Add a dark theme

### ISSUE THREAD

**Issue by julen** [facebook/react-devtools#108]
First off thank you very much for making the new devtools available in environments other than Chrome!

I have started using the React Devtools in Firefox, and the first time I noticed is the inconsistency of the inspector compared to the "native" browser tools.

Let me show two comparing screenshots to explain it all.

React inspector in Firefox:
![react-devtools](https://cloud.githubusercontent.com/assets/16768/9055919/6defa8b2-3a8f-11e5-8f8f-00f74076f665.png)

DOM inspector in Firefox ("native"):
![fx-devtools](https://cloud.githubusercontent.com/assets/16768/9055924/72519eba-3a8f-11e5-8d67-c23c63f92872.png)

I know the extension is a React app and in the end the styling is implemented on its own, however I found this confusing: didn't know if I was in Chrome or somewhere else.

I also know the current state of the new devtools is just beta, so I was wondering if providing a UI theme more in par with the target environment is something you are considering for the future.

Thanks again for all the hard work on this!

**Comment by jaredly** [comment]
Yeah, we're definitely going to improve look+feel for firefox

**Comment by toastal** [comment]
...And maybe even a matching dark theme??

**Comment by chris-kobrzak** [comment]
Since [Chrome Canary now supports a dark theme in its DevTools](https://developers.google.com/web/updates/2016/02/devtools-digest-devtools-go-dark?hl=en), maybe it might make sense to extend the scope of this issue to also cover Google Chrome?

**Comment by morsdyce** [comment]
In general it would be best to respect Chrome/Firefox colors and not create something that just matches the colors if possible.

Since now in Chrome you could create any custom theme.

**Comment by rayshan** [comment]
Chrome 49 became stable today and I had a chance to try it out, here's the result:

![screen shot 2016-03-02 at 11 21 46 pm](https://cloud.githubusercontent.com/assets/3760840/13487306/bd2c4d4c-e0cd-11e5-99e6-db1433b10785.png)

**Comment by wkerswell** [comment]
I have checked too and it seems like some of text is unreadable. I had the same problem when using a custom chrome theme. 
![screen shot 2016-03-10 at 12 01 30](https://cloud.githubusercontent.com/assets/3217365/13668888/96919be8-e6b7-11e5-8431-12b969510324.png)

**Comment by c10b10** [comment]
Are you guys working on a big new version of the de tools or why no love for this issue?

**Comment by spicyj** [comment]
No one's actively working on the React devtools; we just don't have enough time and generally prefer to invest in real features rather than cosmetic changes. If you'd like to work on this and send a pull request I'd be happy to review it.

**Comment by LestaD** [comment]
![image](https://cloud.githubusercontent.com/assets/5620073/16614479/31756a3a-437a-11e6-8747-d630d58aaba4.png)

**Comment by wkerswell** [comment]
Yeah seems to have gotten a little worse with those white lines.

**Comment by xyc** [comment]
Hello in case anyone wants to fix this, here's some colors extracted from Chrome DevTools for your reference: https://github.com/xyc/react-inspector/blob/master/src/styles/themes/chromeDark.js. Thanks a lot!

**Comment by ngyikp** [comment]
This issue wasn't fixable on previous Chrome versions because there's no way to know if the current theme is light/dark, https://github.com/facebook/react-devtools/issues/381 was a temporary hack to always force a white background.

However, Chrome 54 fixed it by adding `chrome.devtools.panels.themeName`
https://bugs.chromium.org/p/chromium/issues/detail?id=608869#c5

Not sure about Firefox though.

**Comment by rredkovich** [comment]
Any plans on adding native firefox dev edition dark mode?
![ff dev theme](https://www.dropbox.com/s/asmsg5u4eyey1yk/native.png?dl=1)
![react theme](https://www.dropbox.com/s/0kzvc31e53rr1yx/react.png?dl=1)

**Comment by clarkbw** [comment]
> Not sure about Firefox though.

I filed [bug 1360281](https://bugzilla.mozilla.org/show_bug.cgi?id=1360281) to implement the same WebExtension API.

**Comment by bvaughn** [comment]
FYI I've started a theming initiative (see PR #698) but it's not quite what's described above. (It doesn't hook into the active Chrome or Firefox theme. Still, I thought I'd point it out since it's at least related to the main topic of discussion here.)

The approach I went with uses a base16 approach instead. Should be easy to expand the built-in set of default themes (since each theme is small). Will probably also add user-defined themes at some point (eg file-upload or something similar).

**Comment by bvaughn** [comment]
I'm going to close this issue in favor of #705 since PR #698 has added initial theme support. I plan to add default dark-mode compliance in a follow-up PR (which will be tracked via issue #705).

**Comment by julen** [comment]
Hey @bvaughn, thanks for all the hard work on this one! :)

**Comment by gaearon** [comment]
Out in the latest version.

![screen shot 2017-05-26 at 22 50 41](https://cloud.githubusercontent.com/assets/810438/26513950/72010de8-4266-11e7-8dfe-a0337d6346b1.png)

**Comment by SimenB** [comment]
Found a bug, if I refresh with the Ract dev tools tab open, I get the default theme instead of the dark one (set to metch browser).

But it looks truly beautiful, thank you!

**Comment by gaearon** [comment]
>Found a bug, if I refresh with the React dev tools tab open, I get the default theme instead of the dark one (set to match browser).

Mind filing a new issue and cc'ing @bvaughn?
