### ISSUE TITLE
Right click on element and "view as root"

### ISSUE THREAD

**Issue by bvaughn** [facebook/react-devtools#1081]
Based on some user recent feedback I gathered [via Twitter](https://twitter.com/brian_d_vaughn/status/1025776259056336897), one commonly requested feature was the ability to filter the elements panel so that really deep trees were easier to explore. The idea of right clicking and pinning an instance as a "root" was mentioned a few times.

Perhaps such a setting could even be persisted between reloads (#1077).

Maybe we could render such a pinned element as though it were another root, but styled differently (maybe with a single element tag around it, like a parent but styled differently, that served as a trigger to "unpin" it?) This is sort of a half formed idea that I just want to write down so that it isn't lost. Let's expand on it with mockups or prototypes.

**Comment by jasonLaster** [comment]
We do this in the debugger's source tree and it is quite nice

**Comment by bvaughn** [comment]
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools
