### ISSUE TITLE
[New DevTools] Show in Elements Pane not working in Opera

### ISSUE THREAD

**Issue by dylanparry** [facebook/react-devtools#109]
Hi,

I’m using the new beta Chrome extension in Opera (v30). When I right-click on a node within the React DevTools, it shows the option "Show in Elements Pane", but clicking it doesn’t appear to do anything. The other options, such as "Show Source" work okay though.

**Comment by egauci** [comment]
Not working in Chrome either. Chrome: Version 43.0.2357.134 m  (Windows 7)

**Comment by jaredly** [comment]
thanks for reporting! got a fix ready
