### ISSUE TITLE
Add inspect button

### ISSUE THREAD

**Issue by SanderSpies** [facebook/react-devtools#11]
Add an inspect button within a toolbar above Props (like the debugging tools within the default Sources tab).

Should do the same as hovering over elements within the React Dev Tools tab. 

Dependent upon #10. 

Challenge here will be to communicate from the page towards the dev tool.

**Comment by facebook-github-bot-7** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by jaredly** [comment]
See https://github.com/facebook/react-devtools/pull/17
