### ISSUE TITLE
[New DevTools] Font size too small in Opera on Windows

### ISSUE THREAD

**Issue by dylanparry** [facebook/react-devtools#110]
Hi,

The font size for the new DevTools is too small. I’d expect it to be using the same size as the elements panel. As it is currently, it’s pretty difficult to see what each node is. I’ve attached an image showing the Elements Panel and the DevTools next to each other so you can see the difference.

Is there a setting somewhere that I have overlooked?

Thanks,

![devtools](https://cloud.githubusercontent.com/assets/3692873/9058444/056ad2da-3a99-11e5-89e6-ceea17d8c960.png)

**Comment by jaredly** [comment]
Thanks for letting us know! It looks like you're on windows?

**Comment by dylanparry** [comment]
Yes, using Windows 10. I’ve got the DevTools installed on Opera 31 using the CRX extension. Bug in Opera makes the scrollbars look like something from Windows 95 :)

**Comment by jaredly** [comment]
Haha OK. I used the font size from Chrome, so maybe opera has slightly different settings? I'll see if I can investigate

**Comment by jaredly** [comment]
In chrome, at least, you can also ctrl "+" to increase the font size in the devtools - for a temporary fix

**Comment by dylanparry** [comment]
Also works in Opera. It also resizes the page’s text if the dev tools are docked, which means having to focus back to the page and hitting crtl+0 to return the correct page font size—oddly this leaves the dev tools font still the bigger size, which is nice.

**Comment by gaearon** [comment]
Going to close since nobody's actively looking into this and there's a workaround.
