### ISSUE TITLE
Don't scroll node into view if it's already fully in the view

### ISSUE THREAD

**Issue by gaearon** [facebook/react-devtools#1104]
See here:

![scrolling](https://dzwonsemrish7.cloudfront.net/items/303d2h2K30162Z1D0Z3g/Screen%20Recording%202018-08-21%20at%2007.19%20PM.gif?v=e94dc6fa)

I wouldn't expect scroll to happen because all of these nodes are already into view. The jumping happens too often and I think it's a bit jarring.

Ideally we shouldn't jump if a node is already fully in the view.

**Comment by gaearon** [comment]
We'll release with this behavior but the plan is that @bvaughn will look into it next week after he's back from a vacation

**Comment by bvaughn** [comment]
Fixed via c74acf5 (PR #1112)
