### ISSUE TITLE
DevTools perf regression for React v16

### ISSUE THREAD

**Issue by bvaughn** [facebook/react-devtools#1106]
### Steps to reproduce:
1. Checkout the repro project:
```js
git clone git@github.com:bvaughn/hamilton.git
cd hamilton
git checkout buggin
yarn install
yarn start
```
1. Open DevTools and let the app connect
1. Scroll slowly and watch for jank

Note that this jank doesn't appear on older versions of the app, although I stepped back as far as 82c1723 (the last release version) and was also able to reproduce it.

This app is a bit unique in what it's doing. It's worth noting that this performance slowness I'm seeing also occurs for React 15.x (when DevTools is active).

**Comment by ChrisFan** [comment]
Come across the same issue...sometimes it may block the webview(inside electron) several seconds

**Comment by alexreardon** [comment]
I can confirm that this is an issue. I am developing for `react-beautiful-dnd` and the dev tools cause the library to become almost unusable - even when the dev tools are closed

**Comment by alexreardon** [comment]
I think it might be struggling with the frequency of updates we are performing (trying for 60 per second)

**Comment by alexreardon** [comment]
<img width="226" alt="screen shot 2018-09-17 at 8 52 09 am" src="https://user-images.githubusercontent.com/2182637/45601863-0f838a00-ba57-11e8-8309-ce5984331119.png">


(last update is the reorder update one which will be expensive)

Most updates:

```
Committed at: 1.2s
Render duration: 1.2ms
```

**Comment by alexreardon** [comment]
I would be fine if there was a performance impact when the profiler was running, but it was unexpected to me for it to have such a big impact even when the profiler was not running

**Comment by alexreardon** [comment]
This issue worries me a bit because it means that consumers of `react-beautiful-dnd` who are running in dev mode on `16.5` will start having major performance drops

**Comment by alexreardon** [comment]
I did some investigation using the `unstable_Profiler` export from `react` and found:

[tweet](https://twitter.com/alexandereardon/status/1041493936194301952)

> - When wrapping in the unstable_Profiler the major performance impact is gone
> - When I open the React dev tools the major performance issue returns

This is closer to the ideal state, except that it would also be great if there was no performance slow down when the react dev tools are open and the profiler is not running

**Comment by bvaughn** [comment]
> When dev tools open but profiler not running: no cost
When dev tools open and profiler running: cost is fine

React auto-profiles when it detects DevTools because DevTools needs "tree base time" values for the tree at any given point in time when a user might start profiling. Else I wouldn't have a baseline for rendering the flame graph. That being said, none of the advanced metrics (beyond base time) are collected unless the user clicks the record button—so the overhead is expected to be minimal.

Sounds like something unexpected is happening here though. Might have something to do with the frequency of your updates, combined with the size of your application tree. (Frequency alone should not be sufficient to cause problems, as our suspense test harnesses renders 60fps for its progress meter.)

If you'd like to dig in and do some profiling of the profiler, you can pop DevTools out to a detached window and then spawn a second set of browser DevTools to profile the react DevTools. I might not be able to dig into this for a few days. Lots going on at the moment.

**Comment by alexreardon** [comment]
I won't be able to take a look this week either - trying hard to get `version 10` of `react-beautiful-dnd` out. 

I totally get that other things are going on!

This issue is fairly major for `react-beautiful-dnd` as a consumer upgrading to React `16.5+` will have a near broken drag and drop experience in dev mode if they have the dev tools installed

**Comment by gaearon** [comment]
>That being said, none of the advanced metrics (beyond base time) are collected unless the user clicks the record button—so the overhead is expected to be minimal.

There is a fixed cost to `performance.now` so I wonder if this becomes noticeable at some point.

**Comment by bvaughn** [comment]
> There is a fixed cost to `performance.now` so I wonder if this becomes noticeable at some point.

This is why I asked Alex to try wrapping his app root in `<React.unstable_Profiler>` to rule that out. His findings [above](https://github.com/facebook/react-devtools/issues/1106#issuecomment-421868056) seem to confirm that the profiler itself (with its calls to `performance.now`) doesn't add much overhead.

The DevTools profiler plugin doesn't call `performance.now()` very often, but it seems like something else that it's doing is adding overhead.

**Comment by alexreardon** [comment]
My current mitigation: log a warning in the console if using `React` version 16.5+ so that people are not taken by surprise 😊

**Comment by marvinhagemeister** [comment]
> React auto-profiles when it detects DevTools because DevTools needs "tree base time" values for the tree at any given point in time when a user might start profiling. Else I wouldn't have a baseline for rendering the flame graph.

@bvaughn I stumbled upon this with my preact integration. I'd love to only collect timings when the Profiler is recording. Perhaps another solution would be to force a re-render starting at the root when record is pressed in the Profiler. That way we could only collect timings when needed.

**Comment by bvaughn** [comment]
Relying on a forced re-render from root doesn't seem like a good idea. Just calling `forceUpdate()` on the top note wouldn't be sufficient, since `shouldComponentUpdate` could block the re-render at any level. The only way (I think) to _safely_ do it would be to essentially unmount and remount the entire tree– but then you blow away application state, which might be essential to the interaction you're trying to profile.

I think paying a (relatively small) amortized cost of updating base times seems safer and better.

**Comment by marvinhagemeister** [comment]
Oh right, I totally forgot about `shouldComponentUpdate` 👍

**Comment by bvaughn** [comment]
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools
