### ISSUE TITLE
Profiler: Always show profiler tab (even when profiling not supported)

### ISSUE THREAD

**Issue by bvaughn** [facebook/react-devtools#1117]
Show Profiler tab _always_ (not just if a profiling capable build of React is present). This tab can be used to up-sell a React upgrade if the version is too old to support profiling.

**Comment by ashtonsix** [comment]
Should the profiler tab always show up (today) when `react@^16.5.0` & `react-devtools@3.3.2` (as Chrome extension) are installed?

**Comment by joetidee** [comment]
I'm using react and react-dom v16.8.1 and cannot see the Profiler tab - any ideas why?

**Comment by bvaughn** [comment]
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools
