### ISSUE TITLE
Ctrl+F find doesn't work, and "Search bar" doesn't attribute names/values or content

### ISSUE THREAD

**Issue by wulftone** [facebook/react-devtools#1136]
I'm on version 3.3.1, and Ctrl+F doesn't actually find anything.

Also, the search bar seems to only match on tag/element names, not element attributes or their values.

**Comment by wulftone** [comment]
It could be noisy, but I was just expecting one or the other to help me find what I was looking for, and it couldn't :(.  I don't know if Ctrl+F ever worked.  I think it would be useful if it did, though.

**Comment by bvaughn** [comment]
For what it's worth, I'm pretty sure that CTRL+F ever worked, and we never intended to match on attributes because that would slow down searching.

**Comment by bvaughn** [comment]
I'm going to close this as "working as intended" 😄We can always continue discussion here and re-open in the future if it seems appropriate.
