### ISSUE TITLE
Chrome Remote Debugger support

### ISSUE THREAD

**Issue by MOZGIII** [facebook/react-devtools#1137]
I'm trying to debug a React app running on an Android tablet at Google Chrome using remote debugger.
I have the extension installed (at desktop Chrome), however "React" tab doesn't show up in dev tools.

How can I make it work? I suspect remote debugger doesn't support extensions at all...

Is there a way to install react dev tools in the app itself, like it can be done with redux dev tools?

**Comment by ngyikp** [comment]
You need to use the standalone app: https://github.com/facebook/react-devtools/tree/master/packages/react-devtools

**Comment by MOZGIII** [comment]
Thanks, it seems to be what I need.
https://github.com/facebook/react-devtools/tree/master/packages/react-devtools#usage-with-react-dom

**Comment by FL0RIANMEYER** [comment]
![image](https://user-images.githubusercontent.com/28124170/45191755-5e564600-b245-11e8-9992-73756bee6a8f.png)


Redux Extension works for remote debugging.
Maybe there is also a way for React DevTools.
