### ISSUE TITLE
Cannot run react-devtools

### ISSUE THREAD

**Issue by MakotoE** [facebook/react-devtools#1143]
I ran the command `yarn global add react-devtools`, which finished successfully.

```
yarn global v1.9.4
[1/4] Resolving packages...
[2/4] Fetching packages...
[-----------------------------------------------------------------------] 0/228(node:4350) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[3/4] Linking dependencies...
[4/4] Building fresh packages...

success Installed "react-devtools@3.3.3" with binaries:
      - react-devtools
Done in 1.16s.
```

However, I can't use the command `react-devtools` because it isn't found.

```
bash: react-devtools: command not found
```

I'm on Debian GNU/Linux 9 (stretch).

Edit: corrected the first output

**Comment by MakotoE** [comment]
Oops, my bad. I have corrected the original post.

**Comment by bvaughn** [comment]
Sounds like something gone wrong with the `yarn global add` / `npm i -g` process. I don't think this sounds like it has anything to do with `react-devtools` specifically. I'd try to verify it but I don't have a Debian machine to try it on, only OSX. Sorry mate.

**Comment by MakotoE** [comment]
No worries; I'll go and bother yarn with this.
