### ISSUE TITLE
dev tool state value is not correct

### ISSUE THREAD

**Issue by mqliutie** [facebook/react-devtools#1153]
Look at the pic
![image](https://user-images.githubusercontent.com/11795518/45332652-6e06bf00-b5a4-11e8-8002-23bcb1dd8f1e.png)

**Comment by ngyikp** [comment]
Please provide a link to the problematic site so others can reproduce the issue and investigate.

**Comment by mqliutie** [comment]
It's development environment.
I change the state by dev tool (not $r.setState()). but now I can not reproduce

**Comment by bvaughn** [comment]
DevTools should reflect the lat _committed_ state value. Your `console.log` call reflects the value on the instance, but the instance may not have actually rendered+committed if e.g. `shouldComponentUpdate` returned false _or_ something directly mutated the state (e.g. `this.state.foo = 123`).

Can you please share a repro case in Code Sandbox (or similar)? There's not a lot we can do without seeing your app source.

**Comment by bvaughn** [comment]
Closing due to lack of repro info. Will re-open later if sufficient info is provided.
