### ISSUE TITLE
Consider injecting styles to style tags?

### ISSUE THREAD

**Issue by infinnie** [facebook/react-devtools#1163]
Inline styles seem to have become a complete mess in React DevTools. We have to add event handlers for even hover or focused states. To make things worse, inline styles do not support pseudo-classes and pseudo-elements like `:before`, `:after`, and placeholders. Using libraries such as Styled Components to dynamically inject styles, the problem could be alleviated to a certain extent.

**Comment by infinnie** [comment]
Improved UI together with
* Pseudo classes
* Pseudo elements
* Key frame animations

Could be a tangible benefit for end users.

**Comment by bvaughn** [comment]
I don't see how pseudo classes or elements improves UI for end-users. They wouldn't even notice.

As for animations, DevTools doesn't currently animate anything _except_ the profiler flame chart, and that's already built with CSS transitions. 😄

**Comment by infinnie** [comment]
Say I want a different color for placeholders which behaves consistently in all browsers.

**Comment by bvaughn** [comment]
> Say I want a different color for placeholders which behaves consistently in all browsers.

I don't understand. This could be implemented with inline styles just as easily as with external styles.

> What’s more, with CSS extracted to style tags more types of animation could be empowered.

True, but we don't have any use cases for new animations currently– so I don't think we should invest a lot of effort into that refactor.

**Comment by infinnie** [comment]
Injected styles but not inline ones.
