### ISSUE TITLE
React devtools are broken in the latest Firefox Nightly

### ISSUE THREAD

**Issue by BrandonWade** [facebook/react-devtools#1169]
As of today, it seems that the devtools are completely broken in the latest Firefox Nightly. The extension is throwing the same 2 errors in the Browser Console.

Screenshot with the errors:
https://i.imgur.com/EruH6dR.png

Reddit post I made with a few more details:
https://old.reddit.com/r/firefox/comments/9it1kl/react_devtools_broken_in_the_latest_nightly/

**Comment by captainbrosset** [comment]
I have a feeling this is caused by a change in Firefox, not in the extension.
So I filed a bug here: https://bugzilla.mozilla.org/show_bug.cgi?id=1494281

**Comment by captainbrosset** [comment]
I found the cause for this to be a bug that landed in Firefox Nightly yesterday: https://bugzilla.mozilla.org/show_bug.cgi?id=1485676

**Comment by captainbrosset** [comment]
Bug https://bugzilla.mozilla.org/show_bug.cgi?id=1494281 is now fixed in Firefox Nightly. So React DevTools will start working again in Firefox Nightly!

**Comment by BrandonWade** [comment]
Looks like everything is working as expected in the latest Nightly. Thanks for your hard work!
