### ISSUE TITLE
I am not able to update state in the dev tools

### ISSUE THREAD

**Issue by budstamper** [facebook/react-devtools#1183]
Here is the app: http://dev-clicker.herokuapp.com You will have to sign into the app to get to a meaningful page.

When I drill down into the component and click the state on the right to update it does not update into my games component or into my axios call. I also tried using $r.setState but that did not work either. Also I got an error that went something like "state cannot be changed in this component instance" before although I am not able to replicate it.

[Here's a screenshot with the important parts penciled in red.](https://memefly.me/i/e23d2fa499098baa06e3df39844abb84.jpg)

Please correct me if I am doing something wrong.

**Comment by bvaughn** [comment]
Hm...works for me? 😄

![kapture 2018-12-05 at 11 15 00](https://user-images.githubusercontent.com/29597/49537908-0a2c2380-f87f-11e8-97d7-9397275e0d5b.gif)

> it does not update into my games component or into my axios call

Not sure what this means, sorry. Looks like DevTools is working for me though!
