### ISSUE TITLE
Using backend via npm

### ISSUE THREAD

**Issue by Raathigesh** [facebook/react-devtools#1185]
I'm experimenting with building a rapid prototying tool and interested in consuming certain components from `backend` folder as below. 
```javascript
import installGlobalHook from "./backend/installGlobalHook";
import setupBackend from "./backend/backend";

installGlobalHook(window);

const hook = window.__REACT_DEVTOOLS_GLOBAL_HOOK__;
setupBackend(hook);

hook.sub("renderer-attached", ({ id, renderer, helpers }) => {});
```

But I did not see a way of doing it using `react-devtools-core` since it only exposes `connectToDevTools`. Is there a way to directly consume just the `backend` methods via npm?

**Comment by bvaughn** [comment]
No, sorry. We only publish `backend` and `standalone` entry points, and they're pre-packaged/bundled. Your best bet for the time being would be to fork the code in this package. It's hard to keep up with DevTools as-is (without supporting additional frontend targets). 😅 Thanks for understanding! 🙇
