### ISSUE TITLE
DevTools + styled-components v4 = unusable bloat

### ISSUE THREAD

**Issue by corysimmons** [facebook/react-devtools#1192]
https://spectrum.chat/?thread=a5856708-0786-499d-ab32-3626b45a1094

Is there anything that can be done to fix this?

**Comment by bvaughn** [comment]
Let's add this as a note to issue #1076– which is about providing more control over filtering components in DevTools. As things currently stand, DevTools is doing the right thing by showing all of the wrappers/HOCs that styled-components is using, but I understand it's not great from an ergonomics standpoint.

The recently-released [static `contextType` attribute](https://reactjs.org/docs/context.html#classcontexttype) can help a little with a single context, but the "silver bullet" for this type of thing in the long term will be our [recently announced feature "hooks"](https://reactjs.org/docs/hooks-intro.html).

In the meanwhile, #1076 will provide some controls over the display tree 😄
