### ISSUE TITLE
Devtools break new projects created with create-react-app when react@16.6.0 and react-dom@16.6.0

### ISSUE THREAD

**Issue by dbryantm** [facebook/react-devtools#1195]
Ran `create-react-app react-test` then `npm start` on the fresh project with no changes and I get the following error when using react@16.6.0 and react-dom@16.6.0:

```
Uncaught TypeError: Cannot read property 'displayName' of null
    at getDisplayName (backend.js:9159)
    at getDataFiber (backend.js:9888)
    at enqueueMount (backend.js:10158)
    at mountFiber (backend.js:10246)
    at backend.js:10306
    at Set.forEach (<anonymous>)
    at Object.walkTree (backend.js:10304)
    at backend.js:8534
    at <anonymous>:52:32
    at Array.map (<anonymous>)
    at Object.emit (<anonymous>:51:66)
    at setupBackend (backend.js:8621)
    at module.exports (backend.js:8567)
    at Agent.<anonymous> (backend.js:116)
    at Agent.g (backend.js:981)
    at Agent.EventEmitter.emit (backend.js:894)
    at backend.js:302
    at backend.js:7619
    at Array.forEach (<anonymous>)
    at backend.js:7618
    at Array.forEach (<anonymous>)
    at Bridge._handleMessage (backend.js:7611)
    at listener (backend.js:92)
```

If I rollback the version to react@16.5.2 and react-dom@16.5.2 then I get no errors. I believe I've tracked down the issue to https://github.com/facebook/react-devtools/blob/faa4b630a8c055d5ab4ff51536f1e92604d5c09c/backend/getDisplayName.js#L27 but not sure where to go from here. 

I've also tried this on an existing project with the same results. Any help would be appreciated. Thanks in advance!

**Comment by bvaughn** [comment]
I think this means that you aren't running the latest release of DevTools (3.4.2). Can you verify?

**Comment by dbryantm** [comment]
Thanks for replying @bvaughn and sorry for the delayed response! I currently have React Developer Tools @ 3.4.2 installed on Chrome @ 70.0.3538.77 running on MacOS 10.14.

**Comment by dbryantm** [comment]
Well, I just tried updating the project and it seems to be working now. There's no direct way for me to verify the version of the plugin I had at that time, according to the Chrome webstore it was released on 10/22, and I tried updating the extensions before reaching out with no luck. I believe this is essentially not reproducible so I'm going to close this issue. Thanks for the help!

**Comment by avanslaars** [comment]
> Well, I just tried updating the project and it seems to be working now. There's no direct way for me to verify the version of the plugin I had at that time, according to the Chrome webstore it was released on 10/22, and I tried updating the extensions before reaching out with no luck. I believe this is essentially not reproducible so I'm going to close this issue. Thanks for the help!

I had the same issue and I was running version 3.4.0. After restarting Chrome, I verified that it was updated to version 3.4.2 and the problem went away.

**Comment by bvaughn** [comment]
I think it probably just required a restart for the new one to be picked up, as @avanslaars mentioned 😄 Either way, glad to hear it's resolved now!

**Comment by kyz1607** [comment]
I also have this problem, thank you for your approach
