### ISSUE TITLE
[dt-next] Move to the search input to the top, and highlight it when a search query is entered

### ISSUE THREAD

**Issue by nt1m** [facebook/react-devtools#120]
- Moving it to the top will make it more discoverable
- Highlighting the search box will make the UX less confusing if the markup view is filtered. See Chrome/Firefox DevTools' filter styles input for example.

**Comment by jaredly** [comment]
A wanted to keep it out of people's faces b/c it seems like a secondary use case.
Open to discussion though.
Highlighting it is a great idea :+1:

**Comment by jaredly** [comment]
@nt1m what do you thing of #141?

**Comment by nt1m** [comment]
@jaredly Unfortunately, I'm getting a bunch of "permission denied" errors trying to `npm install`

**Comment by kassens** [comment]
We highlight the search box now (thanks for the idea) and I think the argument of secondary functionality for filtering is convincing.
