### ISSUE TITLE
Incorrect element position - Y axis

### ISSUE THREAD

**Issue by rubossq** [facebook/react-devtools#1206]
I have the issue with webpack-dev-server and react-devtools.
The page on the picture below contains header from webpack-dev-server and iframe. 
As you can see - offset by Y axis is the same as webpack-dev-server's header height.
I think that there is possibility to remove the header. Btw maybe you need to know about it =)

![image](https://user-images.githubusercontent.com/16590371/47712530-a3449a80-dc40-11e8-8a0f-b2ff76c5f147.png)

**Comment by bvaughn** [comment]
Is this running somewhere we can see?

**Comment by bvaughn** [comment]
I don't feel strongly about this, but my gut tells me that it's not super important to fix.

If we get repro steps in the future, or if more people comment and say they're impacted by this, maybe we will reconsider and reopen. 😄

**Comment by bvaughn** [comment]
I think I figured out how to repro this problem, and fixed it in the new DevTools in commit https://github.com/bvaughn/react-devtools-experimental/commit/c4d6fdbfdbc13885d9abcd493d16bfb607e8f373. That fix _could_ be backported to the legacy DevTools if anyone cared to, but maybe not worth doing? Should be fixed for the next one though!
