### ISSUE TITLE
Better display for string contexts

### ISSUE THREAD

**Issue by lydell** [facebook/react-devtools#1212]
When using `<SomeContext.Provider value="string">` and consuming that with the new `contextType` from React 16.6.0, the devtools displays the context value like an array:

```
0: "s"
1: "t"
2: "r"
3: "i"
4: "n"
5: "g"
```

It would be nicer if it was displayed something like this:

```
"string"
```

Test page:

```html
<!doctype html>
<meta charset="utf-8">
<title>React Context test</title>
<div id="container"></div>
<script src="https://unpkg.com/react@16.6.0/umd/react.development.js"></script>
<script src="https://unpkg.com/react-dom@16.6.0/umd/react-dom.development.js"></script>

<script>
  const LanguageContext = React.createContext();

  class Test extends React.Component {
    render() {
      return React.createElement("p", {}, `Language: ${this.context}`);
    }
  }

  Test.contextType = LanguageContext;

  ReactDOM.render(
    React.createElement(
      LanguageContext.Provider,
      { value: "en-us" },
      React.createElement(Test),
    ),
    container
  );
</script>
```

Screenshot:

![screenshot from 2018-11-01 15-23-03](https://user-images.githubusercontent.com/2142817/47857541-22c19d80-ddea-11e8-98e5-efc50572fc26.png)

**Comment by bvaughn** [comment]
Off the top of my head, I think the reason for this is that the [legacy `context` API](https://reactjs.org/docs/legacy-context.html) supported _multiple context providers_, always wrapping values up in an `Object`.

Newer context APIs ([`Context.Consumer`](https://reactjs.org/docs/context.html#contextconsumer), [`static contextType`](https://reactjs.org/docs/context.html#classcontexttype), and [`useContext`](https://reactjs.org/docs/hooks-reference.html#usecontext)) all support a _single context value_ (which can potentially a primitive value).

DevTools needs to be updated to be aware of this. Maybe `PropsState` could switch between showing a `DataView` for legacy context and a `DataItem` for newer context values?

**Comment by yifei-fu** [comment]
Hi @bvaughn I made a PR (#1256) to fix this issue. I refactored DataView so that it accepts and displays primitive values properly. Here is a test page:
```
<!doctype html>
<meta charset="utf-8">
<title>React Context test</title>
<div id="container"></div>
<script src="https://unpkg.com/react@16.6.0/umd/react.development.js"></script>
<script src="https://unpkg.com/react-dom@16.6.0/umd/react-dom.development.js"></script>

<script>
    const TestContext = React.createContext();

    class Test extends React.Component {
        render() {
            return React.createElement("p", {}, `Context: ${JSON.stringify(this.context)}`);
        }
    }
    Test.contextType = TestContext;

    ReactDOM.render(
        React.createElement(
            React.Fragment,
            {},
            [
                React.createElement(
                    TestContext.Provider,
                    { value: 'string' },
                    React.createElement(Test),
                ),
                React.createElement(
                    TestContext.Provider,
                    { value: {a: 0, b: 1} },
                    React.createElement(Test),
                ),
            ]
        ),
        container
    );
</script>
```
![image](https://user-images.githubusercontent.com/13537021/50545550-141a1b80-0bcc-11e9-9f7d-075455be14ad.png)
![image](https://user-images.githubusercontent.com/13537021/50545551-167c7580-0bcc-11e9-8293-de09bac9a280.png)

**Comment by bvaughn** [comment]
Thanks! I'll review this once I'm back from PTO/holiday (on Wednesday)
