### ISSUE TITLE
ForwardRef components don't show their props in the tree

### ISSUE THREAD

**Issue by Kovensky** [facebook/react-devtools#1213]
Their props always show up as `null`.

![image](https://user-images.githubusercontent.com/73085/47888932-89969380-de8a-11e8-91d0-8ff278b43d4c.png)

https://codesandbox.io/s/8lp03q2l3l / https://8lp03q2l3l.codesandbox.io/

Perhaps this was intended for when `forwardRef` is used solely to rename `ref` to a different prop name; but especially with `useImperativeMethods` there are full-fledged components that would be used as a `forwardRef`.

**Comment by jedwards1211** [comment]
the havoc that forward refs have caused in the ecosystem was not worth it
