### ISSUE TITLE
React 14, Portals, undefined root

### ISSUE THREAD

**Issue by coolassassin** [facebook/react-devtools#1223]
https://github.com/facebook/react-devtools/blob/f8c59704f4a70fb1197404722c1c51104a703c71/plugins/Profiler/backend.js#L27

In react 0.14, while using Portal with the swithced on tool i have mistakes here.
Last root in an agent set is undefined. ([Example](https://drive.google.com/file/d/18B2q0GO4iNmqBUUPW0n7xDFvprxPNJiT/view?usp=sharing))

**Comment by bvaughn** [comment]
Can you point me at a Code Sandbox (or similar) repro case?

**Comment by bvaughn** [comment]
Closing due to lack of repro info and old version of React.
