### ISSUE TITLE
Expected to find at least one React Native renderer on DevTools hook.

### ISSUE THREAD

**Issue by yuyifeng** [facebook/react-devtools#1225]
![simulator screen shot - iphone x - 2018-11-12 at 16 59 04](https://user-images.githubusercontent.com/7882115/48336845-49aa8a00-e69c-11e8-9021-0219418c560b.png)

I got this error when toggle inspector. Need help !!! T_T

ios simulator 11.1
"react-native": "0.55.0"

**Comment by bvaughn** [comment]
[`Inspector` is part of react-native](https://github.com/facebook/react-native/blob/1fa56a0ac4ae24a01811db4cf23c3264c60ac342/Libraries/Inspector/Inspector.js#L42), not DevTools. At least when this was reported before (#1032) it was reported that the [same bug occurred even without react-devtools](https://github.com/facebook/react-devtools/issues/1032#issuecomment-395104543).

Are you by chance using the react-native-root-toast or react-native-root-siblings libraries? Seems related: magicismight/react-native-root-toast/issues/89
