### ISSUE TITLE
Got standalone devtools working with wsl on windows

### ISSUE THREAD

**Issue by williscool** [facebook/react-devtools#1228]
Not an issue just sharing. Not exactly sure how to turn it into a pull request either.

1. 

in the `packages/react-devtools` directory 

```
yarn && yarn remove electron && npm_config_platform=win32 yarn install electron && yarn start
```

2. 

Only patch is 

```
diff --git a/packages/react-devtools/bin.js b/packages/react-devtools/bin.js
index b1d06e4..fd6c5d6 100755
--- a/packages/react-devtools/bin.js
+++ b/packages/react-devtools/bin.js
@@ -10,7 +10,7 @@ updateNotifier({pkg}).notify({defer: false});

 var result = spawn.sync(
   electron,
-  [require.resolve('./app')].concat(argv),
+  [require.resolve('./app').replace('/mnt/c/', 'C:\\')].concat(argv),
   {stdio: 'ignore'}
 );
 process.exit(result.status);

```

I'm sure doing the replace the way I am is wrong and there is something better but it works like a charm

**Comment by bvaughn** [comment]
Thanks for sharing! I'll tag it as a discussion in case it's helpful to someone else in the future :)

**Comment by guschnwg** [comment]
For me:

`sudo npm_config_platform=win32 npm install -g react-devtools --unsafe-perm=true`

and your change in `react-devtools/bin.js`

Thanks :)
