### ISSUE TITLE
Unable to resolve module 'react-devtools-core' from 'node-modules/react-native/Libraries/Core/Devtools/setupDevtools.js'

### ISSUE THREAD

**Issue by qualwebs** [facebook/react-devtools#1229]
"react": "16.3.0"
"react-native": "0.51.0"

![img_3470](https://user-images.githubusercontent.com/13719000/48620403-0dda3200-e9c6-11e8-84b1-4493b57cbaca.PNG)

**Comment by bvaughn** [comment]
I think this should be reported against react-native rather than DevTools. We publish both packages (`react-devtools` and `react-devtools-core`) from this repro, but if core hasn't been bundled correctly along with a particular React Native build, that's a separate issue.
