### ISSUE TITLE
Chrome disables non-Chrome Web Store extensions

### ISSUE THREAD

**Issue by marclar** [facebook/react-devtools#123]
It doesn't even let you manually re-enable them; you must remove and reinstall:

> Extensions that have not been published on the Chrome Web Store are grayed out and you won't be able to turn them back on.

https://support.google.com/chrome/answer/2811969?p=ui_remove_non_cws_extensions&rd=1

Windows 7, Version 44.0.2403.130 m

**Comment by jaredly** [comment]
Well that's annoying.
It will only be an issue during the beta, though. If you really want to try it out before we release, it looks like you can use the [dev channel](http://www.chromium.org/getting-involved/dev-channel), which should allow you to use non-chrome web store extensions.

**Comment by jaredly** [comment]
Does it still happen if you check "Developer Mode" at the top of the extensions page?

**Comment by marclar** [comment]
Yeah, I'm in developer mode :/

**Comment by jquense** [comment]
this is crazy...it refused to let me reenable it b/c "it may have been installed without your knowledge" real classy Google.

**Comment by spicyj** [comment]
If you unzip it (just rename .crx to .zip), you can use "Load unpacked extension…" in developer mode.

**Comment by marclar** [comment]
Cool -- thanks, @spicyj

**Comment by wesbos** [comment]
The unzip didn't work for me, but I was able to:

1.  download the source and open in command line
2. `npm install` 
3. `cd shells/chrome`
4. `webpack`
5. Load unpacked extension via chrome extensions

**Comment by saelfaer** [comment]
just add it to the webstore, and publish it in a hidden state
you can share the URL but never worry about it being installed by people who don't want it, since it won't show up in searches or lists

**Comment by af7** [comment]
I agree with @saelfaer, Google officially supports this "hidden state" policy so you could use it and make things easier. See their answer here: https://productforums.google.com/forum/#!topic/chrome/2yTVWdfC4Gg

(just search for word 'hidden')

**Comment by af7** [comment]
Actually, I just tried to install it on *Google Canary* (which should allow you to do so, as it is very experimental and targeted to developers) and it disabled it. It was under `developer mode`.

**Comment by ngyikp** [comment]
Loading off-store extensions are never allowed on Stable/Beta/Dev/Canary on Windows and Mac.
https://blog.chromium.org/2015/05/continuing-to-protect-chrome-users-from.html

The only thing that "developer mode" does is reveal the three buttons, you still cannot load off-store CRX/ZIP extensions even if you turn it on. You must load it unpacked into a folder like what @wesbos did and probably see an annoying "Disable developer mode extensions" prompt every time you open Chrome.

**Comment by bman654** [comment]
Weird.  I have Chrome 44.0.2403.155 m and I was just able to install it by dragging the CRX into the extensions page.

This is on Windows 7

![image](https://cloud.githubusercontent.com/assets/541772/9275280/9fb70ba4-4261-11e5-9e60-fb1c1cf9b917.png)

![image](https://cloud.githubusercontent.com/assets/541772/9275289/ab045b60-4261-11e5-807e-3f6db3313a4f.png)

**Comment by marclar** [comment]
@bman654 but does it disable it when you restart?

**Comment by bman654** [comment]
@marclar Well, I'd rather not find out right now since it is working :stuck_out_tongue_winking_eye:

**Comment by bman654** [comment]
@marclar I rebooted over the weekend indeed it is now disabled :cry:

**Comment by marclar** [comment]
Sorrryyyyyyy :/

**Comment by wesbos** [comment]
Here is a built version of the dev tools for chrome → http://wes.io/cl6R

1. Go to extensions
2. Click Developer Mode Checkbox
3. Click load unpacked extension
4. Select this folder. 

If someone could try it out and let me know if that works, it would be great. I'm teaching a course where I need these dev tools and I need a fast way have students install the dev tools. 

Ideally we could have the 2.0 tools set as hidden. Any way to do this @jaredly?

**Comment by spicyj** [comment]
@wesbos I'm planning to push out the new devtools this week to everyone on the Chrome store.

**Comment by wesbos** [comment]
Amazing - thank you!

**Comment by kassens** [comment]
Since the new add-on is now on the Chrome store I'm closing this.
