### ISSUE TITLE
Using react-devtools for testing

### ISSUE THREAD

**Issue by isi-gach** [facebook/react-devtools#1231]
I managed to display in `react-devtools` the components mounted by enzyme using [react-render-hook](https://github.com/bruderstein/react-render-hook):
https://github.com/isi-gach/react-devtools-jest
Could be possible to also see the rendered web page? I think that would help a lot to write and debug tests using Jest and jsdom.

**Comment by bvaughn** [comment]
I'm not _entirely_ sure what you're asking for, but this doesn't sound like something we would want to add any complexity to DevTools in order to support. (This extension is already pretty complicated, and added complexity makes it harder to maintain and updated, etc.)

Thanks for understanding 🙇
