### ISSUE TITLE
Searching by props

### ISSUE THREAD

**Issue by alexbourla** [facebook/react-devtools#1232]
I'm trying to utilise React dev-tools when security testing React applications (I realise this is definitely not really the intended purpose). 

As a result one thing that I'd really like to be able to do is search through the entire component tree for any `dangerouslySetInnerHTML` props. 

It doesn't look like this is possible with react dev-tools (or am I missing something obvious) because you can only search by component name. 

Is there any easy way to do this, ideally using React dev-tools or otherwise? I was wondering if I could select the outer most component and interate through the children/props via the `$r` variable but not really got enough experience/knowledge to know if this is worth persuing as a (slightly hacky!) solution.

Any help would be appreciated!

**Comment by bvaughn** [comment]
Sorry @alexbourla, but searching by prop/prop name isn't something we support (or have any plans to support) 🙇

**Comment by joejordan** [comment]
I'm picking up a rather large React app, and searching by prop value would be very helpful in getting up to speed with the project, i.e. determining what is stored where at a glance. +1 for the feature request.
