### ISSUE TITLE
 [3.4.3] Warning: unknown call: "relay:check"

### ISSUE THREAD

**Issue by allmaxgit** [facebook/react-devtools#1233]
I have warning `unknown call: "relay:check"` in React native 0.57.5 after update react-devtools-core from 3.4.2 to 3.4.3.

**Temp solution**
Downgrade react-devtools-core to 3.4.2 in yarn.lock
```
react-devtools-core@^3.4.2:
  version "3.4.2"
  resolved "https://registry.yarnpkg.com/react-devtools-core/-/react-devtools-core-3.4.2.tgz#4888b428f1db9a3078fdff66a1da14f71fb1680e"
  integrity sha512-1pqbxenMeOiVPLf5Fm69woc+Q/pb/lLfWCizJuVJQDm9v7x0fcr76VMcq6Q30Onv3ikkfrlAQgOcOdCk/0t5tA==
```

**Comment by KalebPortillo** [comment]
downgrade it to `3.4.2` didn't work for me, still getting the warning

**Comment by dmitryame** [comment]
This solution didn't work me either. Anybody, any resolution on this issue?

**Comment by vovkasm** [comment]
Solution for me was simple (I described it here: https://github.com/facebook/react-native/issues/22116#issuecomment-440551681).

> This warning was resolved after update global react-devtools package 3.4.2 -> 3.4.3, it was because inconsistent versions of global react-devtools and application react-devtools-core

**Comment by leoek** [comment]
You can disable the yellow box for this warning like this: `YellowBox.ignoreWarnings(['unknown call: "relay:check"']);`

**Comment by bvaughn** [comment]
The Relay classic plug-in was removed from DevTools by @avijohnson in #1224.

The error sounds like there are incompatible versions of `react-devtools` and `react-devtools-core` packages installed– one of which that still has the old plug-in, and one of which that doesn't.

React Native 0.57.7 wants `react-devtools-core@^3.4.2` which **won't** have the plug-in. (I believe 3.4.1 was the last version with it.)

I think you should be able to fix this error by updating `react-devtools` to 3.4.2+ as well, so they're in sync?

**Comment by bvaughn** [comment]
I'm going to close this issue since I'm pretty sure my comment above is the solution ^ but let's keep talking if there are questions or if I'm wrong. (We can re-open it if needed!)

**Comment by leoek** [comment]
@bvaughn Updating react-devtools seems to be the solution. I was using react-native-debugger 7.2.x with react-dev-tools 3.4.1... Unfortunately react-native-debugger 8.x does not work properly for me but that's a different issue.

**Comment by taschik** [comment]
I upgraded to ```react-devtools@3.4.3``` and ```react-devtools-core@^3.4.2``` but still receive the warning on RN 0.57.7. any other idea what could cause it?

```
 React Native Environment Info:
    System:
      OS: macOS 10.14.1
      CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
      Memory: 3.79 GB / 32.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.10.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 26, 27, 28
        Build Tools: 23.0.1, 25.0.0, 26.0.3, 27.0.3, 28.0.1, 28.0.2, 28.0.3
        System Images: android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.6.1 => 16.6.1
      react-native: ^0.57.7 => 0.57.7
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

**Comment by Ashoat** [comment]
Try clearing your lockfile... you may still have an older version being used by a dependency.

**Comment by taschik** [comment]
I removed the entire node_modules folder and reinstaleld everything. my package-lock looks like this:

```
"react-devtools": {
      "version": "3.4.3",
      "resolved": "https://registry.npmjs.org/react-devtools/-/react-devtools-3.4.3.tgz",
      "integrity": "sha512-LVinDD/pdm/WqmjJfyEc5ngv/JTcYaKCLSPeUZXwpjNpbI/w4ewuWklOLBuILOUlX1V9VYDaYRivz3j0DH2Lyw==",
      "requires": {
        "cross-spawn": "^5.0.1",
        "electron": "^1.8.7",
        "ip": "^1.1.4",
        "minimist": "^1.2.0",
        "react-devtools-core": "^3.4.3",
        "update-notifier": "^2.1.0"
      }
    },
    "react-devtools-core": {
      "version": "3.4.3",
      "resolved": "https://registry.npmjs.org/react-devtools-core/-/react-devtools-core-3.4.3.tgz",
      "integrity": "sha512-t3f6cRH5YSKv8qjRl1Z+1e0OwBZwJSdOAhJ9QAJdVKML7SmqAKKv3DxF+Ue03pE1N2UipPsLmaNcPzzMjIdZQg==",
      "requires": {
        "shell-quote": "^1.6.1",
        "ws": "^3.3.1"
      },
      "dependencies": {
        "ultron": {
          "version": "1.1.1",
          "resolved": "https://registry.npmjs.org/ultron/-/ultron-1.1.1.tgz",
          "integrity": "sha512-UIEXBNeYmKptWH6z8ZnqTeS8fV74zG0/eRU9VGkpzz+LIJNs8W/zM/L+7ctCkRrgbNnnR0xxw4bKOr0cW0N0Og=="
        },
        "ws": {
          "version": "3.3.3",
          "resolved": "https://registry.npmjs.org/ws/-/ws-3.3.3.tgz",
          "integrity": "sha512-nnWLa/NwZSt4KQJu51MYlCcSQ5g7INpOrOMt4XV8j4dqTXdmlUmSHQ8/oLC069ckre0fRsgfvsKwbTdtKLCDkA==",
          "requires": {
            "async-limiter": "~1.0.0",
            "safe-buffer": "~5.1.0",
            "ultron": "~1.1.0"
          }
        }
      }
    }
```

and still when building the app from scratch I get

```YellowBox.js:67 unknown call: "relay:check"```

**Comment by bvaughn** [comment]
Hm 🤔 Any chance you can set a breakpoint to see what's making that call? I think something must still be installing 3.4.2.

You can see there's no mention of "relay:check" in 3.4.3, but there is in 3.4.2 [backend](https://unpkg.com/react-devtools-core@3.4.2/build/backend.js) and [standalone](https://unpkg.com/react-devtools-core@3.4.2/build/standalone.js).

(I was wrong about 3.4.1 being the last version with "relay:check" in it. Looks like 3.4.2 was.)

**Comment by taschik** [comment]
Interesting so the only reference of 3.4.2 that I found was in react-native's package-lock.json itself within the node_modules folder:
```
...
"react-devtools-core": "^3.4.2",
...
```

However in my projects package-lock file as well as by calling 
```
npm list |grep react-devtools                                                                        1 ↵
npm ERR! peer dep missing: react@^16.6.3, required by react-test-renderer@16.6.3
├─┬ react-devtools@3.4.3
│ ├── react-devtools-core@3.4.3 deduped
├─┬ react-devtools-core@3.4.3
│ ├── react-devtools-core@3.4.3 deduped
```

I see I am absolutely on the latest version. I put in the call stack, hope that helps:
<img width="392" alt="react native debugger - connected port 8081 2018-12-04 12-04-24" src="https://user-images.githubusercontent.com/351623/49469618-d2f53e00-f7bc-11e8-8916-baaaa9f31b85.png">

**Comment by vovkasm** [comment]
@taschik Can you recheck that you actually run react-devtools version 3.4.3? Can it be so that you run globally installed react-devtools? Can you try to run react-devtools from your local installation as `<projectRoot>/node_modules/.bin/react-devtools` (hope, that yarn places binaries at the same location as npm)?

**Comment by bvaughn** [comment]
> I see I am absolutely on the latest version. I put in the call stack, hope that helps

Unfortunately the callstack doesn't tell me much. Those particular lines are the same between 3.4.2 and 3.4.3 for `backend`

**Comment by vovkasm** [comment]
It's `react-devtools` version <3.4.2 sends remotely packet that can't be handled by new `react-devtools-core`. So local callstack can't help.

**Comment by taschik** [comment]
@vovkasm I don't really get what you mean. How can I provide more context/information on how to fix it?

**Comment by bvaughn** [comment]
@vovkasm That summary sounds right to me 😄

**Comment by izikandrw** [comment]
I'm not totally following...How can we upgrade react-devtools-core as it is a dependency of react-native itself--doesn't react-native control what version it wants? In other words, in my package.json there is no direct dependency on react-devtools-core, it is only installed because react-native lists it as a dependency.

**Comment by taschik** [comment]
Thanks @vovkasm for the explanation. I am not using the electron application nor the debugger in the browser. I am using the React Native Debugger for debugging but there is no update available for it. anything I can do about it?
