### ISSUE TITLE
Pixel values should be rounded

### ISSUE THREAD

**Issue by Daniel15** [facebook/react-devtools#1234]
This is oddly specific 😛 
![image](https://user-images.githubusercontent.com/91933/48811309-08405d00-ece2-11e8-9b70-6b0fc0466b7e.png)

Firefox 63.0.3

**Comment by bvaughn** [comment]
A repro link would be handy, Daniel 😉

**Comment by bvaughn** [comment]
I would say that, initially, I think it's reasonable for the overlay to show whatever values the browser reports. If, in some bizarre condition, the browser actually returns a value of 330.04998778286875...why not show it? 😄

**Comment by bvaughn** [comment]
I don't feel strongly about this, but tend to think that it's an edge case that we don't need to handle explicitly. Let's re-open it later when we get more info about repro (or if it seems common).
