### ISSUE TITLE
The props of memo'ed components are not shown

### ISSUE THREAD

**Issue by Finesse** [facebook/react-devtools#1238]
Here is a live example:

* Source code: https://codesandbox.io/s/zn0jmk23yl
* A place to try Dev Tools: https://zn0jmk23yl.codesandbox.io/

Open Dev Tools and select the `Memo(Button)` element. Its props are not shown.

![image](https://user-images.githubusercontent.com/9006227/48889325-28f2e900-ee81-11e8-96c6-86eda4ce4cf6.png)

The Dev Tools version is 3.4.3 (the latest available in the Chrome extensions store).

**Comment by Kovensky** [comment]
Same bug as https://github.com/facebook/react-devtools/issues/1213, different fiber type :(
