### ISSUE TITLE
Issue with React Tab on FB

### ISSUE THREAD

**Issue by seandevo** [facebook/react-devtools#1241]
Don't forget to specify your OS, browser version, extension version, and the exact instructions to reproduce the issue with a screenshot.

Hi,

I'm having issues viewing the React tab in console. It does not appear even when I'm on the Facebook page.

My current Mac OS version is Mojave 10.14.1 I'm using the Google Chrome browser version 70.0.3538.110 (Official Build) (64-bit), React extension version 3.4.3. Also, there were threads about how the React icon now turns blue when React is running on a page, but that also does not change for me. I'm attaching a screenshot below.
<img width="1440" alt="screen shot 2018-11-29 at 11 42 50 am" src="https://user-images.githubusercontent.com/29469222/49247426-19692800-f3cc-11e8-8214-e39139c7fc94.png">

**Comment by herodrigues** [comment]
Try again using https://reactjs.org/

**Comment by ngyikp** [comment]
Facebook login page does not use React, try https://www.facebook.com/facebook or https://reactjs.org

**Comment by bvaughn** [comment]
As @ngyikp said, the Facebook page you've linked to doesn't use React. 😄 Once you've logged in it should work.
