### ISSUE TITLE
Proposal: add propTypes description

### ISSUE THREAD

**Issue by artalar** [facebook/react-devtools#1243]
It will be great if react-devtools will representing propTypes of inspecting component - that will simplify debug and development when property name wrong or just for short component review

![image](https://user-images.githubusercontent.com/27290320/49364828-3c5e4980-f6f6-11e8-8512-18cf9706d6b5.png)

**Comment by bvaughn** [comment]
I don't think we want to add anything specific to `prop-types` inside of DevTools. It would only apply for DEV builds, and even then– my impression of `prop-types` is that the community has been trending away from them in favor of tools like TypeScript and Flow.

This is a very reasonable idea and suggestion. 😄 But I think the added complexity isn't worth it at present. Hope you understand! 🙇
