### ISSUE TITLE
The dev tools can not connect my react native project

### ISSUE THREAD

**Issue by CrisChr** [facebook/react-devtools#1247]
Hi guys,
I npm installed react-devtools to my project, not global installed, then start it and it shows that `Waiting for React to connect...`
![image](https://user-images.githubusercontent.com/38416380/49696916-f7ea1680-fbeb-11e8-9b78-d61d79fe1b0c.png)

I noticed that its port number is 8097, so I reversed my react-native server to 8097, but it shows `Another instance of DevTools is running` because there are two 8097 port number app running
![image](https://user-images.githubusercontent.com/38416380/49696979-dccbd680-fbec-11e8-89ca-c667be63c579.png)

I also tried to import `react-devtools-core` package to App.js, but not worked too
![image](https://user-images.githubusercontent.com/38416380/49696962-970f0e00-fbec-11e8-9bbe-ac183fc0f2e9.png)

Any one can help me?

Thanks

**Comment by CrisChr** [comment]
Thanks for your reply @herodrigues 
If I don't use the same port 8081 or 8097, the `react-devtools` can not connect my emulator.
I think react-devtools is listening the emulator by the port, but unfortunately it's not worked for me

**Comment by herodrigues** [comment]
If you're using an emulator, the you should try this: https://github.com/facebook/react-devtools/tree/master/packages/react-devtools#usage-with-react-native

**Comment by CrisChr** [comment]
Yes, I tried that,  when I reverse tcp to 8097 using `adb reverse tcp:8097 tcp:8097` and then `react-native run-android` to start it, but the port is still `8081`. I googled it and found when run `react-native run-android`, it can automatically change the port to `8081`, should use `react-native run-android --port 8097` to start emulator with your port. So there are two server listening: one is react-devtools, another one is my emulator, they are all `8097 `port number. They should be same because if the devtools port is different from emulator port, how the devtools listen the emulator?

**Comment by toan301** [comment]
@CrisChr What happens if you use two different port? Just leave the port 8081 as default?

**Comment by danilor** [comment]
I am really interested to know how to solve this issue.

**Comment by CrisChr** [comment]
Hi @danilor
I change to use VS code debug mode solve my problem, that's easy to use

**Comment by tomihbk** [comment]
`react-native run-android --port 8097` This worked for me.
