### ISSUE TITLE
Inconsistent displayName configuration for context Consumer/Provider

### ISSUE THREAD

**Issue by nathanmarks** [facebook/react-devtools#1251]
Due to this change after the original PR:

https://github.com/facebook/react-devtools/commit/c2db8dd5c13edd29444c72714b49cdb1073a1a44

This is now needed to set the displayName for both as for `Consumer` we do not look up the `displayName` on `_context` like we do for `Provider`:

```js
TestContext.displayName = 'TestContext';
TestContext.Consumer.displayName = 'TestContext';
```

Was this intentional or can I submit a PR to fix it?

**Comment by nathanmarks** [comment]
This also needs to be fixed for TS usage: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L307

**Comment by bvaughn** [comment]
This seems to have broken as a result of changes to context made in React v16.6. (Our [regression test harness](https://github.com/facebook/react-devtools/tree/master/test/regression) shows it working for versions 16.3-16.5)

The React team doesn't maintain or contribute to the DefinitelyTyped repo, so you'll probably want to file a separate issue (or PR) there
