### ISSUE TITLE
Code of Conduct Link 404's

### ISSUE THREAD

**Issue by madelyneriksen** [facebook/react-devtools#1253]
Hi, 

The link in the current Code of Conduct returns a 404 Page Not Found error for me currently. I'm using Firefox 64.0.

Thanks!

**Comment by Kovensky** [comment]
It looks like the link is correct in `CONTRIBUTING.md` but not in `CODE_OF_CONDUCT.md`. It should be https://code.fb.com/codeofconduct/.
