### ISSUE TITLE
Props not matching actual props

### ISSUE THREAD

**Issue by jcald1** [facebook/react-devtools#1259]
I'm running React v 16.6.3, React Developer Tools 3.4.3.
I'm passing in the following prop: simulationRunRequestsMetadata.

```
              <SimulationRun
                commonProps={this.state.commonProps}
                refreshSimulationRuns={this.refreshSimulationRuns}
                simulationRunRequestsMetadata={this.state.simulationRunRequestsMetadata}

```

When I log the props in componentDidMount and componentDidUpdate, I can see the value passed in, but in React DevTools, when I click on the components, the Props is showing an array of four values and each object is empty.  

I switched to the console, did a right click on the previously logged variabl in componentDidUpdate, clicked "Store as global variable", and could see the current value with the full results printed out to the console.

simulationRunRequestsMetadata
`[{"id":4,"simulation_run_submission_id":4,"status":4,"status_details":null,"created_at":"2019-01-01T01:33:45.152437+00:00","updated_at":"2019-01-01T01:33:45.152437+00:00","simulation_sumbission":{"id":4,"name":"newsim4","description":"","duration":1,"interval":900,"weather_datasource_id":1,"network_datasource_id":2,"created_at":"2019-01-01T01:33:44.797378+00:00","updated_at":"2019-01-01T01:33:44.797378+00:00"}},{"id":3,"simulation_run_submission_id":3,"status":4,"status_details":null,"created_at":"2019-01-01T01:24:41.477294+00:00","updated_at":"2019-01-01T01:24:41.477294+00:00","simulation_sumbission":{"id":3,"name":"new sim 3","description":"","duration":1,"interval":900,"weather_datasource_id":1,"network_datasource_id":2,"created_at":"2019-01-01T01:24:41.027714+00:00","updated_at":"2019-01-01T01:24:41.027714+00:00"}},{"id":2,"simulation_run_submission_id":2,"status":4,"status_details":null,"created_at":"2019-01-01T01:04:34.647114+00:00","updated_at":"2019-01-01T01:04:34.647114+00:00","simulation_sumbission":{"id":2,"name":"simrun2","description":"","duration":1,"interval":900,"weather_datasource_id":1,"network_datasource_id":2,"created_at":"2019-01-01T01:04:34.282006+00:00","updated_at":"2019-01-01T01:04:34.282006+00:00"}},{"id":1,"simulation_run_submission_id":1,"status":4,"status_details":null,"created_at":"2019-01-01T00:46:06.731906+00:00","updated_at":"2019-01-01T00:46:06.731906+00:00","simulation_sumbission":{"id":1,"name":"new sim 1","description":"","duration":1,"interval":900,"weather_datasource_id":1,"network_datasource_id":2,"created_at":"2019-01-01T00:46:06.391818+00:00","updated_at":"2019-01-01T00:46:06.391818+00:00"}}]`

**Comment by bvaughn** [comment]
Share a repro case?

**Comment by bvaughn** [comment]
Closing due to lack of repro info. Will reopen  later if provided.
