### ISSUE TITLE
SearchInput text is always black, regardless of theme

### ISSUE THREAD

**Issue by Apollinaire** [facebook/react-devtools#1278]
The text inside the searchbar (i.e. the text you type when you want to search for a component) is not using the theme for its color (hence it has the default `black` color), but its background is using the theme. This means that text is almost unreadable when using a dark theme. I'm on Chrome, with React devtools 3.6.

![image](https://user-images.githubusercontent.com/5938985/51310552-2f4bae80-1a47-11e9-8b84-1ac778a54c25.png)

I think adding the right `var` here : https://github.com/facebook/react-devtools/blob/5d4f28c4479d512ed2dab71b5342708bcc4946a4/frontend/SettingsPane.css#L75-L84 would solve it. IMO the right choice is `base05`, for default foreground?
If you agree with me I'll happily submit a PR for this.
And thanks for the work you put in this awesome tool :+1:

**Comment by ngyikp** [comment]
This was regressed during the switch to CSS modules:

https://github.com/facebook/react-devtools/commit/196b381495ec6a5ba090543fbb152e3bff4b1831#diff-2bca863d41a601cd26c345da7bfa587bR93

According to https://github.com/facebook/react-devtools/blob/5d4f28c4479d512ed2dab71b5342708bcc4946a4/frontend/Input.js#L62, you can set the text color to `base05`

**Comment by bvaughn** [comment]
Whoops 😄 Thanks for the report!

Fixed with #1279 ~ will go out with the next release
