### ISSUE TITLE
Poor Performance in Chrome

### ISSUE THREAD

**Issue by timoxley** [facebook/react-devtools#129]
It appears that after opening react-devtools, react-devtools itself becomes the most significant, negative influence on rendering performance:

![image](https://cloud.githubusercontent.com/assets/43438/9147877/45a809b6-3d33-11e5-8c15-c230057520a8.png)

In this case, react-devtools is blocking on the UI thread for 157ms which makes a very perceptible dent in the app's frames per second:

![image](https://cloud.githubusercontent.com/assets/43438/9147686/23a2d5ba-3d30-11e5-94fc-f6cfac6fa76d.png)

Even with the react-devtools tab closed there appears to be no way to stop this from happening without closing Chrome devtools entirely, thus losing any other state one has currently configured in devtools.

Perhaps a solution would be to stop collecting data while react-devtools tab is not focussed, or provide a means to disconnect this polling mechanism without restarting Chrome devtools entirely.

**Comment by jaredly** [comment]
Yeah. There is some redundancy in the data we send over - so we can probably streamline things a bit.
Not sure about what we want to do about "stop collecting data"

**Comment by jaredly** [comment]
actually, I can think of a way to pause the sending of data. I'll investigate that.

**Comment by hummlas** [comment]
When I open up the React tab in chromes dev-tools chrome becomes incredibly slow, almost unresponsive. Even trying to close the dev-tools might take a few seconds, but as soon as the dev-tools closes the speed/responsiveness goes back to normal. 

If I look in Chrome task-manager I can see that the tab where React dev-tools are open increase in memory usage by the second, going up from ~200MB to before switching to the React-tab in the dev-tools and within a minute of switching increasing to 900+ and the it starts going back and forth between 500-ish to 900-ish.

Using Chome version 45.0.2454.85 m and React dev-tools version 0.14, still using React 0.12 though. But a friend with same version of chrome, React dev-tools and the same site does not have the same perf-issues..

**Comment by vasco3** [comment]
Having the same issue with Version 46.0.2490.80 (64-bit)  React devtools 0.14.4

**Comment by ansonkao** [comment]
+1

...also... https://www.change.org/p/github-inc-add-voting-functionality-for-github-issues

**Comment by ayozebarrera** [comment]
Having the same issue here Version 51.0.2704.84 (64-bit) React devtools 0.14.11

**Comment by gaearon** [comment]
#146 made it significantly better. I also made some changes later to address this.
For now the workaround is to close DevTools (or switch to another tab) if it makes the app slow.

**Comment by sshmyg** [comment]
App works fine, but if I open performance tab from react dev tools all site froze, and CPU  usage jump over 100%.

MacOS 10.13.6
