### ISSUE TITLE
React Hooks state

### ISSUE THREAD

**Issue by shirshak55** [facebook/react-devtools#1298]
If there is array in state it just show length is it possible to show full content of array?

For App component it shows like this .
```
App:
State:
5
State:
""
State:
Array[1]
Effect:
fn()

```

**Comment by NathanHeffley** [comment]
There is already an issue tracking this functionality: https://github.com/facebook/react-devtools/issues/1215

**Comment by shirshak55** [comment]
@NathanHeffley hmm it don't say about editing hook state?

**Comment by bvaughn** [comment]
Realistically, improved hooks support probably won't land in DevTools until [the rewrite](https://github.com/bvaughn/react-devtools-experimental) MVP is launched, so I'd prefer to track issues like this under the umbrella (#1215). (It's not like it's an unknown issue, just a known limitation that we're working on.)

I'm going to close this issue. I'll make sure it's explicitly mentioned on the other.
