### ISSUE TITLE
Uncaught TypeError: Cannot read property '_currentElement' of null @getData.js?45d8:60

### ISSUE THREAD

**Issue by terebentina** [facebook/react-devtools#130]
In chrome 44, stack trace:
Uncaught TypeError: Cannot read property '_currentElement' of null
getData @ getData.js?45d8:60
performUpdateIfNecessary @ attachRenderer.js?dda8:109
obj.(anonymous function) @ attachRenderer.js?dda8:180
runBatchedUpdates @ ReactUpdates.js?ce09:151
Mixin.perform @ Transaction.js?6dff:134
Mixin.perform @ Transaction.js?6dff:134
assign.perform @ ReactUpdates.js?ce09:95
flushBatchedUpdates @ ReactUpdates.js?ce09:175
ReactPerf.measure.wrapper @ ReactPerf.js?ef93:70
Mixin.closeAll @ Transaction.js?6dff:207
Mixin.perform @ Transaction.js?6dff:148
ReactDefaultBatchingStrategy.batchedUpdates @ ReactDefaultBatchingStrategy.js?ef70:66
batchedUpdates @ ReactUpdates.js?ce09:110
ReactEventListener.dispatchEvent @ ReactEventListener.js?2365:174

**Comment by terebentina** [comment]
The getData.js file is webpack:////Users/jaredly/clone/react-devtools/backend/getData.js?45d8

**Comment by spicyj** [comment]
Can you give more details? Did this happen just by opening the devtools or did you interact with it in some way? Is this reproducible for you?

**Comment by terebentina** [comment]
This happens on interaction. Everything loads just fine on a full page refresh. I have some react components that change their contents when I click something and that's when this happens.

**Comment by terebentina** [comment]
No other interaction with devtools - it's just opened on the console tab

**Comment by terebentina** [comment]
Ah, here's how to reproduce:
1. have a component that just displays an input field ({render = () => return <input type="text" />})
2. select that input in devtools elements tab and then go to the react tab so it shows the input too
3. make that component display a text instead of the input (by, say, clicking a button or something).
4. that error is now shown in console and it doesn't go away even after a full page refresh

If needed, I can send you the url to my dev site so you can see this happening

**Comment by jaredly** [comment]
Yeah I just saw this too

**Comment by jaredly** [comment]
See attached PR
