### ISSUE TITLE
React components shown as Unknown if exported directly

### ISSUE THREAD

**Issue by Jameskmonger** [facebook/react-devtools#1307]
I am using TypeScript and I have noticed that there is a difference in the way my components are shown in the dev tools based on their export style.

Components exported like this are rendered as `<Unknown>`.

```typescript
export const MyComponent: React.FunctionComponent<MyComponentProps> = (props) => { ... }
```

The compiled JS is like this:

```javascript
exports.MyComponent = function (props) { ... }
```

However, components like this are shown correctly (as `<MyComponent>`) in the dev tools.

```typescript
const MyComponent: React.FunctionComponent<MyComponentProps> = (props) => { ... }

export { MyComponent };
```

That is compiled into this:

```javascript
var MyComponent = function (props) { ... }

exports.MyComponent = MyComponent;
```

**Comment by Jameskmonger** [comment]
This issue is caused because `getDisplayName` only looks at the function `.name` property which won't be there in the first example.

In this case it should fall back to the export name first, before falling back to the `Unknown` name.

https://github.com/facebook/react-devtools/blame/faa4b630a8c055d5ab4ff51536f1e92604d5c09c/backend/getDisplayName.js#L16

**Comment by Jameskmonger** [comment]
This doesn't happen with `class` exports, because they are compiled to this:

```javascript
var MyClassComponent = (function (_super) {
    __extends(MyClassComponent, _super);
    function MyClassComponent(props) { ... }
    return MyClassComponent;
}(React.Component));
exports.MyClassComponent = MyClassComponent;
```

Therefore `.name` will return the correct value.

**Comment by bvaughn** [comment]
`getDisplayName` reads the function `name` – which is available in most cases, e.g.
```js
const Foo = () => {}; // Foo.name === "Foo"
function Bar() {} // Bar.name === "Bar"
const Baz = function() {} // Baz.name === "Baz"
```

It also accepts a [manually specified `displayName`](https://reactjs.org/docs/higher-order-components.html#convention-wrap-the-display-name-for-easy-debugging).

> In this case it should fall back to the export name first, before falling back to the Unknown name.

This information is not available to DevTools 😄 DevTools isn't executing your application code. If you want the `name` (or `displayName`) to be available to DevTools at runtime, you'll need to use a transform or something that compiles your TypeScript in a way that either avoids anonymous functions _or_ that attaches a `displayName` property.
