### ISSUE TITLE
Export utilities used for the Plain Shell

### ISSUE THREAD

**Issue by maclockard** [facebook/react-devtools#1310]
I have a couple different use cases where it would be very useful to setup react devtools in a way that's similar to the [Plain Shell](https://github.com/facebook/react-devtools/tree/master/shells/plain).

I was wondering if y'all would be open to exporting some of the utilities that make that example possible? I would be more than happy to contribute a PR doing so if you are!

I would use the [standalone devtools](https://github.com/facebook/react-devtools/tree/master/packages/react-devtools-core#requirereact-devtools-corestandalone), but they seem pretty tightly coupled to http/ws and I can't use those for the use cases I'm looking at.

The parts I'm interested in would be the ability to make my own wall. Another option would be to expose a couple more options from the standalone package so that I could specify how I want messages to work

**Comment by bvaughn** [comment]
Realistically, this doesn't sound like something we have the bandwidth to support. DevTools are a large surface area and maintaining them is already pretty difficult for the core team without expanding the API surface area 😄 I would suggest you just fork DevTools if you want to supply a custom wall. 😁
