### ISSUE TITLE
Check for data's length in dehydrate.js will throw error if data is ImmutableJS iterable data structure

### ISSUE THREAD

**Issue by evankline** [facebook/react-devtools#132]
I'm using ImmutableJS iterables in my project & received the following error: 
```
iterable.length has been deprecated, use iterable.size or iterable.count(). This warning will become a silent error in a future version. Error
```
In the stack trace I found that data.length was being called on an ImmutableJS iterable.
<img width="1180" alt="devtools-immutable-bug" src="https://cloud.githubusercontent.com/assets/5659108/9153437/c5f23272-3e23-11e5-882d-990e5a989d9e.png">

**Comment by ngyikp** [comment]
Duplicate of #126, #125 and #106

**Comment by mariemcannally** [comment]
I'm UN limited
