### ISSUE TITLE
Extension very slow to initialize in Chrome 75 (Canary)

### ISSUE THREAD

**Issue by borekb** [facebook/react-devtools#1323]
I use Chrome Canary (currently v75) for development on macOS 10.14.4 Mojave and during the past two weeks, the UI of Chrome itself (like opening a new tab or opening a menu) was very slow – almost unresponsive.

After disabling a couple of extensions, it turned out that it's caused by React DevTools – it takes several seconds for its icon to turn "red" on React apps and during this time, Chrome performance is severely impacted.

I tried in Chrome stable (v73 at this point) and everything is fine there.

_(I would think this has been reported already as I've been experiencing this for about two weeks now but couldn't find a similar issue – sorry if this is a duplicate.)_

**Comment by stavalfi** [comment]
this extention takes more than 250%

**Comment by borekb** [comment]
I'm no longer experiencing this, how about you, @stavalfi?

My Chrome Canary version is now "Version 75.0.3761.0 (Official Build) canary (64-bit)".

**Comment by stavalfi** [comment]
I'm using chrome (not canary) v` `Version 73.0.3683.86 (Official Build) (64-bit)` and it seems to be gone for the last week.

**Comment by borekb** [comment]
Ok, not sure what changed but the issue seems to be gone so I'm going to close this.
