### ISSUE TITLE
Can't download React Developer Tools on Chrome

### ISSUE THREAD

**Issue by Carls13** [facebook/react-devtools#1328]
I can't download React Developer Tools. I have Windows 10 and I use Google Chrome. Any help?

**Comment by ngyikp** [comment]
What is the error message when you download from https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi ?

**Comment by Carls13** [comment]
Hi... It failed while running a React server but I have just tried while not and it worked! Thank you
