### ISSUE TITLE
[New DevTools] eval() in backend.js breaks sites with strict CSP

### ISSUE THREAD

**Issue by STRML** [facebook/react-devtools#134]
The `devtool` config in [webpack.config.js](https://github.com/facebook/react-devtools/blob/4d1467804920db10cecb78f3387a6f41d585dc95/backend/integration/webpack.config.js#L15) breaks a strict Content-Security-Policy without `'unsafe-eval'`.

Perhaps a source map could be used instead in the packaged version, if any is needed at all? I like to run my apps in development with the same CSP they'll run in production so there are no surprises.

**Comment by jaredly** [comment]
Very good point

**Comment by bman654** [comment]
I thought I would try devtools today for the first time and hit this issue :cry: I suppose for the moment I can disable CSP in my development environment.

We use `devtool: "source-map"` in our development webpack build to avoid this issue in our code.

**Comment by spicyj** [comment]
I'll make sure we do this right when we publish on the Chrome store.

**Comment by gaearon** [comment]
Closing as we [don’t appear](https://github.com/facebook/react-devtools/blob/dc852a1021d742f1d95204ed3ce2379003747205/shells/chrome/webpack.config.js#L16) to use it in prod.
