### ISSUE TITLE
memo components show as Unknown in the timings section of Chrome

### ISSUE THREAD

**Issue by xaviergonz** [facebook/react-devtools#1340]
Given a component like

```
export const MyComponent = (p) => {...};
MyComponent.displayName = "MyComponent";
```
it shows properly as
![image](https://user-images.githubusercontent.com/6306796/56823548-79b5a600-6854-11e9-8371-a49d7ad5e5b4.png)

but as soon as memo is added
```
export const MyComponent = memo((p) => {...});
MyComponent.displayName = "MyComponent";
```
it shows as Unknown instead
![image](https://user-images.githubusercontent.com/6306796/56823576-92be5700-6854-11e9-8aea-8660277e36e2.png)

Note that both actually show properly on the tree explorer, the issue is only in the timings section of a performance recording in chrome.

**Comment by xaviergonz** [comment]
I also noticed that if this is done instead
```
const _MyComponent = (p) => {...};
_MyComponent.displayName = "MyComponent";
export const MyComponent = memo(_MyComponent);
```
then the timings section will show "MyComponent", it is as if the timings section was showing the wrapped displayName for memo components, completely ignoring its own displayName.

**Comment by bvaughn** [comment]
Hey @xaviergonz. This issue should be filed against the React repo (assuming it's still happening). DevTools does not control the user timings that are shown in your screenshot. 🙇

**Comment by xaviergonz** [comment]
Thanks, just copied it to the react repo
