### ISSUE TITLE
Profiler tab is not showing up in Chrome react dev tool

### ISSUE THREAD

**Issue by zhr1130** [facebook/react-devtools#1343]
Both my react and react-dom version is 16.8.3. My project isn't created by CRA but use webpack 4. I couldn't get profiler tab under Chrome react dev tool. Is there additional setting I need to make to webpack config ?

**Comment by bvaughn** [comment]
The "Profiler" tab will only show up if a profiling-capable version of React is detected, and profiling is only supported in the DEV (and [profiling](http://fb.me/react-profiling)) bundles. Make sure you're not trying to use it in production mode. 😄

Closing this issue for now as that seems the likely cause. If I'm incorrect, please provide additional info about how to reproduce what you're seeing.

**Comment by skirankumar7** [comment]
> The "Profiler" tab will only show up if a profiling-capable version of React is detected, and profiling is only supported in the DEV (and [profiling](http://fb.me/react-profiling)) bundles. Make sure you're not trying to use it in production mode. 😄
> 
> Closing this issue for now as that seems the likely cause. If I'm incorrect, please provide additional info about how to reproduce what you're seeing.

I am working on development mode only using webpack dev server in local but I am not getting show up that profiler tab section in  react devtools I have  "react": "^16.8.6", "react-dom": "^16.6.3",
I have installed react developer tools extension of the latest version.
Help me with this,
I can have even skype call also if someone wants to help me.
Thanks.
