### ISSUE TITLE
Upgraded to React 16.8. getting errors in React dev tools. TypeError: nt.setState.bind 

### ISSUE THREAD

**Issue by xinghengwang** [facebook/react-devtools#1344]
Everything was working fine, with react 15.8. I upgraded to react 16.8.6. My website works fine. 
but react dev tools keep giving this error: 

Uncaught TypeError: nt.setState.bind is not a function
    at B (backend.js:1)
    at $ (backend.js:1)
    at X (backend.js:1)
    at backend.js:1
    at Set.forEach (<anonymous>)
    at Object.walkTree (backend.js:1)
    at backend.js:1
    at <anonymous>:1:1663
    at Array.map (<anonymous>)
    at Object.emit (<anonymous>:1:1640)

**Comment by bvaughn** [comment]
Please provide a repro case?

**Comment by xinghengwang** [comment]
Found the issue. thanks closing.

**Comment by nihlton** [comment]
> Found the issue. thanks closing.

details on the issue?

I am currently seeing this issue...

**Comment by nihlton** [comment]
ooof, this is embarrassing.  

copied some code from the component constructor like:  	  this.state = { foo: 'bar' }

and pasted it someplace else, and changed it to : 	  this.setState = ({ foo: 'bar' })

little ashamed it took me 20 minutes to see the issue....
