### ISSUE TITLE
Unable to install standalone package

### ISSUE THREAD

**Issue by ahmedu007** [facebook/react-devtools#1345]
```
System:
      OS: macOS High Sierra 10.13.6
      CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
      Memory: 2.71 GB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.13.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
```

I tried to install `react-devtools` globally with `sudo yarn global add react-devtools` and `sudo npm i -g react-devtools` and they both failed with similar errors. Error is: 

NPM:
```js
electron@1.8.8 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@1.8.8 postinstall script.
```

Yarn:
```
/Users/umair/.config/yarn/global/node_modules/electron/install.js:47
  throw err
  ^
```

Then I also tried to install the package in the local repo, but the error stayed.

Looks like the issue is with electron which got fixed in the later versions. We might need to update electron version for the package.

To Reproduce:

in any npm initialised project run: either `yarn add -D react-devtools` or `npm i -D react-devtools` and the error will show up.

**Comment by codeocelot** [comment]
Could be the same problem others have reported. Check that you're not behind a VPN.  Electron needs to pull a rather large file (~45mbs) from github, not sure exactly why it fails on VPN though.  You can give `npm` and `yarn` the `--verbose` flag to help you pinpoint if this is the issue plaguing your install.

**Comment by ahmedu007** [comment]
Looks like it was an issue with the system not having permissions on my own account for some reason. Nothing to do with the repo. Closing the issue
