### ISSUE TITLE
Chome dev tools link is not working

### ISSUE THREAD

**Issue by danvoyce** [facebook/react-devtools#135]
Get this error "This XML file does not appear to have any style information associated with it. The document tree is shown below" when I try and download this https://github.com/facebook/react-devtools/releases/download/v2-beta1/react-devtools-chrome.crx

**Comment by jaredly** [comment]
curious. It's a zipfile... can you try downloading it some other way? It works for me in chrome, just clicking on the link downloads the file

**Comment by danvoyce** [comment]
Seems to be ok now. Must have been a temporary glitch with AWS
