### ISSUE TITLE
[New Devtools] Firefox requires a signed addon

### ISSUE THREAD

**Issue by julen** [facebook/react-devtools#136]
Starting from Firefox 41 (currently on the Aurora channel), add-on signing is enforced ([42 onwards it will be mandatory](http://www.ghacks.net/2015/06/19/how-to-disable-the-firefox-40-add-on-signing-requirement/)), so unsigned addons are disabled by Firefox, leaving no way to run the new devtools :disappointed:

Not sure if 3rd parties can sign addons themselves; other than that signing will be done for any addons that are available on AMO and have gone through their review process.

**Comment by jaredly** [comment]
We're planning on going through AMO for the official release

**Comment by fjaguero** [comment]
As commented by @julen, Firefox Developer Edition no longer allows [un-signed add-ons](https://wiki.mozilla.org/Addons/Extension_Signing), so it's not possible to use it now.

**Comment by ngyikp** [comment]
It's still possible to load unsigned extensions on non-release/beta Firefox by changing `xpinstall.signatures.required` at `about:config`.

**Comment by mtrenker** [comment]
[The versions were fixed in the wiki](https://wiki.mozilla.org/index.php?title=Addons/Extension_Signing&diff=prev&oldid=1090449), react tools will continue to work with FX up to and including 42 (Developer Edition) with the config change @ngyikp mentioned.

**Comment by breathe** [comment]
Sorry to chime in on this issue with what may be a user issue -- but is there a signed addon somewhere now -- that is to say -- is there supposed to be a signed version of the 0.14 release for firefox published somewhere?

This is the only url I can find and it seems to offer 0.14.1 without signature?  https://addons.mozilla.org/en-US/firefox/addon/react-devtools/

**Comment by fjaguero** [comment]
@breathe There is no signed version. You should do what @ngyikp said to allow the newest Firefox version to enable the extension.

**Comment by spicyj** [comment]
AFAIK we just need to wait for Mozilla to review it.

**Comment by mezod** [comment]
20 days later...still unsigned

**Comment by spicyj** [comment]
I don't know of any way to speed up the process. Sorry.

**Comment by kassens** [comment]
Maybe @digitarald can help to get this reviewed? https://addons.mozilla.org/en-US/firefox/addon/react-devtools/

**Comment by mezod** [comment]
I'm asking at #amo-editors @ irc.mozilla.org to see if this can be sorted out asap

**Comment by digitarald** [comment]
The switch to signing definitely took a toll on the backlog but the interface should give an indication. I pinged the review team on this.

**Comment by spicyj** [comment]
It was 100 of 150 in the queue when I checked earlier today. So probably a month or two at that rate.

**Comment by spicyj** [comment]
The addon has now passed preliminary review.
