### ISSUE TITLE
React Devtools for hooks 

### ISSUE THREAD

**Issue by prateek951** [facebook/react-devtools#1364]
Hi Facebook Team, 
I installed the latest version of React Developer Tools, but I cannot see my state if it is an object. For primitives, it is showing. How to correct that? I read somewhere that it is already introduced in React Developer Tools the support for Hooks but I am not able to use it. 
Thanks

**Comment by Legym** [comment]
I am having to use the experimental version 

https://react-devtools-experimental.now.sh/

**Comment by prateek951** [comment]
Thanks a lot I will definitely have a look at it.
