### ISSUE TITLE
Can't install in Firefox

### ISSUE THREAD

**Issue by guilhermemarconi** [facebook/react-devtools#1367]
Hi

I'm struggling to install the extension in Firefox 60.4.0esr (64-bit) because the "add-on appears to be corrupt".

![Print screen with the issue](https://user-images.githubusercontent.com/1273436/61721729-55784100-ad3f-11e9-88b5-83e160d5c0e1.png)

Is there something I can do to solve this without your intervention? Or, maybe, need to update the package in the add-ons repository?

**Comment by Bo-Duke** [comment]
This is coming from Firefox, it seems that versions of Firefox from 61 to 65 can't install or run extensions (or Firefox ESR before 60.6.2 in your case)
If you can't update to a newer version, you can install this [extension by mozilla](https://addons.mozilla.org/en-GB/firefox/addon/disabled-add-on-fix-61-65/) which fixes the problem.

Source : https://support.mozilla.org/en-US/kb/add-ons-disabled-or-fail-to-install-firefox
