### ISSUE TITLE
React App not Functioning with Extension Enabled

### ISSUE THREAD

**Issue by Fliktrax** [facebook/react-devtools#1374]
This error started happening right after a react production build with no modifications to the original compose function in the store setup. Commented out  __REDUX_DEVTOOLS_EXTENSION__  and the application is works fine.

![Screenshot from 2019-08-13 11-06-30](https://user-images.githubusercontent.com/21086929/62952975-ac12f100-bdba-11e9-9bfd-a69040831b6f.png)

**Comment by ngyikp** [comment]
Redux devtools and React devtools are 2 different extensions...
