### ISSUE TITLE
Having the devtools extension enabled breaks Kibana

### ISSUE THREAD

**Issue by ThiefMaster** [facebook/react-devtools#1375]
https://github.com/elastic/kibana/issues/22529

I'm pretty sure this happens because Kibana does not expect the message posted by the devtools. While I think it should be fixed in Kibana, they don't seem to are too much about that issue. Any chance something could be done on the devtools side to avoid this? Having to use an incognito window (where the extension is disabled) is quite annoying

**Comment by ngyikp** [comment]
If Kibana breaks when some third-party script calling `postMessage` (not confirmed), then wouldn't other browser extensions also cause trouble?

**Comment by ThiefMaster** [comment]
If they send a message with non-string data then yes, likely... To be honest, I didn't look into its source code to see if they filter out certain messages and the one from the react devtools just gets through for some reason..

**Comment by ThiefMaster** [comment]
I just tried and a simple `window.postMessage({source: 'me'}, window.origin)` crashes it too. So maybe it's not very common for other browser extensions to post messages? Anyway, I guess there's not much that can't be done on the devtools side... :/
