### ISSUE TITLE
React Devtools - Component selection bug v4

### ISSUE THREAD

**Issue by ovidiumihaibelciug** [facebook/react-devtools#1379]
When you select a component the selection remains after the dev tools isn't hovered anymore. 
Even if I refresh the page or click on the page, sometimes the selection remains as you can see in the following video. However after you select something and you hover over the search area of the dev tools or the props state area, that selection will disappear.

react-devtools version: DevTools version 4.0.2-2bcc6c6

https://www.loom.com/share/26f1b025384744439f2f9af86c84ce5b

**Comment by bvaughn** [comment]
Please open this issue in the React repo:
https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

This repository is for the legacy DevTools extension (v3) and is in the process of being shut down.

Thank you!
