### ISSUE TITLE
Remove emoji from browser devtools tabs

### ISSUE THREAD

**Issue by inoyakaigor** [facebook/react-devtools#1380]
![image](https://user-images.githubusercontent.com/1235286/63173784-425c4680-c049-11e9-9708-5fd2c99f9e43.png)
Make it possible to remove emoji from the tabs. It violate the common devtools style.

**Comment by inoyakaigor** [comment]
Also in Firefox 68.0.2 @ Macos it is duplicated
<img width="292" alt="изображение" src="https://user-images.githubusercontent.com/1235286/63266594-ef78ce00-c298-11e9-90ca-73f95ef25181.png">

**Comment by bvaughn** [comment]
Please open this issue in the React repo:
https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

This repository is for the legacy DevTools extension (v3) and is in the process of being shut down.

Thank you!
