### ISSUE TITLE
New Devtools: Update props does not rerender component

### ISSUE THREAD

**Issue by AkhmedovValikhan** [facebook/react-devtools#1381]
In new dev tools when I update props the changes don't lead to component rerender, more over if I navigate to other element and go back to original one, props are reset. 
This is issue seems to be happening with non-boolean props.  

React version: 16.8.6

**Comment by omerts** [comment]
Having the same issue, changing props is not re-rendering

**Comment by bvaughn** [comment]
Please open this issue in the React repo:
https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

This repository is for the legacy DevTools extension (v3) and is in the process of being shut down.

Thank you!
