### ISSUE TITLE
Firefox Private Browser Support

### ISSUE THREAD

**Issue by peterwiebe** [facebook/react-devtools#1383]
It seems that the RDTs won't work for me when I try using them in a Private Browsing tab on Firefox. I tried troubleshooting in the following ways:
- Disable the addon and then re-enable it
- Delete the addon and reinstall it
- Made sure that the addon was turned on for private browsing (see image below)
- I am able to get it to work without fail in a regular tab

![Screen Shot 2019-08-16 at 10 52 44 AM](https://user-images.githubusercontent.com/3029679/63187914-e081e980-c014-11e9-9bbf-22b58140dd3f.png)

**Comment by bvaughn** [comment]
Please open this issue in the React repo:
https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

This repository is for the legacy DevTools extension (v3) and is in the process of being shut down.

Thank you!
