### ISSUE TITLE
Long interaction names cannot be seen

### ISSUE THREAD

**Issue by davidmccabe** [facebook/react-devtools#1385]
Interaction names longer than about 30 characters are truncated without tooltips and so cannot be seen. If you go to the "Interactions" tab of the profiler, both the left-hand column and the right-hand sidebar are of fixed size and show a truncated name.

**Comment by bvaughn** [comment]
Please open this issue in the React repo:
https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

This repository is for the legacy DevTools extension (v3) and is in the process of being shut down.

Thank you!
