### ISSUE TITLE
React devtools 4.0.4 (8/18/2019) Expected to find root ID.

### ISSUE THREAD

**Issue by fuxun2008** [facebook/react-devtools#1388]
My sites always give me errors that "Expected to find root ID".

Below is the javascript resource.

<script src="//g.alicdn.com/platform/c/??react/0.14.9/react-with-addons.min.js,react/0.14.9/react-dom.min.js,reflux/0.3.0/dist/reflux.min.js,lodash/3.10.1/lodash.min.js,jquery/1.11.3/dist/jquery.min.js"></script>

![image](https://user-images.githubusercontent.com/4995935/63243613-abcc9700-c28d-11e9-8350-9cb4b8dac2d4.png)

What's the reason and how can I solve this problem?

**Comment by ngyikp** [comment]
https://reactjs.org/blog/2019/08/15/new-react-devtools.html#which-versions-of-react-are-supported

React 0.14 is not supported on the new devtools

**Comment by techird** [comment]
I can understand the devtools is deprecating old version of React. However, is there a nicer way to do this? I mean, may be just a warning without breaking runtime of the old React.

I love the new devtools, but it just break my old app. Hopes for a solution here.

**Comment by bvaughn** [comment]
Please open this issue in the React repo:
https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

This repository is for the legacy DevTools extension (v3) and is in the process of being shut down.

Thank you!
