### ISSUE TITLE
Sorting objects in alphabetical order

### ISSUE THREAD

**Issue by timuric** [facebook/react-devtools#139]
It can be hard to navigate within objects with many properties http://d.pr/i/105Fh sorting them in alphabetical order would be helpful

**Comment by jaredly** [comment]
Good idea

**Comment by spicyj** [comment]
Don't they appear in insertion order? Seems that sorting loses info.

**Comment by jaredly** [comment]
Chrome sorts alphabetically in object inspection. I think it makes sense
for us to do as well, though there is some info loss.

**Comment by spicyj** [comment]
I guess they're in order in shorthand but sorted when expanded, okay:

![image](https://cloud.githubusercontent.com/assets/6820/9205321/516bc0f4-4016-11e5-81f9-d4431eaaa72c.png)

**Comment by timuric** [comment]
@spicyj @jaredly maybe there are cases when insertion order is more intuitive, but personally I have never encountered such cases, but what I know for sure that working with large object (typically styles) is extremely hard.

**Comment by jaredly** [comment]
fixed by ea67795
