### ISSUE TITLE
Not working for latest chrome

### ISSUE THREAD

**Issue by DERIIIFranz** [facebook/react-devtools#147]
This tool isn't working for the latest version of chrome (44.0.2403.155 m) because it's not listed in the chrome web store. Therefore it's not possible to activate this extension.

**Comment by ngyikp** [comment]
See also: #123

**Comment by stv8** [comment]
Yeah it is not working for me either even though it is listed in the web store for me. When I click on the React tab in the devtools it results in a blank screen. 

Chrome 44.0.2403.157 (64-bit)
Mac OSX 10.10.5

**Comment by nemoo** [comment]
Same for me. Chrome 44 disables it because it is not in the web store.

**Comment by spicyj** [comment]
The final version will be out soon and will be from the web store.
