### ISSUE TITLE
No way to know element key

### ISSUE THREAD

**Issue by salehe** [facebook/react-devtools#148]
There is no way to know an element's key in React tab. It is omitted on the left pane and is not a prop anymore to be shown in the right pane.

![image](https://cloud.githubusercontent.com/assets/1437198/9287911/94d8e238-4343-11e5-9fa3-3abd95e69941.png)

As a walk-around, you can look for `$key` in `data-reactid` attribute in Chrome's own Elements tab or use `$r._reactInternalInstance`, but these are not the best solutions.

**Comment by istrel** [comment]
+1
