### ISSUE TITLE
No react found on the page.

### ISSUE THREAD

**Issue by slorber** [facebook/react-devtools#151]
When opening the new extension on a website where the previous extension used to work, I get a blank page with message "No react found on the page."

Notice I'm using React 13.3, and that there is an available window.React global variable (althought I've just read it may not be required anymore...).

**Comment by spicyj** [comment]
Can you link the website?

**Comment by slorber** [comment]
@spicyj sure but you will have to signup: [https://stample.co/](https://stample.co/)



Also I want to point out that I get this error only when the extension is activated: `Uncaught ReferenceError: Map is not defined `

The line is: `window.__REACT_DEVTOOLS_GLOBAL_HOOK__.nativeMap = Map;`

**Comment by slorber** [comment]
@spicyj I just saw that I'm now unable to run the 0.14 [fiddle](https://jsfiddle.net/reactjs/ghmpo42k/) of @zpao as I get the same error (even with the extension disabled)

Maybe that extension is automatically included in the fiddle?

**Comment by jaredly** [comment]
What is your browser version? `Map` is an es6 class that is provided in all the latest versions of chrome.

**Comment by slorber** [comment]
Chrome Version 37.0.2062.120 (64-bit)
Running on Ubuntu 12.04

Maybe I'm a bit too old but I think Chrome is supposed to auto-update right? Maybe the newer versions are not supported anymore for Ubuntu 12.04?

**Comment by jaredly** [comment]
Huh. Yeah es6 Map was implemented in Chrome 38 :/ Now we're on v44 iirc

**Comment by slorber** [comment]
@jaredly I can confirm it works with v44.

Just didn't know that Chrome did not auto-update magically on Ubuntu so I never upgraded.
