### ISSUE TITLE
Can't easily copy component name

### ISSUE THREAD

**Issue by spicyj** [facebook/react-devtools#153]
You used to be able to double-click the component name and copy it in the tree view, now you can't. The text in the right pane also isn't selectable.

**Comment by ngyikp** [comment]
The text in the right pane is unselectable is due to https://github.com/facebook/react-devtools/blob/da7d9a8c212201ee045c9c2193e26fe59b91cdad/frontend/PropState.js#L173

```javascript
    WebkitUserSelect: 'none',
    MozUserSelect: 'none',
    MsUserSelect: 'none',
    userSelect: 'none',
```

Removing the 4 lines make them selectable again.

**Comment by jaredly** [comment]
Right. we can remove that if desired -- I just like not having accidental selections, so I disabled them.
