### ISSUE TITLE
[New Devtools] deep-level nodes are unselectable

### ISSUE THREAD

**Issue by alexkuz** [facebook/react-devtools#158]
When the components tree is too deep, it's impossible to select nodes deeper than some point.

Here's a video of how it looks like:

http://quick.as/wjv9ugvjr

**Comment by jaredly** [comment]
Yeah, that's due to react 0.13 breaking on depths of >100 nodes. But 0.14
beta inputs are broken :/

**Comment by spicyj** [comment]
beta3 should work.

**Comment by gaearon** [comment]
Привет Саш. )

Closing as this is supposed to be fixed. Please let us know if not.

**Comment by alexkuz** [comment]
@gaearon 👋

(just checked on deep tree, works fine)
