### ISSUE TITLE
Add 'minimum_chrome_version' for Chrome extension

### ISSUE THREAD

**Issue by ngyikp** [facebook/react-devtools#159]
To avoid similar issues like #151 because of an old Chrome version, the manifest should set `minimum_chrome_version` to the current stable version, which is `44`.

https://developer.chrome.com/extensions/manifest

**Comment by jaredly** [comment]
Is there any value in setting it back at 38? I guess most people just have
the auto update going

**Comment by spicyj** [comment]
Whichever. Probably 43 is better than 44 in case people are lagging a little behind.
