### ISSUE TITLE
Integration with non DOM render targets.

### ISSUE THREAD

**Issue by fsbdev** [facebook/react-devtools#160]
I'm doing something similar to react-canvas and react-pixi where the render target is not actually DOM nodes although it somewhat hijacks the react-dom renderer. In my case it's a scene graph that renders to a canvas element using WebGL. When using these devtools with my project I don't see anything below my "Surface" component (the component that contains the canvas element) other than the canvas element. Is there a way to fake it so that my components will show up?

**Comment by spicyj** [comment]
Yeah, looks like we have the same problem with React ART. cc @jaredly – not sure offhand how hard this is to fix.

**Comment by jaredly** [comment]
The devtools decorate methods on the ReactReconciler to get information, and I imagine you're using your own reconciler. To fix it from your end, you would just have to emit `root`, `mount`, `update`, and `unmount` events on the `__REACT_DEVTOOLS_GLOBAL_HOOK__` (which is an EventEmitter).
You can see the current implementation [here](https://github.com/facebook/react-devtools/blob/master/backend/attachRenderer.js#L103), along with the [flowtype](https://github.com/facebook/react-devtools/blob/master/backend/types.js#L13) information of what to emit.

I'm not sure if there's a way to make the devtools compatible with custom renderers in general...

**Comment by spicyj** [comment]
Pretty sure the old devtools worked.

**Comment by fsbdev** [comment]
I'm using the same ReactReconciler since I'm hooking into the DOM renderer similar to the way React ART does. Thanks for the tips though on where to look.

**Comment by fsbdev** [comment]
There's a screenshot on the [React PIXI readme](https://github.com/Izzimach/react-pixi) with the devtools showing the correct components, I'm guessing that's the old devtools too.

**Comment by jaredly** [comment]
Good to know - I'll look into that
