### ISSUE TITLE
How to integrate into nw.js (node-webkit) ?

### ISSUE THREAD

**Issue by dropfen** [facebook/react-devtools#161]
Hi, what should I do to integrate react-devtools into nw.js?

It would be amazing, if we could just add it as dependency into the manifest.
Thanks!

**Comment by dropfen** [comment]
Up Votes welcome :)

**Comment by af7** [comment]
Yes, please do so, thx!

**Comment by gaearon** [comment]
I'm not sure what the integration would entail, but we now expose two npm packages that should contain everything you need.

https://github.com/facebook/react-devtools/tree/master/packages
