### ISSUE TITLE
Meteor support

### ISSUE THREAD

**Issue by markoshust** [facebook/react-devtools#162]
React dev tools don't appear to work with the official Meteor `react` package. There are just a bunch of "Unknown" components:

![screen shot 2015-08-24 at 8 24 58 pm](https://cloud.githubusercontent.com/assets/437029/9455913/66c19e3c-4a9e-11e5-8a9f-4e26adc5878c.png)

**Comment by spicyj** [comment]
This just means that the display name isn't set on those components. If you wrote them, add "displayName" attributes or use the JSX transform that adds them automatically. If those are classes made by Meteor, please file an issue there instead.

**Comment by markoshust** [comment]
Thanks, will file with Meteor -- I'm thinking the transform should handle those automatically.
