### ISSUE TITLE
No react tools tab in chrome mobile developer tools

### ISSUE THREAD

**Issue by lfrodrigues** [facebook/react-devtools#163]
We're developing an app using cordova and react. 

We use mobile developer tools for debugging but there we don't get the react tab.

**Comment by cmacnaughton-al** [comment]
Same issue, react tab is gone.
Chrome Version 44.0.2403.157 (64-bit)

**Comment by spicyj** [comment]
This is a problem with the chrome web store version of the extension (not just the beta), correct?

**Comment by lfrodrigues** [comment]
yes it is

**Comment by spicyj** [comment]
This is somewhat related to #91, I think, in that the devtools hook doesn't get added to the page. Not sure how easy it is to fix.

**Comment by chauthai** [comment]
+1 for cordova support

**Comment by elad-lachmi** [comment]
another +1 for cordova support

**Comment by TheBoroer** [comment]
Another +1 for cordova support! :+1:

**Comment by gaearon** [comment]
Unfortunately +1’s won’t help here because we are not working on Cordova apps. If you are working on one, and would like to see this fixed, please consider fixing this and submitting a PR. You can find instructions to get started here:

https://github.com/facebook/react-devtools#for-hacking

**Comment by gaearon** [comment]
This should be solved with the new standalone version.
https://github.com/facebook/react-devtools/tree/master/packages/react-devtools
