### ISSUE TITLE
Chrome devtools don't work on file: URLs

### ISSUE THREAD

**Issue by spicyj** [facebook/react-devtools#172]
This is presumably because I removed it from the list of permissions… but the old devtools didn't have any permissions listed in manifest.json and did work on file URLs, so maybe we can fix this regression.

**Comment by arm22** [comment]
Sorry, totally new here, but I think that your presumption is correct. Here is what my error looks like if it helps:
`Unchecked runtime.lastError while running tabs.executeScript: Cannot access contents of url "file:///Path/To/React/app". Extension manifest must request permission to access this host.
at installContentScript (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/background.js:91:16)
at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/background.js:67:6`

**Comment by spicyj** [comment]
@arm22 Thanks. I guess chrome.tabs.executeScript doesn't work on file: URLs?

**Comment by kassens** [comment]
According to [this answer](https://stackoverflow.com/questions/19493020/adding-file-permission-to-chrome-extension/19493206#19493206) on StackOverflow users have to tick the checkbox in the settings in order to allow access to `file://`. This seems to work as expected for the `content-script` that we're injecting on every page, but doesn't seem to work for `chrome.tabs.executeScript`. Sounds like a Chrome bug to me. (filed https://crbug.com/529548)

A quick test seems to confirm that doing the work from `contentScript.js` directly in `GlobalHook.js` would fix this issue. This would mean we do slightly more work on every page though.

CC @paulirish

**Comment by dbashford** [comment]
FWIW, allowing access to `file://` gets React dev tools started, but once started, it, for me, gets stuck on "Connecting to react..." as per #179.

**Comment by syndbg** [comment]
@dbashford Confirming that I have the same issue. No errors, but stuck on `Connecting to React`

**Comment by ErikSchierboom** [comment]
@dbashford Same here.

**Comment by kumthekar** [comment]
Same problem on Chrome Version 46.0.2490.71 (64-bit) on Mac OS 10.9.5

Stuck on 'Connecting to react ...'

**Comment by wzpan** [comment]
Same problem.

**Comment by fuchao2012** [comment]
@wzpan open the [react](http://facebook.github.io/react/) to test the dev tools. And do not test the page in file URL

**Comment by Bnaya** [comment]
Same problem, even with "allow access to file urls"

**Comment by darknoon** [comment]
I was trying out React to compare to ComponentKit and I got really stuck trying to set up the chrome developer tools by pointing it at my jsfiddle, I thought I would download the "Starter Kit" and just open some of the example files there.

It ended up being even more confusing and after a bunch more googling, I ended up here. This makes me think that React is hard to use, even though it probably works great when you get it all up and running.

**Comment by spicyj** [comment]
@darknoon Thanks, that's valuable feedback. https://code.google.com/p/chromium/issues/detail?id=529548 was just marked fixed so hopefully that will be in a release soon and we can close this issue completely. As a quick way to get started, you could try using http://react.jsbin.com/ – if you click this icon

![image](https://cloud.githubusercontent.com/assets/6820/11944050/8e913e66-a7f7-11e5-9f3e-85d70fe3e145.png)

then it will open the output in a new window where the devtools should work.

**Comment by spicyj** [comment]
Actually – maybe we can add file URLs to the manifest now? @kassens if you're planning to submit an update anytime soon, mind trying that?

**Comment by darknoon** [comment]
@spicyj I don't see that option on  http://react.jsbin.com/  
![screen shot 2015-12-22 at 12 51 18 pm](https://cloud.githubusercontent.com/assets/355540/11965645/c144b730-a8aa-11e5-923d-1002adcebe33.png)

**Comment by spicyj** [comment]
@darknoon It should show up as soon as you start editing the JS, sorry for not specifying. It's a confusing UI.

**Comment by kassens** [comment]
React devtools 0.14.6.1 are out now and should work on file urls.

**Comment by spicyj** [comment]
Thank you @kassens!

**Comment by jimfb** [comment]
Looks like it requires that the user explicitly open the chrome extension manager and allow `file://` urls as an additional explicit step.  The vast majority of users are going to overlook this.  Is there a way we can have it enabled by default?  Anything else we can reasonably do to make this smoother / work?

<img width="327" alt="screen shot 2015-12-22 at 1 54 19 pm" src="https://cloud.githubusercontent.com/assets/9595985/11966937/ce20d692-a8b3-11e5-81e6-ae7adb7ef046.png">

**Comment by kassens** [comment]
Thanks @jimfb, I created a new issue to track that we could warn people to check that box.

**Comment by spicyj** [comment]
We could change the message we just added to React to mention this setting.

**Comment by syndbg** [comment]
Thank you, guys!

@kassens :beers:

**Comment by Bnaya** [comment]
Hooray !

**Comment by jinglesthula** [comment]
I'm late to the party, but wanted to comment here both in case it helps anyone else stuck on the same thing, and also to see if anyone thinks this is a setup issue or an issue with the extension itself.

I'm using webpack-dev-server and find that if I visit `localhost:8080/webpack-dev-server/` the tab will not show up (whether the file URL box it ticked or not).  However, if I break down and just visit `localhost:8080/` directly the tab does appear (with or without the file URL box ticked).

This server puts the app in an iframe, which I suspect may be the source of the issue.  I tried adding `window.React = React;` in my index.js just for kicks and it didn't make a difference.

If this sounds like something the extension could address I can open a new issue here.
