### ISSUE TITLE
React Native: "No display name" showing in inspector for all custom components

### ISSUE THREAD

**Issue by udfalkso** [facebook/react-devtools#177]
I'm seeing "No display name" for all of my components.  The included React Native ones (View, Text, etc.) are showing up as expected however.  

Is there any way to remedy this?  Do I have to set the displayName myself for all components, or should it get taken from the jsx automatically?  

![screen shot 2015-09-02 at 11 30 35 pm](https://cloud.githubusercontent.com/assets/2029383/9649991/a8ecba98-51ca-11e5-9a86-327bf52fbd17.png)

(Chrome, OSX,  react-native@0.10.0, app running in simulator)

Thanks!!!

**Comment by spicyj** [comment]
Are you using React.createClass? The display name should be set automatically from the JSX transform.

**Comment by spicyj** [comment]
If you paste your code into the Babel REPL at http://babeljs.io/repl/, do you see the displayName property added?

**Comment by udfalkso** [comment]
Yes, I am using React.createClass.  And yes, when I paste it into the Babel REPL I see displayName property added at the top.

**Comment by udfalkso** [comment]
If I set displayName explicitly in my React.createClass({displayName: 'MyComponent' . . .}) then the inspector shows that name correctly.

**Comment by spicyj** [comment]
I assume you're using the RN packager in the standard way, nothing strange about your setup? @amasad Any idea why the babel displayName transform wouldn't be running?

**Comment by udfalkso** [comment]
I don't think I'm doing anything out of the ordinary, no.  

In case it's helpful, here are my package dependencies... 

"dependencies": {
    "react": "^0.13.3",
    "react-native": "^0.10.0",
    "react-native-device": "^0.3.0",
    "react-native-keyboardevents": "^0.4.5",
    "react-native-sglistview": "^0.1.2",
    "react-redux": "^1.0.1",
    "redux": "^1.0.1",
    "redux-thunk": "^0.1.0"
  }

**Comment by udfalkso** [comment]
It seems I might not be the only one with this issue.  Check out the screenshot here: https://github.com/facebook/react-native/issues/2557

**Comment by spicyj** [comment]
Closing in favor of that issue.
