### ISSUE TITLE
Submitting to Opera Addons Catalog

### ISSUE THREAD

**Issue by shwetank** [facebook/react-devtools#178]
This can also be submitted to Opera users. 

The Opera addons catalog also accepts crx files too, so its just a matter of the official creators just submitting the chrome extension to the https://addons.opera.com and it will be available to Opera users too. 

(I can help out with any others things related to this issue).

**Comment by ryentzer** [comment]
I'd like to see this added to Opera also.

**Comment by omgaz** [comment]
Bump

**Comment by b2m9** [comment]
I would also like tot see it in the Opera store. I'm running v0.14.11 on Opera 38 without major problems (there are some minor issues, but I have experienced them in Chrome too).

**Comment by StephanBijzitter** [comment]
bump

**Comment by gaearon** [comment]
We won't be maintaining it in yet another store, sorry!
Hopefully this works for you: https://github.com/facebook/react-devtools/pull/486.
