### ISSUE TITLE
Installed react-devtool extension but it does not show up in devtool

### ISSUE THREAD

**Issue by sarbbottam** [facebook/react-devtools#180]
<img width="1440" alt="screen shot 2015-09-03 at 11 39 41 am" src="https://cloud.githubusercontent.com/assets/949380/9667419/80b2ce08-5230-11e5-962c-6941e19349c6.png">

**Comment by spicyj** [comment]
It only shows up on a page with React. Try http://facebook.github.io/react/.

**Comment by sarbbottam** [comment]
Cool, thanks, I could see the react panel for http://facebook.github.io/react/.

It would better to add this comment to http://facebook.github.io/react/blog/2015/09/02/new-react-developer-tools.html

**Comment by jaredly** [comment]
I guess the reason we didn't mention it there is that this was the same functionality with the previous version

**Comment by spicyj** [comment]
If more people get confused we can update the post.
