### ISSUE TITLE
[firefox] Icon is invisible on light theme

### ISSUE THREAD

**Issue by nt1m** [facebook/react-devtools#183]
Right now, the react tool icon is white, and in light theme, it looks invisible since the background is too light. A simple fix would be adding `invertIconForLightTheme: true` in the tool definition.

**Comment by spicyj** [comment]
Weird, in my testing that doesn't seem to work…

**Comment by nt1m** [comment]
@spicyj Maybe this option doesn't work when the tool is registered with the SDK ? It seems to work fine with my non-SDK add-on : https://github.com/nt1m/devtools-prototyper/blob/master/src/bootstrap.js (I don't recommend using the non-SDK methods, as they are being phased out).
Anyway, I have filed this : https://bugzilla.mozilla.org/show_bug.cgi?id=1201718

**Comment by nt1m** [comment]
@spicyj Submitted a patch to Firefox to get this supported. It should hopefully land soon.

**Comment by nt1m** [comment]
The patch now landed in Firefox Nightly. You might want to try again.
