### ISSUE TITLE
Components displayed as <Unknown ... /> when declaring js variables at the top.

### ISSUE THREAD

**Issue by tiengtinh** [facebook/react-devtools#20]
I'm using grunt task to first build *.jsx files from *.coffee, and then build *.jsx to *.js files.
Therefore, my *.js files would be something like

```
var PhotoListWrapperView, PhotoListView,  PhotoView;
...
PhotoListWrapperView = React.createClass({
...
});
```

And with this js style, when I inspected into the React tab in Chrome, things displayed like:

```
<Top Level>
    <Unknown data="...">...</Unknown>
</Top Level>
```

When I tried to manually change the js variable declaration style to `var PhotoListWrapperView = React.createClass({...` , React inspection displayed correctly.

Look like declaring like `var PhotoListWrapperView` is a must for the tool to work. This may lead to some inconveniences. My case is an example.

**Comment by vkbansal** [comment]
Recently started using devtools and I'm facing similar problems
![capture](https://cloud.githubusercontent.com/assets/5930351/5971447/9c448dd8-a86b-11e4-9050-0e5b84ea683b.JPG)

**Comment by Schtauffen** [comment]
I use coffeescript (without jsx), and it never knows what to name custom elements. 
Is there a variable I can set explicitly set to tip off the react devtools?

**Comment by sebmarkbage** [comment]
You can set `displayName`
