### ISSUE TITLE
Tab doesn't show up on React 0.9.0 [Chrome, Firefox]

### ISSUE THREAD

**Issue by machikoyasuda** [facebook/react-devtools#202]
Hi - I installed the latest Chrome, Firefox and the latest React devtools for both today.

The tab shows up when I go to http://facebook.github.io/react/, but not when I try on my work site, http://thereformation.com, on production and local. The site uses React 0.9.0. 

![screenshot 2015-09-10 13 42 36](https://cloud.githubusercontent.com/assets/3673236/9800457/f18f0dee-57c1-11e5-8c92-333d792ffa70.png)
![screenshot 2015-09-10 13 45 44](https://cloud.githubusercontent.com/assets/3673236/9800525/3f11914a-57c2-11e5-910c-83bae7cc6bd9.png)

I used to use the previous version of the DevTools just fine. Does the new version not support React 0.9.0? Or is this a different bug? Alternatively, is there a link to the previous version?

**Comment by spicyj** [comment]
It does not. We weren't sure if anyone would notice, but evidently you did. :) Is it hard for you to upgrade? We can also look at supporting old versions of React.

**Comment by machikoyasuda** [comment]
@spicyj Thank you for that update :)

**Comment by gaearon** [comment]
Closing as outdated.
