### ISSUE TITLE
Port react devtools to Safari/bookmarklet

### ISSUE THREAD

**Issue by gremzlya** [facebook/react-devtools#203]
It would be grate if devtools would be available on safari

**Comment by kassens** [comment]
As far as I can tell, the Safari developer tools don't have a hook to add custom panels. It might be possible to create a bookmarklet that injects debugging tools into the page similar to [Firebug Lite](https://getfirebug.com/firebuglite).

**Comment by jaredly** [comment]
I think that would probably be pretty simple to do.

**Comment by gaearon** [comment]
You can now use the [standalone DevTools](https://github.com/facebook/react-devtools/tree/master/packages/react-devtools) for this.
