### ISSUE TITLE
Cannot read property 'props' of undefined (DevTools 0.14.3, React 0.14.0-rc1)

### ISSUE THREAD

**Issue by syranide** [facebook/react-devtools#204]
I keep getting the following error in the console when I'm working with my apps (DevTools 0.14.3, React 0.14.0-rc1).

```
backend.js:2427 Uncaught TypeError: Cannot read property 'props' of undefined
```

```js
	  if (element._renderedComponent) {
	    nodeType = 'NativeWrapper';
	    children = [element._renderedComponent];
/*2427*/props = element._instance.props;
	    state = element._instance.state;
	    context = element._instance.context;
	    if (context && Object.keys(context).length === 0) {
	      context = null;
	    }
	  } else if (element._renderedChildren) {
```

**Comment by STRML** [comment]
Same, this appears to have something to do with 0.14's simplified element format, supporting inline elements.

**Comment by spicyj** [comment]
Sure you're on devtools 0.14.3? I screwed up the publish for 0.14.2 so #199 didn't make it to the Chrome store in that version, but 0.14.3 should work if you manually update.

@STRML It's unrelated to that.

**Comment by STRML** [comment]
@spicyj Thanks, you're right. I can confirm `0.14.3` fixes the issue.

**Comment by syranide** [comment]
@spicyj Haha! I even copied it from the extensions page, it must've been updated just as I went to disable it :) yeah, not seeing the issue here anymore either.
