### ISSUE TITLE
Track down a component from elements panel to React panel

### ISSUE THREAD

**Issue by simongong** [facebook/react-devtools#209]
It's great that we can jump into the `Elements Panel` from `React Panel` to inspect a component's HTML DOM.
![0b10ec10-93d2-4262-a74d-a21cb621adb0](https://cloud.githubusercontent.com/assets/729479/9895139/a86e5b6e-5c5e-11e5-973a-48776872863f.png)

But is it possible to do it the other way around? I believe it's very benificial if we can inspect the component of a DOM node (I guess it may need some support from Chrome tho).

**Comment by spicyj** [comment]
Just select a node in the elements panel then switch to the React panel. It's magic!

**Comment by simongong** [comment]
@spicyj Got it. Real magic!
