### ISSUE TITLE
Link event listeners to source location

### ISSUE THREAD

**Issue by SanderSpies** [facebook/react-devtools#21]
Click directly from an Event Listener in the React DevTools tab towards the implementation within the Sources tab. 

Similar to the Event Listeners within the Elements tab.

**Comment by jaredly** [comment]
Update: still not possible

**Comment by jaredly** [comment]
This is actually possible, but only if the function isn't "bound" (via `.bind`). And in my experience, handlers are often bound.
The way to do it is to `inspect(thefn)` from the console and then it will switch you to the sources tab.
There's not first-class access to source filenames and lines though :(

**Comment by jaredly** [comment]
I think this is as good as we're likely to get, and with the additional ability to "jump to source" of a component, I think that the needs here are met.
Feel free to comment here if there are still things missing.
