### ISSUE TITLE
Options to hide <ReactCSSTransitionGroup />

### ISSUE THREAD

**Issue by Huxpro** [facebook/react-devtools#211]
`<ReactCSSTransitionGroup />` is really an eyesore when we inspect component hierarchy seeing it is really frequently used to wrap things.
So I think giving an options to hide it may be a good solution. 
Thanks

**Comment by jaredly** [comment]
Yeah, the Relay team was also interested in this -- being able to hide the "Relay(Something)" wrapper components.

Do you have any ideas about the right way to expose this in the UI? I'd hate to start automatically hiding things and not have a good way to indicate 1) that things have been hidden, and 2) how to un-hide them

**Comment by Huxpro** [comment]
Well...In my view, every component is default displayed, no necessity to auto hiding it. Just support a simple checkbox to hide `<ReactCSSTransitionGroup /> ` or `<Relay-something />` may be the easiest and quickest solution to do it, or you can support a textfield to let user to find and hide some specific component which they want to?

**Comment by gaearon** [comment]
I’m closing because we definitely won’t be adding a checkbox specifically for `ReactCSSTransitionGroup`. If you have a more generic proposal for hiding wrapper components, please file another issue and let’s discuss it there. Thanks!
