### ISSUE TITLE
[RN] Style : Modifying integer property value rise an error 

### ISSUE THREAD

**Issue by Crash--** [facebook/react-devtools#214]
When I try to edit the value of a property that expect an integer (fontSize, margin...) or and one, I get an error, but it works well when it's about a string value (color, align...). 

Here is the error : 
`Error setting property 'fontSize' of RCTText with tag #19: JSON value '30' of type NSString cannot be converted to NSNumber`

![react_dev_tools_bug](https://cloud.githubusercontent.com/assets/1107936/9955717/9122e128-5df3-11e5-9627-3d5ce4d4ca05.gif)

**Comment by jaredly** [comment]
Curious. I think this is a new regression (probably due to a change in react native) -- what react native version are you using?

**Comment by Crash--** [comment]
I'm currently running version  0.11.0-rc

**Comment by jaredly** [comment]
@vjeux do you know of anything that changed recently about string-to-int coersion? Changing font size worked before, I'm pretty sure

**Comment by vjeux** [comment]
Hmm, maybe @sebmarkbage would know

**Comment by sebmarkbage** [comment]
hm. No, that seems unrelated to anything we've been doing in core or devtools recently.

@jaredly Where is the coercion supposed to happen?

**Comment by gaearon** [comment]
Can't reproduce. Likely fixed.
