### ISSUE TITLE
Chrome tab does not show (react 0.14.0-rc1)

### ISSUE THREAD

**Issue by dennybritz** [facebook/react-devtools#215]
React: `0.14.0-rc1`
Dev Tools: `0.14.3`
Chrome: `45.0.2454.85 (64-bit)`

**Comment by spicyj** [comment]
Does it work for you on facebook.com? That uses 0.14.0-rc1 too.

**Comment by dennybritz** [comment]
Yes, it does. Interesting. Could it have anything to do with the fact that I'm opening a local file in Chrome? I.e. the URL scheme is not `http://` but `file://`.

**Comment by spicyj** [comment]
Yes: #172.
