### ISSUE TITLE
Test recording

### ISSUE THREAD

**Issue by SanderSpies** [facebook/react-devtools#22]
I was thinking of an easier way to create tests for React components. Once ReactTestUtils becomes available it could be used by react-devtools for test recording.

What I think it should do:
- A recording should result in a testfile for jasmine, mocha etc.
- The recording should be modifiable within devtools. 
- Should be possible to define expect statements.

Let me know what you think :-).

**Comment by facebook-github-bot-7** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by jaredly** [comment]
This is rather ambiguous in its current form, so if anyone has ideas, please chime in.

My immediate thought is that such a test recorder wouldn't be a unit-testing kind of thing, but integration, and would be beastly difficult to get right. I'll probably close this out for lack of activity soon unless someone wants to champion it.

**Comment by gaearon** [comment]
Going to close as there's nothing actionable here right now. The ideas are cool but since we have 100 open issues, I'd like to trim them down to actionable ones in the near term.
