### ISSUE TITLE
Updating style props in react-native interprets numbers as strings

### ISSUE THREAD

**Issue by bmcmahen** [facebook/react-devtools#223]
When trying to use the react-native style editor to change a `margin`, `borderWidth`, or any property that requires a number as the value, I get presented with the following error in my iOS simulator:  `JSON value '15' of type NSString cannot be converted to NSNumber`.

**Comment by kassens** [comment]
Thanks for the report, we're already tracking this regression in #214.

**Comment by bmcmahen** [comment]
Ahh -- sorry. Couldn't find the existing issue.
