### ISSUE TITLE
Arrays in props/state are sorted using ASCII instead of their numerical value

### ISSUE THREAD

**Issue by ajacques** [facebook/react-devtools#224]
Arrays are sorted using the ASCII value of their index instead of their numerical value in the props list for a React component. This is in the right pane when expanding the props values for a given React component in the React tab.

Tested in Google Chrome 45 and React dev tools 0.14.3

Example:
Props:
 - items: Array[15]
   - 0: {}
   - 1: {}
   - 10: {}
   - 11: {}
   ... etc

Since it's an array it should be able to be sorted correctly.

**Comment by kassens** [comment]
Thanks for the report! #176 is a pull request in progress to fix this.
