### ISSUE TITLE
Side panel missing sections

### ISSUE THREAD

**Issue by ADumaine** [facebook/react-devtools#225]
What happened to the sections other than Props, State, and Router?  There used to be Instance and Event Listeners, etc.  Now it looks like it has been restyled from the collapsible sections like it shows in the Chrome web store.  Is there a config setting somewhere to display the missing sections?

**Comment by jaredly** [comment]
Those haven't been implemented yet, and until now no one has mentioned them :) but they were useful to you?

**Comment by jaredly** [comment]
EventListeners at least have been merged into the props part (onClick, etc.)

**Comment by ADumaine** [comment]
That's odd because I had them about two weeks ago and then I thought I changed something or something in my build or the tools was broken.  I tried removing and re-installing the tools.  Perhaps there was a version update?

Yes they were useful as this is my first react project and I was exploring the relationships between the components, like determining the ref for a given component so its state could be updated.  I don't see the ref property in this current version.

**Comment by jaredly** [comment]
Yeah, there was a major version update recently. Good point about refs, too
-- it would be nice to display those in props (they're a bit special b/c
react strips off the "refs" attribute of properties and handles them
internally). I'll make an issue for that.

**Comment by ADumaine** [comment]
That would be helpful.  Thanks!
