### ISSUE TITLE
All component names showing up as "t"

### ISSUE THREAD

**Issue by saadq** [facebook/react-devtools#239]
*Edit: A screenshot of multiple components: http://i.imgur.com/45Y3aG1.png*

---

[Here](http://i.imgur.com/N8xaRRy.png) is a screenshot of the issue I'm facing (I took out the rest of the components to simplify things). All components are getting assigned a name of "t". In my gulpfile, I am using babelify, browserify, and uglify on my JS code – could that be the issue?

I defined the code for this component in my *TimerButton.js* file:

```js
import React from 'react'

class TimerButton extends React.Component {
  constructor() {
    super()
    this.state = {
      message: 'Start'
    }
  }

  render() {
    let classes = 'btn-large waves-effect waves-light indigo accent-2'
    let message = this.state.message
    return (
      <button id="timer-button" className={classes}>{message}</button>
    )
  }
}

export default TimerButton
```

And I rendered it from my *app.js* file like so:

```js
import React from 'react'
import TimerButton from './components/TimerButton'

$(() => {
  React.render(<TimerButton />, $('#timer-button-container')[0])
})
```

Any help would be appreciated.

**Comment by jaredly** [comment]
Perhaps you need to whitelist the `react.displayName` transformer for babelify? Another possibility is that uglify is getting in your way -- does this problem persist if you disable it?

**Comment by spicyj** [comment]
Yes, it's getting minified. You probably shouldn't use a minifier when developing.

**Comment by saadq** [comment]
Yeah, I probably should have tried it without `uglify()` before raising an issue. Thanks @jaredly and @spicyj.
