### ISSUE TITLE
Bring component as a variable to console

### ISSUE THREAD

**Issue by piranha** [facebook/react-devtools#24]
Would be nice to have component available for tinkering in console when selected - so that I could inspect its props and state using code.

**Comment by roman01la** [comment]
+1

**Comment by tmc** [comment]
does "fixed in v2" mean this is possible now?

**Comment by jaredly** [comment]
Not yet - v2 is under rapid development, and will likely be ready for a beta in a week or so

**Comment by iamdustan** [comment]
What about an alpha release? 😇

**Comment by jaredly** [comment]
Mostly I want to make sure it halfway works before expecting other people
to try it

**Comment by jaredly** [comment]
Here you go http://facebook.github.io/react/blog/2015/08/03/new-react-devtools-beta.html
