### ISSUE TITLE
Line Highlighting with Horizontal Scrollbars

### ISSUE THREAD

**Issue by MethodGrab** [facebook/react-devtools#240]
In Chrome (45.0) the line highlighting for selected items and hover only extends as far as the props panel on the right. When there are horizontal scrollbars, the highlighting gets cut off.

This happens with react-devtools 0.14.3 (current Chrome Store version) and `master`.
It can also be seen in Chrome & Firefox (41) when using `/shells/plain`.
## Initial view:

![image](https://cloud.githubusercontent.com/assets/2421069/10242099/2f5cce4c-68e6-11e5-83d9-587c2d6a8bf2.png)
## Scroll right:

![image](https://cloud.githubusercontent.com/assets/2421069/10242105/46e88f06-68e6-11e5-901b-ef4e987d8789.png)
## `/shells/plain`:

![image](https://cloud.githubusercontent.com/assets/2421069/10242654/4b7f929a-68ea-11e5-83b1-cfd32a411c60.png)

**Comment by gaearon** [comment]
This is super annoying. Do you want to send a PR to fix this?

**Comment by MethodGrab** [comment]
Sure! I did try and fix it before creating the issue but didn't have much luck.
It looks like the fix is actually pretty simple!

**Comment by gaearon** [comment]
Appreciated ❤️

**Comment by MethodGrab** [comment]
No prob! 👍
