### ISSUE TITLE
Fix up minor problems from Firefox addon review

### ISSUE THREAD

**Issue by spicyj** [facebook/react-devtools#243]
We got preliminarily approved with this feedback:

> 1) Please reduce your use of innerHTML. There are multiple instances where it should be easy to replace with other DOM methods that are faster and safer.
>
> 2) I get "Connecting to devtools" when I'm on a website that doesn't support React. You should show a clearer message in this case, since the current message suggests that something else is going to happen if I wait long enough.

#1 probably refers to a couple uses in frontend/Highlighter/ and shells/firefox/panel/run.js. Haven't looked at all at #2 but I imagine it's not hard either.

**Comment by jaredly** [comment]
2) We do this b/c the react might just be late loading... we should probably say "Checking for React" or something, and then maybe have a timeout after 5-10 seconds or something.
