### ISSUE TITLE
No Longer Works with React Native - Because Web Worker

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/react-devtools#247]
React Native's Chrome debugger moved to use a Worker to ensure a DOM-less environment. Unfortunately, this means that the React DevTools doesn't get injected into the Worker.

It would be great to be able to debug a React instance in a Worker regardless.

I don't know if Chrome extensions provide a unified way of injecting scripts into Workers and if so how to communicate with the DevTools extension.

**Comment by spicyj** [comment]
#229
