### ISSUE TITLE
Component names not showing up correctly

### ISSUE THREAD

**Issue by deepakjois** [facebook/react-devtools#258]
See screenshot below. Instead of the actual component names, I am getting letters like 't'. Why is this happening?

<img width="1277" alt="screenshot 2015-10-13 20 29 03" src="https://cloud.githubusercontent.com/assets/5342/10458583/23573fea-71e9-11e5-87bf-5fdaafc774f9.png">

**Comment by jaredly** [comment]
We've seen this before due to the use of `uglify`. Is that your case?

**Comment by deepakjois** [comment]
Yes. I am using `uglify`. Are you aware of any way to prevent this from happening, either by using an alternative to uglify, or tweak uglify options in some way.

**Comment by jaredly** [comment]
I'm not familiar with the internals that would cause these to be minified away -- perhaps take a look at the transpiled but unminified source, see where the names are defined, and see why uglify thinks they are irrelevant. I thought uglify usually preserved strings

**Comment by deepakjois** [comment]
Thank you.
