### ISSUE TITLE
Link to Fx DevTools store in description

### ISSUE THREAD

**Issue by iamdustan** [facebook/react-devtools#259]
Could a link to https://addons.mozilla.org/en-US/firefox/addon/react-devtools/ be added to
<img width="754" alt="screen shot 2015-10-13 at 5 25 52 pm" src="https://cloud.githubusercontent.com/assets/227879/10468858/81930e96-71cf-11e5-8dc5-bacdf5f3cb2d.png">?

**Comment by spicyj** [comment]
Thanks – I removed the URL since you can't have two. They're both in the README.

**Comment by iamdustan** [comment]
:thumbsup: thanks!
