### ISSUE TITLE
Show proper names for stateless functional components

### ISSUE THREAD

**Issue by spicyj** [facebook/react-devtools#267]
@bordoley says they all show up as StatelessComponent.

**Comment by jaredly** [comment]
if you `export default ({name}) => <div>{name}</div>`, it's not going to have a name, but that's on babel.
However, this works fine:
```js
const MyStateless = ({name}) => <div>{name}</div>

    .... somewhere
    <MyStateless name="Sophia" />
```

![image](https://cloud.githubusercontent.com/assets/112170/10819583/7eeb68f0-7e0e-11e5-9961-2da7c7408a38.png)

**Comment by bordoley** [comment]
Internally (Facebook) I was seeing.
```
<StatelessComponent>
  <div>some text</div>
</StatelessComponent>
```

I'll generate a repro using public react to see if this is FB specific or not.

**Comment by steveszc** [comment]
I am seeing this issue as well using public react. 
My root component is a stateless component, if I run a production Browserify build (NODE_ENV:"production") with no mangling I get the following in React DevTools:

![statelesscomponent](https://cloud.githubusercontent.com/assets/6877934/10894645/32f1fd9e-816d-11e5-8615-564e91edc3d0.png)

Here is my code for that same root component:
```
var MyRootComponent = () => (
    <MyChildComponent />
);
```

**Comment by jaredly** [comment]
What's your babel version? This is a babel issue I'm sure

**Comment by steveszc** [comment]
I'm using Babelify 6.3.0 with Browserify

**Comment by spicyj** [comment]
Maybe you don't have the function.name transform enabled? We probably rely on that.

**Comment by joaomilho** [comment]
Using browserify with coffee-reactify. Anything that I can do?

**Comment by jaredly** [comment]
@joaomilho make an issue w/ coffee-reactify asking them about getting `displayName`s enabled

**Comment by xixixao** [comment]
Also see https://github.com/facebook/react/issues/5618

**Comment by basarat** [comment]
For those using TypeScript you can do the following (example notice `displayName`): 

```tsx
declare global {
    interface Function {
        displayName: string;
    }
}

/********
 *
 * Primitives
 *
 ********/


interface PrimitiveProps extends React.HTMLProps<HTMLDivElement>{};

/**
 * Takes as much space as it needs, no more, no less
 */
export const Content = Radium((props: PrimitiveProps) => {
    const style = csx.extend(props.style || {},csx.content);
    return (
        <div data-comment="Content" {...props} style={style}>
            {props.children}
        </div>
    );
});
Content.displayName = "Content";
```

[Sample project work in progress](https://github.com/basarat/gls) :rose:

**Comment by tomduncalf** [comment]
@basarat Old comment I know but hopefully this is useful for someone:

It's possible to get this working automatically using this Babel plugin which will use the filename to assign the function a name if it does not have one: https://github.com/wyze/babel-plugin-transform-react-stateless-component-name/

Few things to watch out for:
- ensure it comes before the `"react-hot-loader/babel"` plugin in your `.babelrc`
- for it to work with Typescript, you need to be using Babel as part of your build (obviously – e.g. running `babel-loader` after `ts-loader` for all your `*.ts*` files) and you need to have `module: "es6"` and `jsx: "preserve"` in your `tsconfig.json` or the plugin won't recognise that the components are actually stateless ones

This doesn't currently work (either in ES6 or Typescript) for SFCs wrapped in a higher order component, e.g. `observe` from MobX. I'll raise an issue on the project for this.

**Comment by tomduncalf** [comment]
Oh, or even easier, you can do away with the plugin and just name your component by putting into a constant, then exporting that separately, for example:

```
const MyComponent = () => <div>Hi</div>

export default MyComponent
```

Will show as `MyComponent` in dev tools (with Typescript again, you need to set the `module` option appropriately I think, although probably not `jsx`).

Slightly more typing but probably clearer. Note this still doesn't seem to solve the HOC problem (already raised at: https://github.com/wyze/babel-plugin-transform-react-stateless-component-name/issues/2)

**Comment by tomduncalf** [comment]
Ah (sorry to spam this thread!) – there is a way round the HOC problem, which is to do as the above and store the component in a named constant, then wrap it when exporting (rather than when creating), so instead of:

```
const MyComponent = observer(() => <div>Hi</div>)
export default MyComponent
```

You have:

```
const MyComponent = () => <div>Hi</div>
export default observer(MyComponent)
```

Which arguably reads better anyway :) (and allows you to export the non-decorated component if needed e.g. for testing)

**Comment by deyceg** [comment]
@tomduncalf Just ran into this problem myself! 

```
const { name } = element.type;
if (name && name.endsWith('Control')) {...}
```

Your fix worked until I turned mangling on with uglifyjs

**Comment by gaearon** [comment]
Closing.

If you use Babel, [es2015 preset](https://babeljs.io/docs/plugins/preset-es2015/) contains [function-name plugin](http://babeljs.io/docs/plugins/transform-es2015-function-name/) that infers the name based on left hand side in expressions.

For Facebook internal use case, @spicyj recently fixed it by enabling the same transform.

**Comment by aaronbeall** [comment]
I'm using TypeScript with:

```
export const MyComponent = ({text}) => (
  <div>{text}</div>
);
```

And I just see `<StatelessComponent>` in the dev tools... is there a fix for this?

**Comment by basarat** [comment]
> is there a fix for this?

As mentioned before : https://github.com/facebook/react-devtools/issues/267#issuecomment-182658039 :rose:

```ts
declare global {
    interface Function {
        displayName?: string;
    }
}
export const MyComponent = ({text}) => (
  <div>{text}</div>
);
MyComponent.displayName = 'MyComponent';
```

**Comment by aaronbeall** [comment]
Thanks that does work... I suppose I was asking if there's a way to make it work without explicitly writing the `displayName` (which means you have to write the name twice).

I found that writing it this way seems to work:
```
function MyComponent({text}) {
  return (
    <div>{text}</div>
  );
}
```

**Comment by basarat** [comment]
> I found that writing it this way seems to work:

Yup, on modern browsers, cause they have `.name` automatically. I'll use that myself as well from now on :rose: :heart:

**Comment by basarat** [comment]
On second thought both are equivalent on chrome as it also adds `.name` for arrow assignments to variables e.g. run the following on the console

```ts
const x = ()=> undefined; function y(){}; console.log(x.name,y.name); // x y 
```

`export` might be throwing the emit (and/or) the v8's name detection off for `const` :rose:

**Comment by aaronbeall** [comment]
I think you're right about the `export` confusing something. If I do this:
```
export const MyComponent = () => { };
```
I get `<StatelessComponent>` in the dev tools.

But if I do this:
```
const MyComponent = () => { };
export {MyComponent};
```
I get `<MyComponent>` in the dev tools as expected.

**Comment by gaearon** [comment]
@aaronbeall Please file a bug with Babel if Babel doesn't add implicit `name` to arrow functions when they're used as exports.

**Comment by gaearon** [comment]
(Or with TypeScript if that's what you use)

**Comment by aaronbeall** [comment]
@gaearon Yep I'm using TypeScript. [It doesn't look like TS emits a `.name` in any case]... but I guess browsers are able to assign a name to functions when they are assigned to a `var` but not when they are assigned to a prop of an `exports` object? [This example](http://www.typescriptlang.org/play/#src=const%20ArrowFunction%20%3D%20()%20%3D%3E%20%7B%20%7D%3B%0D%0Afunction%20NamedFunction()%20%7B%20%7D%0D%0A%0D%0Aexport%20const%20ExportedArrowFunction%20%3D%20()%20%3D%3E%20%7B%20%7D%3B%20%2F%2F%20Shows%20%3CUnknown%3E%20in%20dev-tools%20(all%20others%20work)%0D%0Aexport%20function%20ExportedNamedFunction()%20%7B%20%7D%0D%0A%0D%0Aconst%20ExportedArrowFunctionOnObject%20%3D%20()%20%3D%3E%20%7B%20%7D%3B%0D%0Aexport%20%7B%20ExportedArrowFunctionOnObject%20%7D) shows how TS emits to JS and every component name appears in dev-tools *except* `export const = () =>` (the one I now use most, of course, lol).

**Comment by Zacqary** [comment]
Just stumbled on this thread. I've been running into an issue where the React Dev Tools tell me my component is called `<Unknown>` whenever I do:
```javascript
// MyComponent.js
export default (props) => <someJSX>;
// App.js
import MyComponent from './MyComponent.js';
```

But this works:
```javascript
export default function MyComponent(props) {
    return <someJSX>;
}
```

In case that's useful for anyone.

**Comment by gaearon** [comment]
Yes, this is expected, because Babel only infers the arrow name if you assign it to something.
For example, this would also work:

```js
const MyComponent = (props) => <someJSX />;
export default MyComponent;
```

**Comment by tkrotoff** [comment]
@basarat 
the part:
```TypeScript
declare global {
    interface Function {
        displayName: string;
    }
}
```
is not needed anymore, `MyComponent.displayName = 'MyComponent'` is enough (no TypeScript error, I guess the definition has been enhanced).

**Comment by ravshansbox** [comment]
I could fix the problem in typescript project by setting `module` flag to `es2015` and relying on webpacks native support for es modules. You have to set `moduleResolution` to `node` as well.
