### ISSUE TITLE
Incorrect URL in warning message when using React 0.12 or below

### ISSUE THREAD

**Issue by peterjmag** [facebook/react-devtools#268]
When I use react-devtools on a site with an outdated version of React (0.12 in this case), I get the following warning in my console:

```
You are using a version of React with limited support in this version of the devtools.
Please upgrade to use at least 0.13, or you can downgrade to use the old version of the devtools:
instructions here https://github.com/facebook/react-devtools/tree/devtools-next#how-do-i-use-this-for-react--013
```

This URL gives me a 404: https://github.com/facebook/react-devtools/tree/devtools-next#how-do-i-use-this-for-react--013. Perhaps the devtools-next branch was deleted? I was hoping to submit a pull request with an updated URL, but I can't find a "How do I use this for React 0.x" section in the current readme.

I'm using the latest stable version of the extension (0.14.4).

**Comment by jaredly** [comment]
Good catch! Looks like it got removed from the FAQ section accidentally. We just need to have a link to an old `.crx` extension file (not sure where to dig that up)

**Comment by peterjmag** [comment]
Looks like the [Chrome Web Store doesn't have an archive](http://stackoverflow.com/a/10744580/349353) (surprise, surprise), but perhaps we could just build one from an older version of the repo and then just host it somewhere else? If anyone still has their older clone lying around, that is.

**Comment by jaredly** [comment]
Here's the last commit of the old version:
https://github.com/facebook/react-devtools/tree/329363301da8fad70d1b49f830886c55ed53b1ef
A build off of that should do the trick

**Comment by peterjmag** [comment]
Sure, I built the version at 329363301da8fad70d1b49f830886c55ed53b1ef and I've added it to a personal repo here: https://github.com/peterjmag/react-devtools-issue-228. I'd like to be able to delete this repo later if necessary, so perhaps the actual packed extension should be hosted somewhere else (i.e. a branch on react-devtools, or FB's CDN)?

For now, here's a direct download link to the older version without the warning message in React 0.12 and below: https://github.com/peterjmag/react-devtools-issue-228/raw/master/react-devtools-329363301da8.crx

Once it's hosted somewhere with a "stable" URL, we can update the readme and the warning message URL.

**Comment by peterjmag** [comment]
Ah, and I should probably also add a note that this version needs to be installed by dragging / dropping it on [chrome://extensions](chrome://extensions), since it can't be installed automatically via download due to Chrome's extension signing stuff (I assume): http://stackoverflow.com/a/14454311/349353

**Comment by zpao** [comment]
Could probably go tag our old releases and then stick the compiled extension in the GH releases page

**Comment by davidmarcbrown** [comment]
This is not resolved in the build distributed in the Chrome Web Store - the old, broken link is still displayed in the error message when using the extension with old versions of react.
