### ISSUE TITLE
Namespaced components don't appear

### ISSUE THREAD

**Issue by kendagriff** [facebook/react-devtools#27]
When I namespace my components, the devtools can't find them. Furthermore, they appear to have meaningless data-reactids (".0.0.0.0"). Example:

```
Game.Views.Page = React.createClass({
  render: function() {
    return (
      <section className="page">Hello, World</section>
    );
  }
});
```

I reference my component using `Game.Views.Page()`. Is JSX responsible for producing meaningful information for the devtools? Is there no way to reference namespaced components using JSX?

**Comment by jaredly** [comment]
Is this still an issue?

**Comment by kassens** [comment]
Please open a new issue if this is still a problem. We've since launched a new version of the devtools on the Chrome store (it should've auto-updated already).
