### ISSUE TITLE
Source map support

### ISSUE THREAD

**Issue by petetnt** [facebook/react-devtools#271]
I am using React (in ES6 flavor) through (Grunt) Browserify with `babelify, `envify` and `uglifify` transforms (wow that was a mouthful). I generate inline source maps by having the `--debug` flag enabled and the sourcemaps work as you would expect them to work. 

The only issue is that running through the code through the uglifier uglifies what you see in the `react-devtools` Tree View too, which makes debugging a bit hard:

![image](https://cloud.githubusercontent.com/assets/7641760/10939350/9fb17192-8309-11e5-9d38-2dac9490f963.png)

The obvious workaround is easy: just don't uglify your files when in development. But sometimes that is not an option, or you want to use minified files in development anyway. Source map support would solve this issue but there might be some inner workings of `react-devtools` that I am not aware of that would make this impossible. I know that Chrome has file access behind a opt-in flag in the extensions menu, so there's at least that.

**Comment by jaredly** [comment]
unfortunately chrome devtools' handling of source maps is entirely opaque to extensions like react-devtools.

I expect the easier way of doing things would be to convince `uglify` to not remove the names, or perhaps change the way babel transpiles displayNames such that uglify wouldn't get rid of them.

**Comment by petetnt** [comment]
Yeah, that's something I was expecting too. Thanks @jaredly, I see if I can configure `uglify` to keep the names instead!

**Comment by kassens** [comment]
There's also some option to babel to add an explicit displayName string to React components. Since it's a string assignment, JS minifiers don't touch them.

**Comment by jaredly** [comment]
@petetnt one you figure it out, could you comment back here with the solution or PR the Readme FAQ? Other people have had this issue as well.
Thanks!

**Comment by petetnt** [comment]
Tried using https://github.com/gajus/babel-plugin-react-display-name to add explicit displayNames to the components but `uglify` still managed to mangle the displayNames.  Fiddled around with all the https://github.com/mishoo/UglifyJS2 settings and only way I managed to keep the displayNames was to remove the mangling all together in during the build. For now at least it seems like an reasonable solution, as one can easily toggle that on and off depending on the `NODE_ENV`.

**Comment by spicyj** [comment]
@petetnt That sounds like a good solution. Can you explain why you want to use uglify in development though?

Closing since I don't think there's anything more for us to do here.

**Comment by petetnt** [comment]
@spicyj For no special reason, just for simplifying the build process slightly across environments and maybe occasionally running into a minifying edge case :hamster: 

Thanks all!

**Comment by jo32** [comment]
What if I want to debug production code? For example, I connect to a customer via Teamviewer and debug the production code. In such circumstances, restoring the component name may be useful.

**Comment by slikts** [comment]
> Can you explain why you want to use uglify in development though?

There's a gradient between development and production that can include stages using production configuration while still not being production and requiring debugging.

**Comment by a7madgamal** [comment]
can someone please explain why normal sourcemaps don't just click with the plugin like in sources tab 🤔 ?

**Comment by a7madgamal** [comment]
> chrome devtools' handling of source maps is entirely opaque to extensions like react-devtools.

how can we help solve this someday? chrome team or devtools or react...?
