### ISSUE TITLE
Hovering over component causes Warning: ReactMount: Root element has been removed...

### ISSUE THREAD

**Issue by hilary-L** [facebook/react-devtools#273]
Building a react app with material design lite. I noticed for the first time today that when I use the React dev tools and hover over a component inside the dev tools, I get this warning:

Warning: ReactMount: Root element has been removed from its original container. New container: [object HTMLDivElement]

This doesn't happen if I'm actually interacting with my app, only when I'm inspecting components inside of the react dev tools. I'm using the latest version of react. Any idea what could be causing this?

**Comment by hilary-L** [comment]
Update: this is most certainly an MDL issue, as it is fixed by wrapping the root element in my app in another div. Still not sure why it's happening, though.

**Comment by KristerV** [comment]
yep, exactly the same case. using Material Lite and when I started using the Layout component, this error started showing up. Especially when embedding content. Wrapping into another div for some reason fixes it indeed.

**Comment by JSGraef** [comment]
Same here. I see it when I'm using "mdl-js-layout" as a className, but wrapping it in a div 'solves' it.

**Comment by zpao** [comment]
MDL (at least the layout component) modifies the DOM. In particular it wraps the provided node in a div. This is incompatible with React's internal state, resulting in the issues mentioned. This has nothing to do with the devtools, but the devtools are exposing it as they depend on React internal state.
