### ISSUE TITLE
RFE: move devtools to inspector tab and/or panes

### ISSUE THREAD

**Issue by wmertens** [facebook/react-devtools#274]
Since React in the browser is intimately tied to the DOM, it's a shame you can't see the DOM and the VDOM at the same time.

Here are examples of both in jQuery extensions:
![tab](https://lh5.googleusercontent.com/t6_trxdzpMwyu0eah6Yqg8Nhnz0_m421D5Wy5gTLVlHcCNxNM1NDj0fnkpwib7Mapr0w-YM=s1280-h800-e365-rw)
![panels](https://lh3.googleusercontent.com/_Qwz_MraCAuZx3newJSd-dIowgt6dGHHYK38UdTu84QGJR-E9E8bf6Q0m85fpJX3rBXtwFNu=s1280-h800-e365-rw)

IMHO having the DOM, style, VDOM and React metadata all visible at once is much nicer for debugging and development.

**Comment by jaredly** [comment]
as your screenshot manages to show, things get really crowded really quickly :D 
What precisely do you feel is missing? e.g. what does the Elements tab show that the React tab doesn't?

**Comment by wmertens** [comment]
Mostly it is very annoying to have to hunt for the correct vdom node when
react was not started yet (sometimes this is automatic, sometimes not), and
having to switch between tabs to inspect styles and props.

Furthermore, the element selector always jumps back to the DOM view, and
that is probably the biggest source of frustration. If there was a VDOM
element selector, it would probably be less annoying.

The crowdedness I expect to be the same, because you don't have to show the
full VDOM tree. E.g. you can show a panel for the currently selected node
(as is now), and another panel that shows the vdom starting at the current
node. Open and close as desired.

On Sun, Nov 8, 2015, 1:53 AM Jared Forsyth <notifications@github.com> wrote:

> as your screenshot manages to show, things get really crowded really
> quickly :D
> What precisely do you feel is missing? e.g. what does the Elements tab
> show that the React tab doesn't?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/react-devtools/issues/274#issuecomment-154768222>
> .
>
-- 

Wout.
(typed on mobile, excuse terseness)

**Comment by spicyj** [comment]
> Mostly it is very annoying to have to hunt for the correct vdom node when react was not started yet

We should just fix the cases that this doesn't work. I noticed today one case where it selected the right node upon initial load but didn't scroll to it.

**Comment by wmertens** [comment]
It doesn't have to be an either/or situation... How about having a React
panel in addition to the React tab?

On Sat, Nov 14, 2015 at 8:21 AM Ben Alpert <notifications@github.com> wrote:

> Mostly it is very annoying to have to hunt for the correct vdom node when
> react was not started yet
>
> We should just fix the cases that this doesn't work. I noticed today one
> case where it selected the right node upon initial load but didn't scroll
> to it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/react-devtools/issues/274#issuecomment-156661378>
> .
>
-- 

Wout.
(typed on mobile, excuse terseness)

**Comment by gaearon** [comment]
It's very unlikely that we'd be integrating more tightly with the browser's native tabs given that the extension is cross-browser and cross-renderer (e.g. there's an Electron shell for React Native).

So if we have any selection bugs, let's fix them, but I doubt we'll explore the path suggested here.
