### ISSUE TITLE
Unable to resize smaller than widest component

### ISSUE THREAD

**Issue by wesbos** [facebook/react-devtools#275]
If a component has a couple of props, React Dev Tools makes the DOM pane as wide as the widest one. This makes it really hard to use them when docked to the side. 

Ideally something like this would just cause wrapping or horizontal scroll. I don't think this was an issue until about the last week. 

![Can't see the props / state pane with regular sizing](http://wes.io/dlNk/content)

![I have to expand it this wide just to see the props and state pane](http://wes.io/dlES/content)

**Comment by spicyj** [comment]
Weird, it should do a horizontal scroll.

**Comment by spicyj** [comment]
This is what I see on the React site:

![image](https://cloud.githubusercontent.com/assets/6820/11043161/3ac6274e-86d0-11e5-8d19-f28e837f9ae8.png)

**Comment by jaredly** [comment]
flexbox implementations are evolving (well, coming more in line with the spec), and result in issues like this. I think adding a `min-width: 0` or two would fix this problem. What version of Chrome are you running?

**Comment by wesbos** [comment]
I'm on Chrome Canary - I think I've figured out why its doing it. When I try resize, either to the left or the right, the width of the props/state panel just grows indefinitely. 

If I take the inline width off, it snaps to overflow scroll again. But upon resizing it, the inline width comes back.

Here is a video: http://wes.io/dl31

**Comment by FutureKode** [comment]
I am also seeing this issue Chrome Version 48.0.2552.0 dev (64-bit)

**Comment by wesbos** [comment]
Anyone else having this issue? It still persists for me.

**Comment by ESWAT** [comment]
Yup, still see this in 49.0.2568.0 canary.

**Comment by sillero** [comment]
Still an issue on Chrome (Mac) Version 49.0.2572.0 canary (64-bit)

**Comment by revolunet** [comment]
Same here :)

The panel shows a resize cursor but doesnt work at all, stucked on the longer line width.

**Comment by Ajwah** [comment]
Same here as well.
The panel doesn't allow me to resize.

<img width="1435" alt="screenshot 2015-12-14 08 10 25" src="https://cloud.githubusercontent.com/assets/11848116/11782767/1d801276-a241-11e5-82d5-e40498bf7a38.png">

**Comment by wesbos** [comment]
@spicyj Do you know where in the codebase the resizing code is? This is still an issue for me and a pretty big pain on smaller screens.

**Comment by revolunet** [comment]
i bet on here : https://github.com/facebook/react-devtools/blob/master/frontend/SplitPane.js

anyone knows how to inspect the inspector ? :p

**Comment by wesbos** [comment]
@revolunet Open dev tools in a new window and hit `⌘` + `Shift` + `C`

**Comment by revolunet** [comment]
OK thanks, looks like its `⌘` + `Alt` + `C` here

**Comment by jaredly** [comment]
@revolunet yeah it's the styles -- the flex-box stuff needs tweaking.
Use the [plain html shell](https://github.com/facebook/react-devtools/tree/master/shells/plain) to "inspect the inspector"

**Comment by revolunet** [comment]
thanks a ton @sillero :+1:

**Comment by shaimo** [comment]
I'm having the same issue on my Mac. Can fix it temporarily by opening in a new window and clicking ⌘ + Alt + C then dock again. But then a moment later, e.g. after searching for a component, the right pane is gone out of screen and there is no way for me to bring it back (can't resize the main panel)...

**Comment by shaimo** [comment]
I'm having the same issue on my Mac. The right pane is gone out of screen and I have no way to view it...

**Comment by shaimo** [comment]
I'm having the same issue on my Mac. As soon as I go to a component at depth 7-8 or more (which is almost all components given react-router, relay containers, etc) or just search for a component, the right pane is way out of view with no way to bring it in. Almost unusable at this point...
![screen shot 2016-03-17 at 3 54 59 pm](https://cloud.githubusercontent.com/assets/2842587/13848205/672ae614-ec59-11e5-81be-c1993fed143f.png)
