### ISSUE TITLE
React tab doesn't show up

### ISSUE THREAD

**Issue by lxsameer** [facebook/react-devtools#276]
I'm trying to debug my application using react dev tools but the "React" tab does not show up. here is my console screenshot

![screenshot from 2015-11-10 16-01-34](https://cloud.githubusercontent.com/assets/53159/11062503/a59dcf82-87c4-11e5-8ba6-6f033538e473.png)

I'm on Debian gnu/linux and my react version is 0.14.0-rc

**Comment by kassens** [comment]
Looks like you're using React Native. Unfortunately, that's a known issue: #229.
