### ISSUE TITLE
Component display Name is broken

### ISSUE THREAD

**Issue by micabe** [facebook/react-devtools#286]
see Picture attached

![image](https://cloud.githubusercontent.com/assets/11733571/11237419/11495aaa-8de0-11e5-978d-41e90e8cf70e.png)

**Comment by jaredly** [comment]
there are a variety of possible causes for this (we should probably add things to the FAQ).
What is your setup?
- babel version (if using)
- react version
- is this an es6-style or React.createClass-style or stateless component?

**Comment by micabe** [comment]
Hello @jaredly,
My versions are :
babel@5.6.0
react@0.13.3

my program is written in a React.createClass style..
it used to display my component name 
    var Magnifier = React.createClass({

but for some reasons it stopped working after a while
Thanks for helping!

**Comment by spicyj** [comment]
Can you paste your babel config?

**Comment by micabe** [comment]
Hello @spicyj ,

I am using meteor-babel wrapper for meteor with the default configuration.
Here is the link:
https://github.com/meteor/babel/blob/master/options.js

Cheers

**Comment by wesbos** [comment]
I had this issue as well when I upgraded to Babel 6 - you have to explicitly set `displayName` on your components or use the [React Display Name transform](http://babeljs.io/docs/plugins/transform-react-display-name/)

So, this is not an issue with dev tools.

**Comment by micabe** [comment]
Thanks @wesbos , i have used the transformer and made it to work :+1:
