### ISSUE TITLE
React tab doesn't show in the inspector

### ISSUE THREAD

**Issue by aexmachina** [facebook/react-devtools#287]
When I debug my React Native app in Chrome the React tab doesn't show in the dev tools. I'm running the current version and it does show if I use it on the React website. The debugger connection is working fine, so I can see the sources and interact with the code in the dev tools console, but I can't see the React tab showing component hierarchy.

**Comment by ngyikp** [comment]
Duplicate of https://github.com/facebook/react-devtools/issues/229 ?

**Comment by aexmachina** [comment]
So, is it expected behaviour that React Native apps are not supported by react-devtools?

**Comment by spicyj** [comment]
Yes, unfortunately.

**Comment by aexmachina** [comment]
That's sad :cry:

**Comment by aexmachina** [comment]
Are there any other options for inspecting a running ReactNative app?

**Comment by spicyj** [comment]
See the linked issue.
