### ISSUE TITLE
Fall back to current file name as display name 

### ISSUE THREAD

**Issue by jordi12100** [facebook/react-devtools#292]
Whenever you forget to put createClass in a variable, you'll see "no display name". 
Adding a variable will fix this issue, but it's not necessary in my opinion. Why not use the file name as display name?

**Comment by jaredly** [comment]
That's a good idea! It's a job for babel, though, not the devtools, and it looks like [this babel plugin](https://github.com/gajus/babel-plugin-react-display-name) does just that!

**Comment by kassens** [comment]
The Babel transform for React should support adding the display name based on the variable name. If this isn't sufficient, I would recommend opening an issue for the Babel transform or creating a custom transform that uses the file name.

See [this example](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=true&spec=true&code=var%20React%20%3D%20require('react')%3B%0A%0Avar%20Foo%20%3D%20React.createClass(%7B%0A%20%20%0A%7D)) of the Babel transform adding the `displayName`.
