### ISSUE TITLE
extend context menu

### ISSUE THREAD

**Issue by deepak1556** [facebook/react-devtools#3]
could be helpful if context menu in react tab provides shortcuts to 
- edit
- setting breakpoints
- deletion

**Comment by jaredly** [comment]
Could you expand on this? What breakpoints would you want to set?
I don't imagine deleting a node would play very well with react...

**Comment by jaredly** [comment]
The new beta version has a custom context menu, so we can add things if there's demand.
I'll close this for now due to lack of activity
