### ISSUE TITLE
<option>{1}{2}</option> causes `Uncaught TypeError: Cannot read property 'props' of undefined`

### ISSUE THREAD

**Issue by kolodny** [facebook/react-devtools#307]
demo here: http://kolodny.github.io/react-devtools-bug/  
source here: https://github.com/kolodny/react-devtools-bug

You need to open up the react devtools tab to see the error

**Comment by inklesspen** [comment]
May be a duplicate of #248.

**Comment by spicyj** [comment]
Yeah, dupe of #248.
