### ISSUE TITLE
[Feature request] Make it work with chrome remote debug [if its possible]

### ISSUE THREAD

**Issue by Bnaya** [facebook/react-devtools#309]
I'm developing cordova app with react, and debugging the webview with chrome remote debug
It was very helpful if the react dev tools were also active for remote debug.

https://developers.google.com/web/tools/chrome-devtools/debug/remote-debugging/remote-debugging?hl=en

**Comment by xuchaobei** [comment]
I have the same problem. I hope the feature comes soon.

**Comment by gaearon** [comment]
The standalone [React DevTools](https://github.com/facebook/react-devtools/blob/master/packages/react-devtools/README.md) should probably work for you.
It listens at `localhost:8097`.

**Comment by piotr-cz** [comment]
I'd like to inspect pages that I don't own and it's so so straightforward to use React DevTools when Content security policy is in place.

For example when adding script via console, this is what I'm getting.

```
Refused to load the script 'http://localhost:8097/' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' https://*.twimg.com https://www.google-analytics.com 'unsafe-eval'".
```

Chrome remote debugging window doesn't have a toolbar - so no React-Devtools extension button either, the React tab doesn't show up and I'm not aware of any way to initialize this extension via console.
