### ISSUE TITLE
Inspect the node on which the component is mounted

### ISSUE THREAD

**Issue by stof** [facebook/react-devtools#310]
Currently, there is a scrollToNode option in the React dev tools. But it would be great to also have an option to inspect the node (when switching to the other panels).

**Comment by stof** [comment]
Note that using ``ReactDOM.findDOMNode($r)`` in the console is a workaround for that (as this gives us the DOM node), but it would be great to have some UI for that

**Comment by jaredly** [comment]
I imagine you're in firefox? this is implemented in chrome, but I wasn't able to find a way to do it in firefox

in chrome:
![image](https://cloud.githubusercontent.com/assets/112170/12209181/9d215068-b60e-11e5-922c-b775f372269c.png)

**Comment by gaearon** [comment]
Closing per comment above.

**Comment by stof** [comment]
yeah, I'm in Firefox
