### ISSUE TITLE
$r overwrites application's global $r variable

### ISSUE THREAD

**Issue by patbl** [facebook/react-devtools#316]
> Selected component instance is available as $r from the console

(https://facebook.github.io/react/blog/2015/09/02/new-react-developer-tools.html)

The app I work on uses `$r` extensively ("r" is short for "route"). Could you assign that variable only if it's undefined?

**Comment by kassens** [comment]
Yes, we should do that.

**Comment by yinghaochan** [comment]
pretty please? @kassens

**Comment by gaearon** [comment]
Fixed in https://github.com/facebook/react-devtools/pull/463.
