### ISSUE TITLE
Support iframes that doesn't have the top===0

### ISSUE THREAD

**Issue by hackhat** [facebook/react-devtools#320]
I've found this solution ( https://github.com/facebook/react-devtools/issues/76 ) to debug iframes. Let's say my iframe has `postion: absolute, top: 10px` then when I hover a element in the react-devtools the debug boxes that appear on the webpage are offset by 10px up. This happens because of the top: 10px;

![image](https://cloud.githubusercontent.com/assets/11173732/12611910/2e163bc4-c4e7-11e5-8090-521934a897ce.png)

**Comment by hackhat** [comment]
The fix is to use margin instead of top. Solution: `top: 0; margin-top: 10px`

**Comment by jaredly** [comment]
yeah. I'm not sure there's a super good way to do that. I looked into it a bit

**Comment by gaearon** [comment]
You can now use the [standalone DevTools](https://github.com/facebook/react-devtools/tree/master/packages/react-devtools) to debug iframes.

**Comment by zlbben** [comment]
hi，standalone DevTools had the same problem
