### ISSUE TITLE
Work in electron?

### ISSUE THREAD

**Issue by iamdustan** [facebook/react-devtools#321]
I’m attempting to get this to work in Electrode with [Jam3/devtool](https://github.com/Jam3/devtool). 

Background on my initial attempt is over at [Jam3/devtool/#35 (3 Comments)](https://github.com/Jam3/devtool/issues/35)

I tried configuring *Jam3/devtool* with my already installed chrome plugin ("~/Library/Application Support/Google/Chrome/Default/Extensions/fmkadmapgofadopljbjfkapdkoienihi/{version}") as well as cloning and building the chrome shell in here from source.

Have you had any other experience or knowledge that could assist getting these working together?

Thank you.

**Comment by mattdesl** [comment]
This issue is being tracked in Electron here:
https://github.com/atom/electron/issues/915

:smile:

**Comment by iamdustan** [comment]
Ha. Reading through that thread gives me very little confidence on a fix landing in Electrode in the next 12 months even.

**Comment by iamdustan** [comment]
Closing for #263

**Comment by jsnar** [comment]
NW.js has support for devtool extension for months. Recently React devtools is supported too: http://nwjs.io/blog/v0.13.0-beta7/ 
I believe they have better Chrome features support and newest Chromium version.
