### ISSUE TITLE
Upon opening Chrome devtools: "TypeError: Cannot read property 'network' of undefined"

### ISSUE THREAD

**Issue by kivikakk** [facebook/react-devtools#322]
I'm getting a bit of a weird thing happening.

I have the latest React Developer Tools installed (0.14.8), running Chrome 48.0.2564.103 (64-bit) on OS X.

When I navigate to a page with React (with Chrome devtools closed), then open the devtools, they briefly open, and then the entire page gets redirected (!) to chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/main.html (part of React Developer Tools), with the debugger broken at this line of main.js:

>	chrome.devtools.network.onNavigated.addListener(function () {

With the exception text:

> Uncaught TypeError: Cannot read property 'network' of undefined

Screenshot of the above:

![screen shot 2016-02-04 at 15 29 32](https://cloud.githubusercontent.com/assets/1915/12805859/1b527c0a-cb54-11e5-91a3-93118b65ad9e.png)

A coworker has the same versions without this issue, so I'm a bit lost! With the debugger paused at that line, `chrome.devtools` is indeed undefined, and it makes sense why — the extension has, for whatever reason, been loaded in a tab, and isn't executing in the context of the Chrome devtools.

But I'm unable to track down why the redirect is occurring in the first place. Any hints?

**Comment by kassens** [comment]
Does this happen on every website containing React for your (for example facebook.com) or just a specific one? If it's a specific one, can you share a URL so we can try to reproduce this issue?

**Comment by kivikakk** [comment]
I can reproduce it on facebook.com, yep. This doesn't happen on Canary (installed side-by-side the regular Chrome channel), so I assume it's actually something to do with my Chrome install more than anything; others in my office can't repro this.

Might be worth just closing the issue.
