### ISSUE TITLE
"Inspect in react" context menu

### ISSUE THREAD

**Issue by tnrich** [facebook/react-devtools#323]
I don't know if this would be possible, but it would be awesome if there were a way to select a component on the page and have it jump to that component in the tools a la the normal chrome "inspect element": 
![image](https://cloud.githubusercontent.com/assets/2730609/12830807/091b7e96-cb46-11e5-896a-aec1703a405a.png)

Imagine if there was an "inspect in react" option!

**Comment by spicyj** [comment]
I don't believe this is possible, but if you inspect element and then switch to the React tab, it should select the right component automatically!

**Comment by jaredly** [comment]
Extensions can add items to the context menu, and I think I remember @sebmarkbage opting not to do it for the original extension to avoid clutter.
but I'd be open to it -- would certainly cut two steps down to one

**Comment by spicyj** [comment]
I don't want to show it on non-React pages but if we can do it without that then I'm in favor.

**Comment by tnrich** [comment]
Hey @jaredly thanks for the info about switching tabs to inspect the element. That alone is a big help! I'd still be in favor an "inspect in react" option, but I don't think it is as urgent now that I know the other method. Thanks again!

**Comment by Timothee** [comment]
I don't believe either opening devtools from background or content scripts, nor opening a specific panel programmatically (say when devtools is already open) are possible at this time. I looked through the [`chrome.devtools`](https://developer.chrome.com/extensions/devtools) APIs and couldn't find anything.

> I don't want to show it on non-React pages but if we can do it without that then I'm in favor.

Having it only on React pages should be easy: you'd listen on tab changes and add or remove the context menu item based on the page. But that seems moot from what I can tell.

I'd be happy to be proven wrong though :smile:

**Comment by jrnail23** [comment]
I know Redux DevTools does add something to the context menu (see screenshot below), but I don't think it's quite the same thing being asked for here.

That said, I *really* want this feature.

#### Redux DevTools context menu: ####
<img width="621" alt="screen shot 2016-04-26 at 12 29 37 pm" src="https://cloud.githubusercontent.com/assets/392612/14826166/a42ec7b8-0baa-11e6-9a04-7f57cc10c64f.png">

**Comment by Timothee** [comment]
@jrnail23 I just checked it out and it's not the same thing indeed. All the five options displayed above open a separate browser window, not a panel in Chrome DevTools. ("Open in a chrome panel" made me hopeful but I checked the source code as well, and it just opens a window)

**Comment by gaearon** [comment]
Closing as it doesn't seem possible.
Let me know if I'm wrong and we'll reopen.

**Comment by crimsonsunset** [comment]
If you're open for a good ol' hack, this has been working for me 😁

Prereq: [Better Touch Tool](https://www.boastr.net/)

<img width="1023" alt="screen shot 2017-10-13 at 2 49 40 pm" src="https://user-images.githubusercontent.com/3998637/31561415-ca791e8e-b025-11e7-9ded-99b22e33089d.png">

1) Select [or add] Chrome to the application pane on the left
2) Select desired trigger (for me in the above image, it's keyboard)
3) Set trigger (for me cmd+shift+option+r) to trigger context menu item
4) In resultant input box, do this:
<img width="678" alt="screen shot 2017-10-13 at 2 52 13 pm" src="https://user-images.githubusercontent.com/3998637/31561520-1f18e280-b026-11e7-85f9-66d4d93d6640.png">
5) Attach 2 additional actions by clicking "Attach additional action" button on the bottom right
6) Set 1st additional action -> delay by 0.6 (might vary depending on your computer)
7) Set 2nd additional action -> cmd + ]
8) Profit
