### ISSUE TITLE
What does trace react updates do? 

### ISSUE THREAD

**Issue by bhoomipatel6386** [facebook/react-devtools#327]
I am unable to find any documentation on how to use "trace react updates" checkbox in the developer tools under react section

<img width="721" alt="screen shot 2016-02-17 at 3 13 46 pm" src="https://cloud.githubusercontent.com/assets/6412344/13128240/417aa6f2-d589-11e5-8adb-b3e11f6557b5.png">

OS - Mac 64
Chrome version - 48.0.2564.109 (64-bit)
React developer tool version -  0.14.8

**Comment by iamdustan** [comment]
Did you try it out?

**Comment by bhoomipatel6386** [comment]
Yes checking/unchecking it does show up any changes, or any activity.

**Comment by kassens** [comment]
When you enable it will highlight React elements that are updated on the page. This can be helpful to track down performance issues where potentially too many elements update when you're only expecting a few elements to update.

We should add a description somewhere. cc @hedgerwang

**Comment by iamdustan** [comment]
https://github.com/facebook/react-devtools/pull/297

**Comment by bhoomipatel6386** [comment]
Ah got it!. Thank you.

**Comment by iamdustan** [comment]
Would it be more helpful to add inline docs to the DevTools or create a documentation site for the DevTools?

**Comment by omarjackman** [comment]
@kassens What do all of the colors mean when the elements are flashing? I see blue most of the time and when a ton of updates are happening I see red but what does green mean?

**Comment by omarjackman** [comment]
nevermind, got it 😄
