### ISSUE TITLE
Overlay doesn't disappear when devtools are closed

### ISSUE THREAD

**Issue by spicyj** [facebook/react-devtools#33]

**Comment by facebook-github-bot-7** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by jaredly** [comment]
Fixed in the beta http://facebook.github.io/react/blog/2015/08/03/new-react-devtools-beta.html
