### ISSUE TITLE
[ReactNative][Feature Request] Inspect dimensions of native views

### ISSUE THREAD

**Issue by rigdern** [facebook/react-devtools#330]
It'd be nice to be able to see what dimensions the platform has assigned to a native view. For example, when inspecting a `View` on iOS, it'd be nice to be able to see that the layout engine has assigned the underlying UIView a height of `100` and a width of `150`.

**Comment by gaearon** [comment]
Going to be solved in https://github.com/facebook/react-devtools/pull/590.
