### ISSUE TITLE
Chrome not loading plugin

### ISSUE THREAD

**Issue by arghasarkar** [facebook/react-devtools#332]
Google chrome Version 48.0.2564.116 m is not loading the chrome plugin properly. It is installed and enabled. Whenever I load the chrome console, a message indicating that I should download the dev tools, come up.

**Comment by s-abazi** [comment]
The same bug occurs on:
Chromium Version 47.0.2526.80 Built on 8.2, running on Debian stretch/sid (64-bit)

**Comment by tedbreen** [comment]
I'm currently having this problem as well with React Developer Tools 0.14.8. I am using the same version of Chrome: Version 48.0.2564.116 (64-bit)

The dev tools will work on certain sites, like Facebook and the Facebook React page. On other React sites, I will also get the message:

Download the React DevTools for a better development experience: https://fb.me/react-devtools

**Comment by tmikoss** [comment]
Same situation. 

Dev tools 0.14.8 
OS X chrome 49.0.2623.75 (64-bit)

Shows `background page (Inactive)` in extensions list. Nothing in background page console.

**Comment by gaearon** [comment]
Unfortunately we can't help without a project reproducing the problem.

If you can demonstrate that it works on Facebook.com but doesn't work on a React >=0.14 project elsewhere I'd be happy to take a look.
