### ISSUE TITLE
Cannot set breakpoint in generator function

### ISSUE THREAD

**Issue by narychen** [facebook/react-devtools#334]
It sometimes happens on chrome debugger.
You set the breakpoint in a generator function or in the async await function, the breakpoint will move downward automatically to somewhere.

**Comment by jaredly** [comment]
this is a result of using babel, and is unrelated to the react devtools.
You can disable generator transpilation if you're just targetting chrome (which supports generator functions already), and that will make them easier to debug

**Comment by kassens** [comment]
Yes, this seems to be a bug with either the source maps of the transform or the source map support in the Chrome Devtools.

**Comment by narychen** [comment]
@jaredly  But how to disable the generator trans? I cannot find any doc about it on the babel website.

**Comment by jaredly** [comment]
It has to do with your presets. If you're using babel-preset-stage-0/1/2/3, I think it references a plugin that transpiles async functions to es5. maybe [babel-plugin-transform-async-functions](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-async-functions).

**Comment by narychen** [comment]
@jaredly thanks

**Comment by FoxxMD** [comment]
Sorry to bring this back from the grave but I'm having this same problem and can't find any more recent discussions on it.

I don't have ` babel-plugin-transform-async-functions` installed but I do have stage-0 enabled. Any insight on how I can disable generator transpilation?

Dependencies:

```
    "babel-cli": "6.18.0",
    "babel-core": "6.21.0",
    "babel-eslint": "7.1.1",
    "babel-loader": "6.2.10",
    "babel-plugin-dynamic-import-node": "1.0.0",
    "babel-plugin-import": "^1.1.1",
    "babel-plugin-react-intl": "2.2.0",
    "babel-plugin-react-transform": "2.0.2",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-es2015-modules-commonjs": "6.18.0",
    "babel-plugin-transform-react-constant-elements": "6.9.1",
    "babel-plugin-transform-react-inline-elements": "6.8.0",
    "babel-plugin-transform-react-remove-prop-types": "0.2.11",
    "babel-polyfill": "6.20.0",
    "babel-preset-latest": "6.16.0",
    "babel-preset-react": "6.16.0",
    "babel-preset-react-hmre": "1.1.1",
    "babel-preset-stage-0": "6.16.0",
```

webpack config for babel:

```
  "babel": {
    "presets": [
      [
        "latest",
        {
          "es2015": {
            "modules": false
          }
        }
      ],
      "react",
      "stage-0"
    ],
    "env": {
      "production": {
        "only": [
          "app"
        ],
        "plugins": [
          "transform-react-remove-prop-types",
          "transform-react-constant-elements",
          "transform-react-inline-elements",
          "transform-class-properties"
        ]
      },
      "development": {
        "plugins": [
          "transform-class-properties"
        ]
      },
      "test": {
        "plugins": [
          "transform-es2015-modules-commonjs",
          "dynamic-import-node"
        ]
      }
    }
  },
```

**Comment by narychen** [comment]
@FoxxMD The best way to avoid this is not to async/await but raw Promise instead.
I'm using Promise instead of async/await after encountering this problem. 
In fact async/await is using Promise behind the generator, so you can always  do  with Promise instead of async/await.
