### ISSUE TITLE
Right pane gets pushed off screen

### ISSUE THREAD

**Issue by idris** [facebook/react-devtools#336]
This didn't always happen, but in the last month or so I noticed that there is no horizontal scrolling where the elements are shown, so the right pane (with props) is pushed off screen.  Below are some screenshots:

Completely hidden:
<img width="1071" alt="screen shot 2016-02-28 at 6 12 23 pm" src="https://cloud.githubusercontent.com/assets/13989/13380556/d30ef2f6-de46-11e5-949c-8455b4aa8679.png">

Semi-hidden when I make the window really wide:
<img width="1323" alt="screen shot 2016-02-28 at 6 12 46 pm" src="https://cloud.githubusercontent.com/assets/13989/13380561/e1d81e70-de46-11e5-836b-45983949286c.png">

**Comment by jdivock** [comment]
Same
What I see in full screen
![nuttin](http://i.imgur.com/Ri8pPc4.png)

After I drag the browser left off screen to expand
![oh there it is](http://i.imgur.com/IpTNIMi.png)

**Comment by idris** [comment]
Looks like we're both using Relay, I wonder if that has something to do with it

**Comment by gaearon** [comment]
I can't reproduce this. Assuming it was fixed.

<img width="642" alt="screen shot 2017-04-21 at 2 38 52 pm" src="https://cloud.githubusercontent.com/assets/810438/25279999/518e244c-26a0-11e7-98b5-42c7d151580b.png">

**Comment by classyrancor** [comment]
This is happening to me today. It looks to do with the depth of the tree that you are trying to look through. It is fine when you are looking near the top of the tree.

![right_pane_works](https://user-images.githubusercontent.com/42614634/44472288-d5f86400-a5fb-11e8-864e-2c500e0f7877.PNG)

Once you try and select something further down the tree that is many levels deep the right pane gets pushed off the screen.

![missing_right_pane](https://user-images.githubusercontent.com/42614634/44472157-9b8ec700-a5fb-11e8-9429-a515363c63c6.PNG)

**Comment by gaearon** [comment]
cc @bvaughn might be related to recent changes.

@classyrancor Can you check which version are you on?

**Comment by classyrancor** [comment]
it is React Developer Tools 3.3.0 running on Firefox 61.0.2 (64-bit)

**Comment by gaearon** [comment]
Any chance you could share a website where I can reliably reproduce it? Didn't manage so far.

**Comment by bvaughn** [comment]
Also curious if @classyrancor can repro on Chrome by chance?

I don't think I'll have time to look into this in the next few days, unfortunately

**Comment by classyrancor** [comment]
It seems to only happen running locally with a non-production build React app. If I open React Dev Tools on instagram I can browser anywhere and have no issues. Let me try a couple things. Let me build my application and try it on the production build version and also I can try in Chrome. Not sure what the difference would be. Maybe longer non-breaking strings for class names or something?

**Comment by gaearon** [comment]
>Maybe longer non-breaking strings for class names or something?

Sounds likely.

**Comment by classyrancor** [comment]
This only happens running on the local build. No issue browsing through the production build. I notice a couple things that differ between the builds. The number of displayed components, the length of the displayed component names and the length of the class names.

No issue browsing the non-production build using Chrome.

**Comment by gaearon** [comment]
If you can reduce the local build example to something you could share that would be helpful.

**Comment by classyrancor** [comment]
Once I have it compiling again I can see if I can pull out enough of it to exhibit this behavior.

**Comment by classyrancor** [comment]
With this build if you make the developer console wide enough the right pane will come back in view, but with a reasonably sized console it goes off the page. In any case you can see it bumping over as you go down the DOM tree.

[breaks-dev-tools.zip](https://github.com/facebook/react-devtools/files/2311192/breaks-dev-tools.zip)

**Comment by gaearon** [comment]
Awesome. Thanks. We'll try to look next week. If you'd like to take a stab at fixing it, feel free to as well!

**Comment by classyrancor** [comment]
No problem at all. If i can find some free time I'll take a look.

**Comment by bvaughn** [comment]
Fixed via #1111

**Comment by a55g** [comment]
Very good solution GitHub thank you get up
