### ISSUE TITLE
console event's properties are null in event handle

### ISSUE THREAD

**Issue by inickel** [facebook/react-devtools#339]
env: 
react 0.14.7
react-dom 0.14.7
when i use console.log(event) in event's handle,the properties's values of event are all null, is there someone face that? 
snapshot
![image](https://cloud.githubusercontent.com/assets/5063336/13486865/bf178310-e14f-11e5-8562-4873a0658ea4.png)

**Comment by jaredly** [comment]
@inickel as I understand it, event objects are re-used to avoid memory overhead. So by the time you expand it, all the attributes have been reset to null. Try doing `console.log(JSON.stringify(event))` or something similar, to get a snapshot of what the event looks like at the moment you log it

**Comment by inickel** [comment]
ths 4 u explaination, that is a better way to get snapshot of events;
