### ISSUE TITLE
Show child context in Devtools

### ISSUE THREAD

**Issue by aight8** [facebook/react-devtools#347]
Is this planned or purposely not implemented because it's an experimental feature?

**Comment by spicyj** [comment]
No, I'm not opposed to showing this.

**Comment by gaearon** [comment]
Removing the label because we'll change how context works soon after Fiber, and not sure it's worth exposing right now.

**Comment by gaearon** [comment]
I probably wouldn't bother fixing this now. We plan to change context API in the future and it's just not worth it to expand surface area now IMO. Let's come back to this some time later.
