### ISSUE TITLE
[bug] sometimes tree items are empty & I can't inspect most of my app

### ISSUE THREAD

**Issue by jaredly** [facebook/react-devtools#35]
I haven't figured out how to reproduce this reliably, but it happens several times a week. Refreshing the page fixes it.

Symptoms:

- inspecting element, then switching to the react tab, the tree is totally/mostly collapsed
- trying to expand components in the tree view shows them with apparently no children

**Comment by facebook-github-bot-7** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
