### ISSUE TITLE
No dark theme available?

### ISSUE THREAD

**Issue by krailler** [facebook/react-devtools#351]
No dark theme available?

**Comment by kassens** [comment]
Unfortunately, nobody found the time yet. Contributions welcome!

Tracked more generally in #108.

**Comment by gaearon** [comment]
There is now.

![screen shot 2017-05-26 at 22 50 41](https://cloud.githubusercontent.com/assets/810438/26513950/72010de8-4266-11e7-8dfe-a0337d6346b1.png)
