### ISSUE TITLE
Search often fails

### ISSUE THREAD

**Issue by ffxsam** [facebook/react-devtools#352]
I've been getting this a lot lately. Not quite sure how to reproduce it.

![licecap](https://cloud.githubusercontent.com/assets/12532733/14003510/97760a7c-f110-11e5-9ee9-a6ca389de105.gif)

**Comment by gaearon** [comment]
It's been fixed for a while now.

**Comment by gaearon** [comment]
(Actually, a different issue was fixed... But if you still can repro this please provide an example. Otherwise it's very hard to know why it happens.)

**Comment by ffxsam** [comment]
Thanks Dan! I actually haven't had this issue in forever.
