### ISSUE TITLE
Position of triangle is a bit too low.

### ISSUE THREAD

**Issue by kxxoling** [facebook/react-devtools#353]
![triangle](https://cloud.githubusercontent.com/assets/1227139/14038999/62f6d4a6-f292-11e5-82e8-bff8f70a68c7.png)

My browser is the newest Chrome on OS X 10.11.3

**Comment by juanruizcasas** [comment]
Ok

**Comment by spicyj** [comment]
I think I rewrote this. Let me know if it's still not fixed.
