### ISSUE TITLE
Dark theme needs some tweaking

### ISSUE THREAD

**Issue by Daniel15** [facebook/react-devtools#355]
Chrome devtools now support a dark theme:

![screen shot 2016-03-25 at 3 14 10 pm](https://cloud.githubusercontent.com/assets/91933/14055116/4625a488-f29c-11e5-8c6f-4c520c0f83af.png)

The React dev tools appear to support it somewhat, but there's a few minor styling issues:
![screen shot 2016-03-25 at 3 16 01 pm](https://cloud.githubusercontent.com/assets/91933/14055142/899e8ebe-f29c-11e5-8b16-837fcbe52a7d.png)

 - Side panel: `$r in the console`, `props` and `state` text is black, it should be a light colour
 - Background on a few things ("trace react updates" checkbox, breadcrumbs, and search by component name) should be dark
 - Hover colour on elements in the tree should be dark (is there a way we can reuse the exact same hover colour from the "Elements" tab?)
 - Scrollbars should be dark (https://css-tricks.com/custom-scrollbars-in-webkit/). Chrome itself has this issue too so I'm also going to report it to them.

**Comment by spicyj** [comment]
We actually don't support it at all. Just forgot to add backgrounds to a bunch of things so it actually kinda sorta works. #108.

**Comment by Daniel15** [comment]
Oh, LOL. If I find some free time, I'll see if I can determine how the dark theme works and how to get it working properly in the React devtools.

**Comment by spicyj** [comment]
Please do!

**Comment by gaearon** [comment]
It works now.

![screen shot 2017-05-26 at 22 50 41](https://cloud.githubusercontent.com/assets/810438/26513950/72010de8-4266-11e7-8dfe-a0337d6346b1.png)
