### ISSUE TITLE
Issues with server middleware

### ISSUE THREAD

**Issue by kevinSuttle** [facebook/react-devtools#367]
I've noticed with both Webpack-Dev-Server and React-Storybook, that getting the panel and accessing my component is inhibited. This isn't the case with gulp, though. 
###### FirefoxDeveloperEdition 47.0a2 (2016-04-25)

None of my components can be found. cc: @arunoda 

<img width="1440" alt="screen shot 2016-04-27 at 4 01 17 pm" src="https://cloud.githubusercontent.com/assets/95672/14866358/5b344438-0c91-11e6-86bf-8497dde1ba13.png">

<img width="1440" alt="screen shot 2016-04-27 at 3 57 04 pm" src="https://cloud.githubusercontent.com/assets/95672/14866312/1398d6d4-0c91-11e6-8ab4-cee9e6cac353.png">
###### Chrome 50.0.2661.86 (64-bit)

Same story here. What you're seeing is the Button in the React Storybook app.
<img width="1440" alt="screen shot 2016-04-27 at 4 05 13 pm" src="https://cloud.githubusercontent.com/assets/95672/14866467/eb78140c-0c91-11e6-8dbd-1d1fe574d7de.png">
###### FirefoxDeveloperEdition 47.0a2 (2016-04-25)

<img width="968" alt="screen shot 2016-04-27 at 4 06 17 pm" src="https://cloud.githubusercontent.com/assets/95672/14866495/0ae3dcf4-0c92-11e6-85bc-852ce30c7122.png">
###### Chrome 50.0.2661.86 (64-bit)

Notice no React panel.

<img width="772" alt="screen shot 2016-04-27 at 4 03 37 pm" src="https://cloud.githubusercontent.com/assets/95672/14866431/b48df880-0c91-11e6-8070-16cb65a3669d.png">
cc: @sokra

**Comment by jaredly** [comment]
yeah, the webpack dev server hot reloading stuff puts your app in an iframe, and react devtools can't handle iframes atm :/

**Comment by arunoda** [comment]
@kevinSuttle Try using the latest version of React Storybook, we've added a fix for this.
See: 
![screen shot 2016-04-28 at 3 19 11 am](https://cloud.githubusercontent.com/assets/50838/14869295/190f4c56-0cf0-11e6-9090-452bd933e7c0.png)

Related issue: https://github.com/kadirahq/react-storybook/issues/102

**Comment by kevinSuttle** [comment]
@arunoda Still not seeing it in FirefoxDeveloperEdition 47.0a2 (2016-04-25), Firefox ESR 45.1.0 , or Chrome 50.0.2661.86 (64-bit) unfortunately (all on Mac). 

Chrome shows me the `<button>` at the top of the Storybook UI, but not the <Button> a story was written for. 

<img width="1440" alt="screen shot 2016-04-28 at 3 52 23 pm" src="https://cloud.githubusercontent.com/assets/95672/14899273/48251372-0d59-11e6-9c1a-2d89c6bcd546.png">

`"@kadira/storybook": "^1.19.0",`

**Comment by arunoda** [comment]
As @jaredly mentioned, I assume iframe support for React devtools is not fully supported. 
I hope this is the best you can get at this moment.

**Comment by kevinSuttle** [comment]
@arunoda How were you able to get the screenshot you posted?

**Comment by arunoda** [comment]
I am using the latest version of @kadira/storybook (v1.19.0). Other than that, there's no other change.
(I hope that's the same thing as you got)

**Comment by kevinSuttle** [comment]
Haha, no I meant that I used the latest storybook package from npm (same 1.19) and didn't see my components in Chrome.

**Comment by kevinSuttle** [comment]
Hm. I see them now in Chrome. Shrug.

**Comment by kevinSuttle** [comment]
I wonder if Shadow DOM could help here (is a thing I never thought I'd say).

https://twittercommunity.com/t/upcoming-change-to-embedded-tweet-display-on-web/66215

**Comment by gaearon** [comment]
Not a perfect solution but you can now use [standalone React DevTools](https://github.com/facebook/react-devtools/tree/master/packages/react-devtools) to debug iframes.
