### ISSUE TITLE
Can't see the React Developers Tool Tab in the Console

### ISSUE THREAD

**Issue by seque1990** [facebook/react-devtools#369]
I'm working on an Android React Native project, I added the React Dev Tool from the Chrome Web Store, I went into `chrome://extensions` and clicked on 'Allow access to file URLs' however after doing this, I am not able to see the React Tab in the Chrome console.

<img width="1280" alt="screen shot 2016-04-29 at 5 33 34 am" src="https://cloud.githubusercontent.com/assets/10457555/14914946/f39b5e60-0dcb-11e6-9417-aee2f8c3238a.png">

**Comment by spicyj** [comment]
The tab only appears on a page that uses React. Unfortunately the RN debugger page doesn't work right now. See #229.
