### ISSUE TITLE
Strange behaviour in option tag

### ISSUE THREAD

**Issue by aight8** [facebook/react-devtools#372]
It only occurs when I add the `({category.cnt})` part to it. The whole developer tool crashes than and an error in the console appears.

``` JSX
return categories.map((categoryId) => {
            let category = categories[categoryId];
            return (
                <option
                    key={category.id}
                    value={category.id}
                >
                    {category.caption} ({category.cnt})
                </option>
            );
        });
```

<img width="1099" alt="bildschirmfoto 2016-05-05 um 20 49 59" src="https://cloud.githubusercontent.com/assets/1138623/15053444/04dca6d4-1303-11e6-9dd3-c4cd065ceaed.png">

**edit:**
Btw this works: `{category.caption + '(' + category.cnt + ')'}`

I searched the reason why the dev toolbar don't load for one hour, so I think this crash must be prevented anyway. The application was runnable though.

**Comment by gaearon** [comment]
It was fixed in #345.
