### ISSUE TITLE
hope to add custom font-style setting

### ISSUE THREAD

**Issue by mrdulin** [facebook/react-devtools#375]
The font-style in windows system is ugly~

**Comment by spicyj** [comment]
What font would you use?

**Comment by mrdulin** [comment]
@spicyj Thanks for reply!
As you can see,
![image](https://cloud.githubusercontent.com/assets/17866683/15382259/fe93faf8-1dba-11e6-819b-4cea9883489e.png)

In chrome browser, the font style is ugly and font size is little small.
I like monospaced fonts like 'Consolas' and want to set the font size larger

**Comment by ngyikp** [comment]
Try going to `chrome://settings/fonts` and adjust the Fixed-width font/宽度固定的字体.

Chrome in Chinese sets this to `NSimSun` by default.

**Comment by spicyj** [comment]
I'd be happy to take a pull request to change this to `Menlo, Consolas, monospace`:

https://github.com/facebook/react-devtools/blob/dfe8977860d1ee4298fe18c34dc86012c3d8288e/frontend/TreeView.js#L99

**Comment by spicyj** [comment]
Let's do `Menlo, Consolas, Monaco, monospace` actually.

**Comment by gaearon** [comment]
Was fixed in ea310cda56a44398069c292f0fb1b9893f6c7ff6.
