### ISSUE TITLE
[Feature request] An ability to filter out decorations in the tree

### ISSUE THREAD

**Issue by fckt** [facebook/react-devtools#379]
First I'll just define a problem which me (and, not only me) faced..

It turns out that it's common today to have a deeply nested components thee. In many ways, it becomes as it is due to a heavy usage of decorators of any kind or/and other 'compositions'.
As an example (not a weirdest case):
<img width="628" alt="screen shot 2016-05-26 at 3 41 37 pm" src="https://cloud.githubusercontent.com/assets/547167/15574883/8f11c310-2358-11e6-9c23-3f02d43ddb26.png">

I think, it would be nice to have an ability to filter out decorators-like 
components from the three based on some criteria (could be user-defined, I guess).

**Comment by spicyj** [comment]
Is the tree frustrating to you or only the list at the bottom?

**Comment by spicyj** [comment]
If the latter, perhaps we could do this like Chrome:

![image](https://cloud.githubusercontent.com/assets/6820/15585567/c30b4cdc-2334-11e6-825c-235f5f99e3fe.png)

**Comment by iamdustan** [comment]
I would be a big fan of the second image, @spicyj. Happy to PR it next week.

**Comment by AlexeyFrolov** [comment]
@spicyj both is frustrating for my taste. Bottom list is weird but it's usable at least. I've seen more deep trees in practice, and at some point it's not usable (I'm about the tree itself). Worse that as you can see, stacked containers add more than 50% of deepness (look at the first lines in the list at the bottom). I think, it would be nice if we'll find a way how to flatten them out of the tree.

**Comment by kassens** [comment]
What I like about the current tree is that it gives a very clear image of what components are nested and direct access to all of them. I'm curious to see mocks/sketches of how this could be more compact without suffering by hiding too much information.

**Comment by gaearon** [comment]
Some discussion happening in https://github.com/facebook/react-devtools/pull/503.

**Comment by gaearon** [comment]
Closing in favor of https://github.com/facebook/react-devtools/issues/604 (it's a bit more fresh).
