### ISSUE TITLE
Can the React Devtools see the Event Listener function name

### ISSUE THREAD

**Issue by monkindey** [facebook/react-devtools#382]
i want to debug the react project and find out the element's event listener quickly,
when i use it, and see the element like that when i add the click event listener to it

``` javascript
<input onClick=fn() type="button" value="like">
```

it's the `fn()`, not the specific name; so can the React Devtools support to see what the Event Listener function name? i can find the listener quickly

Thanks

**Comment by spicyj** [comment]
I'd be happy to take a pull request for this.

**Comment by gaearon** [comment]
Doesn't seem to be a problem now.

<img width="386" alt="screen shot 2017-02-15 at 18 58 09" src="https://cloud.githubusercontent.com/assets/810438/22990333/b9c51ba6-f3b0-11e6-9d01-df9bca225c7a.png">

Perhaps your function doesn't have a `name`.
