### ISSUE TITLE
Error: Cannot exapand relay query variables

### ISSUE THREAD

**Issue by mario-jerkovic** [facebook/react-devtools#383]
When trying to expand relay variables ( connection query variables ): 

![capture](https://cloud.githubusercontent.com/assets/16222284/15862484/1f2eb50e-2cd0-11e6-8934-51c585427477.PNG)

there is an error in console: 
`backend.js:1066 Uncaught TypeError: Cannot convert undefined or null to object`

**Version:** 
- Chrome: 51.0.2704.79 m
- React Developer Tools: 0.14.11
- React: 15.1.0
- Relay: 0.9.0

**Comment by mario-jerkovic** [comment]
Any progress?

**Comment by gaearon** [comment]
There is currently no owner for the Relay integration, so I don't know if this will get fixed.

**Comment by gaearon** [comment]
Going to close. If you'd like to fix it, please contribute—there's nobody here with Relay knowledge to help out, and Relay team is not maintaining this extension either.
