### ISSUE TITLE
Stateless Functional Component source code doesn't show up correctly

### ISSUE THREAD

**Issue by keyanzhang** [facebook/react-devtools#384]
cc @spicyj

**Comment by jaredly** [comment]
? please elaborate

**Comment by keyanzhang** [comment]
Hey sorry @jaredly I forgot to update the description... 😢 

The repro is at http://s.codepen.io/spicyj/debug/qNOZOP and the corresponding implementation is at http://codepen.io/spicyj/pen/qNOZOP.

When I right click at a `Board` component (which is a class component) in devtools and "show source", it jumps to its implementation correctly. However if I click "show source" at `Square` (which is a stateless functional component), it takes me to the source code of `ReactCompositeComponent` instead.

Thanks!

**Comment by jaredly** [comment]
Gotcha! didn't realize what "SFC" meant :)

**Comment by tomaszlakomygp** [comment]
I'm getting a "This debug view expired." when trying to access the repro link :/

**Comment by ShiXiaoyYu** [comment]
PR https://github.com/facebook/react-devtools/pull/557 try to fixes this issue. @jaredly
