### ISSUE TITLE
Publish to npm?

### ISSUE THREAD

**Issue by LestaD** [facebook/react-devtools#386]
I want to install devtools to my electron from npm:

```bash
npm i electron-prebuilt react-devtools
```

**Comment by jhen0409** [comment]
I'm recommend use [electron-devtools-installer](https://github.com/GPMDP/electron-devtools-installer), I think it will be better for install React DevTools extension on Electron.

**Comment by nakamin** [comment]
@LestaD from the Electron documentation: http://electron.atom.io/docs/tutorial/devtools-extension/#how-to-load-a-devtools-extension basically just use `BrowserWindow.addDevToolsExtension`
