### ISSUE TITLE
in Source tab, it opens wrong file

### ISSUE THREAD

**Issue by limulidae** [facebook/react-devtools#387]
some file are opened correctly, but some files are always opened as another files.

**Comment by spicyj** [comment]
Can you provide a video of what you're seeing? If you can reproduce it consistently, please also provide repro steps (including a site that exhibits the problem).

**Comment by limulidae** [comment]
I capture screenshot here.
http://imgur.com/a/s4wb8

when open exec.js, it opens user.js
