### ISSUE TITLE
Show more info for Date objects.

### ISSUE THREAD

**Issue by bigblind** [facebook/react-devtools#388]
I'm trying to debug a component that stores `Date` objects in its state, but with the current react dev tools, there's no information about them, other than that it's a Date.
<img width="288" alt="screenshot 2016-06-22 11 14 27" src="https://cloud.githubusercontent.com/assets/737493/16261225/1bda0786-386b-11e6-8cd4-d0bcc7ad4f90.png">

**Comment by gaperton** [comment]
PR #469 contains the fix for the Date type. It's shown like this:

![fixed dates](https://cloud.githubusercontent.com/assets/469462/21735438/e6dd897c-d437-11e6-9b76-82d13e80b711.jpg)

Is it good enough?

**Comment by laurentvd** [comment]
I think this is exactly what we need!

**Comment by gaearon** [comment]
Since we didn't go with #469, happy to accept a PR fixing just this specific case.
@laurentvd @bigblind Would you like to contribute?

**Comment by tarang9211** [comment]
@gaearon Is this still open? If no one's taking it, I would like to contribute.

**Comment by laurentvd** [comment]
I'd love to contribute, but I'm a little short on time at the moment. If @tarang9211 would like to take this, that would be great!

**Comment by zalmoxisus** [comment]
@gaearon we are using [`jsan`](https://github.com/kolodny/jsan) for Redux DevTools Extension. It supports unserializable by `JSON.stringify` data types like `date`, `regex`, `symbol`, `undefined`, `error`, and `function`. Also we'll add support for [global Symbols](https://github.com/kolodny/jsan/pull/11) and [ES6 Map and Set](https://github.com/kolodny/jsan/pull/12) in the next release.

I guess, you'll just have to replace `JSON.stringify(data)`/`JSON.parse(data)` with `jsan.stringify(data, null, null, true)`/`jsan.parse(data)`.

@kolodny did a great work on making it rather performant. Of course, it would be less performant than `JSON.stringify`, but if we'll traverse data to check for `Date` objects it wouldn't be as performant either.

To add support for ImmutableJS, BackboneJS..., we just need to provide a way to specify a JSON [`replacer`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#The_replacer_parameter) / [`reviver`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse#Using_the_reviver_parameter), so it would work as @gaperton intended (but from outside the extension). [Here's how we support ImmutableJS](https://github.com/zalmoxisus/remotedev-serialize/blob/master/immutable/serialize.js#L8-L42).

**Comment by tarang9211** [comment]
I'd love to pick this up! I'm completely new to this so any tips for starting off?

**Comment by tarang9211** [comment]
So I get the dev environment all set up. Could anyone let me know how to produce this specific use case? Currently I got it working by using the instructions listed here: https://github.com/facebook/react-devtools/tree/master/shells/plain

**Comment by gaearon** [comment]
You can probably change `test/examples/target.js` to pass `something={new Date()}` as a prop to the root component and rebuild it by running `../../node_modules/.bin/webpack --watch`. Then refresh the page. Then feel free to document this for the next person 😛

**Comment by gaperton** [comment]
> To add support for ImmutableJS, BackboneJS..., we just need to provide a way to specify a JSON replacer / reviver, so it would work as @gaperton intended (but from outside the extension). 

Almost. Except that my original intention was to open the possibility to create "plug-ins" for DevTools directly. With common API which would be used both internally and externally, making all that and other stuff look trivial; say, the same ImmutableJS support would look like this:

https://gist.github.com/gaperton/4979f9bacbd74051b3ec24fe5a7d3cdb

**Comment by tarang9211** [comment]
@gaearon Why do i not see the dev tools when I run the above command? Am I missing something?

**Comment by tarang9211** [comment]
Could more info be provided on this? A little confused as this is my first time using this tool and contributing to this.

**Comment by gaearon** [comment]
Can you post a screenshot of what you see? I'm not sure I fully understand.

**Comment by tarang9211** [comment]
@gaearon  uh, looks like someone pushed a PR for this already. what do i do?

**Comment by gaperton** [comment]
@tarang9211 You look at the code. If you like it and agree with the approach, you support the PR (commenting like "cool!", etc). If you disagree, you create your own PR. Obvious, isn't it? :)

**Comment by gaearon** [comment]
I closed the other PR. There is a reason I added a "someone is working on this" label, as I don't want contributors competing on the same issues. We have a bunch of other "good first bugs" unclaimed so those should be good for other contributors. 

@tarang9211

Happy to provide you any context you need! If you can't get it running can you show the screenshot of what you see?

**Comment by zinoviev** [comment]
Sory folks, I started work on this after twitter 'call to arms' from @gaearon and this issue wasn't assigned at moment. Really not intended to race someone. Now I understand I should write here on the beginning, and next time I will checkin on github before PR.

I'm not expert how people usually do things in open source, but maybe it is worth to write about "someone is working on this" workflow in contributing.md?

**Comment by jaredly** [comment]
@zinoviev sorry for the confusion :( it's gotta be frustrating, and we're all playing this by ear. I hope this doesn't discourage you from contributing in the future! There's lots of work to be done :)

**Comment by tarang9211** [comment]
@gaearon Heres's the screenshot. 
![screen shot 2017-02-20 at 10 18 49 pm](https://cloud.githubusercontent.com/assets/5876249/23134375/9a00008e-f7ba-11e6-8f0f-473d0f8ffaea.png)

I navigated to `test/examples` and ran the command `../../node_modules/.bin/webpack --watch`
After that I opened the `target.html` file in the browser and the screenshot was the page I saw.

Am I on the right path?

**Comment by gaearon** [comment]
Oh, sorry I wasn't clear. You don't need to open `target.html` itself. You need to open `shells/plain/index.html`. It will contain `target.html` in an iframe, with DevTools attached.

@zinoviev No worries, it happens 😛 . Next time please comment right away if you’ve started working on something so that others don’t start the same.

**Comment by tarang9211** [comment]
@gaearon alright, sweet got it running. So as a first step, I added `time: new Date(),` to the `ToDos` component state. I verified it in the dev tools and this is what it looks like:
<img width="321" alt="screen shot 2017-02-21 at 12 05 24 am" src="https://cloud.githubusercontent.com/assets/5876249/23137717/8f941a86-f7c9-11e6-810d-83595e07822a.png">

**Comment by tarang9211** [comment]
@gaearon PR is here #559

**Comment by gaearon** [comment]
@zinoviev Could you please resume work on this since #559 didn’t get a followup?

**Comment by gaearon** [comment]
Fixed in https://github.com/facebook/react-devtools/pull/554 by @zinoviev, thanks!

**Comment by laurentvd** [comment]
That's great, well done @zinoviev !
