### ISSUE TITLE
I don't see the React tab for this simple example:

### ISSUE THREAD

**Issue by santiagobasulto** [facebook/react-devtools#389]
I've built a simple example for my students, but I can't use the react dev tool when rendering it

This is the example: https://github.com/santiagobasulto/react-basics/blob/a150552e3d04bf72034037b84d18f3806ad0f2ca/index.html

![image](https://cloud.githubusercontent.com/assets/872296/16336754/17135028-39e6-11e6-8e7a-3b07b9c4d9fc.png)

**Comment by ngyikp** [comment]
I can inspect it just fine, make sure "Allow access to file URLs" is enabled for React Developer Tools on your `chrome://extensions`

<img width="770" alt="screen shot 2016-06-28 at 3 10 50 pm" src="https://cloud.githubusercontent.com/assets/6135313/16406745/8ddffcec-3d42-11e6-8ae2-29dc0304d6f0.png">

**Comment by spicyj** [comment]
If that doesn't work for you, follow the instructions in the console warning and use an HTTP server instead of a file: URL.
