### ISSUE TITLE
Please add JSON Viewer for props and state

### ISSUE THREAD

**Issue by nsisodiya** [facebook/react-devtools#391]
react-devtools show `this.props` and `this.state` in tree structure !!
It will be great if you add additional functionality like view JSON in tabular format.
Tabular Format of JSON is quite easy to understand.
Please have a look at - https://github.com/nsisodiya/react-json-viewer

**Comment by spicyj** [comment]
I don't think we're going to do this, sorry. You can access `$r.props` or `$r.state` on the selected node in the console and do whatever you want with those objects though.

**Comment by nsisodiya** [comment]
@spicyj - Hi Ben, I can see $r in console. but I will greatly appreciate if you tell me a way to generate tabular structure (UI). 
From tabular structure, I mean, this
![image](https://cloud.githubusercontent.com/assets/333455/16387362/2a18de94-3cb2-11e6-8eda-49b6a1be21d8.png)

**Comment by spicyj** [comment]
Maybe using console.table:

https://developer.chrome.com/devtools/docs/tips-and-tricks#console-table

This isn't really specific to React though.
