### ISSUE TITLE
Dev tools unreadable on dark theme (Chrome)

### ISSUE THREAD

**Issue by vferko** [facebook/react-devtools#395]
I am using Dark theme in Chrome console, It looks ok as the text color is adjusted as well, however, the React dev tools still use the same font colors that are unfortunately unreadable on dark background. Can you force light theme on react tab or just change the background somehow?

![image](https://cloud.githubusercontent.com/assets/2313018/16488146/5d63dbfe-3ecf-11e6-9fca-16ab913a734d.png)

![image](https://cloud.githubusercontent.com/assets/2313018/16488150/60d5257c-3ecf-11e6-9bdd-3d5f8a5ae8a1.png)

**Comment by spicyj** [comment]
#108 dupe.

**Comment by silesky** [comment]
+1 ... especially since Dev

**Comment by vferko** [comment]
This seems to be fixed now with Light theme forced. Thanks!
![image](https://cloud.githubusercontent.com/assets/2313018/17135623/fb0c98a8-5330-11e6-9f6f-c01fc47ae846.png)

**Comment by spicyj** [comment]
Yes, now readable again. #108 still tracks making a dark theme that works seamlessly.

**Comment by gaearon** [comment]
Out in the latest version.

![screen shot 2017-05-26 at 22 50 41](https://cloud.githubusercontent.com/assets/810438/26513950/72010de8-4266-11e7-8dfe-a0337d6346b1.png)
