### ISSUE TITLE
Nested renders are being displayed as top-level components

### ISSUE THREAD

**Issue by pieter** [facebook/react-devtools#398]
Hi,

This is probably a bit of an edge case, but: we have a component that includes non-React content from a third-party library. Inside this non-React component, we render content we get from our props. We use unstable_renderSubtreeIntoContainer for this so that context still works.

This works good enough for us, the only issue we're seeing is that this subcontent is shown as a top-level component in the react devtools. Is there any way we can pass it a hint or so, so that it's displayed correctly?

**Comment by spicyj** [comment]
Sorry, we don't support this in the devtools for now. Maybe one day.

**Comment by bouzlibop** [comment]
Hello, I have similar issue (*Nested renders are being displayed as top-level components*) and was wondering if this case is also unsupported.

I have Wrapper component which mounts and unmounts inside another component.

```js
 35 class Wrapper extends React.Component {
 36   mount() {
 37     ReactDOM.render(<App />, document.getElementById('a'));
 38   }
 39   unmount() {
 40     ReactDOM.unmountComponentAtNode(document.getElementById('a'));
 41   }
 42   render() {
 43     return (
 44       <div>
 45         <button onClick={ this.mount.bind(this) }>mount</button>
 46         <button onClick={ this.unmount.bind(this) }>unmount</button>
 47         <div id="a"></div>
 48       </div>
 49     );
 50   }
```

in the devtools I see it as:

<img width="429" alt="screen shot 2016-07-18 at 10 13 50" src="https://cloud.githubusercontent.com/assets/8625570/16909167/1c9cb6e4-4cd1-11e6-8c64-4756cb7006db.png">

**Comment by spicyj** [comment]
Yes, this is basically the same issue.

**Comment by bouzlibop** [comment]
I see... Thanks for the info! 😃

**Comment by gaearon** [comment]
Closing as wontfix for the current version of React API.
We have a fix for this for the future versions of React that include a Portal API.

**Comment by slorber** [comment]
that's great to hear @gaearon :)

Currently debugging portal state with react devtoolsis quite annoying because when you inspect an element the devtools focus on the top-level portal element. Often the state controlled just one layer above the portal so we have to navigate painfully the tree to find back our deeply nested component that holds that state
