### ISSUE TITLE
Installed the plug-in but react-devtools is not working.

### ISSUE THREAD

**Issue by vive1994k** [facebook/react-devtools#401]
Its showing no error.

**Comment by vive1994k** [comment]
"If you inspect an element or launch the developer tools on a React page, you should see an extra tab called React in the inspector".
This action is not happening.
<img width="1275" alt="screen shot 2016-07-12 at 12 37 09 pm" src="https://cloud.githubusercontent.com/assets/13715042/16758112/6d57ac54-482d-11e6-9f66-9a3b7bd7007a.png">

**Comment by AntonNiklasson** [comment]
That page does not seem to be built with React. Try facebook.com, that should work.

**Comment by nakamin** [comment]
@vive1994k you're using React DevTools on the chrome web store site which is not built with React. Try this on another website that uses React : http://todomvc.com/examples/react

**Comment by manodupont** [comment]
What if my site is actually a React app, but the tab doesn't show. What exact part of React has to be IN ? Is it a matter of server or client side ? My app is just client for now. No server at all... does this affect the React Tool ? Cause i swear i dont see any tab React.

**Comment by nakamin** [comment]
@manodupont, if you have react in your app you should see the tab. Check the console to see if you have any errors.

**Comment by manodupont** [comment]
I dont know what to say. Its just not there. I have seen that sometimes. I dont think its just a matter of "having React". Its not enough precise. My app is a React app. I mean, its launching, its working, i have been using it for the past month. :) But the tab never showed. So there's got to  be some "element" in DOM or whatever that is NOT there and that the Dev Tools is waiting for to tell that "it is actually a React App".

**Comment by manodupont** [comment]
Well, yes there is a blue warning actually. 

Download the React DevTools and use an HTTP server (instead of a file: URL) for a better development experience: https://fb.me/react-devtools

**Comment by manodupont** [comment]
But i do have the tools when i go in Chrome Extension, i can see it and its saying : Added to Chrome. So its there. And also when i go on facebook, i can see the tab. So the only thing left is related to : "... and use an HTTP server". So thats it .. i am NOT using a web server. So basically, the DevTools works only for complete React App with web server.

**Comment by nakamin** [comment]
So how are you viewing your react app then?

**Comment by AntonNiklasson** [comment]
You can actually allow Chrome Extensions to access file URLs. Try that.

<img width="441" alt="screen shot 2016-07-14 at 22 56 28" src="https://cloud.githubusercontent.com/assets/785676/16855586/4d4bc5f4-4a16-11e6-82ac-cdb34854a63d.png">

**Comment by nakamin** [comment]
You might need to first turn on the developer mode though

**Comment by manodupont** [comment]
@AntonNiklasson : Thanks. That was exactly it.

**Comment by manodupont** [comment]
@nakamin : I open index.html :)  ???!!!

**Comment by nakamin** [comment]
@manodupont lol 😂 works now?

**Comment by manodupont** [comment]
yes! thanks!

**Comment by vive1994k** [comment]
thanks it was the server issue
