### ISSUE TITLE
Color theme is not apply properly

### ISSUE THREAD

**Issue by LAKnoKAL** [facebook/react-devtools#402]
Here is how it looks on dark theme. Chrome 51.0.2704.103 m (64-bit) and Chrome 51.0.2704.106 m (64-bit) 

http://screencast.com/t/I2ycHM6oN

**Comment by heinst** [comment]
In version `0.15.0` they override the dark theme with the default white, this was not the fix I was hoping for...

**Comment by spicyj** [comment]
Better than nothing, I hope. Happy to take pull requests that make dark work properly. See #108.

**Comment by gaearon** [comment]
Out in the latest version.

![screen shot 2017-05-26 at 22 50 41](https://cloud.githubusercontent.com/assets/810438/26513950/72010de8-4266-11e7-8dfe-a0337d6346b1.png)
