### ISSUE TITLE
babel-node: ReactComponentTreeDevtool.js causes ReactDOMServer.renderToString to fail

### ISSUE THREAD

**Issue by ian-speers** [facebook/react-devtools#403]
While following a server-side react tutorial, I encountered a runtime error caused by ReactComponentTreeDevtool. Specifically, the purgeDeep function seems to be problematic under certain conditions (ReactComponentTreeDevtool.js line 47):

**User Code:**

<img width="258" alt="screen shot 2016-07-24 at 3 49 40 pm" src="https://cloud.githubusercontent.com/assets/19496802/17087078/4bac1602-51b6-11e6-98e1-f5302b9f90fd.png">

<img width="532" alt="screen shot 2016-07-24 at 3 47 01 pm" src="https://cloud.githubusercontent.com/assets/19496802/17087051/eaed83e6-51b5-11e6-8213-cc825766fafa.png">

**Stack Trace:**

![screen shot 2016-07-24 at 3 41 00 pm](https://cloud.githubusercontent.com/assets/19496802/17087006/1789cd34-51b5-11e6-9c6b-5c1310c963bb.png)

**Offending Code:**

<img width="371" alt="screen shot 2016-07-24 at 3 47 40 pm" src="https://cloud.githubusercontent.com/assets/19496802/17087056/fd437f64-51b5-11e6-9101-effb16ff81b8.png">

**Resolution:** Adding a check for undefined `childIDs` before the traversal seems to resolve the issue (see below). 

<img width="729" alt="screen shot 2016-07-24 at 3 50 54 pm" src="https://cloud.githubusercontent.com/assets/19496802/17087085/b6c460b6-51b6-11e6-89e3-0e5a50df46fa.png">

![screen shot 2016-07-24 at 4 02 23 pm](https://cloud.githubusercontent.com/assets/19496802/17087147/0fec8460-51b8-11e6-93be-5e82360b0f98.png)

**Additional:**
OS: OS X Yosemite (10.10.5)
Node: 4.4.7
Run on: babel-node (via babel-cli 6.11.4 )

Let me know if there's any additional information I should provide (e.g. dev dependencies). Thanks!

**Comment by spicyj** [comment]
Despite the name, this error is actually part of React proper, not the devtools repo. Do you mind re-filing at https://github.com/facebook/react?

**Comment by ian-speers** [comment]
Sure thing. [Link](https://github.com/facebook/react/issues/7350)
