### ISSUE TITLE
State is not showing completely

### ISSUE THREAD

**Issue by manodupont** [facebook/react-devtools#404]
So i set my default state like that 👍 

```
class Score extends React.Component {

  constructor(props) {
    super(props);

    this.state = {
      imageStatus: null,
      settings: {
        dots: true,
        arrows: true,
        adaptiveHeight: true,
        infinite: false,
        speed: 500,
        slidesToShow: 1,
        slidesToScroll: 1,
        initialSlide: 0
      },
      currentTime: 0,
      currentTransposedRenderings: {
        previews: [],
        prints: [],
        audios: [],
        playbackPositions: []
      },
      currentTranspositionString: 'default'
    };
  }
...
```

Then i open the console, React TAB, and check for the component state ...

![screen shot 2016-08-02 at 15 25 35](https://cloud.githubusercontent.com/assets/7568033/17342047/661cea8c-58c5-11e6-925b-b555b254dba1.png)

And i see that there are  some "missing state", but they really are the state as i put some log few lines ahead in componentDidMount and they are showing the values default that I put ...

**Comment by manodupont** [comment]
Like: 
```
this.state.currentTranspositionString 
this.state.settings 
```

are not there.

But its not true cause i have been developping my app since then and changing the values in the code DO make some changes in my app. So whats wrong ?!?!

**Comment by ryanewtaylor** [comment]
I am having this issue as well. The initial state is what is showing via react dev tools' component inspector, but it does not appear to be updating when the state changes. Retrieving the current state in the console demonstrates this issue.

![image](https://cloud.githubusercontent.com/assets/1215819/18034347/63c0f7e0-6d08-11e6-8e59-d59e05e699a4.png)

**Comment by spicyj** [comment]
If you want any hope of someone looking into this, it would be immensely helpful to post a jsfiddle/jsbin/codepen that reproduces the issue reliably.

**Comment by gaearon** [comment]
Closing as there has been no response to help reproduce this.
