### ISSUE TITLE
Firefox - TypeError: wc is undefined: trackSelection when switching nodes in the Inspector panel

### ISSUE THREAD

**Issue by bgrins** [facebook/react-devtools#408]
Originally filed as https://bugzilla.mozilla.org/show_bug.cgi?id=1296341.

STR:
Open firefox (testing on nightly) with react devtools addon installed
Load the URL: `data:text/html,<body><div></div></body>`
Open devtools
Change the selected node in the Inspector tab (switch between `<body>` and `<div>`
There's an error in the Browser Console:

```
"TypeError: wc is undefined: trackSelection/</</<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://react-devtools/main/trackSelection.js:39:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/event-emitter.js:191:13
Selection.prototype.setNodeFront@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/client/framework/selection.js:163:5
MarkupView.prototype.markNodeAsSelected@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/client/inspector/markup/markup.js:1494:7
MarkupView.prototype.navigate@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/client/inspector/markup/markup.js:951:5
MarkupContainer.prototype._onMouseDown@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/client/inspector/markup/markup.js:2331:5
...""
```

**Comment by bgrins** [comment]
I think this is happening only when the webconsole hasn't been opened yet so inspector-ready has fired bug webconsole-ready hasn't so `wc: https://github.com/facebook/react-devtools/blob/2b72f2b53db28284e84fdfeff23610b7e11421a9/shells/firefox/main/trackSelection.js#L31

**Comment by spicyj** [comment]
Thanks for filing.
