### ISSUE TITLE
element list hides element tree with deeply nested elements

### ISSUE THREAD

**Issue by jackgeek** [facebook/react-devtools#421]
When inspecting deeply nested elements, which my application has a lot of, the tool becomes unusable because the component tree gets hidden by the list below it.  Please see screenshot below
![reactchromeextension](https://cloud.githubusercontent.com/assets/202170/18021696/1a907172-6be1-11e6-8a56-9ddbdd8a7a82.png)

spicyj mentioned possibly changing this [here](https://github.com/facebook/react-devtools/issues/379#issuecomment-221954321).

If the list below was to have a scroll bar or something that limits its size this would make it more usable.

**Comment by spicyj** [comment]
Happy to take a PR for this.

**Comment by gaearon** [comment]
This was fixed in https://github.com/facebook/react-devtools/pull/511.
