### ISSUE TITLE
Typos in Chrome Ext description

### ISSUE THREAD

**Issue by reeddunkle** [facebook/react-devtools#427]
There are a few small typos in the description for this extension in Chrome.

(1) Second Paragraph (_Pictured_)

> You will get new tab called React in your Chrome DevTools.

=>

> You will get **a** new tab called React in your Chrome DevTools.

(2) Second Paragraph

> This shows you the root React components that **was** rendered on the page, as well as the subcomponents that they ended up rendering.

=>

> This shows you the root React components that **were** rendered on the page, as well as the subcomponents that they ended up rendering.

(3) Third Paragraph

> By selecting one of the components in the tree you can inspect and edit **it's** current props and state in the panel on the right.

=>

> By selecting one of the components in the tree you can inspect and edit **its** current props and state in the panel on the right.

![react dev tools](https://cloud.githubusercontent.com/assets/11543198/18225242/50a8184c-71bc-11e6-906a-7ab4e23150db.png)

**Comment by spicyj** [comment]
Thanks, edited!
