### ISSUE TITLE
Cannot read property 'stores' of undefined

### ISSUE THREAD

**Issue by coolmsd** [facebook/react-devtools#428]
I have using with alt devtools and it worked well at that time,
but suddenly I got error when try to see altStore in devtools

`altif.js:147 Uncaught TypeError: Cannot read property 'stores' of undefined`
`(anonymous function) @ altif.js:147`
`map @ altif.js:77parseStores @ altif.js:145`
`registerAlt @ altif.js:280`
`onMessageFromHook @ altif.js:215`

should I have any configuration to resolve this?

**Comment by gaearon** [comment]
I think the issue you're describing is from https://github.com/goatslacker/alt-devtool, not React DevTools.
