### ISSUE TITLE
window.stop() causes perpetual 'Connecting to React...'

### ISSUE THREAD

**Issue by ahfarmer** [facebook/react-devtools#430]
This code seems to break React dev tools. Important part is the `window.stop()`.

```
import React from 'react';
import ReactDOM from 'react-dom';
import Root from './Root';

window.stop();
ReactDOM.render(
  React.createElement(Root),
  document.getElementById('mount')
);
```

I realize that this is not a common use-case. Pointers to potential workarounds would be much appreciated. Does devtools expect `DOMContentLoaded` or the `load` event to fire?

**Comment by dijs** [comment]
I am having a similar issue, can we get some vision on this?

**Comment by jaredly** [comment]
Wow TIL. Maybe `window.stop()` is preventing the extension from loading? I don't know how those interact

**Comment by ahfarmer** [comment]
@jaredly I don't know how the extension starts - I skimmed the code but I wasn't able to figure that out with a brief glance. If I knew that I could easily fix or at least work around this issue.

I can tell you that [window.stop](https://developer.mozilla.org/en-US/docs/Web/API/Window/stop) will prevent the `DOMContentLoaded` and `load` events from being fired, so if React dev tools relies on one of those, it would cause this problem.

**Comment by gaearon** [comment]
I think it's unlikely this would get fixed unless somebody who's affected by it investigates.

**Comment by ahfarmer** [comment]
@gaearon good point - I honestly don't remember the exact circumstances here, and the project I was working on changed and no longer has this issue
