### ISSUE TITLE
Frequent Crashes in Chrome Canary

### ISSUE THREAD

**Issue by halhenke** [facebook/react-devtools#431]
React Dev Tools: v 15.4
Chrome canary: Version 55.0.2858.0 canary (64-bit) 
OS X: 10.11.6

Started a couple of days ago - usually happens when switching between the Elements Panel and the Extension. Not sure if its a temporary Chrome bug or an extension thing or both but thought i'd notify.

**Comment by wesbos** [comment]
Having this issue too in the latest chrome canary - here is how to replicate it. It started when I upgraded to 55.0.2861.0

[![](http://wes.io/hTry/content)](http://wes.io/hTbh)

**Comment by spicyj** [comment]
Anything that causes "Aw, Snap!" is a bug in Chrome and it's hard to know what we might be doing that triggers the crash. Do either of you want to file a Chrome bug?

**Comment by wesbos** [comment]
I'm hoping it just fixes itself in the next release otherwise I will. Thanks Ben!

**Comment by wesbos** [comment]
Just updated chrome canary and it seems to be fixed. This can be closed

**Comment by wesbos** [comment]
Ah - I spoke too soon. It still happens but only when you flip from the element's panel to the react panel. Probably something to do with the code that selects `$0` in the react element panel

**Comment by jacobmischka** [comment]
I'm on the dev branch of chrome and I'm seeing the same problem, crashing when you switch to the React tab.

**Comment by ngyikp** [comment]
Seems to be fixed as of 55.0.2883.11 dev
