### ISSUE TITLE
Cannot select variables in relay query 

### ISSUE THREAD

**Issue by miketamis** [facebook/react-devtools#433]
I cannot select the text, this makes it really hard to copy out text, you have to manually copy.
<img width="308" alt="screen shot 2016-09-16 at 3 07 58 am" src="https://cloud.githubusercontent.com/assets/1079931/18555159/ed40cdc2-7bba-11e6-8cf7-96abf60f3a0f.png">

possible solution would be to have a copy to clipboard button

**Comment by gaearon** [comment]
Would you like to contribute a fix? No one is maintaining the Relay plugin so it relies on help from contributors like you.

**Comment by gaearon** [comment]
Closing as Relay plugin is basically unmaintained now.
