### ISSUE TITLE
Feature request: Dev tools should show sites of React render warnings

### ISSUE THREAD

**Issue by mcclure** [facebook/react-devtools#441]
I am developing a React app. I am running with the debug libraries for React. I open my app and open up the Chrome developer tools. I find these lines in the console:
- **Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `Constructor`. See https://fb.me/react-warning-keys for more information.**
- **Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>. See CLASSNAME_REDACTED > p > ... > div.**

That sounds bad! I'd better fix it. But, there is a problem: React gives me these warnings, but it does not tell me _where_ the issues it's warning me about occurred. With the "key prop" warning there's a stack trace, so I can sort of kind of guess where in the code I didn't do the key props correct. And with the nesting error it gave me the component class name (which I replaced above with CLASSNAME_REDACTED), so that's also sort of a hint. However, this doesn't give me any hint **where in the display hierarchy** the error occurred. This can be inconvenient if, for example, there are many instances of the CLASSNAME_REDACTED component all over the page. (In the situation I am encountering right now with the "key" prop, for example, I have a class which generates its key dynamically based on data. So I feel confident if I could see the particular component causing the problem and inspect its props, I would see immediately why it is rendering duplicate "key" values. But with the data the warning gives me, the best I can do is inspect the code and try to hypothesize when it might go wrong.)

Wait, I think— there's a react dev tools plugin! So I install that. But, it doesn't help me at all with this situation. The warnings are unchanged, and when I open the React tab, there is nothing useful.

**Expected behavior**: If React knows that there is something wrong with my JSX/component tree, as it does in cases where it currently prints a warning to console, then the React-devtools plugin should show me where. Components with associated warnings should be in some way highlighted in the DOM display of the React tab. There should be some sort of "warnings" list in the React tab which lists known issues and, if you click on the list item, jumps you to it in the React DOM display.

**Comment by gaearon** [comment]
Hey, thanks for your feedback.
This is the same request as https://github.com/facebook/react-devtools/issues/34 so I'll close as a duplicate.

That said you can enable detailed component stack traces for most warnings. They would give you the whole hierarchy. To do this, enable [`babel-plugin-transform-react-jsx-source`](https://www.npmjs.com/package/babel-plugin-transform-react-jsx-source) (**only in development—it would produce very large bundles**). That will give you stack traces like this:

![](https://cloud.githubusercontent.com/assets/810438/18787323/4c3fa6ce-819a-11e6-8eed-8e99bb70ba6b.png)

Notice the component hierarchy at the end of the message.

This plugin is already enabled by default in [Create React App](https://github.com/facebookincubator/create-react-app), our suggest way to get started with React. If you can't use it, maybe you could use our [Babel preset](https://github.com/facebookincubator/create-react-app/tree/master/packages/babel-preset-react-app) that includes it in development.

I hope this helps!
