### ISSUE TITLE
Inspected elements within iframes are highlighted incorrectly

### ISSUE THREAD

**Issue by suchipi** [facebook/react-devtools#443]
If you hover over an element that lives within an iframe whose position is not the upper-left corner of the parent page, then the blue/green/orange highlight that is drawn over that element to indicate which you are hovering over is not drawn in the right location (iframe offset not accounted for).

Here I am hovering over the "Hello" button:
![](https://puu.sh/rOpMy/0b44b1a86e.png)

Here's a link to [the page where the screenshot was taken](http://kadira-samples.github.io/react-button/?selectedKind=Button&selectedStory=default%20view&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel&)

**Comment by gaearon** [comment]
Happy to take a fix for this. Would you like to submit one?

**Comment by suchipi** [comment]
I could tackle it this weekend. Could you point me in the right direction? I'm not at all familiar with the devtools codebase, but would love to learn more.

**Comment by gaearon** [comment]
I don't know it that well either. I would start with looking at the [plain shell](https://github.com/facebook/react-devtools/tree/master/shells/plain) and reproducing the issue in it.

I'm also not sure if this is even a DevTools issue at all, or just a Chrome issue. I'm not sure how highlighting is implemented.

**Comment by suchipi** [comment]
Chrome's inspector highlights elements in iframes correctly, and the coloring is slightly different when highlighting in the React Devtools, so it's probably reimplemented.

I'll start from there. Thanks

**Comment by gaearon** [comment]
You'll likely want to hunt for `getClientBoundingRect()` calls or something like this.

**Comment by suchipi** [comment]
I have opened a PR that fixes this issue. If you could review it, I would appreciate it.
