### ISSUE TITLE
Exception running in electron shell: no such module 'ip'

### ISSUE THREAD

**Issue by rigdern** [facebook/react-devtools#444]
When I tried running the devtools using the electron shell, I got an error about the module 'ip' not being found.

[This is](https://github.com/facebook/react-devtools/blob/ec328ee3da8bbcb1afa8fcdd84197cbed33a542e/shells/electron/index.html#L72) the problematic line and it looks like the line was added in d3b52777e143eee737a65995ecbbd32fa75e7d14. Perhaps `ip` needs to be added to `package.json`. /cc @jaredly

**Comment by zetachang** [comment]
Same here, and it did work after install the missing `ip` library.

**Comment by gaearon** [comment]
Fixed now.
