### ISSUE TITLE
Sidebar not showing correct props for selected component

### ISSUE THREAD

**Issue by juliepagano** [facebook/react-devtools#447]
When I select a component in the chrome react devtools, the props shown in the right sidebar are incorrect. I see the correct props inline on the component in the tree view and in the console when I type `$r.props`. It looks like the props shown in the sidebar actually belong to one of the ancestors of the selected component. I didn't see anything like this in the preexisting issues, so filing as a potential bug.

chrome version:  54.0.2840.87 (64-bit)
chrome react-devtools extension version: 0.15.4

**Comment by gaearon** [comment]
Thanks for reporting. So far I couldn't reproduce this. Did you ever see this again?

**Comment by bvaughn** [comment]
Seems like maybe this issue can be closed due to lack of info?

**Comment by gaearon** [comment]
Yea, going to close this, but please let us know if you can share a reliable way to reproduce it!
