### ISSUE TITLE
Component names not showing up

### ISSUE THREAD

**Issue by Deelux** [facebook/react-devtools#450]
Hi everyone, 

I am using these tools in Chrome. But for some reason I don't see any of the names of the components.

Any idea how come?

Cheers, 
Dominic
<img width="794" alt="screen shot 2016-11-04 at 18 53 45" src="https://cloud.githubusercontent.com/assets/4540876/20016525/22a88406-a2c0-11e6-8eab-966d4eaca7c0.png">

**Comment by spicyj** [comment]
Your names get minified in prod by your minifier.

**Comment by Deelux** [comment]
Ok. Any way to turn it off? Because I see this in every website now.

**Comment by spicyj** [comment]
No, the names are not in the JS file so there's no way the devtools could know them.

**Comment by Deelux** [comment]
Ok, thanks for your fast reply.

**Comment by dylanscott** [comment]
Would it be possible in theory to resolve the component names using source maps? I'm not familiar enough with what the devtools/plugins have access to to know if that's possible
