### ISSUE TITLE
"No display name" shown for ES6 component?

### ISSUE THREAD

**Issue by BerndWessels** [facebook/react-devtools#456]
Hi
`react-devtools` in Chrome is showing `No display name` for this component:

    export default connect(stateToProps, dispatchToProps)(
      class extends Component {
        // Initialize the component.
        constructor(props) {
          super(props);
          this.displayName = 'Whaaat';
        }
        // Render the component.
        render() {
          let {ping, isPinging} = this.props;
          return (
            <div className={styles.root}>
              <button onClick={() => ping()}>Ping</button>
              <h1>{JSON.stringify(isPinging)}</h1>
            </div>
          );
        }
      }
    );

How can I fix this? I really want to use `redux` and `ES6 classes`.

**Comment by spicyj** [comment]
Try

class Whaaat extends Component

instead of

class extends Component.

**Comment by BerndWessels** [comment]
Awesome, thank you that works.
