### ISSUE TITLE
import not working anymore on extension upgrade to 2.10.3?

### ISSUE THREAD

**Issue by borisnieuwenhuis** [facebook/react-devtools#458]
Hi, I tried to get importing of state to work in the redux dev tools, first I got an error when I did that about state.merge not being an object, which was correct because I use seamless-immutable for the state. Then I tried to play with deserializeState to deserialize the state into seamless-immutable structure, but when I didnt get that to work, I thought to upgrade my extension, now I am on the latest, 2.10.3, but if I now try to import nothing happens, also no error.
It is unclear to me what should happen, should the list of state in the inspector then be filled with the just loaded actions, and the state of the application be the preloaded state from the import with all the actions applies? that is what I would expect, but I dont see anything happening.
Great extension by the way,
ciao Boris

**Comment by zetachang** [comment]
Maybe you are looking for [redux-devtools-extension](https://github.com/zalmoxisus/redux-devtools-extension) instead of this repo.

**Comment by gaearon** [comment]
Yep.
