### ISSUE TITLE
Double scrollbars appearing when inspecting

### ISSUE THREAD

**Issue by ngyikp** [facebook/react-devtools#46]
Testing on React Developer Tools v0.8.1 from the Chrome Web Store, running Chrome 36.0.1985.125

When you inspect a React element, another set of scrollbars appear.
![Screenshot](https://cloud.githubusercontent.com/assets/6135313/3991345/550103a8-28e0-11e4-8cec-65b89b4029a1.png)

**Comment by facebook-github-bot-7** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by jaredly** [comment]
Is this still an issue with the new devtools beta? http://facebook.github.io/react/blog/2015/08/03/new-react-devtools-beta.html

**Comment by ngyikp** [comment]
Fixed in beta :+1:
