### ISSUE TITLE
Link to a React component from another DevTools panel?

### ISSUE THREAD

**Issue by glasser** [facebook/react-devtools#462]
(This is either a feature request if the feature doesn't exist, or a documentation request if it does!)

I'm working on a new Chrome devtools panel for another project.  One thing that would be really neat is the ability to, in certain places in my panel where you're looking at a thing that's based on a React component, to be able to let you click on it and link directly to the component in the React devtools if you have it installed too.

Is that something that the React devtools supports?

**Comment by spicyj** [comment]
I don't think this exists but we could consider accepting a pull request for this functionality.

**Comment by glasser** [comment]
Cool!  I'm not a devtools expert — you don't happen to know off the top of your head what sort of APIs I'd need to look into for this sort of thing, do you?

**Comment by gaearon** [comment]
AFAIK there is no way to open an extension tab programatically.
Feel free to send a PR if you find a way to make it work but I'll close since we won't be working on this.
