### ISSUE TITLE
Support React Fiber

### ISSUE THREAD

**Issue by brunolemos** [facebook/react-devtools#467]
Apparently the extension doesn't appear on react fiber pages (e.g. [isfiberreadyyet.com](http://isfiberreadyyet.com/))

**Comment by spicyj** [comment]
We're aware and will fix this before releasing Fiber broadly but we're tracking it in the react repo.

**Comment by brunolemos** [comment]
All right, if there is an issue for that please reference here

**Comment by spicyj** [comment]
It's a checkbox on https://github.com/facebook/react/issues/7925 where we're tracking everything else. Please note that Fiber isn't supported yet and we don't promise anything working, including devtools or anything else.

**Comment by brunolemos** [comment]
@spicyj thanks
