### ISSUE TITLE
Troubleshooting error on installing extension: Image decode failed

### ISSUE THREAD

**Issue by lrsnider** [facebook/react-devtools#468]
I’m having trouble getting the React Developer Tools chrome extension to download. I keep getting this message after I click “add to chrome”: There was a problem adding the item to Chrome. Please refresh the page and try again.
Image decode failed
 
Does anyone have a solution to this? I’ve tried: 
- refreshing the page
- restarting chrome
- signing into the chrome extension store
- clearing my cache
- restarting my computer
- removing EmberJS extension and an Angular one in case of any conflicts

**Comment by gaearon** [comment]
Hey, really sorry about this. Unfortunately it seems like some problem on Chrome's end, and we can't really do anything about it. I hope it got solved.
