### ISSUE TITLE
Show possible values of enum props

### ISSUE THREAD

**Issue by ghost** [facebook/react-devtools#47]
It would be helpful to have possible values of enum props available in the sidebar. You get a console warning when using PropTypes.oneOf(/\* {Array<string>} */). A combo list (text entry + dropdown) would be great for enums in the sidebar. A popup auto-complete list when modifying enums directly in the components view would be really nice as well.

If it's not possible to get the propTypes object out of a React component, I think it would be worthwhile to make that feature request to support this.

Thanks!

**Comment by facebook-github-bot-7** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by jaredly** [comment]
this is definitely cool

**Comment by gaearon** [comment]
I don't think we'll be further integrating with PropTypes.
