### ISSUE TITLE
Checkbox labels and search box overflow the column

### ISSUE THREAD

**Issue by albell** [facebook/react-devtools#472]
MacOS 10.12.2, Chrome 55. This doesn't look so hot:

![screen shot 2017-01-16 at 2 52 14 pm](https://cloud.githubusercontent.com/assets/1142025/22001699/8afb9c04-dbfb-11e6-8b79-36e9d0203b97.png)

Checkbox options should probably flow to a single vertical column when narrow. Thanks for a great tool!

**Comment by gaearon** [comment]
Yes, the design there is not very polished.
Would you like to help fix this?

**Comment by timarney** [comment]
I can take a look at this if you like.

**Comment by gaearon** [comment]
Sounds great!

**Comment by timarney** [comment]
Did a quick test - 

![dev-tools](https://cloud.githubusercontent.com/assets/62242/22997015/cd0eb3b4-f39e-11e6-86a4-deca8837345b.png)

I'll see about getting the labels to wrap nicer later.

Is there a way to get the dev tools panel to auto-refresh? 

I seem to have to close it manually and re-open to see the updated view.

**Comment by gaearon** [comment]
Hmm what do you mean by auto-refresh? Which shell are you using?

**Comment by timarney** [comment]
Just getting familiar with things ... I was running the chrome shell should I be using the plain one?

Auto-refresh - I did the webpack watch command from the chrome dir, which updates the code but I wasn't seeing changes until I closed the dev tool panel and than re-opened it.

**Comment by gaearon** [comment]
Plain is simpler to develop against since you just refresh to see the updates.

**Comment by timarney** [comment]
How's this?
![checkboxes](https://cloud.githubusercontent.com/assets/62242/23003791/103ceb7a-f3c1-11e6-901e-2cca3dd72b8a.gif)

**Comment by kp25** [comment]
@timarney that looks better than overflow thing, but I'm thinking about what to do to avoid the text 'Use Regular Expressions' hiding behind.

What about reducing the column width further and replace the labels with some kind of ellipsis? Not sure about how it looks, just a thought.

**Comment by jaredly** [comment]
looks like auto-refer didn't work https://github.com/facebook/react-devtools/pull/519

**Comment by jaredly** [comment]
[fixed by #519]
