### ISSUE TITLE
[React Native][Android only] Standalone app doesn't work after 0.15.4

### ISSUE THREAD

**Issue by jhen0409** [facebook/react-devtools#476]
Use [standalone app](https://github.com/facebook/react-devtools/tree/master/shells/electron) for React Native on Android, it still showing `Connecting to React...`.

Just tracking for commits, I can confirm [0.15.3](https://github.com/facebook/react-devtools/commit/bacc514a31f1b78f34c2761e9d0910ec3264b496) works fine, it looks broken by [0.15.4 change](https://github.com/facebook/react-devtools/commit/4f7582e28e6a5e21c33911acaa3bb0d68a0e1b53). (Just one change: #415)

**Comment by jaredly** [comment]
Thanks for tracking this down! It looks like the standalone app will connect fine if you're debugging js remotely, but not if the js is running in-app (at least that's what I see w/ the ios simulator). I'll investigate

**Comment by jaredly** [comment]
Hmm so I'm seeing it working for me, both in android & iOS. If you reload the standalone app while the react-native app is running, does it start working for you @jhen0409?

**Comment by jhen0409** [comment]
> If you reload the standalone app while the react-native app is running, does it start working for you?

I tried again, looks like it only can be reproduce when I start app with debug remotely mode, otherwise it works fine:

![screenshot](https://cloud.githubusercontent.com/assets/3001525/22218995/0cc1c18a-e1e4-11e6-9121-790c4a8e44fa.gif)

**Comment by jhen0409** [comment]
I tried the new `connectToDevTools` of `react-devtools-core` with different port will solved my problem :), but old `setupDevtools` is still same with above screenshot.

**Comment by jhen0409** [comment]
I'm tracking for this, looks like the problem is related to [`requestIdleCallback`](https://github.com/facebook/react-devtools/blob/master/agent/Bridge.js#L22), the callback never invoked in debugger worker, need to know why the worker has no idle time. :\

**Comment by jhen0409** [comment]
There may be some potential problems in RN for Android, not here, sorry for wasted your time @jaredly. 😅
