### ISSUE TITLE
window.addEventListeners for Window.PostMessage() interferes with multi-window web apps

### ISSUE THREAD

**Issue by KevinCSI** [facebook/react-devtools#477]
Hello there,

We experience a full chrome browser crash when having a multi-window web application (also using Window.PostMessage() to communicate) use the react-devtools in chrome - Version 56.0.2924.76 (64-bit).
This crash occurs when opening the debugging tools for the parent or child window while attempting to establish a connection to React. 

We believe this crash is a result of the event listeners due to isolating the crash in the following scenario:
- having a parent window open the application
- spawn a child window from the parent
- send constant messages of type string and ArrayBuffer from the parent to the child
- open the react dev tools in the child window
- the browser will crash all windows after attempting to connect

If you have any suggestions for a work-around, please let me know

**Comment by gaearon** [comment]
You could try using [standalone version of DevTools](https://github.com/facebook/react-devtools/blob/master/packages/react-devtools/README.md) instead as a workaround.
It would be great if you could file a Chrome bug if you can reduce this to a simple test case.
