### ISSUE TITLE
SyntaxError: Unexpected token o in JSON in es6.object.keys.js

### ISSUE THREAD

**Issue by Lin84** [facebook/react-devtools#478]
Hi, 
Using chrome browser(Version 55.0.2883.95 (64-bit)) with react-devtools (React Developer Tools 0.15.4),

in project I keep getting this error:  
![image](https://cloud.githubusercontent.com/assets/7355572/22395911/07c6b31e-e54c-11e6-90c9-7b0390ac7156.png)

click on:  at es6.object.keys.js:7
I getting this:
![image](https://cloud.githubusercontent.com/assets/7355572/22395948/e3f89e60-e54c-11e6-8452-690ebc418da9.png)

Interesting part is: The error is triggering by HOVERING over the component in the react-devtools:
![image](https://cloud.githubusercontent.com/assets/7355572/22395918/3d0e42f8-e54c-11e6-8229-c5d96aaac844.png)

As a not experienced person in web development, after some investigation I could not understand the reason or solution to fix this. 

Pls let me know if this has nothing to do with the React Developer Tools extension in the Chrome browser and maybe the direction to go to look for solution to fix the error,

Thx in advance,
Linh

**Comment by gaearon** [comment]
Unfortunately it's very hard to say something without a project demonstrating the issue.

**Comment by gaearon** [comment]
Closing as there was no followup info.
