### ISSUE TITLE
Make Chrome extension more Content Security Policy (CSP) compatible

### ISSUE THREAD

**Issue by ptoomey3** [facebook/react-devtools#479]
Apologies up front, as I'm not super familiar with React or the terminology used to discuss it. I'm most familiar with CSP and was just trying to help some other folks that work on Atom (an Electron app) to get this tool working in their development environment. 

Currently, the React devtools seem to inject a bit of JS using a Chrome extension "content script" up front. Since content scripts are exempt from CSP enforcement, you can inject whatever you like in this script. Then, after clicking the "React" tab, additional code is injected into the page if the initial JS determines that this is a "React page". This manifests itself via a script being injected, with a `src` set to `chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/backend.js`. Currently this works, even on sites that have a strict CSP, because Chrome exempts the `chrome-extension` scheme from CSP. Unfortunately, Electron does not. So, when someone tried to use this extension in an Electron app, they were getting CSP errors. We eventually hacked in a temporary workaround by adding `chrome-extension://react-dev-tools` (or something similar) to Atom's `script-src` (Atom, an electron app,  sets a strict CSP to partially mitigate content injection bugs). But, this is less than ideal, as it requires adding each extension you want to allow. And, in discussion with some folks that work on Chrome, the current behavior isn't going to work in the future. In other words, once `chrome-extension` is no longer implicitly allowed by Chrome, the approach used by React devtools will no longer work in the context of a strict CSP policy. 

So, given the above, I'm curious if React devtools would consider moving to a model where all the necessary JS is injected using a content script, and the actual invocation of the bootstrapping code is simply deferred until the React tab is clicked. 

/cc @binarymuse - Since you were trying to figure this out. Please correct me if I've misstated anything in terms of the use case/etc you had in mind.

**Comment by gaearon** [comment]
I think your use case should be solved by the new [standalone React DevTools](https://github.com/facebook/react-devtools/blob/master/packages/react-devtools/README.md).
If not, let me know and I'll reopen.
