### ISSUE TITLE
TreeView not visible if too many components in hierarchy

### ISSUE THREAD

**Issue by Cypcer** [facebook/react-devtools#481]
Hi,

Is it possible to hide or drag panel under the TreeView? If many components are nested is not possible to see TreeView (see attachment).

![treeview not visible if many components are inspected](https://cloud.githubusercontent.com/assets/9745663/22546766/b549c648-e93e-11e6-87e7-d19db228a8d4.jpg)

Kind regards
Rafal

**Comment by gaearon** [comment]
Would you like to contribute to fix this? I agree it’s annoying.
Maybe we could make that area scrollable.

**Comment by Cypcer** [comment]
Currently I'm switching between 3 projects, so at the moment I cannot look at that, but in about 3 months I want to finish 1 of them, so then (I hope) I could find some time to look at this enhancement.

**Comment by gaearon** [comment]
This was mostly fixed in https://github.com/facebook/react-devtools/issues/511.
