### ISSUE TITLE
git tags missing for recent releases

### ISSUE THREAD

**Issue by stof** [facebook/react-devtools#484]
currently, AMO has the addon at 0.15.3: https://addons.mozilla.org/en-US/firefox/addon/react-devtools/?src=search
![react_dev_tools_amo](https://cloud.githubusercontent.com/assets/439401/22562253/0a9894b6-e97c-11e6-8cd6-05a26e14a921.png)

but ca8ff1b0a96bda53027edd258cddc18277234eb1 suggests me that the current version is 0.15.5. Can newer versions be added on AMO too ?

**Comment by stof** [comment]
btw, the git tags don't exist for versions after 0.14.9, which also look weird

**Comment by spicyj** [comment]
0.15.5 is already awaiting review on AMO. It's out of our hands.

**Comment by gaearon** [comment]
Yea, unfortunately 0.15.5 is awaiting review since January 28.
Why do you find git tags helpful?

**Comment by stof** [comment]
@gaearon they make it easier to see what is included in each version (as github displays the name of tags including a commit when looking at it).
They also make it easier to see the latest version (the github release page currently stops at 0.14.9, which is not the latest, and is almost 1 year old). My first thought when creating an issue was about asking when a new release was planned due to the time since 0.14.9, before I realized that my browser was using a newer version (and then went looking at the commit history to see whether I could find some info about the release containing the multiprocess flag)

**Comment by gaearon** [comment]
Tags for releases from now on should show up now.
We have unified versioning for npm packages and the extensions, so there's an abrupt jump to 2.x.
