### ISSUE TITLE
Standalone React-Devtools

### ISSUE THREAD

**Issue by salmankhann** [facebook/react-devtools#491]
I just followed the instructions for installing the standalone version of react-devtools and when I run ./node_modules/.bin/react-devtools, it tells me env: electron no such file or directory. 

Any ideas how to fix this? @gaearon @jaredly 

Thank you

**Comment by gaearon** [comment]
Sorry, there was something broken there.
I fixed it in 1.0.6 via #493.
Please update: `npm i -g react-devtools@latest`, and it should work.
