### ISSUE TITLE
redux devtools on macOS - when clicking icon in chrome and choosing window position, app opens only on primary display

### ISSUE THREAD

**Issue by comatory** [facebook/react-devtools#499]
Just a minor irritation when opening dev tools window. It seems that the window correctly positions itself on selected portion of the screen (left, right) but it is forced to be opened on primary desktop.
I run my browser on secondary desktop, so every time I use this to open dev tools, I have to drag them to the secondary screen as well, even though the command was initiated on the browser residing in secondary desktop.

**Comment by gaearon** [comment]
Are you referring to the Electron app? We don't do any position logic there so maybe you could report this to Electron.

**Comment by comatory** [comment]
Yes that's the one, I will report it there, already found the right repo. Marking as closed, thanks.
