### ISSUE TITLE
getPropertyCSSValue is gone in Canary

### ISSUE THREAD

**Issue by jiyinyiyong** [facebook/react-devtools#50]
I used to debug in Canary:

> Version 40.0.2210.0 canary (64-bit)

Now it looks quite strange because I can't view `props` and `state`.

Then I found:

```js
TreeElement.prototype.isEventWithinDisclosureTriangle = function(event)
{
    // FIXME: We should not use getComputedStyle(). For that we need to get rid of using ::before for disclosure triangle. (http://webk.it/74446) 
    var paddingLeftValue = window.getComputedStyle(this._listItemNode).getPropertyCSSValue("padding-left");
    var computedLeftPadding = paddingLeftValue ? paddingLeftValue.getFloatValue(CSSPrimitiveValue.CSS_PX) : 0;
    var left = this._listItemNode.totalOffsetLeft() + computedLeftPadding;
    return event.pageX >= left && event.pageX <= left + this.arrowToggleWidth && this.hasChildren;
}
```

gives exceptions since `getPropertyCSSValue` is no longer, probably it's now `getPropertyValue`:

```js
x = window.getComputedStyle(this._listItemNode)
x.getPropertyValue('padding-left') // => "0px"
```

not sure what Canary is doing. But I think we need a fix.

![screen shot 2014-11-05 at 7 55 04 pm](https://cloud.githubusercontent.com/assets/449224/4917273/99ddc798-64e2-11e4-8a72-01583d8581a8.png)

**Comment by HurricaneJames** [comment]
I'm curious if any progress has been made on this issue since 40.0.x is beta (and has been for a while, so probably going to be stable pretty soon.
