### ISSUE TITLE
'Execute function' option doesn't do anything. How to use it?

### ISSUE THREAD

**Issue by wzup** [facebook/react-devtools#507]
There is an option `Execute function`. But nothing happens if it is selected. Does this option work? If so, how to use it? 

![chrome react extension - google chrome 2017-02-12 07 57 26](https://cloud.githubusercontent.com/assets/3880497/22858473/75dd6056-f0f9-11e6-9ef3-35d5cd66cb0f.png)

**Comment by gaearon** [comment]
It does what it says—it calls that function.

`getState()` in Redux is a function that just returns a value, so executing it doesn't produce any visible changes.

If you use this feature on some function that produces a side effect (e.g. sends an AJAX request) then that's what will happen.

I hope this helps!
