### ISSUE TITLE
[FEATURE REQUEST] Show event handlers on components and elements

### ISSUE THREAD

**Issue by aackerman** [facebook/react-devtools#51]
Showing event handlers would be a useful feature similar to showing props on components. Something like `onClick="..."`. So a consumer can understand at a glance where events are bound without digging directly into component source code.

**Comment by facebook-github-bot-7** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by aackerman** [comment]
I think this might have been implemented in the 2.0 beta.

**Comment by jaredly** [comment]
Yup! http://facebook.github.io/react/blog/2015/08/03/new-react-devtools-beta.html
Let us know what you think
