### ISSUE TITLE
Warning: Element: `key` is not a prop

### ISSUE THREAD

**Issue by lazopm** [facebook/react-devtools#518]
I'm getting this warnings for `key` and `ref` when I use the extension.
I don't think the issue is in my code, I don't see the warnings if the extension is disabled.

See screenshot below:
![screen shot 2017-02-15 at 6 32 36 pm](https://cloud.githubusercontent.com/assets/5622067/23000208/70e8d9a2-f3ad-11e6-985a-521045cbf9cc.png)

**Comment by spicyj** [comment]
Dan fixed this just a bit ago in #517. Thanks for tracking it down to the devtools!

**Comment by lazopm** [comment]
@spicyj Thank you for the quick response! I force updated the extension and I'm not getting the warnings anymore.
