### ISSUE TITLE
Tools should display an additional field for the 'native js' version of Immutable objects

### ISSUE THREAD

**Issue by twisterghost** [facebook/react-devtools#52]
While working on a React/Flux project and having Immutables here and there, I've noticed that the dev tools become pretty silly when inspecting the state of an element that uses Immutable.

While first looking through the codebase, I noticed that the state of an object is being pulled and pushed to the sidebar [here](https://github.com/facebook/react-devtools/blob/master/views/components/ReactPanel.js#L1001). With a bit of hacking around, I began to notice that there is no place where the actual values are read or passed around, but instead, only references to the values.

I'm not sure how possible this may be, but I feel that with the deep ties between React, Flux and Immutable, the dev tools should be able to detect an immutable and provide either an extra property on the state panel or a new panel altogether with the `.toJS()`'d version of the immutable to help developers work with these utilities.

**Comment by BinaryMuse** [comment]
Agreed, this would be really nice. Not sure if others agree, but I feel like in an ideal world, we could integrate application code into the React devtools (e.g. to make them understand arbitrary data structures)

**Comment by jiyinyiyong** [comment]
After reading this new post I really want this to be fixed
http://facebook.github.io/react/docs/advanced-performance.html
Feeling bad seeing this:
![data](https://cloud.githubusercontent.com/assets/449224/6188001/1008996e-b3c8-11e4-9a70-e45e050af12f.png)

**Comment by 0x80** [comment]
+1

**Comment by cassus** [comment]
+1

**Comment by cesarandreu** [comment]
+1

**Comment by danbruder** [comment]
+1

**Comment by spicyj** [comment]
"+1" comments do not help us. Please stop.

**Comment by cbenz** [comment]
Just asked myself the same question and found that with the [new devtools extension](https://facebook.github.io/react/blog/2015/08/03/new-react-devtools-beta.html), the `$r` global variable helps a lot: even if the sidebar still shows the internals of the immutable variables, I can select the component and type in the console:

```
$r.props.myImmutableProp.toJS()
```

or even use right-click "Store as a global variable" on the immutable prop/state then:

```
$tmp.toJS()
```

**Comment by ntucker** [comment]
+500

**Comment by dubert** [comment]
:+1: 

This is so tedious to open every time:

![screen shot 2015-08-28 at 12 49 15](https://cloud.githubusercontent.com/assets/1843672/9552057/377713ea-4d83-11e5-8604-5fceecd6a7fc.png)

**Comment by neoziro** [comment]
Can we expect a support soon? We can handle it with "store as global variable", but should be great to have the "toJS" displayed directly in the panel. I can work on a PR if you want.

**Comment by jiyinyiyong** [comment]
It reminds of this thing https://github.com/binaryage/cljs-devtools ClojureScript is inventing it own Console panel to display its data nice and fine.

**Comment by kristian-puccio** [comment]
https://github.com/andrewdavey/immutable-devtools

**Comment by ntucker** [comment]
@kristian-puccio that's great for console, but doesn't work on react-devtools

**Comment by kristian-puccio** [comment]
Yeah I was wondering if some of the code is transferable

**Comment by roblabla** [comment]
For those looking for this, PR #149 fixes it. I have an updated fork of this PR here : https://github.com/roblabla/react-devtools

**Comment by wmill** [comment]
+1

**Comment by gaperton** [comment]
> Not sure if others agree, but I feel like in an ideal world, we could integrate application code into the React devtools (e.g. to make them understand arbitrary data structures)

Of course, I agree. Thus, it's done in PR #469 . That's how hooking into dev tools looks like on the example of Date class (which is actually implemented as a part of this PR to resolve #388 ).

```javascript
if (__REACT_DEVTOOLS_GLOBAL_HOOK__) {
  const { addInnerStateInspector } = __REACT_DEVTOOLS_GLOBAL_HOOK__;
  if (typeof addInnerStateInspector === 'function') {
    addInnerStateInspector( Date, x => ({
       local : `${ x.toDateString() } ${ x.toTimeString() }`,
       iso : x.toISOString(),
       timestamp : x.getTime(),
    });
  }
}
```

If it will be accepted, I will implement support for ImmutableJS data structure.

**Comment by gaearon** [comment]
https://github.com/facebook/react-devtools/issues/459 should address this. Can anyone give it a try?

**Comment by gaearon** [comment]
Closing as fixed by https://github.com/facebook/react-devtools/pull/459.
Will be out soon.

**Comment by gaearon** [comment]
Immutable (or any iterable, really) support is implemented in the latest version.
