### ISSUE TITLE
Make empty UI look nicer

### ISSUE THREAD

**Issue by gaearon** [facebook/react-devtools#525]
Lots of low hanging fruit here:

![screen shot 2017-02-16 at 12 48 17](https://cloud.githubusercontent.com/assets/810438/23021903/3b6fe9e8-f446-11e6-82ae-e2ced7b57a43.png)

Both left and right pane could use some UI love.

**Comment by gaearon** [comment]
Here’s another one:

<img width="383" alt="screen shot 2017-02-16 at 12 54 17" src="https://cloud.githubusercontent.com/assets/810438/23022114/107dabc0-f447-11e6-93e1-774f288f3e44.png">

**Comment by lukejacksonn** [comment]
I'd be happy to take a look at this.. is there any particular style in mind?

**Comment by gaearon** [comment]
Just making it look cleaner would be nice!

I was thinking about adding some paddings and maybe not using monospace font for text like "No search results" because it looks odd there.

**Comment by lukejacksonn** [comment]
Something as simple as this could work..

![screen shot 2017-02-16 at 11 22 27 am](https://cloud.githubusercontent.com/assets/1457604/23030013/682b7a9e-f43a-11e6-9ed8-9f89bb278312.png)

Changes that effect specifically, the components outlined in this issue:
- Adds padding to main container
- Vertically and horizontally centers the span in the sidebar
- Increases size of error icon and fixes "x" character alignment

Changes that effect components outside the scope of this issue:
- Adds padding to the search input
- Adds padding to the top checkbox container
- Puts some space between the checkboxes and label

**Comment by gaearon** [comment]
How do you feel about using the same positioning/styling for "No search results" as for "No selection"?

**Comment by lukejacksonn** [comment]
I gave that a go at first but felt the snap from left aligned main content, to absolutely centered main content was quite jarring. Also, the slight difference in height of the main container and sidebar container, causes the "No search results" and the "No selection" text to not quite align vertically, which feels awkward too. See here:

![screen shot 2017-02-16 at 12 40 01 pm](https://cloud.githubusercontent.com/assets/1457604/23033221/45bc73e0-f445-11e6-8621-f802a29c6cbd.png)

**Comment by gaearon** [comment]
Yea, it's a bit awkward.
Maybe let's keep it where you put it at first, but make fonts consistent?

**Comment by lukejacksonn** [comment]
Here is what identical font styles look like:

```
font-family: Menlo, Consolas, monospace;
font-size: 12px;
```

![screen shot 2017-02-16 at 1 12 52 pm](https://cloud.githubusercontent.com/assets/1457604/23034526/1e3ca056-f44a-11e6-96d3-a0afbb0a676c.png)

Here is what the same font-family, but unaltered font sizes looks like:

![screen shot 2017-02-16 at 1 08 39 pm](https://cloud.githubusercontent.com/assets/1457604/23034564/3bbc2fa2-f44a-11e6-9ea9-7c3c408ba640.png)

Do you have a preference?

**Comment by lukejacksonn** [comment]
Also, here is what the sidebar looks like now, when populated (note slightly padded sidebar and baseline alignment of the `<tag>` and `$r in console`):

![screen shot 2017-02-16 at 1 30 59 pm](https://cloud.githubusercontent.com/assets/1457604/23035184/463e1830-f44c-11e6-9e38-67888cdb717d.png)

**Comment by spicyj** [comment]
Especially on smaller screens, the extra space is a little wasteful. I'd rather keep it tight, more like how the Chrome and Firefox devtools themselves are.

**Comment by gaearon** [comment]
Yea, I fully agree with keeping it tight. Space is precious.

My only preference here is that empty states (those that involve a text message) don't bump into pane borders. But we shouldn't do this for real content.

**Comment by gaearon** [comment]
@lukejacksonn Regarding the fonts, I meant the other way around. There is no need to apply a monospace font to a user-friendly message like "Nothing found" or "No selection". We should use monospace for code / components, not just everywhere in the UI.

**Comment by lukejacksonn** [comment]
![screen shot 2017-02-16 at 4 11 43 pm](https://cloud.githubusercontent.com/assets/1457604/23043709/2a051b54-f46b-11e6-8168-ed08adc0da1d.png)

@gaearon ahh my bad, I've made both sans-serif and slightly lighter in color.
@spicyj I hear you, will tighten it back up!

**Comment by gaearon** [comment]
I like this! Send a PR for a closer look?

**Comment by lukejacksonn** [comment]
Sure thing!

**Comment by gaearon** [comment]
Removing labels as there's a PR coming.

**Comment by lukejacksonn** [comment]
@gaearon PR has been made, sorry that took a while I was finding my way around! 😅

**Comment by gaearon** [comment]
Fixed by https://github.com/facebook/react-devtools/pull/538.
