### ISSUE TITLE
[Feature request] Nicer UI for deep tree

### ISSUE THREAD

**Issue by alexkuz** [facebook/react-devtools#526]
DevTools become hardly usable when it comes to inspecting deeply nested elements, especially when it is docked to the right:

![image](https://cloud.githubusercontent.com/assets/790659/23024026/584df726-f469-11e6-95e5-6aa241c9e6ed.png)

What could help:

* Responsive views (arrange them vertically, just like in Elements tab);
* ~Restrict height for view with element path;~
* Maybe shorten element names in the path to the first letter (except for last or selected element);
* "Focusing" for tree view: ability to pin nested element, so that parent elements are not rendered in tree view.

**Comment by gaearon** [comment]
FWIW it's not *as* bad with the latest update. The breadcrumbs should now be limited in height.
Have you tried it yet?

**Comment by gaearon** [comment]
>"Focusing" for tree view: ability to pin nested element

Searching kinda does that, although if you have many elements with the same type name it won't help as much.

**Comment by gaearon** [comment]
The latest version should look like this:

<img width="467" alt="screen shot 2017-02-16 at 14 42 03" src="https://cloud.githubusercontent.com/assets/810438/23025582/56da36c4-f456-11e6-9219-fab3595ee6e4.png">

**Comment by alexkuz** [comment]
![image](https://cloud.githubusercontent.com/assets/790659/23025611/91f91482-f46f-11e6-9090-d0718232134c.png)

(I actually thought Chome would update extension automatically)

Ok, searching is close enough indeed. Would be cool to add "Search by Element name" to element context menu. Also, maybe use a syntax in filter like "ElementName[100]" for many elements?

**Comment by gaearon** [comment]
I'd be interested specifically in the “pinning” feature. I think it’s a great idea. Imagine you could pin a few components from different subtrees and quickly access them in a single place.

**Comment by gaearon** [comment]
Wanna work on it? 😄

**Comment by alexkuz** [comment]
Yeah, I haven't thought about multiple selections - filtering wouldn't help much in that case.

> Wanna work on it? 😄

Kinda! Not sure when though.

**Comment by gaearon** [comment]
Going to close this one but open a separate one for pinning.

**Comment by alexkuz** [comment]
@gaearon what about responsive views? (arrange views vertically in narrow devtools)

**Comment by gaearon** [comment]
Seems like this just got filed in https://github.com/facebook/react-devtools/issues/532?

**Comment by alexkuz** [comment]
Yeah, that's it.
