### ISSUE TITLE
Clean up internal naming

### ISSUE THREAD

**Issue by gaearon** [facebook/react-devtools#529]
There's a lot of confusing naming in the internals.
Specifically, [almost everywhere](https://github.com/facebook/react-devtools/search?utf8=%E2%9C%93&q=element) `element` is used, it actually means `internalInstance`.

React has its own concept of elements which has nothing to do with `element` naming in DevTools, and it makes the code extra confusing.

We should rename all incorrect `element` names to `internalInstance`.
Happy to take contributions since it's not urgent but very useful :-)

**Comment by spicyj** [comment]
Thank you.

**Comment by hozefaj** [comment]
I can take help with this. :)

**Comment by gaearon** [comment]
Sounds great! Let me know if you need any help.
