### ISSUE TITLE
Improve SplitPane.js to support rendering vertical splitting

### ISSUE THREAD

**Issue by jolyonruss** [facebook/react-devtools#532]
Currently SplitPane.js only supports splitting the Panes horizontally, left/right. 

It would be nice to support the Panes splitting vertically at a certain breakpoint in the same way that Chrome's Elements tab works.

My thinking is to start with refactoring the SplitPane component to support splitting in both directions before working out where the breakpoint should be and setting a prop on SplitPane to split in the appropriate direction.

WDYT?

**Comment by gaearon** [comment]
Sounds good!
I'm up with getting more parity with Chrome Elements tab since they've done a pretty good job designing it.

**Comment by jolyonruss** [comment]
I've very roughly hacked the SplitPane to work vertically - how d'you feel about me dropping an onResize listener into Container.js (SplitPane's direct parent) in order to check if it should be vertical or not?

**Comment by gaearon** [comment]
Sure. Send a PR and I’ll be happy to review!
I may need some help from @jaredly on styling details.

**Comment by gaearon** [comment]
Fixed in https://github.com/facebook/react-devtools/pull/541.
