### ISSUE TITLE
Unable to set breakpoints

### ISSUE THREAD

**Issue by super-cache-money** [facebook/react-devtools#54]
I'm unable to set any breakpoints within my JSX script. They simply don't trigger. I'm using the in-browser JSX transformer for now.

**Comment by jaredly** [comment]
This probably isn't an issue with devtools, but rather with the sourcemaps generated by the transformer, or with chrome.
Are you still seeing this problem?

**Comment by saulshanabrook** [comment]
Yeah it does happen when generating source maps. I came accross this problem yesterday

**Comment by jaredly** [comment]
Yeah. This doesn't have to do with react-devtools though -- it's either a bug with the sourcemap generation (webpack/etc) or with the browser itself. It's outside of the scope of this extension
