### ISSUE TITLE
Component name conflict

### ISSUE THREAD

**Issue by farskid** [facebook/react-devtools#542]
In my projects to show a list of Items, I usually create a `List` component and inside it I use another component called `ListItem` which does the mapping shows the list.
Whenever I open the React Devtools, both components are being shown as `List`.
Although the names are being shown the same, the components handle props well and do the job.
Is it a bug or I am doing something wrong?

**Comment by gaearon** [comment]
Can you share the code reproducing the problem?

**Comment by farskid** [comment]
The `List` component:
```
const List = (props) => {
 const {name, children} = props
  return (<div className=`list-${name}`>{ children }</ul>)
}
List.PropTypes = { name: React.PropTypes.string.isRequired }
```
-------------------------------------------------------------
The `ListItem` component:
```
const ListItem = (props) => {
  const {dataList} = props
  
  if (!dataList) return null

  return (
    <div class="row">
      {
        dataList && dataList.map(data => <div key={data.id} className="col-50" >{ data.title }</div>)
      }
    </div>
  )
}
```

**Comment by gaearon** [comment]
How do you use them? Can you show the screenshot of the problem?

**Comment by farskid** [comment]
Sure. I also tried to create a fiddle of the issue. I'll add the link If I succeeded to create the fiddle.
![list-issue](https://cloud.githubusercontent.com/assets/8332043/23074762/37ac6cbe-f54f-11e6-9651-79d2612edd06.png)

**Comment by gaearon** [comment]
Yes, a fiddle would help.

**Comment by farskid** [comment]
I created a simple fiddle to illustrate the issue. Could not test it to make sure if the issue is reproduced in the fiddle cause React Devtools does not detect react code inside jsfiddle.
https://jsfiddle.net/jwm6k66c/2147/

**Comment by farskid** [comment]
@gaearon Any clue of the issue?

**Comment by jaredly** [comment]
This is what I see from that fiddle
![image](https://cloud.githubusercontent.com/assets/112170/23131780/94af0b6a-f748-11e6-975d-c04aa3d88632.png)

**Comment by jaredly** [comment]
you can type `$r.constructor` in the console when you have a component selected to see what class an element came from. If you select the one that's shown as `List` but that you know to be `ListItem` and type `$r.constructor`, what do you see?
You could also check to see of the constructors for the two components are identical

**Comment by farskid** [comment]
My React-Devtools is not active on fiddle page. And when I type `$.constructor` in the console, I got error `ReferenceError: $r is not defined`.

**Comment by gaearon** [comment]
Can you share a project reproducing this locally? JSFiddle doesn't seem to be a great way after all.

**Comment by farskid** [comment]
Yeah there gotta be a fiddle for React anyway. Alright I'll share a project soon. thanks for the support @gaearon

**Comment by gaearon** [comment]
Going to close because I don’t think there’s a bug in DevTools. The logic there is quite simple, and works in our experience. If you can demonstrate, happy to look at it.
