### ISSUE TITLE
Add "Inspect with React DevTools" to context menu

### ISSUE THREAD

**Issue by selbekk** [facebook/react-devtools#543]
Today, if I want to look at a particular component on my page, I typically right click it to show the context menu, then click `Inspect`, and then switch over to the `React` tab in the developer tools.

I would love to be able to have another option - `Inspect with React DevTools` that did this process for me.

**Comment by ngyikp** [comment]
Duplicate of https://github.com/facebook/react-devtools/issues/323

**Comment by selbekk** [comment]
Ah, my bad. Sorry to hear it's not currently possible.
