### ISSUE TITLE
[Feature request]: Ability to add props on demand

### ISSUE THREAD

**Issue by iamdustan** [facebook/react-devtools#544]
Currently the props pane only supports editing defined props through `defaultProps` or that were passed in through `props`. It would be nice if one could add props on demand similar to how browser devtools support adding new CSS properties on the fly.

**Current**
<img width="301" src="https://cloud.githubusercontent.com/assets/227879/23069328/fc413e2a-f4f4-11e6-9a48-bfcdd7a151c7.png">

**Proposal**
(UI would not really look like that, it would be more natural with the current UI)
<img width="303" alt="screen shot 2017-02-17 at 9 56 07 am" src="https://cloud.githubusercontent.com/assets/227879/23069939/5376fdd6-f4f7-11e6-8158-c15d85618a0e.png">

**Comment by gaearon** [comment]
One problem with editing props is they won't "survive" for long in the current implementation.
Next time the parent rerenders, they will be gone.

An interesting case, however, would be to learn to force React to treat the currently edited props as the real ones, and ignore the real ones, until the user "unpins" them. This is a separate (tricky) issue probably, but feel free to file it too, or maybe even work on it. 😉

**Comment by iamdustan** [comment]
Haha. You do realize you’re the primary reason I actually contribute to React versus doing throw-away toys and experiments all the time.

Thanks for the insight. If I ever upgrade my understanding of how this all actually works together I’ll look into It :innocent:

**Comment by gaearon** [comment]
I’ll close because I don’t see an easy/reliable way to do this with the current architecture, and we may need to rethink it at some point in the future anyway.
