### ISSUE TITLE
Waiting for roots to load

### ISSUE THREAD

**Issue by Slapbox** [facebook/react-devtools#547]
Out of nowhere today, React Devtools in Electron no longer works. I have removed and reinstalled the devtools extension, confirmed the file is loaded via webpack, all the things I can think to check.

I get this related error in my terminal the first time I try to open the `React Devtools tab` in the `Chrome/Electron Developer Tools`:

`[60944:0217/193116:ERROR:CONSOLE(12406)] "Uncaught TypeError: Cannot read property 'get' of undefined", source: chrome-extension://react-developer-tools/build/panel.js (12406)`

Strangest of all to me is that I am able to get the developer tools to show the properties of individual React elements if I select them with the element selector tool. The tree does not show though, and I don't think I am seeing the full properties of the objects I select when they do show.

**Edit:** I have rolled back to several versions of my software where I am sure this was working, and it no longer does, which leads me to believe this is not due to any changes I have made.

Any help would be greatly appreciated, as I am dead in the water and out of ideas to try. Thank you!

**What I see**
![image](https://cloud.githubusercontent.com/assets/6835891/23081056/3e94a876-f521-11e6-94ae-9434d8028cff.png)

**Possible source of issue?** `_this.elementData`'s Entries are empty.

![image](https://cloud.githubusercontent.com/assets/6835891/23081182/a9c8291a-f521-11e6-820e-6d40736ae6a9.png)

**Comment by Slapbox** [comment]
![image](https://cloud.githubusercontent.com/assets/6835891/23081056/3e94a876-f521-11e6-94ae-9434d8028cff.png)

**Comment by Slapbox** [comment]
![image](https://cloud.githubusercontent.com/assets/6835891/23081182/a9c8291a-f521-11e6-820e-6d40736ae6a9.png)
`_this.elementData`'s Entries are empty.

**Comment by Slapbox** [comment]
I don't necessarily know how to recreate this.

I removed all but my highest level React components from my project to ensure that it was not a bug related to code I had introduced, but that did not resolve it. As I mentioned, rolling back to previously working versions of my project does not resolve this either.

**Comment by gaearon** [comment]
Can you reduce your project to the smallest example possible and then share it?
It's going to be tough to figure out the cause without a runnable repro.

**Comment by Slapbox** [comment]
I figured as much. I can't release the source, but I can try to pare it down to something I can post publicly without issue very soon.

Thanks very much Dan.

**Comment by gaearon** [comment]
>Possible source of issue? _this.elementData's Entries are empty.

If it's just an empty Map this shouldn't be an issue. The error says it's undefined.

**Comment by Slapbox** [comment]
@gaearon I'm no expert for sure and generally don't have to dive into this.

I am not 100% sure which of the ~130 `.get()` expressions is the one that returns undefined, if any. I know that when I looked at React Devtools on other pages the entries map was always populated which is what led me to believe that was a reasonable starting point for trying to pin this down.

**Comment by gaearon** [comment]
Just to be clear, do I understand it right that you're using the Chrome extension but inside an Electron app? Have you tried the standalone Electron DevTools?

**Comment by Slapbox** [comment]
Because I'm using a boilerplate, I have never had to get too deeply into this topic. I am using `Electron-Devtools-Installer` to install the dev tools. I have confirmed by running other projects that the devtool installation itself runs in general, but not on my app no matter how much I tear away from it.

I'm not entirely sure I know what you mean by standalone Electron DevTools and I don't want to give you the incorrect answer.

**Comment by gaearon** [comment]
Oh okay. We never really supported that way of wiring it up so I'd like to confirm whether you have any problems with the supported way first. 

>I'm not entirely sure I know what you mean by standalone Electron DevTools

See here: https://github.com/facebook/react-devtools/blob/master/packages/react-devtools/README.md

**Comment by Slapbox** [comment]
Unfortunately this didn't make a difference.

The devtool knows when the React application comes online (It stops saying `Waiting for React to connect...`) but once connccted I get the same message, `Waiting for roots to load...`

**Comment by gaearon** [comment]
Can you show the exact full stack? You can inspect it by opening DevTools... inside the DevTools :P

**Comment by Slapbox** [comment]
You mean the full call stack? You can only do that by setting a breakpoint, right? If I'm thinking correctly, where would I set that?

I usually don't have to dive this deep in. Sorry for all the questions and thanks very much for your help.

**Comment by gaearon** [comment]
You can press Cmd+Shift+I in the DevTools app. That will open the Inspector in it. Since it likely crashed you should see the full error stack in the console. I would like to see it.

**Comment by Slapbox** [comment]
Unfortunately I am not getting any error messages, warnings, nothing, when I open the Developer Tools for the React Devtools window.

All that is in the React Devtools' Developer Tools' console is: `[React DevTools] Connected`

Really a fun one to try and diagnose, I know.

**Comment by gaearon** [comment]
Okay, this one is though.

Do you see errors in the console of your extension itself? I see 8 errors in the first screenshot—are these all the same? Can you provide their stacks?

**Comment by Slapbox** [comment]
I've had all of those for the better part of 6 months without issue. I found one build of my application where the roots load, so I am trying to figure out the cause now and I'll report back. If I can't, I'll upload a barebones version of my project and link it here to save you the trouble of trying to troubleshoot blind. 

Thanks very much! I really appreciate your help!

**Comment by Slapbox** [comment]
Alright so here's what it was.. In my top level React component  I had:

**Old code (broken)**
```
componentDidMount() {
    const now = moment();
    let newList = list.filter(item => 
                    (now.diff(item.time) <= 0)
                  );
}
```
**New working code**
```
componentDidMount() {
    const now = moment();
    let newList = list.filter((item) => {
                    (now.diff(item.time) <= 0)
                  });
}
```

Thanks for all your help @gaearon

**Comment by gaearon** [comment]
Hmm I'm not really sure how this related to DevTools, or what the mistake was.
Your new code snippet doesn't do any filtering at all because the return value gets ignored.

**Comment by Slapbox** [comment]
Thanks for pointing that out. I was so happy to have devtools back and ready to quit for the day I didn't test that the code actually worked.

**So in the end the issue seems to be that the filtered results were then mapped, and the map was calling a function from my Redux Actions. This particular function did not return a dispatch, which hosed everything up.**

Slightly off the original topic now, but I suspect you would probably know the answer. Is there a way to call a function from the file that defines my Redux actions `application_actions.js`, without needing to dispatch an action when using Redux-Thunk?
