### ISSUE TITLE
Show whether React is running as production build

### ISSUE THREAD

**Issue by mnquintana** [facebook/react-devtools#562]
Depending on the module bundler you're using with React, it can be really difficult to verify that changing your `NODE_ENV`  to enable the production build is indeed working correctly, without resorting to more indirect checks (e.g. comparing the file size of the bundle outputs, or trying to call one of the `PropTypes` functions to see if it throws). It would be super helpful if the devtools could display an indicator showing whether React was running in production or development mode.

**Comment by gaearon** [comment]
Great idea. This should be a part of https://github.com/facebook/react-devtools/issues/490.

**Comment by gaearon** [comment]
I think we can do it now. I’m not sure what’s the best way to detect a DEV version but happy to hear proposals. Would be nice if it worked without changes to React itself.

**Comment by gaearon** [comment]
Fixed in https://github.com/facebook/react-devtools/pull/667.
