### ISSUE TITLE
Wrap source file location for JSX

### ISSUE THREAD

**Issue by gaearon** [facebook/react-devtools#567]
If you run an app with `babel-plugin-transform-react-jsx-source` plugin (which is enabled by default in Create React App in development mode), you'll see source locations in the bottom right pane.

However currently, if the location is long, it causes the whole pane to be scrollable horizontally:

<img width="312" alt="screen shot 2017-02-24 at 10 24 04 pm" src="https://cloud.githubusercontent.com/assets/810438/23323350/216899fa-fae0-11e6-95a0-f289e96306e9.png">

We should instead fix it to have the same width as the right pane, and wrap accordingly.

**Comment by rubenmoya** [comment]
Something like this?

![screen shot 2017-02-25 at 14 03 47](https://cloud.githubusercontent.com/assets/905225/23331298/562e3018-fb63-11e6-8d61-41edbff9b5e0.png)

**Comment by gaearon** [comment]
It would probably make sense to put the line number inline at the very end.

**Comment by rubenmoya** [comment]
That's true, what about now?

![screen shot 2017-02-25 at 14 07 58](https://cloud.githubusercontent.com/assets/905225/23331325/d6d55250-fb63-11e6-82a5-f32718af6604.png)

**Comment by gaearon** [comment]
Looks great!
