### ISSUE TITLE
The value of `Infinity` displays as `null`.

### ISSUE THREAD

**Issue by hyperh** [facebook/react-devtools#572]
The issue with the React Chrome devtools and Redux Chrome devtools, they both display `Infinity` as `null`. But when I do a `console.log(...)` of my prop value, I get `Infinity`.

Looks like this might be the issue: http://stackoverflow.com/questions/16644597/json-stringify-converting-infinity-to-null

Or do you just suggest writing a custom transform?

**Comment by tomaszlakomygp** [comment]
I'll try to get this fixed, shouldn't be too hard.

**Comment by tomaszlakomygp** [comment]
Done, PR opened.

**Comment by gaearon** [comment]
Fixed in #576, thanks @tomaszlakomygp!

**Comment by tomaszlakomygp** [comment]
No worries @gaearon !
