### ISSUE TITLE
show source  is not  work

### ISSUE THREAD

**Issue by jiexishede** [facebook/react-devtools#573]
I install the developer tool. When I click the `show source`, the developer tool not scrolls the react code. 
![source](https://cloud.githubusercontent.com/assets/9484734/23543552/a91750c4-002d-11e7-8e41-3e18a21e22f9.png)
![447](https://cloud.githubusercontent.com/assets/9484734/23543567/b2f19db6-002d-11e7-95df-7fbc1d5f9521.png)

Why doesn't the developer tool scroll to the `Tabbber.js` tab?

**Comment by gaearon** [comment]
Because you are using some intermediate function that calls `instantiate`. It's hard to say why or what `instantiate` does without your code, but this is the component’s definition from DevTools’ point of view.
