### ISSUE TITLE
Mapping a function returning JSX to a list containing 0 returns a weird element in devtools.

### ISSUE THREAD

**Issue by szhongren** [facebook/react-devtools#579]
Not sure what this is, have only seen it in the React devtools extension on Firefox 51.0.1 (64-bit). I'm using devtools 2.0.12, webpack 2.2.1 and babel-core 6.23.1.

Code [here](https://jsfiddle.net/p16qux88/6/). HTML of the actual page is fine, but in the devtools the

    nums.map(
        (number) =>
            <li key={number.toString()}>
                {number}
            </li>)

turns into

    <li key="-1">-1</li>
    <li key="0"/>0
    <li key="1">1</li>

I'd be happy to put up the full repo if it can't be reproduced.

**Comment by gaearon** [comment]
This is likely a bug where it thinks `0` is an empty child. Probably some check for falsiness in a component that should've been checking for `null` or `undefined` explicitly instead. Would you like to send a PR to fix this?

**Comment by szhongren** [comment]
So I've checked it and it's there in Chrome too, is there something else I need to change to build the extension for debugging? I changed `babel` to `babel-loader` in the `webpack.backend.js` and `webpack.config.js`. 

However, `webpack --config .\webpack.backend.js` gives me a `callback is not a function` error. This is for the chrome extension on Windows.

**Comment by gaearon** [comment]
You should be able to follow the instructions here:

https://github.com/facebook/react-devtools/tree/master/shells/plain

**Comment by gaearon** [comment]
This was fixed by @szhongren in https://github.com/facebook/react-devtools/pull/585!

**Comment by szhongren** [comment]
First PR! Whoop.
