### ISSUE TITLE
Failing when a child is null

### ISSUE THREAD

**Issue by Cactucs** [facebook/react-devtools#584]
I have an element one of which childs is `null`. React devtools fails terribly (do not display anything/is just broken).

The problem occurs in getData function in backend.js, line 8440, when argument `element` is `null` (the line that causes the problem is 8457).

(getData is invoked from walkNode func (line 8367).

**Comment by tomaszlakomygp** [comment]
I think this is caused by:
```
if (element._currentElement === null || element._currentElement === false) {
    nodeType = 'Empty'
```

in `backend/getData.js`. I'm not entirely sure if not displaying `null` elements is a bug, I wouldn't expect null items to appear in the React devtools inspector.

Probably one of the react-devtools members should chime in

**Comment by gaearon** [comment]
Please provide a complete example reproducing this. Just adding a `null` into the component children doesn’t break it for me.

So unfortunately there’s nothing we can do to fix it, and the issue stays unsolved. If you provided an example maybe it would have been solved by now. 😉

**Comment by doytch** [comment]
For me, I can't reproduce it using React, I only see it when using Inferno and its `inferno-devtools` package to provide data to the React Devtools.

[I whipped up an example repo showing when I get this.](https://github.com/doytch/empty-string-inferno-devtools-crash) Native Inferno, not with -compat. I've also [opened a PR against Inferno](https://github.com/infernojs/inferno/pull/1037) to handle it on that end. Inferno's devtools are heavily influenced by Preact's wrapper so there may be a similar bug on their end as well.

(Sharing this info here in case the folks above were using Inferno (or Preact) and that's the cause of their issues as well.)

**Comment by gaearon** [comment]
Going to close as an issue with `inferno-devtools`. If you can repro this in vanilla React please provide a project reproducing it, and I’ll reopen. Thanks!

**Comment by Cactucs** [comment]
(Haven't been using inferno - just saying.)

**Comment by gaearon** [comment]
Thanks for the info. Still, it’s not really fixable without a reproducing case. 😞 

My guess is that your code was throwing an error somewhere, and that corrupted internal tree representation. Maybe that error was silently caught by your code so it didn’t end up in the console. Otherwise I can’t explain this well.
