### ISSUE TITLE
Dock devtools into the browser window that it's debugging

### ISSUE THREAD

**Issue by GreenAsJade** [facebook/react-devtools#586]
I'm pretty sure devtools used to be "in" the same browser window that it is debugging.

Recently (after a big upgrade of a bunch of stuff) I can't find how to ask it to do that - it opens in a separate window, which is a hassle when you want to just minimise that activity (IE it should minimise when the target browser is minimised).

Latest Chrome on OSX, rdt 2.14.2

**Comment by ngyikp** [comment]
This is about Chrome dev tools, not exactly an issue with React dev tools, right?

https://stackoverflow.com/questions/10023640/how-to-reposition-chrome-developer-tools
![](https://cloud.githubusercontent.com/assets/6135313/23995828/22349fea-0a86-11e7-9b9a-be13e4a3c683.png)

**Comment by gaearon** [comment]
Yes, this is not related to React DevTools itself, and I hope the above picture is helpful!
