### ISSUE TITLE
Not working in Chrome latest

### ISSUE THREAD

**Issue by dbaronov** [facebook/react-devtools#587]
React tab not showing up in Chrome Version 57.0.2987.98 (64-bit) dev-tools.

**Comment by tayler-ramsay** [comment]
React tab not showing up  57.0.2987.110

**Comment by xhlwill** [comment]
can't install it! mac 10.12.3 chrome 57.0.2987.110

**Comment by gaearon** [comment]
@dbaronov This is not enough information to diagnose your issue, sorry. It definitely works on https://facebook.github.io/react/ with latest Chrome. Please create a new issue with exact instructions on how to reproduce this.

**Comment by gaearon** [comment]
Note that if you try it on a local HTML file, it won’t work unless you specifically check “allow access to file:// URLs” on Extensions page in Chrome.
