### ISSUE TITLE
Extension `require` scope leaks into page `require` scope

### ISSUE THREAD

**Issue by bmcminn** [facebook/react-devtools#59]
My application isn't using React, so disabling the dev tool extension "resolves" this. Though it seems that the `react devtools` extensions `require()` script is leaking it's scope into my application and injecting dependencies into my applications page level `require()` stack.

![screen shot 2014-12-18 at 4 44 03 pm](https://cloud.githubusercontent.com/assets/879984/5497254/5d251684-86d5-11e4-96f7-ea0a020e94b6.png)

**Comment by clintonhalpin** [comment]
Getting this error as well @bmcminn only work around is to disable extension.

**Comment by facebook-github-bot-7** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by jaredly** [comment]
The "try to require react" functionality should probably be default off and enableable via a setting, as it only applies to React version `0.11`, which is 3 versions behind by now.
What do you think @sebmarkbage?

**Comment by spicyj** [comment]
I vote let's kill it and just look for the global.

**Comment by sebmarkbage** [comment]
Release a beta without it and see if anyone complains.
