### ISSUE TITLE
(Suggestion) Expand / collapse node and all its children 

### ISSUE THREAD

**Issue by jerikson** [facebook/react-devtools#591]
As possible using Chrome Developer Tools:

![suggestionjerikson](https://cloud.githubusercontent.com/assets/4104014/24120264/45e0ba1a-0db4-11e7-8667-3b4e99177e0c.png)

By clickling either `Ctrl` + `Alt `+ &#9654; using Windows. Or `Opt` + &#9654;  using a Mac would
toggle the html nodes and all of its children &#9660;

I know Chrome gives the opportunity to manually configure short-commands..
[chrome://extensions/configureCommands]()

However the end-user of react-devtools would expect the same behavior anyway? 
Obviously, this is not a high prior issue, and I have not completely thought this through myself, maybe there is a good reason for this.

https://developer.chrome.com/extensions/commands
https://developers.google.com/web/tools/chrome-devtools/shortcuts

Kind regards.
Jimmy

**Comment by gaearon** [comment]
I’d happily review a PR adding this.

**Comment by shriah** [comment]
Added a pull request for this. It works but need to test it on a website with large number of nodes.

**Comment by gaearon** [comment]
Fixed via https://github.com/facebook/react-devtools/pull/621.
Will be out whenever we cut the next patch (probably in a week or so).

**Comment by jerikson** [comment]
Thanks everyone! 👍
