### ISSUE TITLE
Changes to state and props not reflected in sidebar

### ISSUE THREAD

**Issue by jgebhardt** [facebook/react-devtools#6]
Go to the test page, inspect it, go to react tab. Notice how the markup of the "hello world" div keeps updating as the rendered number increases. However, values shown in the sidebar do not update accordingly: state.counter in TestComponent should update as the state changes. The same is true for e.g. props.counter on InnerComponent.

**Comment by facebook-github-bot-7** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by jaredly** [comment]
State changes as they happen in the [new version](http://facebook.github.io/react/blog/2015/08/03/new-react-devtools-beta.html) of devtools.
![image](https://cloud.githubusercontent.com/assets/112170/9074917/c6514b76-3ac3-11e5-8fff-4c74853229f8.png)

Let us know what you think!
