### ISSUE TITLE
Changing the port from 8097?

### ISSUE THREAD

**Issue by A7DC** [facebook/react-devtools#600]
Hi everyone, 

Noob question here (and not sure if this is the right place to ask it), but how do you go about changing the default port from 8097 to a custom one, say 3001?

[I've asked the question on StackOverflow](http://stackoverflow.com/questions/43074677/react-devtools-by-default-devtools-listen-to-port-8097-on-localhost-how-to-cus), although figured I'd ask here too.

Sorry if this isn't the correct place to ask - it's the first time I've created an issue on GitHub.

**Comment by jaredly** [comment]
Welcome! It looks like the stackoverflow question got an answer -- although it's only half of it. I realize now there's no way to tell the frontend about a custom port -- I just made a PR to fix that
