### ISSUE TITLE
react dev-tools installed on Chrome but still not working

### ISSUE THREAD

**Issue by mkents** [facebook/react-devtools#603]
With react dev-tools installed on Chrome browser, and navigating to a url with react - https://www.hellosign.com/ (blue indicator sees that it had react.js in it), the dev-tools tab does not appear in the console. This issue has been discussed before, but having researched it for 2014, 2015, and 2016 can find no proposed resolution that seems to work now, save one hack that only applies in one very narrow set of circumstances.

Any new ideas on how to get around this? Thanks.

**Comment by jaredly** [comment]
is the react code located inside of an iframe?

**Comment by mkents** [comment]
Looking at the minified source, there are iframes for the google tag manager and a zendesk widget. Was looking to the chrome extensions to let me view and manipulate the react.js code on the page. I'm a react.js newbie, so I may be missing something that's right in front of me here.

**Comment by jaredly** [comment]
Are you sure there's react on the page? (not sure what you mean by "the blue indicator")

**Comment by mkents** [comment]
Along with the react developer tools there is another chrome plugin that indicates whether a page has react.js code in it, called the react detector.
![image](https://cloud.githubusercontent.com/assets/1467277/24577011/851f699e-168b-11e7-89c2-55de78580643.png) .. so on the https://www.hellosign.com/  page, it indicates that there is react.js code on the page .. but then with no develop tool showing as available in the console, nothing you can do, knowing it's there, but unable to test or manipulate it.

**Comment by ngyikp** [comment]
www.hellosign.com doesn't seem to use React for me... Their main application at app.hellosign.com does though.

Besides that, react-detector may probably break in the future as it doesn't light up on www.facebook.com (when logged in to a FB account)

**Comment by martellaj** [comment]
Not working for me either; even on facebook.com. Stuck on "Connecting to React...".

**Comment by Tushkiz** [comment]
it is working for me, tried on [app.hellosign.com](app.hellosign.com) and also facebook home page.

Chrome: Version 57.0.2987.133 (64-bit)
OS: Windows 10

**Comment by martellaj** [comment]
I bit the bullet and just uninstalled/re-installed the extension and now it's working properly.

**Comment by kyleshevlin** [comment]
This wasn't working for me either. After quitting Chrome completely and restarting Chrome, the React Devtools worked again.

**Comment by gaearon** [comment]
Going to close because this seems like a mix of misunderstanding (“React detector” is not an official thing and I don’t know how it works) and Chrome bugs (the ones reported to be fixed by reinstalling / quitting the app).

**Comment by rishikeshct** [comment]
The Simplest solution is to restart your Chrome, I mean close it and then open it.

**Comment by edwardchase** [comment]
i had the same problem.   it didn't show up, but i ran my react app then opened the dev tools and there it was.  i think the website you're currently on needs to be using REACT for the REACT dev tool option to be available

**Comment by dovydasbu** [comment]
The solution for me was to grant access for react to access my files

![react-ext](https://user-images.githubusercontent.com/25294534/45809388-b1fa7200-bcd0-11e8-9c61-937f23270297.png)

**Comment by micahbales** [comment]
dovydasbu's suggestion worked for me. Thanks!

**Comment by joeljerushan** [comment]
Just after restarting browser, newly installed react dev tools start working...
