### ISSUE TITLE
React version error with Chrome extention

### ISSUE THREAD

**Issue by dmwelch** [facebook/react-devtools#606]
Hi all, 

I get this perplexing error running in dev (especially with the broken link):

> You are using a version of React with limited support in this version of the devtools.
> Please upgrade to use at least 0.13, or you can downgrade to use the old version of the devtools:
> instructions here https://github.com/facebook/react-devtools/tree/devtools-next#how-do-i-use-this-for-react--013

React: 15.4.2
Chrome: 57.0.2987.133
react-devtools: 2.0.12

**Comment by gaearon** [comment]
Please provide a full way to reproduce the problem. It is very hard to guess in cases like this 😉

**Comment by gaearon** [comment]
I’ll close because there’s too little information. If you provide a project reproducing this, happy to reopen.
