### ISSUE TITLE
Cmd+Shift+D should trigger DevTools dock position change

### ISSUE THREAD

**Issue by roman01la** [facebook/react-devtools#607]
By default Cmd+Shift+D changes DevTools dock position (bottom, right or separate window) when pressed with DevTools open. But when React pane is active it doesn't seem to work. Instead it triggers default action “Bookmark all Tabs” when DevTools is closed.

**Comment by ngyikp** [comment]
This isn't a bug specific to React Dev Tools, this is a general Chrome issue that also happens with [HTTPS Everywhere](https://chrome.google.com/webstore/detail/https-everywhere/gcbommkclmclpchllfjekcdonpmejbdp) and [Redux DevTools](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd).

**Comment by gaearon** [comment]
Tagging “difficulty: starter” because it needs (a presumably simple) investigation into whether it’s something we can fix or not. It is very likely that it’s impossible to fix on our side, but we just need a confirmation (e.g. a Chrome bug tracker discussion).

**Comment by shriah** [comment]
I spent some time trying to find any ticket in chrome bug tracker about this but could not find it. But this behavior is present in all the devtool extensions I tested in both Widows and macOS.

It is not just Cmd + Shift + D almost all global devtool shortcuts don't work. I have created an issue in the bug tracker. [https://bugs.chromium.org/p/chromium/issues/detail?id=714430](url)

**Comment by gaearon** [comment]
Great, thank you. Going to close for now as I assume this isn't our bug, but would be interesting to see how that resolves.
