### ISSUE TITLE
Top Level state shows last selected component state

### ISSUE THREAD

**Issue by henrik** [facebook/react-devtools#61]
I assume this is a bug:

![](https://s3.amazonaws.com/f.cl.ly/items/3u10102u091L3Z0x1C1A/gurka.gif)

Expected: for Top Level state to be empty.

Actual: Top Level state is the state of the last selected component.

React Developer Tools 0.12.1.

**Comment by facebook-github-bot-7** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by jaredly** [comment]
This is fixed in the [beta version](http://facebook.github.io/react/blog/2015/08/03/new-react-devtools-beta.html) that was just released. Check out the blog post for installation instructions, and let us know what you think!
