### ISSUE TITLE
"Down" button doesn't always work in Fiber mode

### ISSUE THREAD

**Issue by gaearon** [facebook/react-devtools#612]
I can't navigate past some `<div>`s with the down button if the project uses Fiber. I think this is related to the hacky way I implemented fragment support (which are used in Fiber in more cases).

**Comment by gaearon** [comment]
To reproduce this you'd need to use React DevTools in a project using React 16 alphas.

**Comment by Tushkiz** [comment]
Hey @gaearon,

I tried to reproduce this issue, it is working for me.
I am using 16.0.0-alpha.3 and created an app with 'create-react-app'

**Comment by gaearon** [comment]
I'll see if I can get a full example reproducing this. I think it happened for me when going "down" into an array.

**Comment by Tushkiz** [comment]
Ohh, with an array I see that while going up, it jumps to the first element from that array. I think these are related.

![going_up](https://cloud.githubusercontent.com/assets/1854763/25427310/c785987c-2a8f-11e7-8235-96b6f3fd1b2d.PNG)

Example:
```
class App extends Component {
  render() {
    return (
      <div className="App">
        <div className="App-header">
          <h2>Welcome to React</h2>
        </div>
        {
          ["foo", "bar", "baz", "fiber"].map((str) => <div key={str}>{str}</div>)
        }
      </div>
    );
  }
}
```

But if I wrap those array elements, it works.

```
class App extends Component {
  render() {
    return (
      <div className="App">
        <div>
          <h2>Welcome to React</h2>
        </div>
        <div>
          {
            ["foo", "bar", "baz", "fiber"].map((str) => <div key={str}>{str}</div>)
          }
        </div>
      </div>
    );
  }
}
```

**Comment by trueadm** [comment]
@Tushkiz can you try out my PR (https://github.com/facebook/react-devtools/pull/781) and tell me if this fixes this issue for you? Thanks!

**Comment by Tushkiz** [comment]
@trueadm Yup! trying it out.

**Comment by Tushkiz** [comment]
@trueadm great, this fixes my use case 🎉
