### ISSUE TITLE
Make component source link clickable

### ISSUE THREAD

**Issue by gaearon** [facebook/react-devtools#625]
It would be nice if the component source link in the right bottom corner was clickable.

I'm not sure if this is doable. Unlike "Show Source", we don't want to navigate to *function definition*, but to *`createElement` call*. We can only do so if the user has `babel-plugin-transform-react-jsx-source` plugin, but it is enabled in development for projects generated with Create React App.

All information we'd have is filename and line number. While this may not be enough in Chrome, it might be enough for Electron, so maybe we should at least enable this feature for Electron shell. (See https://github.com/facebook/react-devtools/pull/588 for related PR).

How "Show Source" works:

![](https://d2ppvlu71ri8gs.cloudfront.net/items/451n2u1s2c1Q1e1q1u1u/Screen%20Recording%202017-04-25%20at%2002.51%20PM.gif?v=f4dcd4b2)

Here is the link I want to make clickable:

![](https://d2ppvlu71ri8gs.cloudfront.net/items/1S0G1X0K1k2X1i3B451k/Screen%20Recording%202017-04-25%20at%2002.51%20PM.gif?v=c72dbc33)

**Comment by nanot1m** [comment]
Is it good variant to pass prop with viewSource action through the Panel component to PropState component?

**Comment by gaearon** [comment]
Yes, maybe. Note I slightly tweaked related code in https://github.com/facebook/react-devtools/pull/630 because of https://github.com/facebook/react-devtools/issues/631. So you'd need to rebase on top of that. Tagging issue for you.

**Comment by gaearon** [comment]
Fixed in https://github.com/facebook/react-devtools/pull/633.
