### ISSUE TITLE
Clicking outside context menu should not select things

### ISSUE THREAD

**Issue by gaearon** [facebook/react-devtools#626]
This is wrong:

![](https://d2ppvlu71ri8gs.cloudfront.net/items/0e1Z1B3q0i3U1F373m23/Screen%20Recording%202017-04-25%20at%2003.00%20PM.gif?v=749f8a04)

It doesn't match how system menus work:

![](https://d2ppvlu71ri8gs.cloudfront.net/items/3i0C3m3h1r3y0o0O1b2L/Screen%20Recording%202017-04-25%20at%2003.02%20PM.gif?v=a5c7f7ba)

While I don't want to have a system look, I think context menu should have an invisible backdrop to prevent any mouse events below them until the context menu disappears. Hover shouldn't happen either while the menu is active.

**Comment by ioantm** [comment]
@gaearon  I would like to help to fix this issue

**Comment by gaearon** [comment]
Sounds great!

**Comment by gaearon** [comment]
https://github.com/facebook/react-devtools/pull/696

**Comment by gaearon** [comment]
Fixed!
