### ISSUE TITLE
Rename BananaSlug plugin to TraceUpdates

### ISSUE THREAD

**Issue by gaearon** [facebook/react-devtools#628]
There is a "Trace React Updates" checkbox, but its implementation in code is called [`BananaSlug`](https://github.com/facebook/react-devtools/tree/master/plugins/BananaSlug). As a non-native speaker, I find it very confusing, and I forget what this plugin does every single time I touch this codebase.

Let's rename the plugin to `TraceUpdates`. This involves renaming the folder, all its files, as well as occurrences in code (including some occurrences in a different case, such as `bananaslugchange` event).

Please exercise judgement when doing the rename: for example, `bananaslugchange` should not just become `traceupdateschange`. I encourage you to look at what the code does, and come up with the most sensible names in every specific situation.

**Comment by mjaltamirano** [comment]
@gaearon I'd like to work on this!

**Comment by gaearon** [comment]
You got it!

**Comment by mjaltamirano** [comment]
Hi @gaearon,

I've made the updates to all instances (folders, files, and code) of bananaslug and BananaSlug, changing them to traceupdates and TraceUpdates, respectively.

However, I am having trouble improving on the existing language like in the example you referenced. I've spent a bit of time now poking around the code and brainstorming, and `traceupdateschange` seems straightforward enough to me. Do you have any suggestions for how to approach making name changes like this? I might just be a bit gunshy but I also don't want to make things worse via original substitution.

**Comment by gaearon** [comment]
What exactly is changing there?

**Comment by mjaltamirano** [comment]
store.traceupdatesState

(So perhaps `traceupdatesstorechange` or `traceupdatesstatechange` is an improvement?)

**Comment by gaearon** [comment]
traceupdatesstorechange seems ok to me. (If there is such a store.)

**Comment by mjaltamirano** [comment]
I opted for `traceupdatesstatechange` since it concerns the `traceupdates` slice of state in the store, so I believe the aforementioned `traceupdatesstorechange` suggestion on my part was inaccurate/incorrect. Please see PR #637 for more details! 

Thank you for the advisement! Let me know if you have any questions or requested follow-up!
