### ISSUE TITLE
Can't inspect state or props

### ISSUE THREAD

**Issue by TomClarkson** [facebook/react-devtools#63]
See around 18.50 https://www.youtube.com/watch?v=kNVatRjnU7U . It used to expand with state and props information but does not work anymore.

**Comment by jaredly** [comment]
It's just buggy --- sometimes it does work

**Comment by jhollingworth** [comment]
This used to work but I think it's broken in newer versions of Chrome. I've traced the bug down to an [error thrown on this line](https://github.com/sebmarkbage/blink-devtools/blob/master/Source/devtools/front_end/treeoutline.js#L943) but not sure what the fix is

**Comment by facebook-github-bot-7** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by jaredly** [comment]
This is fixed in the [beta version](http://facebook.github.io/react/blog/2015/08/03/new-react-devtools-beta.html) we just released.
Let us know what you think!
