### ISSUE TITLE
A more maintainable way to styling react-devtools

### ISSUE THREAD

**Issue by pastelsky** [facebook/react-devtools#636]
First of all, it's great to hear that the react team is focusing on improving react devtools. As a contributor to this project, one of the major limitations I faced when trying to improve the look and feel was the fact that most of the styling in devtools is done using inline styles.
The issues are -
1) Hard to maintain consistent styling across different components.
2) Writing css for simple things like hover and focus states requires adding event handlers and that has an adverse effect on performance, esp. when the DOM tree is large.
4) Writing media queries is a pain.
3) Maintenance only gets worse with time as inline styles continue to grow.

It would be less time consuming and easier to contirbute to making devtools look better if it were to have a CSS / SCSS  stylesheets based approach to things. Things like adding a dark theme ( #108 ) would become possible too.

While I know that doing this isn't a small task, it might be worth it?

**Comment by gaearon** [comment]
I'm totally open to this. Any particular solutions you have in mind? I kinda like styled-components, seems like best of both worlds.

**Comment by agustif** [comment]
I forked this atom package in order to remove a deprecation, it has a good structure for themes and includes 3 dark themes already great!

https://github.com/agustif/dev-tools-dark/tree/master/themes

Maybe we can recycle some stuff?

**Comment by pastelsky** [comment]
I'm a little skeptic about CSS in JS because -
1) Auto complete/Intellisense / Editor Warnings  don't work
2) Not sure if there are simple alternatives to mixins, variables other scss features.
3) It ships with a runtime, so the performance when styles update is a concern.

 I don't know what use case CSS in JS tries to solve. We could use CSS modules if we wanted local styling, or just use SCSS stylesheets as it is since devtools isn't a very large app anyway.

**Comment by bvaughn** [comment]
I've started working on a related issue (see WIP PR #698) so I'm going to mark this as claimed for now to avoid conflicts.

I've found myself wanting something like styled-components while working on theme integration but I've been reluctant to add even more churn to a PR. If there's consensus that it's a worthwhile improvement though, I could try to take that on as well.

**Comment by bvaughn** [comment]
I pushed an initial commit [ee411fc](https://github.com/facebook/react-devtools/pull/698/commits/ed3448659a61fdf38dfbe110861f67245dec506f) at refactoring the inline styles to (hopefully) be a bit more readable and maintainable (and theming-compatible). Sharing in case anyone is interested.
