### ISSUE TITLE
How does $r work with functional components?

### ISSUE THREAD

**Issue by gaearon** [facebook/react-devtools#645]
I noticed an oddity: accessing the `($r in the console)` message is displayed for functional components too, and I get an internal representation as a result:

<img width="955" alt="screen shot 2017-04-28 at 1 45 46 pm" src="https://cloud.githubusercontent.com/assets/810438/25529197/01e458d4-2c19-11e7-98a2-0ac3417a0c3f.png">

This will likely break with Fiber.

Should we just expose a dummy object with `props` in this case?
I’m not sure.

**Comment by fletcher91** [comment]
This difference between components seems to have caused some confusion (https://github.com/facebook/react-devtools/issues/929 https://github.com/facebook/react-devtools/issues/1142 https://github.com/facebook/react-devtools/issues/366#issuecomment-280312516), so it'd seem useful from a community perspective.

Our developer tools use this feature as well, to display extra information (e.g. all available data of a resource) based on the currently selected component.

Upgrading those components to use hooks broke those, so I can see the confusion grow once hooks reach stable and get wide-spread deployment.

**Comment by gaearon** [comment]
I think currently `$r` is ignored for functions at all which is super annoying. Ideally it should maybe show props? Or something like `{ props, hooks }` where `hooks` is the introspected Hooks state.

**Comment by fletcher91** [comment]
The latter seems more consistent to me, imagine anticipating whether to type `$r.propName` or `$r.props.propName` depending on the component.

It'd be extensible as well, with hooks as you say, either literal or via some mapping between hooks and their (virtual, flat?) `state` and `context` counterparts (though that might be hard since they're essentially nameless)

**Comment by gaearon** [comment]
For now I think we'll set `$r` to elements like we did for host nodes (https://github.com/facebook/react-devtools/pull/619). This should be a quick fix. Later we can reconsider and figure something out for state.

**Comment by bvaughn** [comment]
Closed by #1281
