### ISSUE TITLE
Waiting for roots to load...

### ISSUE THREAD

**Issue by samit4me** [facebook/react-devtools#648]
Today I saw a tweet by @gaearon *"[Anybody with Windows 10 who could test it?](https://twitter.com/dan_abramov/status/858033145614086145)"* and I have Windows 10, so I thought I'll give it a go. First I tried a couple of my own apps and all was good, the icon would light up and the react tab would appear for sites with react 👍

After that, I switched over to `https://<chatroom>.slack.com` and I noticed the icon was light up, so I opened the devtools and clicked the react tab and I was greeted with the following, so I clicked **click here** to reload but no change.
<img width="178" alt="slack" src="https://cloud.githubusercontent.com/assets/3248531/25546459/870db8c4-2ca6-11e7-8b2a-09ad854e398c.PNG">

I then relayed this to Dan, who asked me to open an issue 🎉 

Unfortunately, I do not work for Slack, nor do I have access to their codebase, so um yeah, not sure what good this issue can bring 😢. Maybe Slack are doing this on purpose? Not sure if there is an API to disable react devtools or if this is even wanted.

I did a quick search and found #354 and #547 which are reporting the same issue. In both of these issues, Electron was mentioned, so I spun up a clone of [electron-with-create-react-app](https://github.com/csepulv/electron-with-create-react-app) to test but the devtools worked as expected.

I apologize for reporting an issue without a minimal project reproducing the issue, but if it helps, I've got the same issue on the following:
* Win10 (v1607) + Chrome (v57)
* macOS (v10.12.3) + Chrome (v57)

**Comment by gaearon** [comment]
Another data point: I think you’ll see this message **if React is on the page but no React components are mounted**. At least that’s my impression from why it fires up on https://facebook.github.io/react/tutorial/tutorial.html.

Regardless, we should change the message to say something like:

>React was detected on the page, but no components are currently mounted.
>If this seems wrong, you can try [reloading the inspector].

**Comment by samit4me** [comment]
Okay thanks for that, after looking at the code it makes sense to fix this in #655. I'll push an update tonight as part of a small refactor.

**Comment by MrEfrem** [comment]
I also have the same issue. But I have a mounted components on the page. Specifics of my case what I to inject React components in websites. I have opened this websites in the separate iframe.

**Comment by samit4me** [comment]
Did you have a URL or some code you can share? Would be good to find the root cause.

**Comment by MrEfrem** [comment]
No. I work on the private repo.

**Comment by MrEfrem** [comment]
If I have opened the iframe URL in a new browser tab, then it is work. I have a parent URL and a iframe URL with different ports. Maybe it causes a problem.

**Comment by gaearon** [comment]
@MrEfrem Extension won’t work across iframes. From README:

>**If your app is inside an iframe, a Chrome extension, React Native, or in another unusual environment, try the [standalone version](https://github.com/facebook/react-devtools) instead.** Chrome apps are currently not inspectable.

**Comment by MrEfrem** [comment]
@gaeron I thought it issue about the standalone version. I use standalone of course and I receive this error in the Electron App.

**Comment by mrdulin** [comment]
same issue!!
