### ISSUE TITLE
[feature] Ability to move components anywhere in the structure.

### ISSUE THREAD

**Issue by DancingQualia** [facebook/react-devtools#65]
It would be great to have the ability to move components from one place to another, much like the DOM inspector in Chrome does. 

I realize that I could do it from Inspector directly, but I feel that this is a better abstraction (possibly styling leaks can be helped this way?).

**Comment by jaredly** [comment]
This doesn't sounds like it would play well with react's view of the world :/ In what situation do you find yourself wanting this?

**Comment by gaearon** [comment]
React doesn't support this so we won't be implementing it.
