### ISSUE TITLE
The React tab stays in DevTools even when switching to a website not using React

### ISSUE THREAD

**Issue by samit4me** [facebook/react-devtools#650]
Was able to get the react-devtools stuck with the message "Looking for React..."

Steps to reproduce:
* Visit https://www.facebook.com/ in Chrome
* Open the Chrome devtools
* react-devtools icon should be light up and the react tab visible *(as expected)*
* Now click the react tab and it should work *(as expected)*
* Then change the URL to https://www.google.com/
* react-devtools icon "grayed out" *(as expected)*
* react tab is still visible and selected with the message "Looking for React..." ***(possibly an issue)***

Not sure what the correct behavior should be, but possibly:
* Hide the react tab and select the "default" tab in Chrome devtools *(if that's even possible)*, OR
* Provide a different message in the react tab, maybe something similar to what the icon shows when react is unavailable.

**Comment by gaearon** [comment]
Oh, I see. This is because it's the same tab right? This doesn't happen when you open Google in a new tab, does it?

**Comment by samit4me** [comment]
> This is because it's the same tab right?

Yes that's correct, the issue only occurs when changing the url in the **same tab**. 

> This doesn't happen when you open Google in a new tab, does it?

Correct, if you open the Google url in a new tab it doesn't happen.

**Comment by gaearon** [comment]
Tagging as a good first issue to look into. My suspicion is we only show the tab, but never tear it down. We should probably tear it down when we load a new page.

**Comment by samit4me** [comment]
Would you be happy for me to try and fix this? I don't know the codebase but keen to learn it.

**Comment by gaearon** [comment]
Sure, give it a try! You’ll want to look specifically at `shells/chrome` for this. I don’t really know how that part works either.
