### ISSUE TITLE
Add an update nudge to the CLI version

### ISSUE THREAD

**Issue by gaearon** [facebook/react-devtools#662]
The Electron version (`packages/react-devtools`) is often installed globally, so we should add an updating nudge that prints a message when a newer version is available.

`update-notifier` is a good package that already knows how to do this so we should just integrate it there.

**Comment by tsriram** [comment]
I'll take a look at this.

**Comment by sumnerevans** [comment]
@gaearon, @tsriram, Is there a reason this is still open? If yes, is there anything that I can do to help complete this?

**Comment by gaearon** [comment]
Sorry, I think it was done and I forgot to close the issue. Thanks for reminding!
