### ISSUE TITLE
Search by component name disappeared

### ISSUE THREAD

**Issue by JaxonDvl** [facebook/react-devtools#665]
The feature for Searching by component name disappeared from React Dev Tools, before it was there and working fine on the same project with the same configuration. Any fix for this ?
![screen shot 2017-05-02 at 11 59 49](https://cloud.githubusercontent.com/assets/4042136/25611218/ec1cd3f0-2f2e-11e7-92f2-0c708bc52d2f.png)

**Comment by iamdustan** [comment]
It’s still there just moved to the top-right.

![untitled drawing](https://cloud.githubusercontent.com/assets/227879/25620697/4221efe0-2f1d-11e7-9b67-6f0643209101.jpg)

**Comment by gaearon** [comment]
It moved to the right top corner of the left pane.

https://github.com/facebook/react-devtools/blob/master/README.md#search-bar

![](https://raw.githubusercontent.com/facebook/react-devtools/master/images/devtools-search-new.gif)
