### ISSUE TITLE
react-devtools for Safari

### ISSUE THREAD

**Issue by oveddan** [facebook/react-devtools#67]
Maybe this is the wrong repo to request this, but it's becoming more and more common for people to build React apps embedded in ios webviews.  The only way to currently debug those is using the Safari developer tools.  It would be great if there was a port of the react-devtools for Safari.

**Comment by adbl** [comment]
+1

**Comment by nmn** [comment]
+1 - The recent addition of type inference to webkit makes webkit nightly a great environment for debugging javascript.

**Comment by michaeltroy** [comment]
+1

**Comment by ekurennyy** [comment]
+1

**Comment by spicyj** [comment]
We're not planning to add this functionality anytime soon, sorry. We'd love to see a community project that makes this work though.

**Comment by F1ow** [comment]
+1

**Comment by jaredly** [comment]
On my fork of react-devtools I have an electron-based app that can be used to debug things like WebViews (or safari), though it requires that you add a script tag to your page. https://github.com/jaredly/react-devtools/tree/inspection-server/shells/electron

**Comment by TylerBrock** [comment]
Even as someone who enjoys using Chrome I think a web development monoculture based entirely around a single browser is a bad thing.

**Comment by iamdustan** [comment]
it is available for Firefox as well. Does Safari Devtools even allow extensions?

**Comment by TylerBrock** [comment]
Ah, I wasn't aware of the firefox one. I believe Safari does allow extensions. As long as there are 2 options that is ok.

**Comment by iamdustan** [comment]
If Safari does indeed, then support can be added by creating another shell here: https://github.com/facebook/react-devtools/tree/master/shells

**Comment by rustanacexd** [comment]
+1

**Comment by kassens** [comment]
I can't see anything in the [Safari extension API](https://developer.apple.com/library/safari/documentation/Tools/Conceptual/SafariExtensionGuide/Introduction/Introduction.html) to extend the developer tools. One option that might work is to write an [OS X companion app](https://developer.apple.com/library/safari/documentation/Tools/Conceptual/SafariExtensionGuide/CommunicatingwithyourOSXApplication/CommunicatingwithyourOSXApplication.html#//apple_ref/doc/uid/TP40009977-CH23-SW4) for the debugger extension. We don't have plans to work on this though.

**Comment by freddyrangel** [comment]
This would be useful for debugging React in the iOS simulator.

**Comment by StormNetwork** [comment]
+1

**Comment by taime** [comment]
+1

**Comment by DomVinyard** [comment]
+1

**Comment by sunlee-newyork** [comment]
+1

**Comment by joshhepworth** [comment]
For those trying to debug in the iOS simulator (or another unsupported browser) this seems to be useful: https://github.com/facebook/react-devtools/tree/master/packages/react-devtools

**Comment by ericdfields** [comment]
+1

**Comment by rensftw** [comment]
+1

**Comment by DomVinyard** [comment]
+1

**Comment by kristaponis** [comment]
+1

**Comment by jhessin** [comment]
+1

**Comment by TheTourer** [comment]
+1

**Comment by raphael-thibierge** [comment]
+1

**Comment by Aarbel** [comment]
@sophiebits 

Safari React inspector could help to debug some weird behaviors on iOS Safari. Could you re-open this issue ? thanks :)

**Comment by zcaceres** [comment]
+1

**Comment by cristiandan** [comment]
+1

**Comment by gastonmorixe** [comment]
+1

**Comment by mdavies-solsys** [comment]
+1

**Comment by ezfe** [comment]
+1

**Comment by jecacs** [comment]
+1

**Comment by jasonwoodland** [comment]
+1

**Comment by gianglevan94** [comment]
+1

**Comment by mcrowder65** [comment]
+1

**Comment by daniel-costa** [comment]
+1

**Comment by dascheaten** [comment]
+1

**Comment by hurvajs77** [comment]
+1

**Comment by visuallization** [comment]
+1

**Comment by yeyuguo** [comment]
+1

**Comment by ur92** [comment]
+1

**Comment by nisevi** [comment]
+1

**Comment by maxkohl88** [comment]
+1

**Comment by suberg** [comment]
+1

**Comment by jgabriele** [comment]
+1

**Comment by J-Liu** [comment]
+1024

**Comment by bupy7** [comment]
+1

**Comment by dkassen** [comment]
+1

**Comment by flyinhigh** [comment]
if there is a safari extension,  will be great.

**Comment by camilo86** [comment]
+1

**Comment by marcoroth** [comment]
+1

**Comment by seepls** [comment]
+1

**Comment by superandrew** [comment]
+1

**Comment by tinegrunau** [comment]
+1

**Comment by mikelyons** [comment]
+1

**Comment by aapelismith** [comment]
+10086
