### ISSUE TITLE
React.PropTypes.oneOf() to show <select> with the options described

### ISSUE THREAD

**Issue by iddan** [facebook/react-devtools#673]
As oneOf allows only exact values React DevTools shouldn't provide option to insert invalid values

**Comment by bvaughn** [comment]
This is a reasonable request! 😄 but I don't think worth implementing. DevTools has no direct support of `propTypes` (at least not that I'm aware of) and I don't think the added complexity of this feature woulds be worth the small UX improvement it provided.

**Comment by iddan** [comment]
Wow this was opened a long time ago! Maybe propTypes was still officially supported (I can't recall). Thanks for addressing it Brian, I appreciate it

**Comment by bvaughn** [comment]
😆 No problem. Yeah we're pretty behind on some issues!
