### ISSUE TITLE
No longer work since last update

### ISSUE THREAD

**Issue by plus-** [facebook/react-devtools#686]
I know this is not very informative but since today the tab is showing "connecting to React..."  but never displays the elements.

I can see the plugin displaying the "This page is using the development build of React. " message, can't remember seeing that in the past.

**Comment by bvaughn** [comment]
Sorry to hear the devtools aren't working well for you. Could you provide a little more info, such as:
* Which browser you're using them in?
* Which website you're trying to connect to unsuccessfully?

The "development build" message was a recent addition.

**Comment by plus-** [comment]
I'm using Chrome. It's a private webapp, reinstalling the plugin fixed the issue.
