### ISSUE TITLE
Meteor + React : This page is using the development build of React

### ISSUE THREAD

**Issue by mansarip** [facebook/react-devtools#687]
The extension (chrome) still telling me that I'm running in development mode.

I have build the app with `meteor build`.

and also set `NODE_ENV=production` as well.

But still it tells me the same thing. Is there anything I can do to change the flag from development to production?

**Comment by ericm546** [comment]
I have the same issue here and I was wondering if it's a bug with react-devtools or if meteor is really running react in development mode.

I test running their sample with the meteor --production command and I have the warning. https://github.com/meteor/simple-todos-react

**Comment by deepak-jacob** [comment]
This is where my debugger is hitting.

<img width="552" alt="screen shot 2017-05-05 at 00 27 10" src="https://cloud.githubusercontent.com/assets/430289/25728886/c903ae14-3129-11e7-8fb8-b81aa2c791fc.png">

comment says,

- PROD build without proper dead code elimination.
- empty shim.

`meteor build` not doing dead code elimination, thats why it is not considered as proper production builds.

**Comment by mansarip** [comment]
I suspect the dead code issue is the problem here.

Tried this https://github.com/ssrwpo/uglifyjs2 and it's working fine now.

Remove `standard-minifier-js` from meteor and replace with `uglifyjs2`.

I'm closing this, as this is nothing to do with devtools I guess. Btw thanks @deepak-jacob for your reply. Appreciate that.

**Comment by monkeydri** [comment]
for the record the standard meteor JS minifier (standard-minifier-js as of 2.4.1 at least)  is now correctly stripping dead React code (for development only) and react dev tool extension is showing prod mode
