### ISSUE TITLE
Development mode

### ISSUE THREAD

**Issue by prasanna1211** [facebook/react-devtools#688]
This is more of clarification than issue. I have forked the repo and trying to do some changes to it. I was trying to edit standalone.js in devtools-core/src. But it has jsx code which is transpiled by npm build and it is present in .js format inside devtools-core/build. So during development should I build for every single change to debug ? Also I feel Readme can have a more information about it.

**Comment by bvaughn** [comment]
Maybe buried a little, but try following the development instructions here:
https://github.com/facebook/react-devtools/tree/master/packages/react-devtools#developing

**Comment by prasanna1211** [comment]
Ah. Thanks.

**Comment by bvaughn** [comment]
😄  No problem
