### ISSUE TITLE
No tab in Chrome 42

### ISSUE THREAD

**Issue by sscotth** [facebook/react-devtools#69]
A couple of Play Store reviewers also mention Chrome 40

https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi/reviews?hl=en

**Comment by zpao** [comment]
Can you specify the React version you're testing with? For example, when I view the React website with Chrome 41, I can use the devtools.

It looks like most of the Chrome 40 reviews are before the latest update to devtools.

**Comment by sscotth** [comment]
Maybe I had a pending update yesterday...

Using React Developer Tools 0.13.0

Browsing to the react site works on Chrome Version 41.0.2272.64 beta (64-bit) but **does not** work on Version 42.0.2309.0 canary (64-bit)

**Comment by ngyikp** [comment]
DevTools on Chrome 42+ is currently bugged and only one extension panel can be loaded, try disabling any other extension that hooks into DevTools (e.g. EditThisCookie/SnappySnippet/HTTPS Everywhere)

https://code.google.com/p/chromium/issues/detail?id=460065

**Comment by ngyikp** [comment]
This seems to be fixed as of 42.0.2311.22 dev-m, so this issue should be resolved/closed.

**Comment by subblue** [comment]
The React devTools tab is also empty with Chrome 43.0.2327.5 dev

**Comment by Swaagie** [comment]
Could it be that no tab is showing if the page is simply loaded from file? No tab visible for both canary and 41.0.2272.118, but both versions do show the tab for the react website.

**Comment by nozpheratu** [comment]
I'm also experiencing the issue with the React tab not showing up when the page is loaded from the local file system. Using Chrome v43.0.2357.81 on Ubuntu. I see the tab when visiting an external page using React, however.

**Comment by spicyj** [comment]
Yes, I believe the extension does not work on `file://` URLs due to a Chrome security restriction.

**Comment by nozpheratu** [comment]
@spicyj It worked for me by enabling the local file URLs setting.

**Comment by spicyj** [comment]
Good point.

**Comment by srigi** [comment]
@nozpheratu can you please tell where exactly you did changed that configuration?

Anyway, it is not working for me. I completely cleaned/reinstalled my Chrome app/profile to be sure.
What I get is blank React devtools window, even when I exported React to `window`.
Any ideas?
![blank React dev-tools](https://s3.amazonaws.com/f.cl.ly/items/0S0i290e1k411W2S0D0p/Screen%20Shot%202015-07-08%20at%2018.43.07.png)

**Comment by jesstelford** [comment]
I was having this problem also, and no amount of reinstallation got it working. BUT! I managed to fix it by following these steps (I'm not sure which part fixed it though):

- Disable ALL extensions
- Load React app / note "React" tab missing from DevTools
- Re-enable React extension
- Note "React" tab still missing
- Allow React in Incognito mode
- Open new Incognito window
- Note "React" tab now shows
- Open new regular window
- Note "React" tab now shows
- Disallow React in Incognito mode
- Re-enable all the other extensions
- Note "React" tab still shows

**Comment by jaredly** [comment]
Has anyone had this issue with the [new beta version](http://facebook.github.io/react/blog/2015/08/03/new-react-devtools-beta.html). It's a complete rewrite, so my assumption is that this bug will have gone away...

**Comment by loganfuller** [comment]
Can confirm I'm still having this issue with the latest v0.14 in Chrome 44.0.2403.157 (64-bit) on OSX 10.11 Beta.

**Comment by spicyj** [comment]
@loganfuller Can you link to a site where you see this problem?

**Comment by FutureKode** [comment]
Hi, with react dev tools v0.14, the tab does not show. If I click "Allow access to file url's" then chrome says "This extension may have been corrupted." so I click repair but still have same issues.

**Comment by hilkeheremans** [comment]
I did not have this issue in the beta version, but since the final release I am regularly getting the "This extension has been corrupted" message.

Only uninstalling, closing Chrome, reopening and reinstalling seems to resolve this until it, frustratingly, happens again. It occurs intermittently and does not seem to be related to any specific events.

Can't provide you with an example site since, unfortunately, confidential. Let me know if I can do anything else to help you track this down.

**Comment by loganfuller** [comment]
@spicyj turns out the problem was that my React app runs in an iframe. I used the code below as a fix and it works great now. Thanks for the awesome tools!

```javascript
if (window.parent !== window) {
    window.__REACT_DEVTOOLS_GLOBAL_HOOK__ = window.parent.__REACT_DEVTOOLS_GLOBAL_HOOK__;
}
```
