### ISSUE TITLE
2.1.7 flagging our page is using development build. It works fine with v2.1.2 

### ISSUE THREAD

**Issue by AmolPWaghmare** [facebook/react-devtools#691]
Hello Guys,

Has anything changed for recent v2.1.7 release around flagging the page that it is using the development build of React.
It worked fine with v2.1.2. 
Can you check this page? https://www.mint.com/credit-cards?src=ttaxcreditscore

We are using npm and adding minified version of react to our project using requireJS. Hope this is a right way to do this with requireJS.

Thanks & Regards,
Amol

**Comment by ngyikp** [comment]
That page has two React libraries loaded:

<img width="641" alt="screen shot 2017-05-06 at 10 19 46 am" src="https://cloud.githubusercontent.com/assets/6135313/25769177/8d9f838a-3245-11e7-9c9a-65b93c0a9a83.png">

https://www.mint.com/html/waystosave/widget.js is using an unminified development build and it is loaded from here:

<img width="642" alt="screen shot 2017-05-06 at 10 23 54 am" src="https://cloud.githubusercontent.com/assets/6135313/25769216/237d2b8c-3246-11e7-9370-70cf2888c534.png">

**Comment by gaearon** [comment]
@ngyikp Thanks for investigating!

**Comment by AmolPWaghmare** [comment]
Thank you guys. Appreciate it 👍
