### ISSUE TITLE
allow to copy/paste props/state from dev tools

### ISSUE THREAD

**Issue by hozefaj** [facebook/react-devtools#697]
Would be useful if it were possible to copy/paste props/state key-value. Currently right click is disabled so there is no way to copy it. 

https://twitter.com/HozefaJ/status/860202273753845760

**Comment by bvaughn** [comment]
I'm not sure why the `DetailPane` is styled `user-select: none`. Maybe this was an accident? Maybe a style that was copy-pasted from another component like `TreeView` where it actually made sense?

If I remove that style, you can select the text and copy. It won't copy in the best format (eg there will be extra newlines and stuff) but that's probably better than nothing. 😄

**Comment by hozefaj** [comment]
Thanks....
