### ISSUE TITLE
Inspect with React devtool

### ISSUE THREAD

**Issue by aganglada** [facebook/react-devtools#701]
What about adding a contextual menu item that inspects directly in React devtool view.

Right now when you inspect the page, it will go to the normal "Elements" view.

Would be really helpful to have that functionality.

<img width="208" alt="screen shot 2017-05-09 at 14 25 56" src="https://cloud.githubusercontent.com/assets/922348/25853182/c957d654-34c3-11e7-82ac-2f5c29b783c6.png">

**Comment by gaearon** [comment]
It’s not possible with Chrome APIs (this has been suggested many times).

However it would be nice to implement a "click to inspect" button in React pane, similar to how Chrome has a button for finding the DOM node.

**Comment by aganglada** [comment]
Yes, that would be cool. At least it will improve the user experience a little bit. i.e. Every time I inspect it goes to Elements and I have to click back to the React Pane.

Thanks! :)

**Comment by bvaughn** [comment]
> However it would be nice to implement a "click to inspect" button in React pane, similar to how Chrome has a button for finding the DOM node.

I think I'll take a stab at this 😄

**Comment by bvaughn** [comment]
![click-to-inspect](https://cloud.githubusercontent.com/assets/29597/26220043/625fe5d6-3c11-11e7-99db-5e4ef0c044c7.gif)
