### ISSUE TITLE
React-Devtools Flickers Followed by Crash

### ISSUE THREAD

**Issue by UpWorks** [facebook/react-devtools#72]
Chrome Version: Version 43.0.2325.0 canary (64-bit)
React-DevTools Version: 0.13.0

Have disabled all known dev tool extensions as reco'd in previous Chrome Tab issue: https://github.com/facebook/react-devtools/issues/69

**Comment by bsr203** [comment]
@UpWorks . I have the same issue. Have u solved it?

**Comment by UpWorks** [comment]
No - tool has bug w/Chrome Canary per other thread, did not need another thread so I closed this one.
