### ISSUE TITLE
Context menu popup should be properly positioned when is opened at the bottom of the page

### ISSUE THREAD

**Issue by ioantm** [facebook/react-devtools#723]
![popup-is-cutted](https://cloud.githubusercontent.com/assets/16886448/26074453/959ef206-39ba-11e7-86a4-190f96373120.png)

Not found any issue that report this problem so filled this new issue. I can try to fix it by positioning the menu above the item that is selected.

**Comment by ioantm** [comment]
I will prepare a PR for this.

**Comment by LanceJernigan** [comment]
This issue should be fixed with pr #764.

**Comment by bvaughn** [comment]
Fixed via PR #768
