### ISSUE TITLE
React Dev tools tab not showing up

### ISSUE THREAD

**Issue by DeeMacD** [facebook/react-devtools#727]
When going to the site https://www.hellosign.com/ (which lynda.com uses as it's react example) the react detector shows that React is being used on the site, but the React developer tab does not show up in dev tools. Clicking it shows the message 'This page doesn't appear to be using React'

**Comment by rodor87** [comment]
Same for me.

Chrome Version 58.0.3029.110 (64-bit)
React Developer Tools 2.1.9

**Comment by bvaughn** [comment]
> the react detector shows that React is being used on the site

Hm...using React dev tools 2.1.9 as well but the detector doesn't light up for me.

<img width="680" alt="screen shot 2017-05-20 at 2 09 25 pm" src="https://cloud.githubusercontent.com/assets/29597/26275642/fc48b272-3d65-11e7-9cd9-b6c38f99d194.png">

**Comment by bvaughn** [comment]
What do you mean by it "lights up" ? Can you show a picture.

**Comment by ngyikp** [comment]
See also https://github.com/facebook/react-devtools/issues/603

The home page at www.hellosign.com doesn't seem to use React, however their main application at https://app.hellosign.com does

**Comment by bvaughn** [comment]
The bug report said "www.hellosign.com" specifically, which doesn't "light up" for me. "app.hellosign.com" seems to work fine with devtools.

I assume this bug was a misunderstanding given the above, and things seem to work as expected so I'm going to close the issue. OP can add more info about how to repro the bug if there's still something going on. :smile:

**Comment by geetab19** [comment]
Same issue for me. React Dev tool tab not showing despite the setting allow access to file URls 
![image](https://user-images.githubusercontent.com/4486041/48774043-16e14100-ecef-11e8-8e27-51aca656b71c.png)


Clicking extension  icon shows troublshooting instruction but it doesn't works. 
![image](https://user-images.githubusercontent.com/4486041/48774072-2fe9f200-ecef-11e8-8cd0-f4854e600365.png)

**Comment by bvaughn** [comment]
Hey @geetab19. It's hard to help with no more information than what you've provided. Can you share a repro page (even if you just have to zip and upload it somewhere)?

**Comment by geetab19** [comment]
Hi @bvaughn ,  Reinstalling this extension again works for me. Sorry may be some issues with my browser.

Thank you !

**Comment by bvaughn** [comment]
Great!
