### ISSUE TITLE
Flickering when opening

### ISSUE THREAD

**Issue by caseyyee** [facebook/react-devtools#73]
Hi there,
I have been experiencing a issue with the DevTools flickering when the Reactis selected.  I have tried the plugin in both standard Chrome Version 41.0.2272.76 (64-bit) and Chome Canary Version 43.0.2327.5 canary (64-bit) with exactly the same results.

It looks like others are experiencing this issue as well:
https://code.google.com/p/chromium/issues/detail?id=248966

The video on post #3 looks pretty much identical to what I am seeing.

Casey

**Comment by caseyyee** [comment]
Hmm.  Not sure why, but it seems that it is no longer happening with standard Chrome Version 41.0.2272.76.  I continue to see flashing issues with Canary as per original comment.

**Comment by zpao** [comment]
Sounds like it's a bug in Chrome so I'm going to close out. If it actually traces back to our extension, let us know.

**Comment by caseyyee** [comment]
@zpao The issue seems to only happen with the React tools.   Other parts of dev tools is fine.

**Comment by yzmtf2008** [comment]
Same here with 43.0.2327.5 dev-m (64-bit)

**Comment by jrodl3r** [comment]
Can also confirm. Looks like an infinite loop tree-rendering bug in Latest Chrome Canary (43.0.2330.4).

Chrome (41.0.2272.89) is fine.

**Comment by malechite** [comment]
Having the same problem with Chrome Version 43.0.2327.5 dev (64-bit)

**Comment by DhirajAdPushup** [comment]
Same problem with 43.0.2327.5 dev-m (64-bit)

**Comment by alexisvincent** [comment]
+1, but only on Canary

**Comment by malechite** [comment]
Still happens after updating Chrome to Version 43.0.2334.0 dev (64-bit) (Mac OS 10.10.2)

**Comment by jeffbski** [comment]
+1 confirm issue when opening in Canary 43.0.2336.0 canary (64-bit)

**Comment by taion** [comment]
I am seeing this on 43.0.2334.0 dev (64-bit).

**Comment by schaki** [comment]
Seeing this in 43.0.2334.0 dev (64-bit)

**Comment by chanakyabhardwajj** [comment]
+1, on 43.0.2341.0 canary (64-bit)

**Comment by zpao** [comment]
As you can tell, we have a number of confirmations, we don't need anymore. Only comment here if you have something *new* to add.

**Comment by bittersweetryan** [comment]
Nothing new to add, but this bug just landed in the Chrome beta (Version 43.0.2357.18 beta (64-bit)) build today, looks like it might be landing in stable soon...

**Comment by dustintheweb** [comment]
Was going insane trying to figure out why this was happening. Disabled the extension > back in business. Plz fix soon! :rocket:

**Comment by Katahdin** [comment]
+1 on Version 44.0.2373.0 canary (64-bit)

**Comment by LeZuse** [comment]
Found out that https://github.com/facebook/react-devtools/blob/49f5346104b6289d572196b0f3a9dc4d55f6d30f/injected/Overlay.js#L223 throws

```
Uncaught TypeError: Cannot read property 'style' of undefined
    at Object.eval (eval at evaluate (unknown source), <anonymous>:1:16)
    at Object.InjectedScript._evaluateOn (<anonymous>:895:55)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:828:34)
    at Object.InjectedScript.evaluateOnCallFrame (<anonymous>:954:21)
    at Object.__REACT_INSPECTOR_RUNTIME__0_13_0.Overlay.Overlay.hideHighlight (<anonymous>:2111:5)
    at Object.__REACT_INSPECTOR_RUNTIME__0_13_0.DOM.DOMHost.hideHighlight (<anonymous>:2525:15)
    at <anonymous>:2:39
    at Object.InjectedScript._evaluateOn (<anonymous>:895:140)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:828:34)
    at Object.InjectedScript.evaluate (<anonymous>:694:21)
```

Which in turn propagates to https://github.com/facebook/react-devtools/blob/49f5346104b6289d572196b0f3a9dc4d55f6d30f/agents/ReactInspectorAgent.js#L168 

Seems like there is a problem with initializing the `inspectorIframe` variable. I don't have much time to dig deeper though.

**Comment by kayluhb** [comment]
+1 for Chrome 43.0.2357.37 on Macintosh OS X 10.10.3 64x

**Comment by vkbansal** [comment]
+1 for Chrome 43.0.2357.37 beta-m (64-bit) on Windows 8.1 x64

**Comment by babsonmatt** [comment]
+1 Chrome 44.0.2383.0 dev-m (64-bit)

**Comment by Gioni06** [comment]
+1 Version 43.0.2357.45 beta (64-bit) OSX 10.9.5 x64

**Comment by iget-master** [comment]
+1 Version 43.0.2357.45 beta-m (64-bit)

**Comment by zachrip** [comment]
+1 Version 43.0.2357.45 beta-m (64-bit)

**Comment by turadg** [comment]
I hope this superfluous comment prevents further superfluous comments. Please see above from maintainers:

> As you can tell, we have a number of confirmations, we don't need anymore. **Only comment here if you have something new to add.**

Each additional "confirmation" probably just annoys the people who can fix it, not a good way to entice them. Please don't create a reason to close commenting and make it harder for contributors to collaborate to solve it. Props to @LeZuse who contributed some debugging investigation.

If you're commenting in order to be notified of changes, just click Subscribe under Notifications.

**Comment by spicyj** [comment]
Thanks @turadg.

**Comment by jrodl3r** [comment]
:+1: You rock @turadg!

**Comment by taion** [comment]
Yay! :+1:

**Comment by jeffbski** [comment]
@turadg Thanks for tracking this down and fixing it.
