### ISSUE TITLE
Error accessing window.localStorage in chromium 40

### ISSUE THREAD

**Issue by recursive-madman** [facebook/react-devtools#74]
This error renders the tool unusable (react tab shows up, but it always blank).

The message is:

```
Uncaught SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
```

(from Settings.js:131)

**Comment by zpao** [comment]
I think this is the same as what we documented in the readme: https://github.com/facebook/react-devtools#the-react-tab-is-blank

Reopen if that's not the case.
