### ISSUE TITLE
cannot npm install react-devtools

### ISSUE THREAD

**Issue by Fandekasp** [facebook/react-devtools#741]
Running:
```
$ sudo npm install -g react-devtools
```
Hangs when trying to install electron. Can be reproduced with `$ npm install electron`.

**Comment by Fandekasp** [comment]
installing electron with my package manager, then reinstalling react-devtools seems to work

**Comment by Fandekasp** [comment]
hmm actually, even if npm install didn't raise an error, react-devtools is still unusable:

```
$ react-devtools                                          [99f5547; 14:23:33]
/usr/lib/node_modules/react-devtools/node_modules/electron/index.js:9
  throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
  ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at Object.<anonymous> (/usr/lib/node_modules/react-devtools/node_modules/electron/index.js:9:9)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/react-devtools/bin.js:2:16)
    at Module._compile (module.js:571:32)
```

**Comment by gaearon** [comment]
Why are you running this command with sudo? Generally using sudo with npm is extremely error prone and leads to all sorts of issues with corrupted permissions.

**Comment by Fandekasp** [comment]
I used sudo because I cannot install globally as my user, something to do with the nobody user.
```
➜ npm install -g react-devtools                                                           [62f233c; 10:59:45]
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/react-devtools/node_modules/electron
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/react-devtools
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/react-devtools/node_modules/react-devt
ools-core
npm WARN checkPermissions Missing write access to /usr/lib/node_modules
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/react-devtools/node_modules
/usr/lib
└─┬ react-devtools@2.2.1 
  ├─┬ electron@1.6.10 
  │ └── @types/node@7.0.22 
  └── react-devtools-core@2.2.1 

npm ERR! path /usr/lib/node_modules/react-devtools/node_modules/electron
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/lib/node_modules/react-devtools/node_modules/electron'
npm ERR!  { Error: EACCES: permission denied, access '/usr/lib/node_modules/react-devtools/node_modules/electr
on'
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/lib/node_modules/react-devtools/node_modules/electron' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dori/.npm/_logs/2017-05-29T01_59_56_811Z-debug.log
```

**Comment by gaearon** [comment]
You should change global Node modules directory to something writable by all users. Not saying this will fix the problem but it's a better way. Npm just doesn't work well with sudo.

**Comment by bvaughn** [comment]
Did changing permissions on the `/usr/lib/node_modules/` directory resolve this issue for you @Fandekasp?

I just checked and was able to `npm i -g react-devtools` without any problem.

**Comment by Fandekasp** [comment]
sorry, I had switch to react-native-debugger, which installs react-devtools on its own, and my react native project got cancelled yesterday, so I won't be playing again with it for a while.

Closing.

**Comment by Fandekasp** [comment]
my react native project got cancelled, and I'm already using the chrome extension for react-devtools, so I don't need to install this locally anymore. Closing.

**Comment by AlexanderKosianchuk** [comment]
chown USER:root /usr/lib/node_modules/ resolves "EACCES: permission denied, access /usr/lib/node_module"

**Comment by lpetkovic** [comment]
Been having the same issue (wasn't using sudo for npm i), resolved it by globally installing electron and then react-devtools.

**Comment by Richard-CH-NG** [comment]
After fixing the permission issue with npm global install, i do the following:
```sh
$ npm uninstall -g react-devtools
$ npm uninstall -g electron
$ npm install -g --verbose react-devtools
```
Then the terminal will show the downloading process:
<img width="823" alt="screen shot 2017-09-14 at 11 15 05 am" src="https://user-images.githubusercontent.com/18453398/30410657-0e46d24e-993f-11e7-82fb-9af6f1fa1f98.png">
For me it was done within 5 minutes, and then ``` $ react-devtools  ``` works.

**Comment by brancooo1** [comment]
This does the trick for me.

`sudo npm install -g react-devtools --unsafe-perm=true`

**Comment by enriquesime** [comment]
@ghost Thanks that solve the issue !!!

**Comment by mrshafiqueqadri** [comment]
@brancooo1  Thanks your solution works for me.

**Comment by vink1987** [comment]
@brancooo1 thanks ... it works (Y)

**Comment by peterfei** [comment]
@ghost  thanks a lot!

**Comment by mckmarc** [comment]
@brancooo1  yeah

**Comment by seftrick** [comment]
I've changed rights on global node_modules directory and then installed devtools
`cd /usr/local/lib
sudo chown -R user:user node_modules   
npm i -g react-devtools`

**Comment by aino-gautam** [comment]
after trying all other options - this one worked as pointed out by @brancooo1

sudo npm install -g react-devtools --unsafe-perm=true

**Comment by min9nim** [comment]
adding `--unsafe-perm=true` option is work for me

**Comment by bbmattieu9** [comment]
What does the flag --unsafe-perm=true mean???? I used it and it worked but i do know understand what i just did. Please point me to a resource to learn this.to know.thanks

**Comment by jundat95** [comment]
Maybe this is what you want
https://stackoverflow.com/questions/49260428/how-can-i-open-react-devtools/53058331#53058331

**Comment by serpel** [comment]
> sudo npm install -g react-devtools --unsafe-perm=true

The real solution!

**Comment by Ethanng329** [comment]
> This does the trick for me.
> 
> `sudo npm install -g react-devtools --unsafe-perm=true`

**Comment by PrimeTime416** [comment]
--unsafe-perm=true works for me, thanks Peoples.

https://geedew.com/What-does-unsafe-perm-in-npm-actually-do/

**Comment by rudiss** [comment]
> This does the trick for me.
> 
> `sudo npm install -g react-devtools --unsafe-perm=true`

jedi

**Comment by gonpeche** [comment]
Faced same issue, tried several answers found on the web and the solution provided by @brancooo1 worked like a charm, thanks bro.

**Comment by nawartamawi** [comment]
you need to change the node_modules permission to all users 
1- ```cd /usr/local/lib/```
2- ```sudo chmod 777 node_modules```  
3- ```npm install -g react-devtools``` 

that should fix it.

**Comment by farshadfahimi1371** [comment]
it's better to look at this link it's work 
[https://askubuntu.com/questions/869168/node-modules-have-755-permissions-what-permissions-should-i-set-so-that-npm-don?newreg=2327c9ea958d461d88c5d7f4f197b678](url)
