### ISSUE TITLE
Weird <div><div> on master

### ISSUE THREAD

**Issue by gaearon** [facebook/react-devtools#747]
Probably messed this up as part of style refactor:
<img width="264" alt="screen shot 2017-05-26 at 6 40 17 pm" src="https://cloud.githubusercontent.com/assets/810438/26506000/d3e1dcf0-4242-11e7-8c28-d481ef526135.png">

**Comment by bvaughn** [comment]
Lies 🤡

**Comment by gaearon** [comment]
Old?

**Comment by bvaughn** [comment]
Actually I was just joking. 😄

But a simple empty div (eg `<div></div>`) doesn't behave this way on head of master, at least not using the plain test harness.
<img width="438" alt="screen shot 2017-05-27 at 5 13 27 pm" src="https://cloud.githubusercontent.com/assets/29597/26522768/db8aca12-42ff-11e7-9f16-c9c82303ced0.png">

**Comment by gaearon** [comment]
Oops, it actually happens for any non-self-closing node that fits on one line:
<img width="532" alt="screen shot 2017-06-05 at 4 19 17 pm" src="https://cloud.githubusercontent.com/assets/810438/26790188/c7c94028-4a0a-11e7-9492-7490b10d72af.png">
