### ISSUE TITLE
Component name gone from the right panel, can't copy the name

### ISSUE THREAD

**Issue by kortv** [facebook/react-devtools#754]
![image](https://cloud.githubusercontent.com/assets/10098905/26604925/a116d488-4594-11e7-9fb6-a0cbd06ee7e2.png)

**Comment by glennreyes** [comment]
Not sure if that has been removed intentionally (cc @bvaughn @gaearon @jaredly). This is how it looked like before and what @kortv means iirc:
![9ffeac6c-463c-11e7-8f08-ea594ad9228d](https://cloud.githubusercontent.com/assets/5080854/26646693/d863a5b2-463c-11e7-8c84-760db21807e6.png)

**Comment by gaearon** [comment]
This was intentional, to clean up some space. Why do you copy the name?

**Comment by bvaughn** [comment]
Yup. Was intentional b'c vertical space is limited and we thought the props were more important than the name (given that the name is also shown in the left panel).

**Comment by kortv** [comment]
@gaearon I copy the name to fast finding it in the IDE.
@bvaughn I see the name in left panel but it's not copyable
Maybe it's possible to add copy name through right click menu at the bottom?
![image](https://cloud.githubusercontent.com/assets/10098905/26653132/dacc0380-465a-11e7-87c6-481ab07995df.png)

Or add option to show the name at old place?

**Comment by bvaughn** [comment]
> Or add option to show the name at old place?

Subjective opinion here, but I don't think this is worth the added complexity it would introduce to the codebase.

> Maybe it's possible to add copy name through right click menu at the bottom?

Adding an option to the context menu to copy some info from the node, maybe including name, seems potentially worth exploring.

**Comment by kortv** [comment]
Maybe to make the name selectable in the selected component tab, at bottom, will be not so complex?

**Comment by kortv** [comment]
Cursor at selected tab is changing from "pointer" to "default", even now. So maybe changing it to the text instead of default, will not make UX so bad?
Or even, changing the cursor to default, as it now, but, only at selected tab, on double click, make a select the name text, or enable selection.

**Comment by bvaughn** [comment]
Debatably the current behavior should be changed to always preserve cursor as pointer when over a tab, even if current.

I feel pretty strongly that we should not make tab text selectable.

**Comment by glennreyes** [comment]
What if we add a `Copy element name` item to the `ContextMenu`? Similar to the Chrome devtools. Unlike the `Copy element`, this would only copy the name of the selected element. This way you have an easy alternative to copy complex component names.

**Comment by kortv** [comment]
@glennreyes sounds great

**Comment by bvaughn** [comment]
Yeah, that option was mentioned above.

>> Maybe it's possible to add copy name through right click menu at the bottom?

>Adding an option to the context menu to copy some info from the node, maybe including name, seems potentially worth exploring.

Copying text from JS is a bit clunky. And I'm not personally convinced it's a feature most people will need/use. But if you'd like to submit a PR to add it, I'd be happy to review it.

**Comment by LanceJernigan** [comment]
@bvaughn I actually just submitted pr #768 to address this feature.

**Comment by bvaughn** [comment]
@LanceJernigan Yup! I'm reviewing it. 😄

**Comment by LanceJernigan** [comment]
Nice!

The only issue right now is notifying the user that their text was copied.  Do we have any way to post a notification to the user?

**Comment by bvaughn** [comment]
I don't think that's necessary. To my knowledge, we don't have any such notification framework built into devtools at the moment.

**Comment by bvaughn** [comment]
Fixed via PR #768
