### ISSUE TITLE
Support inspecting elements inside iframes

### ISSUE THREAD

**Issue by byudaniel** [facebook/react-devtools#76]
If a react component is running within an iframe there is no way to inspect it with the current version of dev tools.

**Comment by jv-PintoBobcat** [comment]
:+1:

**Comment by EatYourSpinach** [comment]
Yes please!

**Comment by sktguha** [comment]
yes I have the same problem, any updates ?

**Comment by nickbouton** [comment]
+1

**Comment by sktguha** [comment]
(y)

**Comment by sktguha** [comment]
:+1:

**Comment by facebook-github-bot-7** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by pcostanz** [comment]
Since webpack-dev-server runs components in an iframe, this would be really helpful for those of us who use these two things together.

**Comment by sktguha** [comment]
Any hints on how to proceed with this ?

**Comment by jaredly** [comment]
Here's how to do it, as long as the two iframes share the same origin (so they can access each other's javascript context).
At the top of your script/page, *before* react gets loaded, do 
```js
if (window.parent !== window) {
  window.__REACT_DEVTOOLS_GLOBAL_HOOK__ = window.parent.__REACT_DEVTOOLS_GLOBAL_HOOK__;
}
```

You can remove the surrounding `if` if the script will always be in an iframe

**Comment by hackhat** [comment]
+1

**Comment by KODerFunk** [comment]
+1

**Comment by fkrauthan** [comment]
I guess the 30 days are long over any new updates @jaredly ?

**Comment by spicyj** [comment]
No new updates.

**Comment by zetachang** [comment]
With https://github.com/facebook/react-devtools/pull/440 landed, iframe could now be debugged using the electron app under https://github.com/facebook/react-devtools/tree/master/shells/electron.

**Comment by gaearon** [comment]
This is now supported.
Please see [`react-devtools`](https://github.com/facebook/react-devtools/blob/master/packages/react-devtools/README.md) npm package for the documentation.

**Comment by benwiley4000** [comment]
@gaearon not sure I'd consider this resolved - the standalone package is certainly useful, but it lacks some of the power of the browser extensions (e.g. direct element inspection and syncing with the selected element from the `elements` tab). Ideally it would just work with iframes, but the next best thing would be if I could simply add something like what @jaredly suggested above (which no longer appears to activate dev tools).

**Comment by Hurtak** [comment]
What solved it for me was putting that code inside script tag before the main bundle. If I put it inside the bundle, it did not work.

**Comment by gaearon** [comment]
The important part is that it needs to be put before `react-dom` executes. However ES6 imports get hoisted so even if you put it before the import, it will still execute later. Putting it outside of the bundle (or right in the HTML) is probably a good way to do it.

**Comment by qlqllu** [comment]
@jaredly your way works well! Thanks!

**Comment by DianaSuvorova** [comment]
has anybody successfully done this lately for a webpack app?
Example I am trying is 2 instances of `create-react-app` one embedding another as an iframe. I have added the script to the top of `.public/index.html` it executes and iframe renders but this makes no difference for React dev tools - it still sees just an iframe el. Any suggestions/debugging tips?

**Comment by StachuDotNet** [comment]
2019 here, hello!

I'd like to reiterate what @Hurtak mentioned.

What worked for me was adding:
```js
<script>
    if (window.parent !== window) {
      window.__REACT_DEVTOOLS_GLOBAL_HOOK__ = window.parent.__REACT_DEVTOOLS_GLOBAL_HOOK__;
  }
</script>
```

right at the end of our `<body>` tag of our main `.html` file. In our case, WebPack injects the "React stuff" right after this script.
