### ISSUE TITLE
"Click-to-select" and "Theme selector" needs visual feedback e.g. tooltips

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/react-devtools#772]
I'm scared to click them before I hover and know what they will do. :)

**Comment by sebmarkbage** [comment]
Search could use one as well.

**Comment by bvaughn** [comment]
> Search could use one as well.

Search has placeholder text. Doesn't this search a similar function?

**Comment by sebmarkbage** [comment]
To clarify: My confusion was a bit around *what* it searches. Maybe that's too much info.

**Comment by bvaughn** [comment]
Makes sense! I added a tooltip that says "Search React elements"

**Comment by gaearon** [comment]
>"Search React elements"

This is still a bit ambiguous. Maybe "Search React component names and text"?
