### ISSUE TITLE
Warning: getDOMNode(...) is deprecated

### ISSUE THREAD

**Issue by gsklee** [facebook/react-devtools#78]
I'm getting lots of the following warning: `Warning: getDOMNode(...) is deprecated in plain JavaScript React classes.`

**Comment by zpao** [comment]
I don't think this is related to the devtools. Are you using ES6 classes in your application?

**Comment by spicyj** [comment]
Might be:

https://github.com/facebook/react-devtools/blob/fa6a0aff240ffa55a4f7c373f427ae8825b2af7a/injected/Overlay.js#L176

**Comment by zpao** [comment]
Ah yea, you're right. Just reproed with our ES6 example.
