### ISSUE TITLE
Right and left arrows behave unexpectedly when tail tag is focused

### ISSUE THREAD

**Issue by gaearon** [facebook/react-devtools#783]
The right and left arrow keys behave unexpectedly when a tail tag of a node with children is selected.

Note that Firefox doesn't really let you select a tail tag. (Keyboard nav skips it. Mouse clicks redirect to the head tag.) So we'll compare to Chrome's behavior.

#### Chrome
Chrome jumps to the head tag.
![chrome-left](https://cloud.githubusercontent.com/assets/29597/26733766/b510a378-4770-11e7-9c0d-ad5f38dd5b1c.gif)

#### DevTools
DevTools collapses the node. I don't feel strongly about this but it might be nice to match Chrome's behavior.
![devtools-left](https://cloud.githubusercontent.com/assets/29597/26733909/2730f84a-4771-11e7-9981-cab2bad6f040.gif)

#### Chrome
Chrome does nothing in this case.

#### DevTools
DevTools steps into the tree (into children, moving the cursor up). This feels unnatural.
![devtools-right](https://cloud.githubusercontent.com/assets/29597/26733923/36ff1d42-4771-11e7-94be-6b11dcc15aaa.gif)

**Comment by jobala** [comment]
@gaearon,

I can pick this up, mainly because I have free time on my hands.
And willing to learn.

How do I get started.

**Comment by gaearon** [comment]
Hey, thanks for offering to help! The related logic is in `frontend/keyboardNav.js`. You can follow "Contributing" instructions in README to set up the enrichment.

**Comment by bvaughn** [comment]
Sweet! Feel free to ping me on Twitter if you hit a snag @jobala 😄

**Comment by jobala** [comment]
@bvaughn I will.

**Comment by jobala** [comment]
@bvaughn,

I git cloned, the repo to my local machine.
I will need to be able to see the effect of the changes I am making.

How do I set it up, ie like a chrome extension running from my machine?
Or better yet, you could point me to a resource that has this information.

Could be a dumb question, but yeah 😅

**Comment by jobala** [comment]
Otherwise,

I have done some digging and think this could be a possible solution.

I followed a rabbit hole from keyboardNav.js to dirToDest.js

for the right arrow `(dirToDest.js line 39-50)`
```
...
if (hasChildren) {
  if (bottom) {
     // This is the cause for our first bug, if we are at the bottom of a tree,
     // return the last child of the tree. A solution would be to return...uhm...
     // not really sure what to return perhaps an empty string or just return null
     return 'lastChild'
  } else {
    return 'firstChild'
  }
}
```

for the left arrow `(dirToDest.js line 39-50)`
```
if (dir === 'left') {
  if (!collapsed && hasChildren) {
     // source of the bug, we are collapsing the tree, I am not sure what we should
     // return here, something equivalent to the opening tag
     return 'collapse'
  }
  return 'parent'
}
```

This analysis could be wrong, waiting for your suggestions and insight 😄 

@gaearon @bvaughn

**Comment by bvaughn** [comment]
Hey @jobala,

The main README has a [contributing section](https://github.com/facebook/react-devtools#contributing) that mentions shells. For example, the easiest one to run is the [plain shell](https://github.com/facebook/react-devtools/tree/master/shells/plain). I made a [walkthrough video](https://www.youtube.com/watch?v=IaLROWK14mg&t=7s) recently that shows how to iterate on this shell.

You can also test in the browser using the [Chrome shell](https://github.com/facebook/react-devtools/tree/master/shells/chrome) or the [Firefox shell](https://github.com/facebook/react-devtools/tree/master/shells/firefox).

**Comment by jobala** [comment]
@bvaughn 

I have the right arrow bug fixed.

I have hit a snag with the left arrow, how do I get it to got to the opening tag ?

**Comment by bvaughn** [comment]
I think all you want to do is toggle `isBottomTagSelected` in the `Store`. So basically take the currently selected id (`store.selected`) and call either `store.selectTop` or `store.selectBottom`. (I think in your case you want `store.selectTop`.)
