### ISSUE TITLE
Follow-up keyboard nav fixes for Fiber

### ISSUE THREAD

**Issue by bvaughn** [facebook/react-devtools#786]
There's one remaining keyboard nav issue (mentioned [here](https://github.com/facebook/react-devtools/pull/781#issuecomment-305832447) and [here](https://github.com/facebook/react-devtools/pull/781#issuecomment-305833600)): on facebook.com, click on any of the Like/Comment divs:
![screen shot 2017-06-02 at 9 06 29 am](https://cloud.githubusercontent.com/assets/29597/26734446/dbeb33ee-4772-11e7-9bfc-c2b59385b1b4.png)

Then use up/down arrows to step over the "clearfix" node:
![skip-null-2](https://cloud.githubusercontent.com/assets/29597/26734704/dd1098e4-4773-11e7-96db-c632d67b1b9e.gif)

The focus will disappear for one up/down press, showing "null" in the bottom breadcrumbs area, and then re-focus when you press up/down arrow again.

**Comment by gaearon** [comment]
I’m still having this issue in UFI.

![](https://d2ppvlu71ri8gs.cloudfront.net/items/2y1B3P1M0E3219373O0D/Screen%20Recording%202017-06-09%20at%2004.57%20PM.gif?v=ab937276)

**Comment by gaearon** [comment]
Fixed by #807.
