### ISSUE TITLE
Store version doesn't work on our site (fin.com) -- fixed version

### ISSUE THREAD

**Issue by indigoviolet** [facebook/react-devtools#803]
For some reason, the store version of this extension breaks on fin.com, here's the fix that makes it work: https://github.com/facebook/react-devtools/compare/master...indigoviolet:master . 

Not sure how we're triggering this FB-specific hack -- if someone could give me a hint, we can try to fix our code. Would also be nice for the hack to not make it into the public version..

**Comment by indigoviolet** [comment]
We figured it out - we were setting `displayName` to be a function in a higher-order component.

**Comment by gaearon** [comment]
Nice catch. We should probably turn it to string somewhere earlier to avoid this.

**Comment by bvaughn** [comment]
@indigoviolet I believe the change in PR #839 should work for fin.com but I'm unable to verify it since there is no sign-up. 😄

**Comment by indigoviolet** [comment]
Thank you! @bvaughn
