### ISSUE TITLE
Wrongly saying outdated version

### ISSUE THREAD

**Issue by marcogreselin** [facebook/react-devtools#813]
I'm working on a `create-react-app` app and it says I have an outdated version of React. I made sure to run `npm update` and have checked the version of the `react` module and it's 15.6.0. The website is https://marcogreselin.com/ and the code in question is in [this](https://github.com/marcogreselin/portfolio) repo. What am I doing wrong?

**Comment by ngyikp** [comment]
The extension's warning is correct, your page is loading two copies of React.

Following this diagnosis guide: https://github.com/facebook/react-devtools/issues/692
We can see that there are two React renderers:
<img width="733" alt="screen shot 2017-06-15 at 1 27 05 am" src="https://user-images.githubusercontent.com/6135313/27145856-c40de306-5169-11e7-87f0-d6f0f9dd1a1d.png">

Luckily, source maps are uploaded, making diagnosis much easier.
One way to find the ReactDOM modules is to search for `__REACT_DEVTOOLS_GLOBAL_HOOK__.inject(`, which shows two results:
<img width="767" alt="screen shot 2017-06-15 at 1 34 25 am" src="https://user-images.githubusercontent.com/6135313/27146405-d70d683a-516b-11e7-92c5-0f37241c99f0.png">
<img width="771" alt="screen shot 2017-06-15 at 1 34 46 am" src="https://user-images.githubusercontent.com/6135313/27146406-d7772a4a-516b-11e7-9cb6-fd31f394a389.png">

By looking at the module ID comment that Webpack inserts at the top of each module, we can step through each module:
* Module ID 242 -> 228 -> 180
  <img width="723" alt="screen shot 2017-06-15 at 1 46 38 am" src="https://user-images.githubusercontent.com/6135313/27146609-7d0249b8-516c-11e7-8d9a-6ee87afa62fb.png">

* Module ID 344 -> 340 -> 385 -> 141
  <img width="829" alt="screen shot 2017-06-15 at 1 47 09 am" src="https://user-images.githubusercontent.com/6135313/27146638-9098d186-516c-11e7-810b-e78a5368c325.png">

We found the culprit, a third-party component react-typewriter links to an outdated React version using `dependencies`, it should be linked with `peerDependencies` instead

https://github.com/ianbjorndilling/react-typewriter/blob/3fa2fcd04b6efb33c94b0fbb11d46dc603c5db9d/package.json#L27

Your solution is to either notify the author or fork the component.

**Comment by marcogreselin** [comment]
Oh wow thanks @ngyikp for your help!
