### ISSUE TITLE
Flow errors with npm

### ISSUE THREAD

**Issue by zinoviev** [facebook/react-devtools#817]
The last PR builds failed with flow errors on promise package

I spot these on last two PR https://github.com/facebook/react-devtools/pull/569 and https://github.com/facebook/react-devtools/pull/677 and it's true for master as well

On my local environment, everything is fine with yarn but doesn't work with npm
Promise is fbjs dependency ^7.03, with yarn it's resolved  with 7.1.1 version for npm it's 7.3.0

7.3.0 promise kills our build
https://github.com/then/promise/issues/135

Not sure how to deal with it - wait for promise team for fix or pin promise version in fbjs

**Comment by ForbesLindesay** [comment]
This should now be resolved.

**Comment by bvaughn** [comment]
Can confirm, CI seems happy now. Thanks for the update, @ForbesLindesay!
