### ISSUE TITLE
react-devtools doesn't work with React + Meteor

### ISSUE THREAD

**Issue by grigio** [facebook/react-devtools#82]
Hi, I don't see the React DOM in the React tab in the inspector, just an empty tab

This is a Meteor React example [leaderboard](https://github.com/grigio/meteor-react/blob/leaderboard/examples/leaderboard/leaderboard.jsx)

**Comment by dgreensp** [comment]
We (Meteor) are fixing this on our end.  Related to #90.

**Comment by spicyj** [comment]
Thanks @dgreensp!
