### ISSUE TITLE
Minor: Update this repo's description to also mention Firefox

### ISSUE THREAD

**Issue by captainbrosset** [facebook/react-devtools#829]
Thanks for the awesome work making this supported on Firefox too.

The repo has the following description now: 
An extension that allows inspection of React component hierarchy in Chrome Developer Tools. 

It should now be updated to something like:
An extension that allows inspection of React component hierarchy in Chrome and Firefox Developer Tools.

**Comment by bvaughn** [comment]
Agreed! The description should either mention Chrome+Firefox or be even more generic and mention neither browser. (This repo is also the source for the standalone DevTools used for React Native.)

**Comment by bvaughn** [comment]
Done!

**Comment by captainbrosset** [comment]
Thanks @bvaughn!
