### ISSUE TITLE
Support Inspection of Immutable JS objects 

### ISSUE THREAD

**Issue by abritinthebay** [facebook/react-devtools#83]
It's your own library guys - checking that it's Immutable and displaying the toJS output can't be that hard can it? ;)

But seriously - right now it doesn't even show the data when you expand it - just "fr" and an object with properties no-one care about.

Given that Immutable objects are becoming a _recommended_ pattern (and FB has a library for it) this seems like a no brainer.

I'll see if I can fork + patch but would love to know if you're working on this...

**Comment by Daniel15** [comment]
+1 I'd love to see this too

**Comment by phuson** [comment]
+1

**Comment by wilkerlucio** [comment]
+1 I would love this feature as well

**Comment by zpao** [comment]
Going to merge this into #52.

**Comment by gaearon** [comment]
Immutable support is implemented in the latest version.

**Comment by lukeknep** [comment]
@gaearon Thanks for digging into this. Is the latest version released? I just updated to 2.1.7 (released today) and am still seeing Immutable Maps and Records visualized like arrays of size-2 arrays (rather than key / value pairs).

**Comment by gaearon** [comment]
I don’t think it’s too hard. Just needs someone dedicated to fixing it.

**Comment by vdh** [comment]
@gaearon So will Immutable.js Maps get a better implementation? Maps with string keys are really hard to read like this.
