### ISSUE TITLE
Add support for copy props as JS

### ISSUE THREAD

**Issue by orta** [facebook/react-devtools#833]
### Use case

I'm currently writing storybooks / jest snapshot tests for code that uses Relay, I'd like to be able to get the props that are passed to a component in prod into my source code so that I can reliably stub the networking. 

![screen shot 2017-07-10 at 11 01 31](https://user-images.githubusercontent.com/49038/28024645-51c366d6-655f-11e7-8155-543f1e617d80.png)

Functions can probably be stubbed functions that do nothing for example.

**Comment by bvaughn** [comment]
Yo @orta. Check out #837 and let me know your thoughts.

**Comment by bvaughn** [comment]
Moving forward with the approach in #837 based on initial positive feedback and my own testing.

We can always iterate and improve.
