### ISSUE TITLE
Collapser not red for components with state

### ISSUE THREAD

**Issue by leoasis** [facebook/react-devtools#834]
It seems the collapser in the component tree is not red, for components that have state. I'm seeing this behavior with latest Chrome and devTools version 2.4.0.

Pasting a screenshot to show the behavior:

The top component (named "k") contains state, as you can verify in the second screenshot.

![image](https://user-images.githubusercontent.com/328001/28035820-63b36a6c-658c-11e7-8a6f-bd8379889072.png)
![image](https://user-images.githubusercontent.com/328001/28035829-6b6ff8d8-658c-11e7-9805-9545100254d5.png)

**Comment by leoasis** [comment]
Ah never mind, just noticed the color is no longer red, but pink, while the other arrows are dark gray.

Maybe that needs an update in the README and in the screenshot used?

**Comment by bvaughn** [comment]
The README (and its screenshots) probably all predate the addition of themes. Theme color changes the color of components with state/context, so that's a bit tricky. I agree with you that the way the current docs refer to "red" specifically is not great. I'll take a stab at improving it. 😄

**Comment by leoasis** [comment]
Awesome, thanks for the fast answer!
