### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by pedrogarciyalopez** [facebook/react-devtools#846]
macOS Sierra 10.12.5
node 8.1.3
npm 5.2.0

sudo npm install -g react-devtools

and:
<img width="1322" alt="2017-07-13 18 20 36" src="https://user-images.githubusercontent.com/14232660/28173752-0dae89b2-67f8-11e7-9e91-d6354773ccac.png">

**Comment by bvaughn** [comment]
Using sudo with NPM is error prone and leads to issues with corrupted permissions.

Try changing `/usr/local/lib/node_modules/` to something writable by all users and then installing without sudo. 😄
