### ISSUE TITLE
`yarn run test:firefox` fails with `Unhandled promise rejection`

### ISSUE THREAD

**Issue by flarnie** [facebook/react-devtools#847]
Steps to reproduce;

1) Use `n` to run node v8.0.0.
2) run `yarn install` and `yarn build extension`
3) run `yarn run test:firefox`

Output:
```
Using globally installed version of Yarn
yarn run v0.28.1
$ node ./shells/firefox/test
(node:10470) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): ChildProcessError: Command failed: web-ext run --start-url=https://facebook.github.io/react/ --firefox-profile=/Users/flarnie/Library/Application\ Support/Firefox/Profiles/lyr8wuj6.default --keep-profile-changes --browser-console
/bin/sh: web-ext: command not found
 `web-ext run --start-url=https://facebook.github.io/react/ --firefox-profile=/Users/flarnie/Library/Application\ Support/Firefox/Profiles/lyr8wuj6.default --keep-profile-changes --browser-console` (exited with error code 127)
(node:10470) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by flarnie** [comment]
tagging @bvaughn since you have been helping with setting up these test scripts

**Comment by flarnie** [comment]
`yarn run test:chrome` seems to hang for me.

I also tried switching to node v7.6.0 and got the same result. Going to do the manual testing steps for now and come back to this and investigate when I have time.

**Comment by flarnie** [comment]
Now I'm thinking I might just need to install `web-ext` globally. The 'unhandled promise' looks unrelated.

**Comment by flarnie** [comment]
That was it - ignore this.

**Comment by bvaughn** [comment]
Sorry for the snag Flarnie. The [Firefox shell README](https://github.com/facebook/react-devtools/tree/master/shells/firefox#testing-in-firefox) mentions this as a pre-req but maybe the CLI output should also call it out? Thoughts?

**Comment by clarkbw** [comment]
> The Firefox shell README mentions this as a pre-req but maybe the CLI output should also call it out? Thoughts?

What if we made `web-ext` one of the `devDependencies`?  This helps maintain a consistent version.  Lemme open a quick PR.

**Comment by bvaughn** [comment]
I dig it
