### ISSUE TITLE
Developing react-devtools in Firefox will break your Firefox

### ISSUE THREAD

**Issue by kumar303** [facebook/react-devtools#852]
When developers work on react-devtools, they run [this web-ext command](https://github.com/facebook/react-devtools/blob/67c857341ccf03602dd35cc0dd57caf0353bffd0/shells/firefox/test.js#L35) to start Firefox.

I wanted to point out that since this uses the developer's **default** profile, it will apply all of web-ext's required profile changes and thus make their default instance of Firefox very insecure and, well, nearly broken. This will be surprising to your developers since there is no warning.

I suggest removing the `--keep-profile-changes` option to that command. This will tell web-ext to copy the default profile into a new temporary profile. Thus, your will still retain all of your logins and sessions from your default profile.

Specifically, web-ext [will make the following profile changes](https://github.com/mozilla/web-ext/blob/7b390e45f3a998a57238ddb9f163da4a61dfb08a/src/firefox/preferences.js#L22) among others *to your default profile*:

- It will disable automatic updates to Firefox
- It will disable updates to all add-ons
- It will disable the prompt for accepting a remote debugging connection -- this means anyone can silently connect a remote debugger to your Firefox
- It will disable signature checks for add-ons (but only in pre-release builds of Firefox)
- It will allow side loading add-ons which is how a lot of crapware installers inject their add-ons without user consent

The [web-ext docs](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Getting_started_with_web-ext#Keeping_profile_changes) had a warning about this but it didn't mention the security issues -- sorry, I just updated those docs. I think we need to disallow using the default profile like this in web-ext so I filed an issue: https://github.com/mozilla/web-ext/issues/1005

**Comment by kumar303** [comment]
For any of your developers who have run this, they can type `about:support` into the URL bar of Firefox and click the 'Refresh Firefox' button. I'm not sure if this will fix everything though. They should go to `about:config` and check the prefs linked to up above.

**Comment by bvaughn** [comment]
cc @clarkbw to confirm the issue and proposed fix. Want to include this with your changes in #848?

If not I'm happy to follow up on it. Just thought you'd have more context.

**Comment by bvaughn** [comment]
Thanks for filing this issue and for all of the provided info, @kumar303 !

**Comment by clarkbw** [comment]
> cc @clarkbw to confirm the issue and proposed fix. Want to include this with your changes in #848?

Yes, I just confirmed this and I can pick this up over there.
