### ISSUE TITLE
React Dev Tools don't show when i inspect devices

### ISSUE THREAD

**Issue by Meshredded** [facebook/react-devtools#854]
So i'm writing a cordova app that uses react based on [this project](https://github.com/phonegap/phonegap-template-react-hot-loader)
The problem is that react dev tools won't show when i inspect devices using google chrome.
Html inspection works good but not react dev tools.

**Comment by bvaughn** [comment]
Hey @Meshredded,

Have you tried the [standalone DevTools](https://github.com/facebook/react-devtools/tree/master/packages/react-devtools)?

```
npm install -g react-devtools
react-devtools
```

I think it should work with Cordova apps (although I haven't tried).

**Comment by Meshredded** [comment]
Hey @bvaughn  Thank you so much it worked well with the standalone devTools.

**Comment by bvaughn** [comment]
Glad to hear
