### ISSUE TITLE
Cannot copy selected react code (JSX)

### ISSUE THREAD

**Issue by af7** [facebook/react-devtools#86]
I look at a site that uses JSX and would like to copy the JSX code so that I paste it on a sample app and learn fast.

This is not possible with CTRL-C, neither with a right mouse-click option.

This is something that we can do in the "Elements" tab of the Chrome Dev Tools, but not here?

**Comment by camsong** [comment]
Really want this to be added, for many times, I'm using CMD+C to copy code, but the react generated HTML is mess, would like to contribute this feature if got some hint.

**Comment by facebook-github-bot-7** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by jaredly** [comment]
@af7 and @camsong:
from my own experience, there is enough logic involved that copy+pasting a JSX'd form doesn't seem super helpful. In the [new beta version](https://facebook.github.io/react/blog/2015/08/03/new-react-devtools-beta.html), you can right-click an element and jump to the source code itself, which I find much more useful.
Does that fit your needs?

**Comment by kassens** [comment]
There's a few things that make "copy JSX" difficult:
- Most likely, you'll have components in multiple modules, so we would have to require them somehow.
- Most react component have at least some logic, would you expect to just copy the low level `<div>` and `<span>` elements or complex components like `<TodoItem>` to be copied?

I'll close this for now, but happy to re-open if there's more specific ideas to the functionality!
