### ISSUE TITLE
Chrome can't add react-devtools

### ISSUE THREAD

**Issue by healscm** [facebook/react-devtools#863]
when i click the icon 
![image](https://user-images.githubusercontent.com/11639958/28779234-f5158658-7634-11e7-9d6c-55bd24d48708.png)
,it shows like that ,how i can do ?
![image](https://user-images.githubusercontent.com/11639958/28779113-93576c2e-7634-11e7-81c8-efc98e1d5c48.png)

**Comment by bvaughn** [comment]
This icon means that the website you're currently viewing (in the active tab) doesn't appear to be running React. If you open a website that's using React, eg the [devtools theme preview site](http://facebook.github.io/react-devtools/), the icon should change to reflect which build of React is running on that site. At this point, you can open Chrome DevTools (Cmd+Option+i) and you should see a "React" tab.
