### ISSUE TITLE
New context menu option: copy tree

### ISSUE THREAD

**Issue by bvaughn** [facebook/react-devtools#865]
Right-clicking an element currently shows 2 options: "Copy element name" and "Copy element props". It might be nice if there was an option to copy a tree representation (for the current element and its children). I assume it would be sufficient to copy the names of elements only and not their props.

For background info, see [this discussion thread](https://twitter.com/JustRodders/status/894911150105792512) on Twitter. Filing this issue now for later consideration.

**Comment by hristo-kanchev** [comment]
@bvaughn Are you still considering adding this feature?

**Comment by bvaughn** [comment]
Not really. Haven't thought about it in a long time.
