### ISSUE TITLE
Read-only props for functional components

### ISSUE THREAD

**Issue by chrislloyd** [facebook/react-devtools#868]
![screen shot 2017-08-10 at 4 14 31 pm](https://user-images.githubusercontent.com/718/29196083-12ecb340-7de7-11e7-824c-9a2836be548b.png)

It looks like props for functional components are being marked at "read-only". From digging around, 
it seems like this is because functional component instances don't have a `forceUpdate()` method. I definitely understand why this is, but I've seen this be confusing to developers. I can see two obvious options to help with this:

1. Update the label in the devtools to something more descriptive than "read-only". I'd suggest "functional component (read-only)".
2. Change the implementation to be able to edit props of all components (forceUpdate for functional component instances).

Option 1 is easier (and I'd be happy to provide a PR) but I think option 2 is the best long-term solution. From the POV of the React Core team trying to encourage people to use functional components, there probably shouldn't be any significant downsides to using them (refs aside). This would be more involved but it would lead to the devtools "just-working".

Happy to help out any way I can here.

**Comment by avalanche1** [comment]
Strangely, this still doesnt work for me.

**Comment by neptunian** [comment]
i also have this issue.  it still says 'read only" props and they can't be modified.
