### ISSUE TITLE
Plugin says I'm using a production build even when NODE_ENV is undefined

### ISSUE THREAD

**Issue by odonnellnoel** [facebook/react-devtools#878]
This is more of a question than an issue, but I'm using babel-node and webpack to build (haven't got time to un-es6ify the entire project just to test without babel-node though). Yes I checked during build time *and* run time and on both occasions process.env.NODE_ENV is undefined. 

Could somebody point me to where in the code the plugin actually decides what icon to show (production or development) then perhaps I can figure it out for myself,

Many thanks

**Comment by ngyikp** [comment]
https://github.com/facebook/react-devtools/blob/master/backend/installGlobalHook.js

**Comment by odonnellnoel** [comment]
thanks. I guess it's not so clear-cut, especially when I read "Hope for the best if we're not sure."
