### ISSUE TITLE
Type "findDOMNode" instead of "getDOMNode"

### ISSUE THREAD

**Issue by af7** [facebook/react-devtools#88]
Since getDOMNode is now deprecated it should be changed to findDOMNode:

![image](https://cloud.githubusercontent.com/assets/7850073/7622213/139bcb1a-f9d6-11e4-8567-7b9ec1a61c98.png)

**Comment by spicyj** [comment]
That just shows the properties of your component instance. Currently components still have a getDOMNode function that warns. Nothing to do for the devtools here.
