### ISSUE TITLE
Chrome: Can't press `Esc` to toggle console when React panel are open

### ISSUE THREAD

**Issue by sophiebits** [facebook/react-devtools#889]
Testing on OS X with Chrome 63 canary.

If I press `Esc` while React devtools is open, I expect this to open a JS console in a split view with the React devtools. This is how every other tab behaves. Instead, I see the console slide up and immediately back down in a split second.

We should fix this so the console can be used again.

Workaround: Switch to another tab, hit Esc, switch back to React.

**Comment by michaelshiel** [comment]
I've tried to debug this for an hour or so, but I don't think it's actually the extensions fault. I commented out almost the entire codebase, and it still happens. It also happens on other extensions I use that have Developer Tools tabs (Cookie Inspector, and Redux Devtools)

**Comment by ngyikp** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=772697

**Comment by ngyikp** [comment]
Fixed on Chrome 65.0.3311.3, currently on dev channel

**Comment by satyapramodh** [comment]
Chrome 65.0.3325 is the current production build and the issue is now fixed. this issue can be closed.

**Comment by sophiebits** [comment]
Nice. Thanks both of you for following up!
