### ISSUE TITLE
Permission denied for access `build/` folder in v2.5.1

### ISSUE THREAD

**Issue by jhen0409** [facebook/react-devtools#895]
The latest version of chrome extension have a problem with [`electron-devtools-installer`](https://github.com/MarshallOfSound/electron-devtools-installer):

<img width="738" alt="screen shot 2017-09-21 at 4 53 40 pm" src="https://user-images.githubusercontent.com/3001525/30687328-896a92bc-9e80-11e7-8d08-68d7b2679e25.png">

See also https://github.com/chentsulin/electron-react-boilerplate/issues/1220, we can use the boilerplate to reproduce the problem.

/cc @gaearon

**Comment by gaearon** [comment]
Wow. Could the build script mess up permissions somehow?

**Comment by jhen0409** [comment]
I can confirmed the latest version package is missing executable permission for the folders.

<img width="752" alt="screen shot 2017-09-22 at 3 49 58 pm" src="https://user-images.githubusercontent.com/3001525/30734433-c5ceb11e-9f40-11e7-8941-7f778d579422.png">

I guess Chrome Store modified folder permission for recently uploaded extensions, I got the same problem by tried another extensions like [Relay DevTools](https://chrome.google.com/webstore/detail/relay-devtools/oppikflppfjfdpjimpdadhelffjpciba), so this should report to [`electron-devtools-installer`](https://github.com/MarshallOfSound/electron-devtools-installer).

**Comment by gaearon** [comment]
Can you help me understand how this is related to Chrome Store? Our npm package is built separately from the Chrome extension.

**Comment by jhen0409** [comment]
The devtools-installer will download the extension from Chrome Store. (see [here](https://github.com/MarshallOfSound/electron-devtools-installer/blob/master/src/downloadChromeExtension.js#L19))
