### ISSUE TITLE
this page doesnt appear to be using react

### ISSUE THREAD

**Issue by xclidongbo** [facebook/react-devtools#905]
this page doesnt appear to be using react.

**Comment by xclidongbo** [comment]
This is a  terrible debug tool.

**Comment by ngyikp** [comment]
Is there a test page to help reproduce the issue? Also: https://github.com/facebook/react-devtools#the-react-tab-doesnt-show-up

**Comment by Saba-d-coder** [comment]
> Is there a test page to help reproduce the issue? Also: https://github.com/facebook/react-devtools#the-react-tab-doesnt-show-up


> this page doesnt appear to be using react.

Same here
