### ISSUE TITLE
undefined props

### ISSUE THREAD

**Issue by davidrenne** [facebook/react-devtools#906]
Hi there, why do you hide undefined props?  The key is still there and this.props.keyName exists in props but the value is undefined.  It tricks developers into thinking the prop just isnt there but that is not the case.  You should show undefined as the values so people know all of the props in the object.  I believe the same is with the rendered nodes, you hide the undefined values in props.

Are props of undefined values something everyone wants to ignore?  Please make an option to show undefined props if the developer likes seeing them.

**Comment by gaearon** [comment]
It's probably a bug. You're welcome to send a fix. :-)

**Comment by davidrenne** [comment]
Could you point me in the direction of possibly where in the chrome plugin code it shows the props/state of a given node?  This will help me send over a pull request quicker than reading through the code and ill take a look at undefined use cases.  I really think the keys of all props should be shown and undefined should show up as its important to know what keys you have to work with and what was passed as props.  I havent even read the source code, but its helpful to know the module that renders out the keys and values of the state and props within the render of the plugin in dev tools.

Great to hear from you again when I chime in and I get to talk to someone super famous and who is a living code legend who created a paradigm shift in web development.  If you remember last year or so you sent a tweet about my friends implementation of pydux https://github.com/usrlocalben/pydux with urwid his todo list.  Thank you for being an inspirational engineer who created a great thing for the community and opened many developers eyes to functional programming with your original talk and amazing killer demo.

Sadly though I still have not fully written a redux app and we wrote our own javascript router and state management tools in golang.

Thanks @gaearon!

**Comment by OliverJAsh** [comment]
I've also just ran into this. Where abouts can we find the code that needs fixing? I'm also happy to raise a PR. /cc @gaearon

**Comment by OliverJAsh** [comment]
Just spent 30 minutes on this but couldn't track down the source of the bug. I wonder if it could be somewhere we call `JSON.stringify`, which would lose the property.

**Comment by davidrenne** [comment]
Yea guys we need to figure this out.  It’s something we need to know if a caller to a component passes undefined we need to see the key as undefined.  It’s very 8mportwnt to provide transparency to the devs using it.  I might take a stab soon at this and send a pr

**Comment by hristo-kanchev** [comment]
Can I take this issue, @gaearon?
I think I've found the problem and have a potential fix.

**Comment by davidrenne** [comment]
I "linked you in" ill message you privately on there to thank you and goof
off about react and other languages we write

**Comment by hristo-kanchev** [comment]
Hey @davidrenne 

This should be fixed. Can you check again and close this issue?

Thanks!
