### ISSUE TITLE
React Native produces many "Unknown" nodes

### ISSUE THREAD

**Issue by brentvatne** [facebook/react-devtools#92]
As per https://github.com/facebook/react-native/issues/800

![68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f662e636c2e6c792f6974656d732f326833793356306431643155304533713174314d2f496d616765253230323031352d30342d3130253230617425323031302e32352e3332253230706d2e706e67](https://cloud.githubusercontent.com/assets/90494/7903399/29fe7f66-0790-11e5-8c0f-9be7a4439beb.png)

- Setting `displayName` didn't help
- These are not text elements

**Comment by spicyj** [comment]
That's funny, I thought I fixed that…

**Comment by brentvatne** [comment]
@spicyj - I just tried it on the master branch of React Native, freshly reinstalled React Devtools and see this:

![screen shot 2015-05-31 at 12 30 34 pm](https://cloud.githubusercontent.com/assets/90494/7903416/d926f568-0790-11e5-9c90-adcc202fa50d.png)

**Comment by brentvatne** [comment]
:heart:
