### ISSUE TITLE
how to download react-devtools-chrome.crx?

### ISSUE THREAD

**Issue by txiaocao** [facebook/react-devtools#924]
how to download react-devtools-chrome.crx?
i can not access google , and can not found react-devtools-chrome.crx in github release

**Comment by lettywiterock** [comment]
https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi
我在readme找到了这个地址，我也连不上google，所以无法验证

**Comment by ngyikp** [comment]
If you can't access Chrome Web Store, then the second best solution would be to compile the extension yourself if you are on Mac/Linux:

1. Make sure you have Node.js version 8+ (`node -v`)
2. Make sure you can run `git` from the command line (`git --version`)
3. Git clone this repo OR download the latest release at https://github.com/facebook/react-devtools/releases
4. Run `npm install` or `yarn`
5. Run `npm run build:extension:chrome`, the extension will be compiled to `shells/chrome/build/unpacked/`

Unfortunately, building the extension on Windows is a bit broken, you can either:
* Edit some files to fix it, see https://github.com/facebook/react-devtools/issues/908
* Or use [this CRX](https://github.com/facebook/react-devtools/files/1398476/fmkadmapgofadopljbjfkapdkoienihi.zip) that I have downloaded from the Store, extract the CRX with 7-Zip or another unzipper program, then delete the `_metadata` folder inside

To load the extension in Chrome:
1. Go to More tools (更多工具(L)) > Extensions (扩展程序(E))
    ![screen shot 2017-10-19 at 8 59 48 pm](https://user-images.githubusercontent.com/6135313/31772017-bdc3963e-b510-11e7-9991-2cf6d67f9b09.png)

2. Enable Developer mode (开发者模式) at top-right, click Load unpacked extension (加载已解压的扩展程序), then browse to that folder:
    ![screen shot 2017-10-19 at 9 01 15 pm](https://user-images.githubusercontent.com/6135313/31772020-c0416b2a-b510-11e7-9aed-56ee3c9b050a.png)

**Comment by txiaocao** [comment]
very thks...

**Comment by bleedkaga** [comment]
@ngyikp Nice!

**Comment by Oleh-Matviiv** [comment]
Would be very nice if answers were in the same language as questions.
