### ISSUE TITLE
你好，请问一下，chrome怎么离线安装这个插件？

### ISSUE THREAD

**Issue by lettywiterock** [facebook/react-devtools#925]
插件怎么使用呢？
npm install 
之后怎么运行？
我尝试了
npm run ...
可是找不到指令。
请求帮助。

**Comment by txiaocao** [comment]
下载该文件，并解压
https://github.com/facebook/react-devtools/files/1398476/fmkadmapgofadopljbjfkapdkoienihi.zip

访问
chrome://extensions/

将crx文件拖放到扩展当中即可

**Comment by wangbangzhi** [comment]
感谢楼上兄弟支持

**Comment by gaearon** [comment]
We only provide support for issues in English, sorry.
