### ISSUE TITLE
how to import json from javascript

### ISSUE THREAD

**Issue by adityos2003** [facebook/react-devtools#926]
(function() {

	var model = function(voter, party, precinct, ageGroup, lastVoted, yearsReg, ballotStatus) {
		this.voter = voter; 
		this.party = party;
		this.precinct = precinct;
		this.ageGroup = ageGroup;
		this.lastVoted = lastVoted;
		this.yearsReg = yearsReg;
		this.ballotStatus = ballotStatus;
	};

	  
	window.demo = {};
	window.demo.data = [];

	
	var data = getData();
	for(var t=0;t<1;t++) {
		for(var j = 0;j < data.length; j++) {
			window.demo.data.push(data[j]);
		}
	}

	
	function getData() {
		return ;
	}

	
	function getData1() {
		return ;
	}
}());

![test](https://user-images.githubusercontent.com/23629493/31872344-6cc318b8-b7e5-11e7-9bf0-b1e094187a49.jpg)

(function() {

	var model = function(voter, party, precinct, ageGroup, lastVoted, yearsReg, ballotStatus) {
		this.voter = voter; 
		this.party = party;
		this.precinct = precinct;
		this.ageGroup = ageGroup;
		this.lastVoted = lastVoted;
		this.yearsReg = yearsReg;
		this.ballotStatus = ballotStatus;
	};

	window.demo = {};
	window.demo.data = [];

	var data = getData();
	for(var t=0;t<1;t++) {
		for(var j = 0;j < data.length; j++) {
			window.demo.data.push(data[j]);
		}
	}

	function getData() {
		return [
['Contoso Florida', 'Proseware LCD17W E202 Black', 'Proseware, Inc.', 'Economy', 'Monitors', 4, 509.55],
['Contoso New Jersey', 'Adventure Works CRT15 E101 Black', 'Adventure Works', 'Economy', 'Monitors', 4, 351],

		];
	}

	function getData1() {
		return [
		new model(1012, 'REPUBLICAN', 2408, '71 +', '08/2006', 51, 'PERM'),

				];
	}
}());

![test2](https://user-images.githubusercontent.com/23629493/31872358-8ba7cec2-b7e5-11e7-855b-eb12500a3235.jpg)

how to render javascript then process file json (maybe import) ? trims

**Comment by gaearon** [comment]
This question has nothing to do with this repository. Please use StackOverflow or support forums.
