### ISSUE TITLE
CONSOLE.LOG

### ISSUE THREAD

**Issue by karenYerevan** [facebook/react-devtools#928]
HI.
How can i see my console.log(params) on React Developer tools ?????

**Comment by greenais** [comment]
The same question is here.
Chrome-based version shows in-app console.log calls like a charm, while standalone one doesn't.
Why?
Any suugestions to make console work in standalone devtools?

**Comment by greenais** [comment]
Any response from mantainers, perhaps?
By now only RN connect/disconnect information logged in devtool console

**Comment by gaearon** [comment]
I don't understand what you're referring to. React DevTools never showed console logs. You are probably thinking about some other tool.

**Comment by greenais** [comment]
Chrome-based version (which I referenced above) does - I doublechecked it right now, see proof below.
Standalone one, according to your response - doesn't.
Probably this should go to documentation.

![image](https://user-images.githubusercontent.com/16271522/32779623-84227ae6-c94f-11e7-9a1c-15b85718088d.png)

**Comment by karenYerevan** [comment]
i use a good solution.
i do like this
after
react-native run-android ... react-native log-android
and i see my console.log()

**Comment by greenais** [comment]
@karenYerevan, I do the same, but it's definitely more conviniet to have everything in one place.
 On top of this log-android is quite more verbose and doesn't allow to expand objects and arrays - which is very handy sometimes.

**Comment by karenYerevan** [comment]
maybe you true .... but for me log-android a best way ...
its my nature that i don't like when my package.json is overloaded )))))))

**Comment by greenais** [comment]
I have RDT installed as Chrome plugin and as standalone global app - so my package.json stays untouched as well)

**Comment by gaearon** [comment]
Where do you expect to see the logs in standalone version? On your screenshot the console is part of the *browser* DevTools. It's not a part of React DevTools. Therefore standalone React DevTools doesn't have it (just like React DevTools tab in Chrome doesn't have any dedicated console).

**Comment by greenais** [comment]
In console tab, I suppose, it will be the most convinient.
Thank you for explanation, but probably pointing in docs this internal RDT dev knowledge about sources of resulting functionality would prevent such questions from users which are quite a bit right expecting the same behaviour from both RDT versions.
Or - probably even better - feature request for standalone RTD, why not?

**Comment by gaearon** [comment]
This is not internal knowledge, it is just a misunderstanding between us. Happy to take a PR clarifying it.

>In console tab

The console tab **is not and has never been a part of React DevTools**. "React DevTools" is just the panel with React components. 

The console tab has absolutely no relation to it. They are independent. We are not in control of the "Console" tab. It only exists in Chrome.

You can always use the console tab in Chrome DevTools (note: "Chrome DevTools" is not the same as "React DevTools"). Even if you use standalone React DevTools, *you still can* use the Console tab in Chrome DevTools if you choose "Enable Remote JS Debugging".

**Comment by gaearon** [comment]
In other words:

Chrome DevTools = Console + Network + ... + React DevTools

This is why it doesn't really make sense to ask about Console in standalone React DevTools. Console has never been a part of it. The only reason you see Console in the browser is because *it is part of the browser DevTools*, not because we are doing something special to provide it.

**Comment by gaearon** [comment]
Also to be clear, you can still have Console open in Chrome while using standalone React DevTools. They should work fine together.

**Comment by jrwpatterson** [comment]
the issue is that then the chrome js engine takes over so debugging doesn't work...

**Comment by rawadrifai** [comment]
@gaearon can we add console logs? I think it would make a lot of sense to have it in react dev tools
