### ISSUE TITLE
Props mutation warns when changing props in devtools

### ISSUE THREAD

**Issue by spicyj** [facebook/react-devtools#93]
cc @Daniel15 

![image](https://cloud.githubusercontent.com/assets/6820/8002057/73832194-0b20-11e5-82e6-08014d26a45f.png)

**Comment by spicyj** [comment]
Not sure how hard this is to fix.

**Comment by jimfb** [comment]
Related question: What will happen when we freeze props in dev?  The devtools error would be fatal instead of just annoying, right?

cc @sebmarkbage

**Comment by jaredly** [comment]
I've had a couple of errors b/c of frozen props

**Comment by spicyj** [comment]
@jaredly Can you be more specific? Do you mean this issue when changing props in the devtools or something else?

**Comment by jaredly** [comment]
It was actually some hackery that probably shouldn't be supported :) nvm

**Comment by spicyj** [comment]
Fixed in the new devtools: http://facebook.github.io/react/blog/2015/08/03/new-react-devtools-beta.html.
