### ISSUE TITLE
Unexpected token b in JSON at position 6766 while parsing near

### ISSUE THREAD

**Issue by lilin666** [facebook/react-devtools#938]
when i run npm install -g react-devtools  this happend.

npm ERR! Unexpected token b in JSON at position 6766 while parsing near '...:{"tape":"^3.0.1"},"bin'
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lilin/.npm/_logs/2017-11-10T06_48_15_063Z-debug.log
mac os
using npm@5.4.1
using node@v7.7.3
can anyone  help me?

**Comment by hertzebogdan** [comment]
try rm package-lock.json

**Comment by lilin666** [comment]
@hertzebogdan Thank you all the same
