### ISSUE TITLE
Breadcrumb trail gets cut-off when not scrolled all the way down

### ISSUE THREAD

**Issue by uber5001** [facebook/react-devtools#94]
If too many elements are expanded in the React element inspector, the breadcrumb trail gets pushed off to the bottom of the last element, instead of staying in a fixed position.

Here's a screenshot of the breadcrumb trail partially scrolled out of view.

![screen shot 2015-06-08 at 10 08 24 am](https://cloud.githubusercontent.com/assets/3348363/8040621/b652d3a4-0dc6-11e5-8f74-741f908fb234.png)

**Comment by jaredly** [comment]
this no longer applies with the release of the [new devtools beta](http://facebook.github.io/react/blog/2015/08/03/new-react-devtools-beta.html).
