### ISSUE TITLE
Question about Redux-connected anonymous pure functional React-components

### ISSUE THREAD

**Issue by kinware** [facebook/react-devtools#944]
When you define Redux connect()-ed React components that wrap anonymous pure functional React components, the tree in React devtools only show ```<Connect(Component) /> == $r<Unknown .../>"```. Example:

```
const mapState = ({someStateVariable}) = ({somePropName});
const MyComponent = connect(mapState, undefined)(
  ({somePropName}) => (
  <div>{somePropName></div>
));
```

Ideally the tree would show the text "MyComponent" somewhere, but it does not today. Maybe 
something like ```<MyComponent:Connect(FunctionalComponent) /><Unknown />```.

Question: Is this even possible? I.e is there enough information for the React devtools to determine this?

**Comment by greenimpala** [comment]
It wouldn't be possible for `connect` to determine the var its been assigned to but you can just promote the function declaration?

```
const MyComponent = () => <div/>
const Wrapped = connect(...)(MyComponent)
```

**Comment by kinware** [comment]
Yeah. Also works if I create the pure component, and do the connect() in the default export.

Just thought I'd ask if I had overlooked something.

Thanks for input.

Closing issue.
