### ISSUE TITLE
Breadcrumb trail shows wrong path

### ISSUE THREAD

**Issue by uber5001** [facebook/react-devtools#95]
I'm using react native, and the React inspector shows a structure like this:

	<Top Level>
		<AppContainer>
			<View>
				<RCTView>
					<View>
						<RCTView>
							<reactComponent>
								...

The odd thing is, when I step over these one by one, the breadcrumb trail shows:

	Top Level
	AppContainer
	AppContainer | View
	AppContainer | View | RCTView
	AppContainer | View
	AppContainer | View | RCTView
	AppContainer | View | ReactComponent
	...

I'm not sure whether this is an issue with the breadcrumb trail showing the wrong information, or the React element inspector wrongly showing me the native RCT elements.

**Comment by jaredly** [comment]
The breadcrumb trail shows the 'owner' hierarchy as opposed to the parent hierarchy shown in the tree view.
