### ISSUE TITLE
Why update highlight with React 15 doesn't work well ? 

### ISSUE THREAD

**Issue by Aarbel** [facebook/react-devtools#957]
Quote from the README:
```
Does "Highlight Updates" trace renders?
With React 15 and earlier, "Highlight Updates" had false positives and highlighted more 
components than were actually re-rendering.
```

Why do Highlight Updates has false positive with React 15 ?
We want to track unexpected components updates for performance with React 15, do you know a way to track them accurately on this React version ? (Passing to React 16 is a lot of time for us)

Thanks !

**Comment by gaearon** [comment]
Because of how it was implemented. No, unfortunately there's no way to get it working accurately with React 15. (But you can use `react-addons-perf` which still works in React 15.)

**Comment by Aarbel** [comment]
Thanks @gaearon, unfortunately i think we have to pass to React 16
