### ISSUE TITLE
Refreshing the IOS Simulator with react-native breaks the element inspector

### ISSUE THREAD

**Issue by uber5001** [facebook/react-devtools#96]
After refreshing the IOS simulator when working with React Native, I get only `<Top Level>`:

![screen shot 2015-06-08 at 10 33 36 am](https://cloud.githubusercontent.com/assets/3348363/8041030/168fda02-0dca-11e5-8bda-358761f7c77b.png)

I can't expand this node in any manner that I know of.

My current workaround is to close the chrome debugging tab, and let the IOS simulator re-open the tab on refresh. This causes the debugging tab to work correctly, until the tab is refreshed (by the simulator).

**Comment by gaearon** [comment]
This should be fixed.
