### ISSUE TITLE
npm ERR! during npm install

### ISSUE THREAD

**Issue by metaarts** [facebook/react-devtools#960]
after trying npm install -g react-devtools i got an error like:
> cannot conver undefined or null to object

my npm-debug.log:
https://gist.github.com/metaarts/16d485bebe5008a7bd991f510c4d166a

i found out that the dependency "duplexer3" is npm not available anymore. is there any alternatives existing?

**Comment by ngyikp** [comment]
https://github.com/npm/registry/issues/255

**Comment by metaarts** [comment]
nice :D, thanks for the information
