### ISSUE TITLE
React DevTools not working on Unsplash

### ISSUE THREAD

**Issue by deadcoder0904** [facebook/react-devtools#969]
When I open Instagram page like [@therock](https://www.instagram.com/therock), React DevTools work but when I open [Unsplash](https://unsplash.com) it doesn't work. I'm on Chrome 63.0

**Comment by ngyikp** [comment]
Unsplash deliberately disabled the hook to React Developer Tools, this is not an extension issue and partially mentioned at https://github.com/facebook/react-devtools/issues/191:

<img width="1202" alt="screen shot 2018-01-21 at 6 40 00 pm" src="https://user-images.githubusercontent.com/6135313/35193247-dd85e602-feda-11e7-9ca5-95d958d1aecf.png">

It's possible to un-break the hook if you know how: (tip: use a debugger proxy)

<img width="1440" alt="screen shot 2018-01-21 at 6 38 40 pm" src="https://user-images.githubusercontent.com/6135313/35193284-4a347b74-fedb-11e7-9a1a-68433e322d90.png">

**Comment by deadcoder0904** [comment]
Thanks I thought this was a long-standing issue I've been having from 6 months or so 😂. I didn't post it for a long time though. I think its a good idea to mention it in the README as FAQs.
