### ISSUE TITLE
cannot install react-devtools

### ISSUE THREAD

**Issue by EdisonLiao** [facebook/react-devtools#974]
when i run : npm install -g react-devtools, this command works
but when i run react-devtools, it shows me follow errors, how can i fix it(i have tried delete the node_modules/electron)?
Error: Electron failed to install correctly, please delete node_modules/electron and try installing again

**Comment by SmokeSmell** [comment]
![image](https://user-images.githubusercontent.com/26245817/35482256-4f54bc9e-046d-11e8-8907-6b0e7faa17bd.png)
is like this picture when you install
