### ISSUE TITLE
Unexpected top-level <Unknown> element when using react-0.14.0-beta1

### ISSUE THREAD

**Issue by jacowley** [facebook/react-devtools#99]
When I try to use react-0.14.0-beta1 I'm seeing a new top-level element that looks like this wrapping my React element:
```
<Unknown ref=“null” _owner=“null” props=“…” _store=“…”>…</Unknown>
```

This appears harmless, but looks a bit ugly. I'm not sure if this is something that needs fixing in React or in the dev tools.

**Comment by jaredly** [comment]
Yeah it looks like each top-level rendered node now has a wrapper. I imagine we just want devtools to ignore it.

**Comment by spicyj** [comment]
Fixed in the new devtools: http://facebook.github.io/react/blog/2015/08/03/new-react-devtools-beta.html.
