### ISSUE TITLE
Firefox React tab not appearing

### ISSUE THREAD

**Issue by andywillis** [facebook/react-devtools#990]
I noticed that the React tab was no longer visible in the dev tools:

* FF 59.0b10 (64-bit)

I tried reinstalling the add-on but it made no difference.

Here is the add-on in my add-on list:
![image](https://user-images.githubusercontent.com/1903595/36427123-2d9fa0ee-1644-11e8-9a23-129bd4ee4f8e.png)

But no corresponding tab:
![image](https://user-images.githubusercontent.com/1903595/36427140-37b1a21c-1644-11e8-8002-fc1d79f3aad6.png)

**Comment by gaearon** [comment]
Might be a transient bug in Firefox? We didn't change anything related so please report it to FF directly.

**Comment by donaldboulton** [comment]
https://forums.meteor.com/t/meteor-react-client-app-works-in-chrome-safari-but-not-in-firefox/17558/2
