### ISSUE TITLE
Make it look better

### ISSUE THREAD

**Issue by aganglada** [facebook/react-devtools#999]
Do you think we could make react-devtools look like the vue one?

It looks really good.
https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd?hl=es

I'm more than in to make it real.

**Comment by gaearon** [comment]
We don't want it to "look like the vue one", we want it to be the best tool for React :-). Happy to take specific improvements!
